### ISSUE TITLE
update schema with id optional for div

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1000]
but create rule for throwing a warning for these instances

**Comment by njr2128** [comment]
reference #999 and the spreadsheet:
errors logged in GD, https://docs.google.com/spreadsheets/d/13R19RkmicK-fxoeaFh9SVrLzwBzdUb2oR7gisl2iOEY/edit?usp=sharing

**Comment by tcatapano** [comment]
`<id>` in `<div>` now optional. Added embedded schematron rule to warn if missing.

https://github.com/cu-mkp/m-k-manuscript-data/blob/500605c7d12b1335cd1ab16c46aa704a4ff3a046/schema/ms-transcription.rng#L57-L71
