### ISSUE TITLE
Three small markup puzzles (errors?)

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1002]
- [x] [156v TC](http://edition-staging.makingandknowing.org/#/folios/156v)
```
margin>left-middle</margin>
<mark>+</mark>
Sil vient quelque<lb/>
default aulx aisles<lb/>
de ta <al>mouche</al> bas de<lb/>
l<m>estain</m> fort tanvre<lb/>
ou d<del>&amp;</del><m><add>o</add>r</m> ou d<m>argent</m><lb/>
```
THU: I don't see the deleted ampersand in the facsimile. Can we remove it from the markup?

- [x] [106v TC](http://edition-staging.makingandknowing.org/#/folios/106v/tc) 
```
<ab><emph>Le <m>plastre</m></emph> co<exp>mm</exp>e dict est le plus dur
est le meilleur estant en<lb/>
<m>pierre</m> prens le doncq tout cru en telle sorte <tl>Pile</tl> le
<del>bien</del> <add>plus</add><lb/>
subtillement quil te sera possible
```
THU: I think this "plus" should be taken out of <add> tags

- [x] [106r TC](http://edition-staging.makingandknowing.org/#/folios/106r) 
`<head><add>Faire courre l</add><m>Or</m> pour gect</head>`
THU: It looks to me like "pour gect" is also an addition—no less of one than "Faire courre l"

**Comment by ps2270** [comment]
156v: the o of the ou is actually written over the ampersand, so it needs to be revised to reflect that.
106v: I agree that it's just the "bien" which is deleted and the "plus" is not an addition
106r: I think that is reasonable to mark up

**Comment by thuchacz** [comment]
Done
