### ISSUE TITLE
Square brackets and when we use them

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1003]
So far, square brackets have been used to indicate corrections made by the editorial team. Corrections are conveyed in a straightforward manner, supplying either missing letters, striking through extra ones, or some similar direct correction in the TCN. E.g., "il[z]"

There is also talk of rendering the content of `<sup>` tags within square brackets (rather than in bold, as they are now), with the word "supplied." E.g., "oil of [supplied: sulfur]"

Nick has recently implemented a rendering solution for gap tags (`<gap/>`) and illegible tags (`<ill/>`). For the former, the word "gap" is given in square brackets: [gap]. For the latter, the word "illegible" is given in square brackets: [illegible].

I am concerned that it might look as though we are supplying text. One way to differentiate would be to italicize the words "gap" and "illegible."

Thoughts?

**Comment by ps2270** [comment]
Square brackets are used to show editorial comments, corrections, interventions in an original text.  Thus, our corrections in [ ] are appropriate, as are, I think, [gap] and [illegible] as they also our comments on the original. If you feel they could be mistaken for supplied text, we could italicize them, but they seem self explanatory to me.  For the supplied text [ ] are not inappropriate, so this is ok, but if we are going to put in "supplied:" which makes some sense, then I would like the "supplied:" to be italicized.  I must say that when a term has been supplied not for the sake of meaning, but rather for search purposes it seems clunky to me.
