### ISSUE TITLE
Replace "box mold" with "frame"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#101]
replace “box mold” with “frame” and markup as <tl></tl>

**NOTE**
If “box mold” is used to translate the word “chassis,” then _probably_ change to “frame” depending on the context; some cases may need to be supplemented with qualifiers, such as “casting frame."

**Comment by TillmannTaape** [comment]
Replaced all instances of "box mold" with frame.

**Comment by TillmannTaape** [comment]
Question for @ps2270 on fol. 61v: the vocab says (under 'chassis'): "Kept in French in p061v “Chassis des Allemands” because seems to refer to a “viewing frame.” (PHS, 06/23/2017)" but the latest translation has "viewing frames of the Germans". Can you arbitrate?

**Comment by ps2270** [comment]
delete vocab about kept in french, and leave latest translation, i.e, viewing frames of the Germans
thanks.

**Comment by TillmannTaape** [comment]
NB in this branch I also dealt with #194.

**Comment by TillmannTaape** [comment]
I made sure that "chassis" and "frame" are marked up as <tl> where appropriate in TC, TCN, and TL.
