### ISSUE TITLE
Translation - 13v

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1010]
May I suggest a change to this translation, or let me know why you chose "shape" and "pictured":
Crapaudine
Celle qui est de la teste du crapault & qui ha la figure
du crapault naturellement paincte co{mm}e tu as veu est la plus
excellente On tient que si on mect de la pouldre dicelle sur
un brasier en la chambre de quelques uns de nuict quilz
ne pourront se mouvoir ne parler ne donner empeschement
aulx larrons 

Toadstone
The kind which comes from the head of the toad & has the shape of the toad pictured naturally, as you have seen, is the most excellent. It is held that if one puts the powder of it on a brazier in the chamber of some persons at night, they will be neither able to move, nor speak, nor thwart thieves. 

Suggested revision:

Toadstone
The kind which comes from the head of the toad & has the FIGURE of the toad PAINTED naturally, as you have seen, is the most excellent. It is held that if one puts the powder of it on a brazier in the chamber of some persons at night, they will be neither able to move, nor speak, nor thwart thieves.

**Comment by njr2128** [comment]
is this directed at @thuchacz and @TillmannTaape

**Comment by ps2270** [comment]
yes, sorry.  just assigned them.  Working in haste. On a plane all day tomorrow.

**Comment by thuchacz** [comment]
As I recall, we went with "shape" and "pictured" in order to minimize confusion about human agency here. No one is actually painting. @TillmannTaape can probably clarify further.

**Comment by TillmannTaape** [comment]
That's right, but reading the two versions, I don't actually find the current version any less weird than PHS's suggestion, which is much more literal, so I'm inclined to go with that

**Comment by ps2270** [comment]
@TillmannTaape can you please go ahead with the revision with njr gives us the go ahead?

**Comment by TillmannTaape** [comment]
Done.
