### ISSUE TITLE
run validation with schema and correct errors

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1011]
with new schema that allows for optional id of div (see #999, #1000), re-run validation. Identify errors and correct

**Comment by njr2128** [comment]
Outstanding issues are:

File | Location
-- | --
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tc\tc_p006v_preTEI.xml | Start line 62:2End line 62:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tc\tc_p016r_preTEI.xml | Start line 59:2End line 59:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tc\tc_p033r_preTEI.xml | Start line 121:2End line 121:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tcn\tcn_p006v_preTEI.xml | Start line 61:2End line 61:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tcn\tcn_p016r_preTEI.xml | Start line 59:2End line 59:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tcn\tcn_p033r_preTEI.xml | Start line 117:2End line 117:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tl\tl_p006v_preTEI.xml | Start line 32:2End line 32:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tl\tl_p016r_preTEI.xml | Start line 35:2End line 35:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tl\tl_p033r_preTEI.xml | Start line 68:2End line 68:2

**Comment by njr2128** [comment]
@tcatapano and @thuchacz  - I have fixed all errors except one:

File | Location
-- | --
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tc\tc_p033r_preTEI.xml | Start line 121:2End line 121:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tcn\tcn_p033r_preTEI.xml | Start line 117:2End line 117:2
C:\Users\naomi\Github\m-k-manuscript-data\ms-xml\tl\tl_p033r_preTEI.xml | Start line 68:2End line 68:2

This is:
`<div> <id></id>` 
`<fig> [associated fig tags] </fig> `
`<head></head>`
`<fig> [associated fig tags] </fig>`
Which I believe is throwing an error because the div opens with a figure.
I have two questions here: 
1. can you look at the markup and see a way around this schema error?
2. are these two figs even figs? I'm not so convinced. Perhaps need to consult the team. If they aren't figs, we may be able to fix the errors by tagging more appropriately (e.g., marks?)

**Comment by tcatapano** [comment]
The issue here is whether `<figure>` should be allowed in `<div>` at all. It is not currently. 

https://github.com/cu-mkp/m-k-manuscript-data/blob/ea4a3bd9436a32fc0f11cffef801174986e12984/schema/ms-transcription.rnc#L55-L62

It could be added, but I'd like to see how the code at https://github.com/cu-mkp/making-knowing-edition handles `<div>` and `<figure>` before deciding whether to adjust the schema.

**Comment by tcatapano** [comment]
the asset-server code does allow for `<figure>` in `<div>`, so we should align the schema with it by allowing `<figure>` in `<div>`

https://github.com/performant-software/making-knowing-assetserver/blob/a14324eccfb1899155b1021067f7ca245332dc64/scripts/content_import/convert.js#L213-L226

creating new issue for this

**Comment by tcatapano** [comment]
With `<figure>` added to content model of `<div>` currently only 1 error (repeated across all versions) `<figure>` before `<head>` in `<div>`: 

https://github.com/cu-mkp/m-k-manuscript-data/blob/27df8dfd76cd25e862b933198d1e60fde7f0ee5a/ms-xml/tc/tc_p033r_preTEI.xml#L109-L125

Should this be `<mark>` in the `<head>` maybe:

```
<head>
<mark>X</mark><lb/>
Pour rallumer une <tl>chandelle</tl> estainte<lb/>
entre les <bp>mains</bp> sans soufler</head>
```

**Comment by njr2128** [comment]
> @njr2128 @thuchacz: With `<figure>` added to content model of `<div>` currently validation returns only 1 error (repeated across all versions) `<figure>` before `<head>` in `<div>`:
> 
> https://github.com/cu-mkp/m-k-manuscript-data/blob/27df8dfd76cd25e862b933198d1e60fde7f0ee5a/ms-xml/tc/tc_p033r_preTEI.xml#L109-L125
> 
> Should this be `<mark>` in the `<head>` maybe:
> 
> ```
> <head>
> <mark>X</mark><lb/>
> Pour rallumer une <tl>chandelle</tl> estainte<lb/>
> entre les <bp>mains</bp> sans soufler</head>
> ```

Thanks, Terry. The update of figs in divs makes sense to me.

As for this particular instance, I am really tempted to change it to mark as per my first comment about it. It is the only problematic instance, and I am not convinced these two figs are not actually marks. @thuchacz - thoughts?

**Comment by njr2128** [comment]
As part of work on #1027, I have come across a very similar-looking "x" that occurs on 84v. It was tagged as a figure, but entered as a mark:
https://github.com/cu-mkp/m-k-manuscript-data/blob/eb8eaf589c161727b4b19e7f354e25c191248305/ms-xml/tc/tc_p084v_preTEI.xml#L128

Thus, I am going to make an executive decision now and change all three instances to marks (8v plus the two on 33r).

This will now no longer cause schema errors
