### ISSUE TITLE
identify and fix discrepancies in number of figures, links, and their ids

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1027]
Related to #807 

Running the following xpath queries shows that number of figures, links, and fig-ids is the same across all versions. HOWEVER, the number of figures vs links vs ids is NOT the same.

Identify where these problems are occurring:

xpath query |   | number
-- | -- | --
//figure | tc | 157
//figure | tcn | 157
//figure | tl | 157
  |   |  
//figure/id | tc | 155
//figure/id | tcn | 155
//figure/id | tl | 155
  |   |  
//link | tc | 156
//link | tcn | 156
//link | tl | 156

**Comment by njr2128** [comment]
Difference between figures and links occurs on 84v, where a figure has been entered with no id. It is actually a mark, so I am updating the markup:
https://github.com/cu-mkp/m-k-manuscript-data/blob/eb8eaf589c161727b4b19e7f354e25c191248305/ms-xml/tc/tc_p084v_preTEI.xml#L128

**Comment by njr2128** [comment]
Figure vs link have been matched:

xpath query |   | number
-- | -- | --
//figure | tc | 154
//figure | tcn | 154
//figure | tl | 154
  |   |  
//link | tc | 154
//link | tcn | 154
//link | tl | 154

**Comment by njr2128** [comment]
Discrepancy with ids has been identified on 46r. There is a figure with no id, as well as with this old attempt at a comment, which should be removed:
https://github.com/cu-mkp/m-k-manuscript-data/blob/0d83fc4dd22196e8da6eee4335f859431700396b/ms-xml/tc/tc_p046r_preTEI.xml#L62-L75

**Comment by njr2128** [comment]
all discrepancies seem to have been resolved:

xpath query | number
-- | --
//figure | 154
//figure | 154
//figure | 154
  |  
//figure/id | 154
//figure/id | 154
//figure/id | 154
  |  
//link | 154
//link | 154
//link | 154

**Comment by ps2270** [comment]
It looks like an inkblot to me. I don't think a figure tag is warranted, do you? No need for a comment unless we are sure what it is (which I don't believe we are).
thanks

**Comment by njr2128** [comment]
I don't think so, but there a possibly a few others like this that we should review.
I have added figure tags for now, and as we go through the index of all figures, I think we can make a better decision (especially as part of captioning work)
