### ISSUE TITLE
Compare structural+semantic markup across versions

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#103]
## structural 
Find method to verify that structural markup across the versions (tc, tcn, tl) is the same. If it is not, identify and fix

## semantic
From #443 
Find method to verify that semantic markup across the versions (tc, tcn, tl) is the same. If it is not, identify and fix

These would include all tags like `<m>, <tl>, <pa>` etc

And the ordering of nested tags

**Comment by njr2128** [comment]
Update:
@tcatapano to develop xpath query to get count of each element for tc, tcn, and tl

then review the counts across all versions and identify discrepancies to be fixed

**Comment by tcatapano** [comment]
using xmlstarlet over each ms-xml directory produces reports for per file element counts for analysis in spreadsheet https://docs.google.com/spreadsheets/d/12jTV_9d2uvZDGSg0lMU2gg6j0S8usRaOvuZjNQsp2Jk/edit?usp=sharing

```
or XML in `find ms-xml/tc -name '*.xml'` ;do echo $XML; xmlstarlet el "$XML" | rev | cut -d'/' -f1 | rev | sort | uniq -c ; done
```

**Comment by njr2128** [comment]
See tables created:

https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/el-counts_20190815_1r-85r.csv

https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/el-counts_20190815_85v-170v.csv

Which are easier to view in the working doc in GD, el-counts_20190815

**Comment by njr2128** [comment]
there are two sheets in el-counts_20190815
the first one is folios 1r - 85r
the second one is folios 85v-170v

**Comment by njr2128** [comment]
A status column has been added to show whether the three versions contain the same counts for each element type per folio ("EQUAL") or whether they are different ("NOT EQUAL").
The formula used is =IF(REGEXMATCH(A2, "p[0-1][0-9]"), " ", IF(AND(A2=C2,C2=E2),"EQUAL","NOT EQUAL"))

**Comment by njr2128** [comment]
For the status column to be accurate, and for the data to be easier to work with, the three columns must be aligned by element type for each folio. 
For example, if the original is:

ms-xml/tc/tc_p086r_preTEI.xml |   | ms-xml/tcn/tcn_p086r_preTEI.xml |   | ms-xml/tl/tl_p086r_preTEI.xml
-- | -- | -- | -- | --
3 ab |   | 3 ab |   | 3 ab
1 al |   | 1 al |   | 1 al
1 bp |   | 1 bp |   | 1 bp
1 comment |   | 1 comment |   | 1 comment
6 del |   | 6 del |   | 6 del
1 div |   | 1 div |   | 1 div
2 emph |   | 2 emph |   | 2 emph
11 exp |   | 11 exp |   | 5 fr
43 lb |   | 43 lb |   | 27 m
26 m |   | 26 m |   | 1 pa
1 pa |   | 1 pa |   | 1 root
1 root |   | 1 root |   | 13 tl
13 tl |   | 13 tl |   | 1 underline
1 underline |   | 1 underline |   |  


It will be changed to:

ms-xml/tc/tc_p086r_preTEI.xml |   | ms-xml/tcn/tcn_p086r_preTEI.xml |   | ms-xml/tl/tl_p086r_preTEI.xml
-- | -- | -- | -- | --
3 ab |   | 3 ab |   | 3 ab
1 al |   | 1 al |   | 1 al
1 bp |   | 1 bp |   | 1 bp
1 comment |   | 1 comment |   | 1 comment
6 del |   | 6 del |   | 6 del
1 div |   | 1 div |   | 1 div
2 emph |   | 2 emph |   | 2 emph
11 exp |   | 11 exp |   |  
  |   |   |   | 5 fr
43 lb |   | 43 lb |   |  
26 m |   | 26 m |   | 27 m
1 pa |   | 1 pa |   | 1 pa
1 root |   | 1 root |   | 1 root
13 tl |   | 13 tl |   | 13 tl
1 underline |   | 1 underline |   | 1 underline

**Comment by njr2128** [comment]
Sheet 1 (1r-85r) has been aligned and the status is accurate

**Comment by njr2128** [comment]
Sheet 2 (85v-170v) has been aligned and status is accurate

**Comment by njr2128** [comment]
As suggested by @thuchacz, one approach to compare the contents across versions is to make lists by element type for all three version by folio and look for the mismatched words.
For example, 
If tc has 2 materials and tcn has 2 materials, but tl has 3 materials, we could see a list:

>tc [arene, huile]
>tcn [arene, huile]
>tl [sand, oil, iron]

We could more easily identify what to look for in the tc and tcn entries

**Comment by njr2128** [comment]
![image](https://user-images.githubusercontent.com/14779727/68489319-e0107d80-0214-11ea-8ffb-98f5f289152f.png)

**Comment by njr2128** [comment]
As detailed in #1260, **el_counts_20191111** has been refreshed with new data.

Use with spreadsheet created in #1256, **el_counts_property_comparison_20191111**

**Comment by njr2128** [comment]
THU - tab 1
TT - tab 2
CAG - tab 3

**Comment by njr2128** [comment]
Also, tab 4:
129r - 139r & 129r–139r: THU
139v - 150r: TT
150v - 170v: CAG

**Comment by njr2128** [comment]
completed for silent release (dec 18)
