### ISSUE TITLE
ann_003_fa_14_CarlsonKatz_MoldedRoses - images need re-uploading

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1032]
@njr2128 . I had to find some new images for ann_003_fa_14_CarlsonKatz_MoldedRoses, so the images need down and uploading. I could log in as GE and do it, or we could wait for Caroline (probably latter is better).  Then I will re-link.
Just letting you know

**Comment by njr2128** [comment]
completed! all images now owned by GE
