### ISSUE TITLE
viscorter f.41v

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1047]
I do not think _viscorter_ is actually a word. It does not appear in any dictionary, and after a long research I could only find an old occitan term _vistornar_ which indeed means "to castrate." Questions:

1. Is the transcription accurate or is the A-P using some sort of super local Occitan variant that has not been recorded in any vocabulary?
2. Should we at least tag the word as Occitan? 
3. Should we add an entry in the glossary?

**Comment by TillmannTaape** [comment]
Transcription is accurate I think. 

Suggestion: tag as Occitan, and add ed note in TC and TCN saying "Likely a variant of the old Occitan `<i>vistornar</i>`, meaning 'to castrate.'"

**Comment by TillmannTaape** [comment]
And no glossary entry for this one-off occurrence I think.

**Comment by ps2270** [comment]
Agreed, but please pull editorial comment across all 3 versions.
thanks,

**Comment by TillmannTaape** [comment]
Done
