### ISSUE TITLE
Translation revision suggestions based on intro essay work

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1049]
101r ruby glass
Original:
La premiere experience que jen ay faicte il nest venu quune masse jaulne

Current TL: 
The first experience that I made thus, it only returned a yellow mass

Suggestion:
The first experience that I made **of it**, it only returned a yellow mass

(Reason: "of it" is a more literal translation of "en", and I think makes more sense here – it's not entirely clear what the "thus" is referring to)

@ps2270 ok?

**Comment by TillmannTaape** [comment]
157r rouge clair

Original:
Aulcuns orfevres lesprouvent sur de lor esp battu tanvre
& bien bruny avecq le chaple

Current TL: 
Some goldsmiths assay it on thinly beaten gold & that is well burnished with a chaple.

Suggestion:
Some goldsmiths assay it on gold, thinly beaten & well burnished with a chaple.
(Avoids the silently added "that is", which besides does not read well)

**Comment by ps2270** [comment]
Good. Go ahead and charge

**Comment by TillmannTaape** [comment]
Done
