### ISSUE TITLE
discrepant element counts across 26r versions

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1051]
@thuchacz could you investigate, diagnose, and fix?

see spreadsheet for element counts:

https://docs.google.com/spreadsheets/d/12jTV_9d2uvZDGSg0lMU2gg6j0S8usRaOvuZjNQsp2Jk/edit#gid=0&range=871:871

**Comment by thuchacz** [comment]
TC: used as standard
TCN: tags added: 1 `<tl>` 
TL: tags added: 1 `<env>`, 1 `<tmp>`, 1 `<wp>`

@njr2128 I didn't manually update your spreadsheet (in case that would cause problems). I leave this to you. Once you do it, you can close this issue (for 26r, at least).

**Comment by njr2128** [comment]
Updates have been made to the el-counts spreadsheet based on @thuchacz's work:

ms-xml/tc/tc_p026r_preTEI.xml |   | ms-xml/tcn/tcn_p026r_preTEI.xml |   | ms-xml/tl/tl_p026r_preTEI.xml
-- | -- | -- | -- | --
2 ab |   | 2 ab |   | 2 ab
1 comment |   | 1 comment |   | 1 comment
1 del |   | 1 del |   | 1 del
2 div |   | 2 div |   | 2 div
1 emph |   | 1 emph |   | 1 emph
1 env |   | 1 env |   | 1 env
3 exp |   | 3 exp |   |  
2 figure |   | 2 figure |   | 2 figure
2 head |   | 2 head |   | 2 head
7 lb |   | 7 lb |   |  
5 m |   | 5 m |   | 5 m
1 root |   | 1 root |   | 1 root
3 tl |   | 3 tl |   | 3 tl
1 tmp |   | 1 tmp |   | 1 tmp
1 wp |   | 1 wp |   | 1 wp


Closing this issue
