### ISSUE TITLE
Check consistency of chandelle

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#106]
Chandelle should be marked up as `<tl>`

**Comment by njr2128** [comment]
In oXygen,
Find all, search for "candle" in tl first, then crosscheck with "chandelle" in tc, tcn.
Changed manually

**Comment by njr2128** [comment]
@ps2270 and @TillmannTaape, can you look at the notes column and see if you have suggestions of how to proceed?
General problems:

- "candlestick" is inconsistently marked as a tool sometimes and not other times. What is guiding principle - tagged or not?

- a few places have the candle used more as a material than a tool, but other similar cases had a tool tag. Should tool tag still be applied?

- 2 translation issues: chandelle = lamp; and bougie = candle (see below)


| folio | notes                                                                                                      | tl                                                                                                                   | tc                                            | tcn                                                                          | 
|-------|------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------|-----------------------------------------------|------------------------------------------------------------------------------| 
| 5v    | candlesticks marked as tool                                                                                | changed                                                                                                              | changed                                       | changed                                                                      | 
| 13v   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 15r   | candlesticks NOT marked as tool                                                                            | ?                                                                                                                    | ?                                             | ?                                                                            | 
| 16v   |                                                                                                            | changed                                                                                                              | changed                                       | changed                                                                      | 
| 20v   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 32v   | candlesticks NOT marked as tool                                                                            | ?                                                                                                                    | ?                                             | ?                                                                            | 
| 33r   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 34r   | candlestick marked as tool - INCONSISTENT ACROSS VERSIONS                                                  | marked as tool (candlestick)                                                                                         | marked as tool (candlestick)                  | changed - not marked as tool (candlestick) --> marked as tool to match tl/tc | 
| 36v   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 37r   |                                                                                                            | changed                                                                                                              | changed                                       | changed                                                                      | 
| 47v   |                                                                                                            | ?                                                                                                                    | ?                                             | ?                                                                            | 
| 49r   | "resin candle" -- more material than tool?                                                                 | changed                                                                                                              | changed                                       | changed                                                                      | 
| 61v   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 65r   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 68v   |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 82v   |                                                                                                            | changed                                                                                                              | changed                                       | changed                                                                      | 
| 99r   |                                                                                                            | ?                                                                                                                    | ?                                             | ?                                                                            | 
| 103v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 119r  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 129v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 131v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 139v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 140r  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 147v  | candlesticks NOT marked as tool                                                                            | ?                                                                                                                    | ?                                             | ?                                                                            | 
| 152r  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 153r  | "chandelle" translated as "lamp". Marked as tool, but decision needed about whether lamp is ok translation | changed - "chandelle" translated as "lamp". Marked as tool, but decision needed about whether lamp is ok translation | changed                                       | changed                                                                      | 
| 158v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 160v  |                                                                                                            | no change needed                                                                                                     | no change needed                              | no change needed                                                             | 
| 166v  | more material than tool? Word used is "bougie" not "chandelle"                                             | changed                                                                                                              | changed - Word used is "bougie" not chandelle | changed - Word used is "bougie" not chandelle                                |

**Comment by njr2128** [comment]
DECISIONS MADE:

1. Candlestick - not universally tagged as tool but instead case by case. 

>- Not a tool: 5v,15r, 32v, 47v, 99r, 147v

>- Tool: 34r

2. More material than tool: decision made to keep blanket application of tool for all cases.

3. Translation issues:

>- 153r - "Chandelle" changed from "lamp" to "candle". 
>- "Bougie" is fine to be translated as "candle"
