### ISSUE TITLE
add constraint for order of <ab> to schema

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1073]
see: https://github.com/cu-mkp/making-knowing-edition/issues/173#issuecomment-522142964

`The issue here is that my code expects the margin blocks to follow the main block. Sorry not to have made that clear. If you move the <ab> that is middle-right to the bottom of the <div> it sits in, it renders in the right margin middle. So no code change for this fix, just need to adjust the markup.`

**Comment by njr2128** [comment]
@tcatapano - has this been completed?

**Comment by njr2128** [comment]
Not followed up with, but after the last comment, THU completed her complete review of all rendering. That would have fixed this issue or made it no longer applicable.
