### ISSUE TITLE
fix positioning heading in145v

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1075]
see: https://github.com/cu-mkp/making-knowing-edition/issues/67

use margin attribute for head "fleurs" to position to see if that fixes things

**Comment by thuchacz** [comment]
On TC, TCN, and TL:
- updated heading positioning
- divided 145v_2 into two continued/continues divs on the same folio to accommodate interpolated image from 145v_1 — THC signed off on this solution and is now opening new issues with Nick related to rendering
- adjusted position and render tags across the folio to approximate facsimile page
