### ISSUE TITLE
fol. 114r - rendering of marks

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1081]
@thuchacz pls. look at 114r - which contains multiple marks to indicate sequence of reading, one of which is rendered by an image, and the others by Unicode characters (or maybe they are rendered by both). But, in either case, I suggest they all be rendered by unicode, which also would entail adding a + before "tantost": "ventre, # + tantost".
Also the positioning of the marginal comments on this page need to be fixed.
thanks

**Comment by njr2128** [comment]
make sure to tag with `<mark>`

**Comment by thuchacz** [comment]
1) I will update the margin blocks and the unambiguous + and # marks (using
a mark tag).
2) I do not agree with the decision to convert some of these hashed marks
to a #. He is using triple-line hashes in some cases. I will propose a
solution to you in our meeting next Wednesday.

T.

**Comment by thuchacz** [comment]
in consultation with NJR, I created new images of non-standard hashtags/marks and added new figures to 114r. As far as I can tell, everything is now captured.
