### ISSUE TITLE
model for entry category info in schema

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1085]
related to  #819, integrating entry terms into the markup, I see at least 3 options:

1. a category attribute with multiple values separated by pipes

```
<div id="p005r_1" category="casting|metal process|practical optics" >
```

2. a category1, category2 annd category3 attributes each with a single value

```
<div id="p005r_1" category1="casting" category2="metal process" category3="practical optics" >
```
3. repeatable empty <category> child elements with value attributes containing a single category term

```
<div id="p005r_1">
<category term="casting"/>
<category term="metal process"/>
<category term="practical optics"/>

```

@NickLaiacona do you have any preferences?

**Comment by NickLaiacona** [comment]
We're currently drawing the data from here:

https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/entry_metadata.tsv

Will your code add the categories to this csv?

**Comment by tcatapano** [comment]
Actually, the most up to date entry metadata table is here:

https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/DCE_entry-category-metadata.csv

The aim of this task is to add the category terms into the XML markup so that the transcriptions and translations contain this info rather than it be completely external. It can, but does not need to replace a lookup table for your purposes. If you think it would be too onerous for you to draw from the XML data rather than a table in building the entry list feature, we can continue to maintain a lookup table, in which case this issue is irrelevant for you.

**Comment by NickLaiacona** [comment]
Terry, please do continue to generate a csv that tallies up all the metadata about entries, including this new data. DCE_entry-category-metadata.csv doesn't have the columns I need to process the entries. (al, bp, cn, env, etc) . Those are only in entry_metadata.tsv, presently.

**Comment by tcatapano** [comment]
OK. We're going to consolidate all the info into the entry_metadata table you have been using.

**Comment by njr2128** [comment]
categories have been integrated into markup as well as into the extraction of entry metadata
