### ISSUE TITLE
develop python-based entry metadata extraction

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1088]
add:

* supplied titles
* categories
* filter out:
  * non-entry divs
  * continued divs

see: #731, #819

**Comment by njr2128** [comment]
@matthewkumar, this has now become an automation task in python:
- Entry metadata table
https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/entry_metadata.tsv
Python script to generate this table from ms-xml files

**Comment by tcatapano** [comment]
When heading contains supplied text, wrap it in square braces. E.g.,

https://github.com/cu-mkp/m-k-manuscript-data/blob/e212e4f5aa445063b5bfe4e29362aeaa0a476cf7/ms-xml/tc/tc_p001r_preTEI.xml#L9

should be rendered in entry metadata table as:

```
[Liste de noms]
```

**Comment by matthewkumar** [comment]
<root page=“001r”> —> <root page=“001r” n = “1r”>
Now when you create entry metadata, popular a new field
//folio -> folio id, add folio_name = name

**Comment by njr2128** [comment]
To get folio-name, simply strip folio-id of all leading 0s

**Comment by tcatapano** [comment]
@matthewkumar entry metadata table should have rows for `<div>`s **with** id attributes only.
