### ISSUE TITLE
add/remove comment anchors to text versions where needed

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1093]
In DCE_comment-tracking, there are comment anchors that appear in certain versions (tc, tcn, or tl) as recorded in columns D ("TC"), E ("TCN"), and F ("TL").

Column I ("comment-edit-notes") records which versions the comment SHOULD appear.

Steps:

- confirm that the anchors actually appear in the version recorded in columns D, E, and F.

- compare to column I, noting where anchors need to be added/removed

- add/remove anchors

**Comment by njr2128** [comment]
Working doc in GD: [comments_20190908](https://docs.google.com/spreadsheets/d/1p5XBb6-J2VB11obqHWobPIYeYqumtL3fovQDtIB2aKs/edit?usp=sharing)

**Comment by njr2128** [comment]
![image](https://user-images.githubusercontent.com/14779727/72012774-83d4d480-322a-11ea-9fda-ed3e5102f46c.png)

**Comment by njr2128** [comment]
working from **DCE_comment-tracking** GD doc.
In oXygen, find/replace across ms-xml, look for each comment anchor individually.
If it supposed to be on all three versions and it is not, add it

**Comment by njr2128** [comment]
columns DEF - record of where anchors are present (assume this is correct)
column I - dictates where anchors _**should**_ be

If there is a discrepancy, fix by adding/removing anchors.

If there are more than 3 occurrences of an anchor, check column P for places where the anchor  has been reused on another folio (usually up-to-date)

**Comment by TillmannTaape** [comment]
I've finished my assigned half (lines 68–300). 
I searched for individual comment IDs across all three versions and checked/fixed occurrences of that ID on all folios (where the same ID was used more than once).

**Comment by Pantagrueliste** [comment]
Two anchors do not appear in any verison of the text. Where shall I place them?


p136r | p135v_1 | c_136r_02 | x | x | x | THU | Latin: sun [i.e., gold] | tc, tcn, tl
-- | -- | -- | -- | -- | -- | -- | -- | --
p136r | p135v_1 | c_136r_03 | x | x | x | THU | The word could not be traced. It appears to refer to some kind of device to hold molds in place. | tc, tcn, tl

**Comment by thuchacz** [comment]
Sorry for confusion @Pantagrueliste — I made an error inserting them in the first place:

The anchors for both comments are already in the right place in all three versions, but they have the wrong comment IDs. So... in the xml on 136r, 
look for comment c_135r_02 and change it to c_136r_02 
look for comment c_135r_03 and change it to c_136r_03

**Comment by Pantagrueliste** [comment]
80 lines to go! I'll finish tonight (UTC +1)

**Comment by thuchacz** [comment]
Way to go! Keep up the awesome work!! :)

**Comment by Pantagrueliste** [comment]
done
