### ISSUE TITLE
create explanation of unicode characters resource for DCE

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1097]
a simple table of the symbol with their meanings would suffice, even what we already have:
https://github.com/cu-mkp/m-k-manuscript-data/blob/master/reference_docs/alchemical-measurment-symbols_unicode.csv

**Comment by njr2128** [comment]
DECISION: will go into glossary - @Pantagrueliste to do. 
Form/indexing/rendering TBD with Nick (9/25/19)

**Comment by njr2128** [comment]
As per search functionality summarized in #1245:
Create a separate resource for these under DCE "Resources" that also includes counts and occurrences (because the search cannot be used to find them)

**Comment by ps2270** [comment]
see https://docs.google.com/document/d/1OL7YjYUS39bhQTOPrpwqqCRrqJQXK7w1kt1-5Zeuu5Y/edit

**Comment by njr2128** [comment]
done, see https://github.com/cu-mkp/edition-webpages
