### ISSUE TITLE
Check consistency of "or couleure"

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#110]
- What  is this?

- DECISION: 
**TAG AS MATERIAL** 
TT: from a combined reading of 7r_a1, 65r–4, and 100r_1 I get the impression that or couleur refers to the concoction of stand oil, massicot etc. which is used to stick or mat or gold leaf to a surface. That would suggest he thinks of it as a specific material rather than generic gold colour.

**Comment by njr2128** [comment]
See also #185 for translation of "couleur/e"
and related #123 for markup of "couleur/e"

**Comment by Pantagrueliste** [comment]
I'm de-assigning myself from this specific issue, which needs someone with better experience on the subject-matter.

**Comment by TillmannTaape** [comment]
I checked this as part of resolving issue #185 .
