### ISSUE TITLE
11v - remove comma

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1100]
in the tcn of 11v, the following comma before [gap] should be removed per MHS (and PHS agrees):

Frotte d’eau fort commune l’acier, meslant avecq ladicte eau de
la terre, [gap] & aprés frotte le tout avecq de la cendre
ou sable, & l’or touchera & l’argent co<mm>e sur une pierre de touche.

comma was not carried over to tl

**Comment by Pantagrueliste** [comment]
done
