### ISSUE TITLE
Add folio/ entry id reference to annotation abstracts

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1108]
As per https://github.com/cu-mkp/making-knowing-edition/issues/170, links back to the annotations' folios will be hyperlinks as part of the abstract.

All abstracts should be edited to include this

**Comment by ps2270** [comment]
added to annotation workflow

**Comment by TillmannTaape** [comment]
i.e. change folio references to fol. <8r> etc. as per the protocol developed during WGM?

**Comment by ps2270** [comment]
The point of this issue was to make clear that the main folios with which an annotation deals must be included in the abstract, and, yes, it makes sense to cite them with the brackets as per protocol.
