### ISSUE TITLE
Compose Scholarly Review Statement

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1114]
See GD files:
2019-09-13 Meeting Agenda
Consolidated Points - Collaborative Working Spaces

for notes and discussion

**Comment by ps2270** [comment]
see https://docs.google.com/document/d/1-VW_O2I9OMMrdvJomebWD4Q2_e10HyhPPSTfrOVwLJM/edit

**Comment by njr2128** [comment]
done, see https://github.com/cu-mkp/edition-webpages
