### ISSUE TITLE
assoir, assiette as seating, seat

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1115]
"assoir" and "assiette" used in painting/gilding recipes to refer to either the bole layer (in water gilding) or the sticky underlayer in mordant gilding.

We had translated "assiette" as "ground," but JK and MS suggest this is misleading/inaccurate because it might be confused with a gesso layer for painting.

See for instance the recipe on 6r entitled:
TCN: Pour poser et assoir d’or bruny et donner rouge ou verd ou bleud
Current TL: For laying down and setting burnished gold and giving red or green or blue
Suggested TL: For laying down and seating burnished gold and giving red or green or blue

SCOPE OF WORK:
1) implement translation change on 6r from "setting" to "seating"
2) look through instances of "assoir" and "assiette" to see if "seat" "seating" could be applied

**Comment by thuchacz** [comment]
See table here:
[https://docs.google.com/spreadsheets/d/1pIIhv_6HXcMfi4VhYxE8wz0nFtY1QjHDhca4GWtmVQw/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1pIIhv_6HXcMfi4VhYxE8wz0nFtY1QjHDhca4GWtmVQw/edit?usp=sharing)

**Comment by thuchacz** [comment]
@ps2270 @TillmannTaape 
The table is now done. Please review. Note:
1. the change from "ground layer" to "seat" for "assiette" is unproblematic for gilding recipes. Varnishes and painting recipes are less clearly served by this change.
2. "asseoir, etc." has been translated in a variety of ways elsewhere. The term is used sparingly but in all manner of entries. Does it make sense to change to "seat," "seating" where possible?

**Comment by TillmannTaape** [comment]
Suggestions for _assiette/assicte_ in context of varnish and painting: ground layer, base layer, underlayer.

The verb is more case by case; see my suggestions in the table. I don't think "to seat" is a good translation anywhere, and "set" or "settle" already have the etymology of "sitting" built in.

**Comment by ps2270** [comment]
Ok, done. I agreed to all changes except 6r (seating) and am not sure about 20r, as this issue of the reflexive is one CAG and I discussed at length, and during the translation read-through, he wanted to give reflexives a connotation of agency.  What do you think?

**Comment by thuchacz** [comment]
I've implemented the changes.
I've added "seat" (for gilding) as a translation of "assiette" in the glossary.

There is no entry in the glossary for "assoyr" (and its many spelling variants) in the glossary.
@TillmannTaape, if you think the glossary would benefit from such an entry, please make it. In either case, please close out this issue when you are decided/done.

**Comment by njr2128** [comment]
Tillmann says no to adding to glossary, closing issue out
