### ISSUE TITLE
Translation of "Le sable pres de mon sol" on 69v

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1116]
TCN:
- "Le sable pres de mon sol est fort excellent Mays il fault pour fayre ouvrage excellent le prendre frais qui naye gueres travaille"

Current TL:
- "The sand near my area is very excellent. But one ought to, in order to make an excellent work, take it fresh, which has been hardly put to work."

Notes from WGM:
- MHS: literally “the sand close to my soil” would make perfect sense as close to my ground, i.e. either on my neighbor’s land  or, even better, immediately below the soil on my own land.

**Comment by ps2270** [comment]
I think "area" is nicely generic, but I could also imagine using "land".  MHS believes the a-p may likely be a landholder.
Before taking action, wait for @TillmannTaape and @Pantagrueliste to weigh in.

**Comment by thuchacz** [comment]
Decision by PHS, CAG, and THU: leave as is, with "sand near my area"
