### ISSUE TITLE
"grès/grais" translation

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1117]
Current glossary entry:

Gres, grais: n.(m) a particular type of potters' clay or earth for making stoneware vessels, or the stoneware vessels themselves [COT1611 | OED2008]

Suggestion from MHS (re 30r):

“As for interpretation: I strongly believe grais/grès in this case is sandstone, not ceramic. See e.g. here https://books.google.com/books?id=dg9XztgmyMwC&pg=PA24&lpg=PA24&dq=moules+de+gres+etain&source=bl&ots=PdDHaEK0d6&sig=ACfU3U0btnP1o0KKsihapyYbvQydVUT87w&hl=fr&sa=X&ved=2ahUKEwjNi6Ke2cnkAhWOjlkKHR8_C7c4ChDoATABegQICRAB#v=onepage&q=moules%20de%20gres%20etain&f=false” 

The book he links to does indeed refer to sand, schist/shale, _grès_, and gypsum as materials for molds for tin casting (p. 24), and elsewhere glosses _grès_ as "schistes, pierres de tôlier" (p. 197) which does suggest a kind of stone rather than earthenware.

Cotgrave:
"Grez: m. A greetie, browne-gray, shining, hard, and long-lasting free-stone, good to pave with; and (small-broken) to scowre brasen, or pewter vessel ; See Grais."
"Grais: m. A kind of Potters clay, or earth, fit to make vessels of; also, a hard, and sparkling-browne free stone; as Grez;..."

I've gone through all instances, and the stone alternative seems to make more sense in most cases (for tin molds, and also where the ap talks about "hollowing out" a grais, which makes more sense with a stone than with earthenware).

My only question is about Crucibles on fol. 47r:

```
ab>Those from <pl>Bayonne</pl>, which seem to be made of
<m><fr>grès</fr></m><comment rid="c_047r_02"/> are better, for they last, without comparison,
longer than others.
```
I can't decide here whether clay or stone makes more sense for crucibles, although we could assume/hope that the ap means the same material (i.e. stone) every time.

@ps2270 ?

My suggestion: keep in Fr. as we have, and change the ed. note to 
"According to Cotgrave, _grais/grès_ means either a kind of stone used for paving and (in powder form) for polishing, or a particular type of potters' clay or earth for making stoneware vessels, and also the stoneware vessels themselves. In the context of the manuscript (molds for tin casting and crucibles), a stone is more likely, such as schist or sandstone, which was indeed used by pewterers for casting dishes (see https://books.google.com/books?id=dg9XztgmyMwC&lpg=PA24&dq=moules%20de%20gres%20etain&hl=fr&pg=PA24#v=onepage&q=moules%20de%20gres%20etain&f=false [LINK TO BE REPLACED WITH BIB REFERENCE])"

**Comment by ps2270** [comment]
Good. Please go ahead.  It does make more sense.  On 47r, it would appear that he means, those that seem to be made of the stone. Some crucibles do appear to be stone, but are just filled with refractory material.
Go ahead and make change.

**Comment by TillmannTaape** [comment]
DONE. 

@Pantagrueliste I've left a note in the status column for your to integrate this new reference into the Bibliography, please – for this comment and another one. If you search for "CAG" in the status column you will find them both. They are also in bright green like your other open Bibliography issues.

**Comment by njr2128** [comment]
This is what has happened:
there are multiple comment with unique ids about gres/grais. Tillmann changed for c_008r_02, but not for any of the other instances.
Work to be done is now summarized in #1159
