### ISSUE TITLE
Ambiguous parent entry for first two marginal blocks on 132v

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1118]
@ps2270 
I'm sure you've agonized over this before, but I'd like you to reconsider whether the two short marginal blocks currently attached to "Common sand from the _mine_" on 132v are more appropriately considered the children of "_Crocum ferri_" directly below. There is a strong argument to be made that the second of marginal block ("It is better made with distilled vinegar.") is about crocum rather than sand (though I admit he could be referring to vinegar as a binder here...).

Thoughts?

**Comment by ps2270** [comment]
It's a difficult call, but I can see why you are urging this, and I think what you say makes sense, w.r.t. to placement (marginally more joined to Crocum Ferri heading), and apparently connected to the discussion of mixing it among the sand/in the molds.  Do go ahead with the changes as you proposes.
thanks,

**Comment by thuchacz** [comment]
moved the two blocks from the "sand" div to the "crocum ferri" div
