### ISSUE TITLE
Sayes and sayettes (and sayetes), sometimes "de pourceau"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1120]
@ps2270 1) Can you please sign off on the proposed solutions below. 2) Please also weigh in on the seemingly arbitrary translation of "sayes" sometimes as cloth, sometimes as "brush" in three instances below

**PROBLEM**
Very inconsistent translation of "sayes" and "sayettes"

**GLOSSARY WORK**
@TillmannTaape  has just made a new glossary entry for "saye" and updated "sayette":

- **Saye**	1	small bristle brush used by goldsmiths
- **Saye**	2	light wool fabric known as "say" in English, or a garment made of such fabric
- **Sayette**     very small bristle brush (diminutive of <i>saye</i>, i.e. a small bristle brush used by goldsmiths)

**THU has scoped translation and markup consistency:**

13r
``` 
- TCN: <tl><m>sayes de <al>porceau</al></m></tl>
- TL: <tl><m><al>hog</al> bristles</m></tl>
- TL recommendation: <tl>small <m><al>hog</al> bristle</m> brushes</tl>
```
85r
```
- TCN: <tl>sayettes de <al>pourceau</al></tl>
- TCN recommendation: <tl><m>sayettes de <al>pourceau</al><m></tl>
- TL: <tl>small bristle brushes of <al>pig</al></tl>
- TL recommendation: <tl>very small <m><al>hog</al> bristle</m> brushes</tl>
```
111v (NB: sayes = cloth)
```
- TCN: avecq des <tl>sayes</tl> on en frotte l<del>e</del>’ouvrage moulé
- TL: with some <tl>cloths</tl>, one rubs the molded <del><fr>e</fr></del>work.
```
114r
```
- TCN: petites <tl>sayetes de <m>poil de <al>pourceau</al></m></tl>
- TCN recommendation: <tl>petites sayetes de <m>poil de <al>pourceau</al></m></tl>
- TL: little <tl>brushes of <m><al>pig</al> bristle</m></tl>
- TL recommendation: <tl>tiny <m><al>hog</al> bristle</m> brushes</tl>
```
119r (NB: sayes = brushes)
```
- TCN: avecq des <tl>sayes</tl> l’ay nettoyée
- TL: cleaned it with <tl>small bristle brushes</tl>
```
135r
```
- TCN: la nettoyeras bien avec des <tl>sayettes</tl>
- TL: clean with it well with <tl>very small bristle brushes</tl>
```
144r (NB: sayes = cloth)
```
- TCN: la nettoye<lb/> bien avecq tes <tl>sayes</tl>
- TL: clean it well with your <tl>cloth</tl>
- TL recommendation: clean it well with your <tl>cloths</tl>
```
146r
```
- TCN: <tl>sayes de <al>porceau</al></tl>
- TCN recommendation: <tl><m>sayes de <al>porceau</al></m></tl>
- TL: <tl>small <al>hog</al> bristle brushes</tl>
- TL recommendation: <tl>small <m><al>hog</al> bristle</m> brushes</tl>
```
163v
```
- TCN: tes <tl>petites <m>sayettes de <al>pourceau</al></m></tl>
- TL: your <tl>small <m><al>hog</al> bristle</m> brushes</tl>
- TL recommendation: your <tl>very small <m><al>hog</al> bristle</m> brushes</tl>
```

**Comment by ps2270** [comment]
good solutions. Please go ahead.

**Comment by thuchacz** [comment]
I've made the translation and markup changes (they might not be visible yet since the staging edition is not refreshing from GitHub at the moment). 

@ps2270 
can you look at these three instances and think about when we decide when something is a cloth versus a brush? 

111v (NB: sayes = cloth, but you can also "frotter" smth with a brush...)

```
- TCN: avecq des <tl>sayes</tl> on en frotte l<del>e</del>’ouvrage moulé
- TL: with some <tl>cloths</tl>, one rubs the molded <del><fr>e</fr></del>work.
```

119r (NB: sayes = brushes)

```
- TCN: avecq des <tl>sayes</tl> l’ay nettoyée
- TL: cleaned it with <tl>small bristle brushes</tl>
```

144r (NB: sayes = cloth)

```
- TCN: la nettoye<lb/> bien avecq tes <tl>sayes</tl>
- TL: clean it well with your <tl>cloth</tl>
- TL recommendation: clean it well with your <tl>cloths</tl>
```

**Comment by ps2270** [comment]
It kind of impossible to tell. It could be either. It seems to me more likely that all 3 should be "small hog bristle brushes" or "small bristle brushes" because I don't see in TLFI that "saye" is used as generic cloth (like linge), but always as cloth destined for clothing.  I recommend changing all these "cloth/s" to "small bristle brushes".
While you are doing that on 144r, could you please consider changing the translation of the following:
Doncques pour mectre la main à l’œuvre,
aprés que tu l’auras faicte entierem<ent> mourir dans le vinaigre...

Therefore, to start working hands-on, after you have killed it entirely in vinegar ...

Suggested revision:
Therefore, to put your hand to the work after you have killed it entirely in vinegar ...

Let me know if you disagree

**Comment by thuchacz** [comment]
I have made all the changes PHS mentioned above. There are no longer versions of the word "saye" that refer to cloth(s)—all are now referring to some kind of small bristle brush.

@TillmannTaape, since you worked on the definitions for "saye" I want you to sign off on all this before we close. And, if you're okay with "saye" never being cloth, can you delete that second definition in the glossary and close this issue?

**Comment by thuchacz** [comment]
@TillmannTaape 
Reminder: double check glossary work and close out this issue when you finish

**Comment by TillmannTaape** [comment]
Checked definitions and deleted the "cloth" meaning from glossary.
