### ISSUE TITLE
Add <lb/> in TL and tcn,tc for margin notes with marks 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1127]
A number of marginal notes start or are separate by +, #, and other marks. 
In the facsimile, they are above and on a separate line than the text that follows, e.g. 142v (not yet fixed)
Where appropriate, add line breaks to ease rendering.

This seems to be a vestige of when line breaks were not allowed in TL

**Comment by njr2128** [comment]
also an "x" on 150v

**Comment by njr2128** [comment]
This does not seem to be done consistently in tc and tcn (see 150v). Consult with team

**Comment by njr2128** [comment]
also 17v - top left corner circle

**Comment by njr2128** [comment]
Will be done as part of rendering position readthrough (related to #1071 or figure work)

**Comment by thuchacz** [comment]
This has been done as part of the render check campaign.
Closing.
