### ISSUE TITLE
Check consistency of Sable

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#113]
- sometimes tagged as a material when it is used as a material, so we should do a search at the end--tag all “sand” and compare to when “sand” has been tagged as a material.
- Used as a material vs a composite material
- DECISION: mark up sable in each case, paying attention to qualifiers (sable de mine etc.)

**Comment by TillmannTaape** [comment]
TC done. Search term: sable

**Comment by TillmannTaape** [comment]
TCN done. Search term: sable.
Also checked "arene" in TC and TCN.

**Comment by TillmannTaape** [comment]
TL done.
