### ISSUE TITLE
Create "how to use" the edition resource

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1133]
Need prose version (with images?) as well as video version described in #777

**Comment by ps2270** [comment]
See
https://docs.google.com/document/d/16Lds3JoQd9qkRlTtMHu1GzONOTcuDxLot6RT-YxEZvI/edit#

**Comment by njr2128** [comment]
done, see https://github.com/cu-mkp/edition-webpages
