### ISSUE TITLE
Review and edit PW protocols into something consolidated and useful

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1134]
Including resources:

- "PW18 Translation Protocol AND VOCABULARY LIST" (GD)
- "PW18 Markup Protocol" (GD)
- Find to add: Marc’s latest principles of transcription
- Update with MHS tidbits in emails over last year (e.g., accents)

**Comment by ps2270** [comment]
See Principles of markup: https://docs.google.com/document/d/1OL7YjYUS39bhQTOPrpwqqCRrqJQXK7w1kt1-5Zeuu5Y/edit
and 
Principles of Translation: 
https://docs.google.com/document/d/1YnMf1Qc8HCgNej1PIvZtfK8zvhH_s9UwmSpAWQyiUms/edit
and
Principles of Transcription:
https://docs.google.com/document/d/1t_mpyw9OMJAn2YFGdqaIa1UvKYlmdDEcQ9WCes4jmm0/edit

**Comment by ps2270** [comment]
Remaining questions in the Principles documents:
Translation: leave Appendix as is, or create a separate resource? Links need to be checked in Appendix.
Encoding: chart rendering; is all markup accounted for?  highlighted Attributes
Transcription: Letter Form resource? The questions below are open questions that need to be corrected in the Principles of Transcription if they are not accurate:
– The æ ligature (but not the œ ligature used in modern French), a form used specifically for Latin and for the Latinate spelling of the prefix præ- in French, has been maintained.  

- Acute accents: é marks stressed, i.e. non-mute, e in final syllables, but not in monosyllabic words except for disambiguation between homographs. (NOTE FROM MARC: Wondering if we have any cases ? (e.g. prés = fields / pres = close, dés = dice) ? Maybe not worth mentioning.)

@thuchacz @Pantagrueliste @TillmannTaape ARE THESE STATEMENTS IN Principles of Transcription accurate; do they need revision?!

**Comment by TillmannTaape** [comment]
Correct I believe.

**Comment by njr2128** [comment]
done - see https://github.com/cu-mkp/edition-webpages
