### ISSUE TITLE
fol. 6v and 66v - translation of canule

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1142]
Sorry for raising this, but there is a perfectly good descriptive english word for _canule_: Canulla
OED has first use in 1616. It is generally now a medical term, but it does fit the meaning perfectly.
@TillmannTaape - since we discussed, can you let me know what you think?  These are the only 2 instances (i.e., multiple instances on these 2 folios)

**Comment by TillmannTaape** [comment]
Very good, I wasn't quite happy with our previous solution when we re-visited the issue today. The OED even has "cannule" which also has the meaning "small channel or canal" and is used much earlier, in 15th-century translations of Guy de Chauliac, to refer to syringes etc. Shall I translate as "cannule" in all cases?

**Comment by ps2270** [comment]
Yes, great.
Thanks

**Comment by TillmannTaape** [comment]
Done
