### ISSUE TITLE
Confirm and define thematic categories of essays

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1144]
Unlike the categories of #539, all essays (intro and research) will be organized by an additional set of categories.

The current list of categories are (with notes):

1. **The Making and Knowing Project**
2. **The Making and Knowing Laboratory**
>JAK essay
>reconstruction annotations
>Lab videos from website

3. **The Manuscript, Ms. Fr. 640**
4. **Society and Culture** 
5. **Art and its Making**
 >Spring/Kirby essay
 >ephemeral art essays

6. **Knowing Nature**

TO DO:
flesh these out with descriptions - write description and then finalize the actual category name.

**Comment by ps2270** [comment]
The current list of categories are (with notes):

**The Making and Knowing Project** 
- Essays that provide information about the The Making and Knowing Project, including its procedures and personnel

"The Making and Knowing Laboratory"
 - Essays that discuss hands-on work in the Making and Knowing Laboratory, principles of reconstruction, and results or conclusions from hands on work in the laboratory
e.g, JAK essay, reconstruction annotations, Lab videos from website

**The Manuscript, Ms. Fr. 640**
- Essays that provide information about the manuscript, e.g., codicology, or that compare Ms. Fr. 640 to other genres, or that contain sustained arguments about the identity of the author-practitioner of the manuscript.
e.g., Bergen, Faulkner essays

**Society and Culture**
- Essays that discuss the historical context of the manuscript, and society and culture in sixteenth-century France.

**Art and its Making**
- Essays that discuss art, the materials, making, and meaning of art, and the training of professional artists.
e.g., Spring/Kirby essay, ephemeral art essays

**Knowing Nature**
- Essays that discuss the investigation, exploration, and manipulation of natural materials and principles
e.g., Lores-Chavez, Landsman/Rowen w.r.t. sulfur

Next Step:
@thuchacz @TillmannTaape @Pantagrueliste   PLEASE COMMENT AND REVISE

**Comment by njr2128** [comment]
This has been copied to the Google Drive in the document, **Essay-category-themes-descriptions**, under DCE > Annotations + essays.

Please edit/comment/revise there

**Comment by TillmannTaape** [comment]
I left edits in suggest mode. I'm not sure we want/need "Essays that..." every time, but it depends how exactly it looks on the website (and how clear it is that these are essay categories).

**Comment by ps2270** [comment]
Thanks.  @Pantagrueliste and @thuchacz , please just quickly pass your eyes over these descriptions and ok or revise in suggest mode:
https://docs.google.com/document/d/18vfnUIob3GZclWSqy__S_fgEfOk-1yN4ZfahB0ITThM/edit

**Comment by thuchacz** [comment]
Done.
