### ISSUE TITLE
supplied headers in entry list

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1146]
with @NickLaiacona, determine solution for supplied headers to be pulled for entries list when `<sup>` terms are not to be rendered in folio views

**Comment by tcatapano** [comment]
My proposed solution:

* changed rendering of `<sup>` in DCE to "do not render"
* `<sup>` in `<head>` will be used for the "entry title" field in the entry metadata table used to generate the Entries list page

**Comment by njr2128** [comment]
@matthewkumar if head is supplied, wrap text in square brackets for entry-metadata

**Comment by njr2128** [comment]
seems like this has been put into effect (entry-metadata.tsv has bracketed supplied headers)
