### ISSUE TITLE
Corrections to 166r

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1147]
Que le jour precedent est præcepteur du subsequent par ainsy que tu as
eu besoing daprendre des præcedents pour enseigner les subsequents 

so that as the preceding day is teacher for the subsequent, thus you needed to learn from those who **proceeded** you in order to teach to those who come after.

"proceeded" should be "preceded"

Thanks

**Comment by njr2128** [comment]
done
