### ISSUE TITLE
In-text figure callouts 

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1148]
Need consisten treatment of figure callouts within the text e.g.

fig.
Fig.
figure (spelled out)

E.g.: "As fig./Fig./figure 2 shows..."

**Comment by ps2270** [comment]
I think the protocol should be:
Fig. after a preceding period
As fig. 2 shows
No use of "figure"

But I'm open to other solutions.

**Comment by njr2128** [comment]
Confirmed.
