### ISSUE TITLE
check that all editorial deletions are in <corr><del></del></corr>

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1157]
#120 listed the following concern:

More generally, there is inconsistency in the ways that the deletion tag has been used--the tags are only used as editorial tags!, so correction tag must always be around the del tag in tl. TL should follow tcn in this place.
check consistency of this!!

**Comment by njr2128** [comment]
As of this posting, there are 66 in tcn and only 54 in tl. @thuchacz will review and correct

**Comment by thuchacz** [comment]
63 <corr><del> in the TCN
50 <corr><del> in the TL
I added the missing 13.
Closing.
