### ISSUE TITLE
Check consistency of lute/luting

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#116]
- Material tag may have been misunderstood
- is this a verbified material or not, and a tool?--tagged inconsistently
- “lute(r)” should be tagged `<m>`(verbified material)
- Searchm mission: “lute”, “luth” and decide whether any of them are worth marking up as tools

**Comment by TillmannTaape** [comment]
Search terms: lute, luth

Tagged all occurrences (verbs and nouns) as materials. 

Decided not to tag any as <tl> – it would seem odd to tag some but not others, and in context it does not seem that it is always used in the sense of a tool.
