### ISSUE TITLE
Cross-check principles of TCN against its <corr> tags

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1169]
PHS noticed that the following correction from TC to TCN should probably not have been marked up and have been part of the "silent" normalization.

jaulnes deouf | jaulnes d’[œ]uf
-- | --

Once statement of "principles of normalization" is finalized, go back and review `<corr>` tags in TCN to make sure there are no non-necessary uses.

On `<corr>` tags, see also #804 #120 and the table in the GD.

**Comment by njr2128** [comment]
note: upon further discussion, this transposition of letters in this word IS in fact a correction (not just normalization).

For other potential instances, we think this that consequence of potential switches between corrections and silent normalizations is very small. Closing.
