### ISSUE TITLE
Check consistency of measurement tag, overlapping measurement, coin, and temporal tags

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#118]
Measurement tag, and overlapping measurement, coin, temporal tags need to be checked for consistency and outliers - **TWO ACTIONS**:

1. Overlapping tags, eg measurement and temporal (“leave for a day”; measurement and coin (“add spanish coin” with a specific size and amount of silver)
2. Also need to check across the three versions (tc, tcn, tl) to make sure same markup is applied to each version

THC task help

**Comment by thuchacz** [comment]
Used XPath/XQuery Builder in Oxygen to verify:
1) across all three versions, tags are in this order: `<ms><cn><fr></fr></cn></ms>`, with extremely few exceptions, as dictated by the text.
2) across all three versions, all nested measurement and temporal tags in this order: `<ms><tmp></tmp></ms>`

PROBLEMS
9v and 170v, `"<cn>livre..."` is not translated as pound. There is nothing in the translation protocol about this.

36r, 60v, 95r, 104r, `"<cn>liard..."` is inconsistent—sometimes in `<fr>` tags, sometimes not. "general rules" section of translation protocol says leave all coins in original language and give `<fr>` tags, but entry for "liard" gives the English equivalent "liard." NB: Cotgrave doesn't give a translation; he only discusses its value. It is, however, a word in the OED...
