### ISSUE TITLE
Entries that exist as entries in Pw18 tracking but not marked up as such

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#12]
p106v div IDs
There are two entries on this page that 1) have been entered as distinct entries in PW18 tracking and 2) have distinct titles in PW18 ("Tuiles" and "Plastre").
However, these are not actually marked up as either being distinct DIVs with proper IDs or as having titles.

**Comment by njr2128** [comment]
AMENDMENT: I understand what is happening - these are actually marked up as <rub>, which is described in our Markup Protocol as "Rubric: A word or phrase in italic script in the body of the text that is not a new div, heading, or or <ab>"

This is this a larger conceptual question: for entry_metadata, do <rub>s get included? They are not as of the posting of this issue. Because editorial team has included them in PW18 tracking, should they receive unique IDs as an entry heading would?

**Comment by njr2128** [comment]
Another example is 108v,  "Lardille" and "Alum de plume"

**Comment by njr2128** [comment]
Additional issue for schema, the inclusion of 
<man>
Manchette: a word or phrase in the margin, usually in italic script, that indicates something in the text block. It is not a heading (although sometimes it looks like it), but rather explains something in the text block, e.g., within “Pierrerie,” there is a <man> in the margin that indicates where he mentions “Esmeraulde.”

Included in PW18 tracking as a distinct entry, but no ID assigned

**Comment by tcatapano** [comment]
```<rub>``` is not the proper element in a margin. It is intended essentially for inline headings; i.e., highlighted text that functions as a heading but is inline and does not really start a new text division/entry

The (improperly named) "manchette" is a string of highlighted text, but in the margin, related to some content in an entry in the body text. 

Neither ```<rub>``` nor ```<man>``` should be in divs in the place of headings. This will be easy to test for via schematron in an xml aware environment.

**Comment by tcatapano** [comment]
> This is this a larger conceptual question: for entry_metadata, do <rub>s get included? They are not as of the posting of this issue. Because editorial team has included them in PW18 tracking, should they receive unique IDs as an entry heading would?

If ```<rub>```s  are seen as {inline} headings for an entry, then they should be contained inside their own ```<div>``` in the place of the ```<head>``` usually used. If they are not seen as introducing a new entry, then they should not be in the entry metadata spreadsheet.

**Comment by njr2128** [comment]
From PW18 Markup Protocol:

Manchette: a word or phrase in the margin, usually in italic script, that indicates something in the text block. It is not a heading (although sometimes it looks like it), but rather explains something in the text block, e.g., within “Pierrerie,” there is a <man> in the margin that indicates where he mentions “Esmeraulde.” 

`<man><margin>`position`</margin>`text`</man>`

**Comment by njr2128** [comment]
In PW18 index tracking, there are 30 entries being tracked that do not have div IDs and thus not considered an actual entry as defined through markup (ie as divs with IDs).
EDITORIAL TEAM - what to do with these?

**Comment by njr2128** [comment]
3 entries from Index Tracking have been updated:

p106v_3 | p106v | Tuiles | Tiles | casting
-- | -- | -- | -- | --
p106v_2 | p106v-p107r | [Plastre]  p1 | Plaster p1 | casting
p106v_2 | p106v-p107r | [Plastre]  p2 | Plaster p2 | casting


See #565

**Comment by njr2128** [comment]
Pulled from Index Tracking, these are all the "entries" that have been included in the index but that do not have any IDs assigned to them:

Div ID | Folio # | Entry title transcription | Entry title translation | Group
-- | -- | -- | -- | --
p108v - NO ID | p108v | Lardille | Clay | casting
p108v - NO ID | p108v | Alum de plume | Feather alum | casting
p118v - NO ID | p118v | Sable excellent | Excellent sand | casting
p125r - NO ID | p125r | A scavoir | Something to know | casting
p135r - NO ID | p135r | Adoulcir lor | Softening gold | casting
p009v - NO ID | p009v | Brouillart | Waste book | Not grouped
p028v - NO ID | p028v | Va au cinquiesme foeillet | Go to the fifth leaf | Not grouped
p054v - NO ID | p054v | [no title] | [no title] | Not grouped
p120v - NO ID | p120v | Siscitatio dubia | Doubtful question | Not grouped
p162r - NO ID | p162r | Navigation marchandise | Navigation, trade | Not grouped
p162r - NO ID | p162r | Galeres | Galleys | Not grouped
p162r - NO ID | p162r | Vases dor | Gold vases | Not grouped
p162r - NO ID | p162r | Vase de fer raporte et soulde | Iron vase joined and soldered | Not grouped
p059v - NO ID | p059v | Paincture darmes | Painting of armory | painting
p026r - NO ID | p026r | Balle de canon | Cannon ball | weapons
p026v - NO ID | p026v | Balle de couleuvrine | Culverin ball | weapons
p027r - NO ID | p027r | Balle de bastarde | Bastarde ball | weapons
p027r - NO ID | p027r | Balle de moyene | Average ball | weapons
p027r - NO ID | p027r | Piece de campagne | Field piece | weapons
p027v - NO ID | p027v | Faulconeau | Falconet | weapons
p027v - NO ID | p027v | Faulconeau de 4 quintals autrement passevolants tire 8 pans | Falconet of 4 quintals, alternatively passevolant, is 8 pans long | weapons
p027v - NO ID | p027v | 3 quintals tire de long 9 pans | 3 quintals, is 9 pans long | weapons
p027v - NO ID | p027v | 2 quintals tire de long une cane qui sont 8 pans de monpelier | 2 quintals, is one cane long, which is 8 Montpellier pans | weapons
p027v - NO ID | p027v | 1 quintal tire six pans et demy | 1 quintal, is six pans and a half | weapons
p027v - NO ID | p027v | 1 quintal et demy tire 7 pans et demy | 1 quintal and a half, is 7 pans and a half | weapons
p027v - NO ID | p027v | mousquet de 60 livres tire 5 pans de long ou 6 | A 60 lb musket, is 5 pans and a half or 6 | weapons
p027v - NO ID | p027v | 5 quintals tire onze pans et demy | 5 quintals, is eleven pans and a half | weapons

**Comment by njr2128** [comment]
From NJR and PHS work:
Most of the entries here were tagged as `<rub>`s or `<man>`s. Those that were not already had an entry id, which was updated in Index Tracking. The remaining entries without IDs were captions (cannonballs).


Div ID | Folio # | Entry title transcription
-- | -- | --
rub | p108v | Lardille
rub | p108v | Alum de plume
man | p118v | Excellent sable
man | p125r | A scavoir
man | p135r | Adoulcir lor
p009v_3 | p009v | Brouillart
rub - marginal note instead? | p028v | Va au cinquiesme foeillet
p054v_1 | p054v | [no title]
man - part of "por la boutique" | p120v | Siscitatio dubia
man - part of "por la boutique" | p162r | Navigation marchandise
man - part of "por la boutique" | p162r | Galeres
man - part of "por la boutique" | p162r | Vases dor
man - part of "por la boutique" | p162r | Vase de fer raporte et soulde
p059v_1 | p059v | Paincture darmes
caption - listed in entry list? | p026r | Balle de canon
caption - listed in entry list? | p026v | Balle de couleuvrine
caption - listed in entry list? | p027r | Balle de bastarde
caption - listed in entry list? | p027r | Balle de moyene
caption - listed in entry list? | p027r | Piece de campagne
caption - listed in entry list? | p027v | Faulconeau
caption - listed in entry list? | p027v | Faulconeau de 4 quintals autrement passevolants tire 8 pans
caption - listed in entry list? | p027v | 3 quintals tire de long 9 pans
caption - listed in entry list? | p027v | 2 quintals tire de long une cane qui sont 8 pans de monpelier
caption - listed in entry list? | p027v | 1 quintal tire six pans et demy
caption - listed in entry list? | p027v | 1 quintal et demy tire 7 pans et demy
caption - listed in entry list? | p027v | mousquet de 60 livres tire 5 pans de long ou 6
caption - listed in entry list? | p027v | 5 quintals tire onze pans et demy

**Comment by njr2128** [comment]
`<man>`s should not be included in entry list, and should be removed from Index tracking.

A separate resource should be created of `<man>`s

`<rub>` decision to be made with THC

**Comment by njr2128** [comment]
all `<man>`s identified in table have been removed from Index tracking:

Div ID | Folio # | Entry title transcription |  
-- | -- | -- | --
man | p118v | Excellent sable | Excellent sand
man | p125r | A scavoir | Something to know
man | p135r | Adoulcir lor | Softening gold
man | p120v | Siscitatio dubia | Doubtful question
man - part of "por la boutique" | p162r | Navigation marchandise | Navigation, trade
man - part of "por la boutique" | p162r | Galeres | Galleys
man - part of "por la boutique" | p162r | Vases dor | Gold vases
man - part of "por la boutique" | p162r | Vase de fer raporte et soulde | Iron vase joined and soldered

**Comment by njr2128** [comment]
The remaining  'entries' without IDs in Index Tracking that should be discussed are `<rub>`s and   captions:

Div ID | Folio # | Entry title transcription
-- | -- | --
rub | p108v | Lardille
rub | p108v | Alum de plume
rub - marginal note instead? | p028v | Va au cinquiesme foeillet
caption - listed in entry list? | p026r | Balle de canon
caption - listed in entry list? | p026v | Balle de couleuvrine
caption - listed in entry list? | p027r | Balle de bastarde
caption - listed in entry list? | p027r | Balle de moyene
caption - listed in entry list? | p027r | Piece de campagne
caption - listed in entry list? | p027v | Faulconeau
caption - listed in entry list? | p027v | Faulconeau de 4 quintals autrement passevolants tire 8 pans
caption - listed in entry list? | p027v | 3 quintals tire de long 9 pans
caption - listed in entry list? | p027v | 2 quintals tire de long une cane qui sont 8 pans de monpelier
caption - listed in entry list? | p027v | 1 quintal tire six pans et demy
caption - listed in entry list? | p027v | 1 quintal et demy tire 7 pans et demy
caption - listed in entry list? | p027v | mousquet de 60 livres tire 5 pans de long ou 6
caption - listed in entry list? | p027v | 5 quintals tire onze pans et demy

Moving this to new issue: #
