### ISSUE TITLE
Delete and correct tags

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#120]
- correction tags in TC - there are 69 that are correction expanded, which is ok, but the rest-ca 30-40- are problematic
- how are editorial corrections treated in TL? We do not have a clear policy on this.
  - ML and CC: carried corrections into TL, as best they could.
- in TL the editors are not consistently correcting the a-p, e.g., repeated words have sometimes just been left in the English, but sometimes they have been corrected. What is our policy on this?  Just leave them in the TL. `<corr>` tags should only be carried over into TL if they entail a change in meaning; inconsequential spelling mistakes in the French should not be flagged using `<corr> `in the TL
  - e.g., when a-p added a word but forgot to delete the one it was replacing, so what to do in this case? Affects meaning, therefore carry over.
  - `<corr> `tags should only be carried over into TL if they entail a change in meaning; inconsequential spelling mistakes in the French should not be flagged using <corr> in the TL
  - Campaign 1: look for corr tags in TC to make sure only abbreviation expansions are corr tagged
  - Campaign 2: look for corr tags in TCN and decide which ones need to be carried over to TL; and check that any editorial deletions are within the corr tag in TCN and TL
  - **Two campaigns need to be in tandem or back to back**
- More generally, there is inconsistency in the ways that the deletion tag has been used--the tags are only used as editorial tags!, so correction tag must always be around the del tag in tl.  TL should follow tcn in this place. 
  - check consistency of this!!
- A-p has gone back to correct something, that produces a deletion, followed by an addition, usually interlinear
  - marked up as `<del>` followed by `<addition>`
- When a-p is overwriting something, when he starts writing, then realizes that he needs to start again with a new initial letter, and Marc has marked up as a deleted initial in tc and tcn and tl.

**Comment by thuchacz** [comment]
the issues outlined above are now dealt with, except for one, which is now isolated in #1157 

Closing.
