### ISSUE TITLE
Acier de damas - 11v, 15v, and 55v

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1201]
Michael Assis noticed that 11v is translated as follows:
Couleur dacier de damas sur costeaulx
Color of damascene steel on knives

15v:
Tablettes
Il s’en faict de buys marquetées d’ebene, sandal, yvoire ou d’or
et d’argent comme damasquine.
Tablets
Some are made from boxwood inlaid with ebony, sandalwood, ivory, or gold and silver like damascening. 

55v:
Acier de damas
Damascus steel

11v seems like it must be wrong.  @Pantagrueliste @TillmannTaape  Can you check on this, please?

**Comment by TillmannTaape** [comment]
I've changed to "Damascus steel" on 11v.
