### ISSUE TITLE
Correction and translation question - 10r

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1204]
Et la corne represente un lustre & polyment gras co<mm>e le jaspe

now translated as 
And the horn presents a lustre & a fatty polish like jasper.

1. lustre should be luster (american English)

2. Isn't it "a fatty luster & polish ..."?  The "gras" applies to both?

**Comment by thuchacz** [comment]
it looks like "a fatty polish & lustre" would be the safer way to phrase
this.

**Comment by ps2270** [comment]
Ok.  Isn't it luster not lustre?

**Comment by thuchacz** [comment]
Sorry—Canadian moment. Got my -er -re endings mixed up. Right you are!

**Comment by ps2270** [comment]
Revisiting this: actually, I assigned @Pantagrueliste , in order to understand whether it is safe to assume that "gras" applies to both, and thus can leave it as "a fatty luster and polish." Also, we need to search and replace luster for lustre, as I see there are others on this page, and perhaps elsewhere.

**Comment by Pantagrueliste** [comment]
Syntaxically it is safe to assume that gras applies to both. Semantically, however, lustre is usually understood as the effect of polyment (or polissage in modern French) and "polissage gras" is a frequent occurence, contrary to "lustre gras." So I'd rather opt for "a luster, and fatty polish"

**Comment by ps2270** [comment]
ok, @Pantagrueliste . Thanks.  Can you please, at your earliest convenience, change 10r to read "a luster and fatty polish" [no comma], and correct "lustre" at the other instances in this folio and in the rest of the ms to (american spelling) "luster"?
thanks,
