### ISSUE TITLE
Annotation elements --> field notes, add to html repo

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1206]
Related to #1199 

Some elements of annotations (such as appendices) have been designated accompanying field notes rather than an important inclusion in the annotation itself.

These items will be moved out of their annotation folders in GD and added to a new dedicated folder under "Students Files" > **Field Notes pre-FA18 to be added to repo** (this is the same place that the other items for addition to the field notes repo lives)

Rename the item to start with annotation folder name (that include id, short title, etc)

**Comment by njr2128** [comment]
## List of items moved:

- ann_045_fa_16_Lores-ChavezKang_ImitatingRawNature_Appendix I: Ms. Fr. 640 Imitation Terms

**Comment by thuchacz** [comment]
Added:

- ann_052_fa_16_Donefer-Hickie_ForCagesAndGlass_Appendix1
