### ISSUE TITLE
Convert fig 2 of ann_001 Wax-Tallow to table in text

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1207]
fig 2 is just an image of a table. 

Type out as table in annotation text and remove fig 2

**Comment by njr2128** [comment]
Original figure moved to annotation archive in Instructor Files folder in GD.

@ps2270, can you approve the placement of reference to the table in the text file?
If it is ok, close out this issue

**Comment by ps2270** [comment]
Looks good. I've added a version of the caption as a title for the Table. Thanks!
