### ISSUE TITLE
remove rows of letter headings in glossary

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1208]
The googlesheet (and the subsequent version in the repo) has header rows for each letter, e.g., "A:"

These render as entries in the edition glossary, and duplicate the headers automatically inserted by Nick.

@Pantagrueliste, please remove these rows, and let @njr2128 know when this is complete.

NJR will then reupload a version to the repo.

**Comment by njr2128** [comment]
has this been completed? I think it has..?

**Comment by Pantagrueliste** [comment]
DONE
