### ISSUE TITLE
Essay IDs needed for Keller extra essays

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1211]
@njr2128 Please see Vera Keller's essay folder, https://drive.google.com/drive/u/0/folders/1KuexCQYY1wxl3rPrij1C5lB3GgyZf-Az
which now contains 3 essays.  These should be divided into separate folders (I presume) and should be given separate IDs in the metadata tracking sheet. 
thanks!

**Comment by njr2128** [comment]
These are now the essay ids, and new folders have been created within her larger folder. 
Will send email to you and her with updated info:


ID | Title | Author
-- | -- | --
ann_320_ie_19 | (Essay 0) - “Everything depends upon the trial (Le tout gist à l’essay)”: Four Manuscripts between the Recipe and the Experimental Essay | Vera Keller
ann_330_ie_19 | Essay 1-short | Vera Keller
ann_331_ie_19 | Essay 2-short | Vera Keller
