### ISSUE TITLE
Convert 2 metalworking Amsterdam annotations to GD format

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1212]
Before #1202, these essays need to be converted from pdf to the format and structure of all other research essays in Google Drive.
i.e., one folder with:

1. Text googledoc

2. Abstract googledoc

3. Bibliography googledoc

4. Captions googledoc

5. Folder - Illustrations

**Comment by caro27** [comment]
- no abstract for Incuse Casting, but two introductions. Have removed transcription/translation. 
- Taken out captions and bibliography. Began parts of essay text, however CMS/NJR will return to later.

**Comment by njr2128** [comment]
This has been overridden by new decisions from PHS (some have either been incorporated into other essays, some are archived as fieldnotes, some are outstanding as "Amsterdam" annotations and will be dealt with en masse)
