### ISSUE TITLE
66v - Translation - capitalize

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1217]
66v_4: "paintbrushes" Change to 
Paintbrushes (capitalize)

**Comment by Tititesouris** [comment]
Fixed with #1219

**Comment by ps2270** [comment]
@thuchacz I don't see that this happened, but maybe the Edition is not updating.

**Comment by thuchacz** [comment]
@ps2270 Staging edition is not updating at the moment. I also pushed a number of changes that Naomi and I made yesterday on an editorial comment editing campaign, but those new/moved comment anchors are not showing up in staging.

**Comment by njr2128** [comment]
I do not know of any ongoing maintenance from Nick's team, but it may be a result of other work they are doing. 

Let's see if things change by the end of today. If not, I'll reach out to Nick
