### ISSUE TITLE
Check consistency of couleur

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#123]
- Couleur (f.) = a substance to make metals flow more easily, a flux or liquifier. We need to search all instances of “couleur” to make sure we have distinguished “color” and this substance.  Mark as a material in all versions of the ms, and leave in French (and mark with Fr tag)

**Comment by njr2128** [comment]
See also #185 for translation of "couleur/e"
and related #110 for markup of "or couleur/e"

**Comment by Pantagrueliste** [comment]
272 matches for *couleur* across 101 pages.

**Comment by TillmannTaape** [comment]
Done, see #185
