### ISSUE TITLE
insert hyperlinks to folio references in annotation texts

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1238]
In the annotation texts, links back to folio pages of DCE have been signaled with angle brackets (e.g., `fol. <165r>`

Once the URLs have been finalized, all callouts to the folio pages need to be inserted as hyperlinks

**Comment by njr2128** [comment]
See GD doc, **annotations_folio-essay-linking** for protocol.

As of this posting, linking for almost all MVP annotations has been completed by Kelsey

**Comment by ps2270** [comment]
implemented
