### ISSUE TITLE
Bergen essay: needs link to DCE, page uncertain

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1242]
In a footnote, Katie Bergen writes:
"For a breakdown of the topics covered in Ms. Fr. 640, please see the Digital Critical Edition of Ms. Fr. 640. "

We need to add a link to the appropriate place in the DCE, once settled. It could be:
Entries page:  http://edition-staging.makingandknowing.org/#/entries
PHS essay
Larger landing page that describes the M&K entry categories

TBD.

**Comment by njr2128** [comment]
completed as of Feb 6 public release
