### ISSUE TITLE
update schema: allow figure inside ups

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1243]
figure 170v_2 is tagged with `<ups>`

update to allow for figures inside `<ups>`

**Comment by tcatapano** [comment]
Implemented. `<ups>` contains m.phrase which contains `<figure>`Closing.

https://github.com/cu-mkp/m-k-manuscript-data/blob/036672dcac1b4e175df35353d818275bbebd3b55/schema/ms-transcription.rnc#L149-L150

https://github.com/cu-mkp/m-k-manuscript-data/blob/036672dcac1b4e175df35353d818275bbebd3b55/schema/ms-transcription.rnc#L326-L337
