### ISSUE TITLE
update schema: comments inside figure captions

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1244]
allow for the following
`<figure...><caption><comment …></caption>`

**Comment by tcatapano** [comment]
This seems to already be the case. So closing.

See:  https://github.com/cu-mkp/m-k-manuscript-data/blob/1ffc8ae75fa5c46dbe7ebac40b73acdb24e65b67/schema/ms-transcription.rng#L120-L125

`<caption>` allows text and the elements in the m.phrase pattern, of which `<comment>` is a member:

 https://github.com/cu-mkp/m-k-manuscript-data/blob/1ffc8ae75fa5c46dbe7ebac40b73acdb24e65b67/schema/ms-transcription.rng#L597-L641
