### ISSUE TITLE
create search functionality explanation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1245]
Based on:

**FROM NICK**
Summary of new search features:
The search system now looks for entries which contain all of the terms entered into the search bar. If the terms are enclosed in quotes, the terms will be treated as a phrase. Only entries containing the entire phrase will be matched. Search results can now be ordered by folio ID or relevance. Also, the search system no longer attempts to stem text. This means that it will only match terms that are pluralized and conjugated the same as the search term. Lastly, "stop words" have been eliminated, so common words will now match (the, or, etc.)

**Notes from NJR**
AND searches implemented
>Burnt and lead

Phrase search
>“Burnt lead”

EDGE CASES
>“Or couleur = phrase search
>Or couleur” = AND search
>The “gold leaf” = AND search for “the” with phrase search of “gold leaf”

Stop words eliminated
>Or

Stemmers in use
>Guard 
>Guards 
> —> Return different results
>No way to return both
>Search of [guards guard] will only return entries that have BOTH these words (AND not OR)

Special characters cannot be searched for (including alchemical symbols)
>Work-around: list occurrences in the separate resource dedicated to them

**Comment by ps2270** [comment]
Done here: https://docs.google.com/document/d/16Lds3JoQd9qkRlTtMHu1GzONOTcuDxLot6RT-YxEZvI/edit
@tcatapano and @njr2128  pls sign off on this
