### ISSUE TITLE
Essay Caption format for images from institutions 

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1246]
see also #1228 for M&K images

Final decision example:
Fig. 4. Lampworkers, Johann Kunckel, Artis Vitrariae Experimentalis (Frankfurt, 1679), plate X. A group of lampworkers sit around a table underneath a vent and use small flames bolstered by foot-powered bellows to heat glass rods and tubes. This is the earliest visual representation of the lampworking process. It is likely close to the activities that the author-practitioner may have witnessed. © HAB Wolfenbüttel. Permalink: http://diglib.hab.de/drucke/od-215/start.htm?image=00487  (CC BY-SA 3.0 DE).

**Comment by njr2128** [comment]
implemented
