### ISSUE TITLE
67r - translation change

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1249]
@TillmannTaape  please change the following according to your suggestions

a little oil, not of spike lavender, but another odorant that resembles olive oil.
change to: a little oil, not of spike lavender, but another fragrant one that resembles olive oil.

We also need to note that fragrant one needs to go into normalization campaign, and pls check that markup is correct here across all 3 versions.
thanks!

**Comment by TillmannTaape** [comment]
Changed tl and extend the material tag to encompass `<m>another fragrant one that resembles olive oil<m>` in all 3 versions.
