### ISSUE TITLE
Tag other languages

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#125]
Initial note: 
> Other language tags from vocab list - search for occitan and poitevin words in the vocabulary list, then search the ms and make sure they have all been tagged properly.

**We need to make decisions about, then add/revise, some language markup**
- For passages in Italian and Latin, in the TRANSLATION we should come up with a specialized tag and mark it up we will leave the original text and provide a translation in an editorial note
  - DECISION: leave all languages other than French in the original language, and include the translation as an editorial comment 

EXCEPTIONS:
- Discuss whether common expressions eg agnus dei (but also when he uses both latin and french for a flower name) should be marked up as Latin.  M&K needs to make a decision.
  - **DECISION**: agnus dei - no latin tags in any version - it is common enough in English and French
  - **DECISION**: “crocum ferri” and “crocum” should be marked up as Latin in the English translation (and get an explanatory editorial note)
  - **DECISION**: other terms (like flower names) - need case-by-case determination by looking at their use in 16th c (ie if it is commonly used in French and/or English → no tags; not commonly used → tag)
- Occitan, poitevin tags - **TENTATIVE DECISION**: leave in original in the translation, carry occitan tags across all versions, and include the translation as an editorial comment
  - distinguish between tags that are marking vernaculars of various sorts, and tags for leaving a portion   in the original.

**Comment by Pantagrueliste** [comment]
All language markup questions merged in this issue

**Comment by njr2128** [comment]
See also #36 Translation tags

**Comment by thuchacz** [comment]
See more specific issues for workflow:
#587 (poitevin)
#588 (occitan)
#561 (latin)
#566 (french)

DONE as part of this issue:
Italian <it>: p002v_1; p043r_3; p055r_1; p123r_1
Greek <gk>: p013v_4; p162r_1
German <ge>: p118r_3

Outstanding question of whether p055r_4 contains Italian or Spanish. See #589
Outstanding question of whether "ana" on p083r_1; p092v_2 is a Greek measurement. See #590
Outstanding question of content for editorial comments for "spat" and "spalt" (108r; 119v; 138r). See #591

**Comment by thuchacz** [comment]
Resolved #589 #590 #591. Closing this issue.
