### ISSUE TITLE
31r - translation change

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1250]
@TillmannTaape  pls change according to your suggestions:
“Flanders varnish, made with turpentine & oil or from mastic

**change to:** “Flanders varnish, made with turpentine & oil of turpentine or mastic

Pls check markup across the 3 versions, and pls add to normalization tasks.

**Comment by TillmannTaape** [comment]
Changed tl and extended material tag to include "oil of turpentine or mastic" in all 3 versions.

I don't know how to add to normalization tasks – @njr2128?

**Comment by ps2270** [comment]
@njr2128  - added to Matthew workflow?

**Comment by ps2270** [comment]
This will come up when pulled
