### ISSUE TITLE
ed comment on 20v - DO NOT DELETE, finish comment, and add to bibliography

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1251]
p020v_5 | c_020v_02 | X |   |   | TT | See <i>Histoire de l'église de Montauban</i>: https://books.google.com/books?id=wwI7AAAAIAAJ&lpg=RA10-PA4&dq=cardaillac%20cloche&hl=fr&pg=PT5#v=onepage&q=cardaillac%20cloche&f=false
-- | -- | -- | -- | -- | -- | --

If one follows the link, "cloche" does appear, just lower down on the page in footnote 1:
![image](https://user-images.githubusercontent.com/14779727/68412755-cd397280-015a-11ea-961c-dfcf1dca7dd4.png)

**Comment by ps2270** [comment]
Oh, wow, good catch! So, let's go ahead an include this comment. @Pantagrueliste  please add this to your list of bibliog. entries to complete. Comment could read:
According to the Histoire de l'église de Montauban [add bibliog info], this bell was given to the Saint-Etienne Church of Toulouse by the abbot of Montauban and Aurillac Jean III de Cardaillac in 1531, google books URL.
Make sure I have that info correct, and add all diacritical marks. THANKS

**Comment by ps2270** [comment]
@Pantagrueliste and @thuchacz  was this done?

**Comment by njr2128** [comment]
Bib key has been made, and comment updated now.
