### ISSUE TITLE
Check consistency if ordure, immundice, crasse (tag as Material)

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#126]
Ordure, immundice, crasse (nastiness/filth) have been inconsistently marked as material - **regularize all as materials**

**Comment by TillmannTaape** [comment]
TC/TCN search terms: ordure* (RE), cras*e (RE), im*undice (RE), im*mondice (RE)

TL seach terms: filth, nastiness, impurities (for immundice, see vocab)

Tagged all as material.
