### ISSUE TITLE
69r - meaning and possible translation change

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1262]
I'm working on Jiang's "What is stone?" and on 69r, there is a crucial passage that I can't quite figure out:
Does "a se former en pierre"  have the sense of "it starts its formation in stone" or "that it starts to form into stone", or "that it is starting to form itself into stone":

Comme il senleve ainsy en
grands lopins on diroit quil commance a se former en pierre 

 Since it comes out in large lumps one would say that it starts to form in stone

@Pantagrueliste  @TillmannTaape 
What translation do you think best conveys the meaning of "a se former en pierre"

**Comment by Pantagrueliste** [comment]
"se former en" + substantive means: to take/have the shape/form/appearance of something.
Good translations would be something along the lines of: "to start shaping as a stone," "taking the appearance of a stone," "taking the shape of a stone" ...

**Comment by ps2270** [comment]
How is this @Pantagrueliste ? OK?  If so, could you please correct 69r? Thanks!

Comme il senleve ainsy en
grands lopins on diroit quil commance a se former en pierre

Since it comes out in large lumps one would say that it starts to take shape as a stone

**Comment by Pantagrueliste** [comment]
done
