### ISSUE TITLE
update all media+essay references to entry-category analysis

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1268]
Through work in #819, two new divs not previously accounted for were found:
23v_1
66r_6

category assignments were made, and their inclusion updated in a new analysis tab of **DCE_entry-category-metadata** spreadsheet.

This means all numbers are slightly off (see archived tab)

**Comment by ps2270** [comment]
is this an action item for me?

**Comment by njr2128** [comment]
Action item for both you and me to consider. Will add to meeting notes and discuss in person.
Wanted a record here of the issue

**Comment by ps2270** [comment]
@njr2128 
does this mean there are 928 entries?? I'm just trying to get an accurate count for the explanatory texts.

**Comment by njr2128** [comment]
Superseded and corrected to "over 900 entries"
