### ISSUE TITLE
convert non-text field notes to html and add to fieldnotes.makingandknowing

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1279]
#1199 dealt with all docx/gdoc files and their embedded media of FA18 field notes.

all other file types (including gslides/powerpoint, gsheets/xlsx, etc) were not carried over.

Need to develop workflow for conversion to html and deployment

**Comment by tcatapano** [comment]
Need to investigate tools and target forms for the migration for these filetypes. @njr2128 could you provide a list of these non-textual files (including filename extensions or filetypes. Big question is: do we need to migrate these to html or could they be linked in their original format?

**Comment by njr2128** [comment]
listing created in GD DCE - Field Notes folder, **listing of folder Field Notes Fall 2018**

**Comment by njr2128** [comment]
Target archival file formats: https://www.loc.gov/preservation/resources/rfs/textmus.html#digital

**Comment by njr2128** [comment]
For archival process - spreadsheets:

- If want **presentation** - convert to tables in docs (and then to html)
- If want **data** - convert to csv and provide as download

**Comment by njr2128** [comment]
[listing of folder Field Notes Fall 2018.zip](https://github.com/cu-mkp/m-k-manuscript-data/files/3843851/listing.of.folder.Field.Notes.Fall.2018.zip)

**Comment by njr2128** [comment]
DECISION from editorial team:
spreadsheet --> tables in doc files
presentations --> pdf/a

**Comment by njr2128** [comment]
DECISION from 2019-11-15 meeting:
All spreadsheet --> tables in word docs
All presentations --> pdf/a
