### ISSUE TITLE
thumbnail image needed for ann_046_fa_16_LePouesard_PainOstieRostieBreadInEarlyModernEurope

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1282]
Can you make one and add to thumbnails folder, then add link to annotation tracking?

**Comment by caro27** [comment]
https://docs.google.com/spreadsheets/d/1xSqGL-8d5QNvGtDSE6bIogeKu5NAw_bbJN6OK-8q9zc/edit#gid=0
No original images in this annotation.

**Comment by njr2128** [comment]
to be resolved in #1287
