### ISSUE TITLE
annotation metadata - create tracking columns for refresh

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1283]
(discussion in digital meeting, Performant Meeting 74_2019-11-14)

As part of new pipeline for pulling down annotation data, add 3 new columns in annotation tracking and metadata:
Add to annotations metadata - to indicate which to be pulled down

- Status column to designate staging vs production vs nothing
   - published = on production and staging
   - staging = in staging only
   - no = nowhere (don’t pull)

- Refresh column: yes/no (binary)
- Remove yes after each refresh and add to date column
- Timestamp for last refresh date: date 
- Have limit to number of items to be refreshed (like 10-15)

**Comment by njr2128** [comment]
@tcatapano and @NickLaiacona, this has now been implemented. Let me know if changes should be made

**Comment by njr2128** [comment]
an additional column has been added for M&K team tracking processing (status-phs) - which can be ignored for digital team

**Comment by NickLaiacona** [comment]
@njr2128 can you send me a link to this file? was expecting to find this change in:

https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/annotation-metadata.csv

but don't see it there.

**Comment by njr2128** [comment]
Apologies, @NickLaiacona  - I forgot to update. I have uploaded a new version: https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/annotation-metadata.csv

**Comment by NickLaiacona** [comment]
got it. thanks!
