### ISSUE TITLE
entry categories for p139v_1

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1289]
this entry, Cast of wax to represent an animal that one has not got, is currently only assigned the category "casting"

However, it contains the instructions for creating black sulfured wax (which is the basis for reconstruction in ann_051_fa_16_KangLores-Chavez_BlackSulfuredWax)

I think this should  get an additional entry category of wax process.

If you agree, let me know and I will update the markup (and DCE_entry-category-metadata)

**Comment by ps2270** [comment]
Yes, definitely! That should also be included in wax process. Thank you!

**Comment by njr2128** [comment]
Great!

Updated entry category assignments, annotation metadata, and xmls files.
