### ISSUE TITLE
use of specialized "..." on 157v

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1295]
@tcatapano, a series of ellipses on 157v seem to be entered as a single character (ellipsis proper as formatted in word processors) instead of three characters (periods) in succession.

Is there a proper form? Is one preferable over the other? Standard ASCII?

Downstream effects include searching (e.g., right now, in oXygen, searching "..." (three periods) does bring up the character)

**Comment by tcatapano** [comment]
This is U+2026, &#8230; Keep it

**Comment by njr2128** [comment]
Proper way is to use the ellipsis character (U2026)

We will keep the ellipsis already there
