### ISSUE TITLE
Check consistency of urine

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#130]
Mark “urine” as a body part throughout (in addition to having been marked as a material).

**Comment by njr2128** [comment]
Accidentally referenced #106 in commit message instead of this issue

**Comment by njr2128** [comment]
In oXygen:
> Find all "urine" in tl, then in tc and tcn to crosscheck. 

Summary of changed and notes below:

|       |                                                                                    | 34 occurance                                                                   | 32 occurances                                                                  | 32 occurances                                                                  |
|-------|------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| folio | notes                                                                              | tl                                                                             | tc                                                                             | tcn                                                                            |
| 7v    |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 31r   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 37v   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 38r   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 43r   | "purpurine", 2   instances (tl); 1 instance (tc) - other is "purpurina"            | no change                                                                      | no change                                                                      | no change                                                                      |
| 51v   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 52r   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 58r   | One instance in tl was   "purpurine" WHICH HAD DOUBLE "m" TAGS - REMOVED DUPLICATE | changed                                                                        | changed                                                                        | changed                                                                        |
| 60v   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 63r   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 76r   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 81v   |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 103v  | Inconsistent markup of   "headache"/"teste" - changed tl to have bp tag (see #236) | changed                                                                        | changed                                                                        | changed                                                                        |
| 112r  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 112v  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 115r  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 129v  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 143r  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 144r  |                                                                                    | changed                                                                        | changed                                                                        | changed                                                                        |
| 153r  |                                                                                    | no change                                                                      | no change                                                                      | no change                                                                      |
| 160v  |                                                                                    | no change                                                                      | no change                                                                      | no change                                                                      |
| 163v  |                                                                                    | no change                                                                      | no change                                                                      | no change                                                                      |
| 165v  |                                                                                    | no change                                                                      | changed - one instance; the other   was fine                                   | changed - one instance; the other   was fine                                   |
| 169v  |                                                                                    | changed - from bp around   "urine" to around "warm urine" to match other cases | changed - from bp around   "urine" to around "warm urine" to match other cases | changed - from bp around   "urine" to around "warm urine" to match other cases |
