### ISSUE TITLE
Annotations not connected to entries - do something about this?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1304]
Bergen's essay on household management texts discusses many entries, but is linked to none of them. Doesn't it make sense to at least link it to some featured ones (or all of them)?  This is the case for a few other essays as well.

**Comment by njr2128** [comment]
Agreed.
Let me know which entries and we can update the metadata.
Or, let me know if you need help deciding

**Comment by ps2270** [comment]
Done.
