### ISSUE TITLE
purger, se purger, repurger = to cleanse?

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#131]
purger, se purger, repurger = to cleanse?
Check occurrences to see whether this translation makes sense in each case

**Comment by thuchacz** [comment]
DECISION: purger and repurger = to purge
mundifier = to cleanse
nettoyer = to clean
espurger = to prune

**Comment by thuchacz** [comment]
Searched "purg" (19 hits).
Ensured all "purger" translated as "purge"; "se purger" used mostly to construct the passive "is purged".
