### ISSUE TITLE
Translation - 46v  Escrivain

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1310]
Why translate Escrivain as "scribe" in heading and as "writer" in the first sentence? I think it should be "scribe" both times.
@Pantagrueliste @TillmannTaape can you please confirm?

46v: 
Escrivain huile de soufre
Si lescrivain veult promptement netoyer sa plume de lespesseur
de lancre qui si est deseche Il ne la fault que tremper
dans lhuile de soufre Et incontinent elle sera blanche
& nette Urb.

Trans:
Scribe, Oil of sulfur
If the writer wants to clean his quill promptly of the thickness of the ink which has dried on it, one only needs to soak in oil of sulfur. And it will immediately be white & clean. Urb.

**Comment by Pantagrueliste** [comment]
Yes, I also think it should be scribe. Do you want me to change it?

**Comment by TillmannTaape** [comment]
Yes, agreed. Sorry I missed this over the holidays.

**Comment by ps2270** [comment]
@pantagrueliste pls change
