### ISSUE TITLE
ann_055_sp_17_Eom_Distillation - check figure links

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1329]
E.g. Fig 3

Check all figure links and add missing ones.

Hyperlinks are also not always including the figure number, spanning just "fig." etc.

**Comment by ps2270** [comment]
I checked the figure links and changed the hyperlinks to include the numbers of the figures. There are some Fig. numbers which are not linked b/c they refer to earlier figures. They should not be linked.

**Comment by njr2128** [comment]
thank you!
And yes, confirming there are multiple references for some figures, so only the first instance should be linked.
