### ISSUE TITLE
"drogue" – translation decision needed

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#133]
Search occurrences of "drogue" and make decision. Should drogue drogue be translated as "drug"? Does it referred to medicines/remedies, or dried ingredients in general?

**Comment by ps2270** [comment]
A search shows that it seems to mean ingredients in general; the same use as in Palissy.  DMF: a remedy. Cotgrave: "drug"; OED: "Originally: any substance, of animal, vegetable, or mineral origin, used as an ingredient in pharmacy, chemistry, dyeing, or various manufacturing processes."

Decision: translate with "drug".  I've added an entry in the Protocol as follows: “drug,” meaning any substance used as an ingredient in various making processes.

**Comment by TillmannTaape** [comment]
Search terms: drogu, drog

10 instances, all were already translated as drug(s).
