### ISSUE TITLE
ann_055_sp_17_Eom_Distillation - entry assignment + category

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1330]
This annotation has been assigned entry p003v_1, however, I believe it is actually connected to p003r_3 which continues onto 3v with the distillation vessel image. It is this one that discusses the vessel and any distillation. p003v_1 simply discusses turpentine vs. spike lavender varnish behavior.

To do:

- [x] confirm associated entry

- [x] check / edit annotation text to reflect the continued entry

- [ ] add entry category to p003r_3: varnish AND corrosives?

**Comment by ps2270** [comment]
You are correct. It should be attached to 3r_3. Good catch. Thank you.
@ps2270 will correct annotation, abstract, etc.
Not sure how it became "corrosives"! But I don't see the justification for that.

**Comment by ps2270** [comment]
I revised the annotation to reflect the corrected folio.

**Comment by njr2128** [comment]
associated entry has been updated in annotation-metadata.

NOT adding corrosives as entry category.
