### ISSUE TITLE
replace bib keys with more complete citation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1331]
to be done in editorial comments and in glossary.

Form of citation TBD

**Comment by njr2128** [comment]
Form of citations has been confirmed:

- Editorial comments - footnote citations Chicago
   - For NJR/THU to try this and see what it looks like
- Bibliography - leave all as keys with hyperlink to bib page of DCE
   - pending information from Nick that this is possible for release 1

**Comment by njr2128** [comment]
To do:

1. @Pantagrueliste 

   - [ ] generate footnote Chicago citations for all bibliographic objects and provide as resource to NJR/THU

2. @njr2128 and @thuchacz 

   - [ ] try adding footnote Chicago citations to all editorial comments in place of their bib key

   - [ ] if needed, explore shorter option

3. @Pantagrueliste and @TillmannTaape 

   - [ ] pending info/decision, make changes to glossary

**Comment by njr2128** [comment]
(NJR+THU) all bib keys replaced in editorial comments using Chicago footnote format EXCEPT for ones flagged in #1515 for which we have no corresponding bib reference.

Used the following reference files: 
https://github.com/cu-mkp/m-k-manuscript-data/blob/master/bibliographies/output/CommentCitations.md
https://raw.githubusercontent.com/cu-mkp/m-k-manuscript-data/master/bibliographies/output/CommentCitations.md
https://github.com/cu-mkp/m-k-manuscript-data/blob/master/bibliographies/output/bibliography.md

**Comment by Pantagrueliste** [comment]
Can we close this?

**Comment by njr2128** [comment]
completed for editorial comments as of Feb 6 public release.
Different decision reached for glossary - keys remain but explanatory text added (in progress by Nick as of this post) at top of glossary and on bibliography page (done)
