### ISSUE TITLE
Translation of "histoire" in the context of painting

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#134]
Histoire (f.) = use “history” (in painting, p031v, 39v, 57v, also 64v).  
Does it refer to a historiated initial or descriptive/narrative painting like historia?
Is there word that better captures this sense than "history"?

**Comment by thuchacz** [comment]
**THU RECOMMENDATIONS:**

- Keep as “history” (See OED “history, n.” 5.) and “historiated” (OED “historiate”) or “historied” (OED “history, v.” 2.)
- there is no better English alternative. For English use of “history” to describe paintings as early as 1514, see Toynbee, “A note on storia, storiato, and the corresponding terms in French and English.” See also Grafton, “Historia and istoria: Alberti’s terminology in context”
- Cf., OED “story” 2a. and 2b. account for pictorial representations, but both are obsolete
- Cotgrave: historie, storie, chronicle, relation

<img width="664" alt="screen shot 2019-03-08 at 07 19 52" src="https://user-images.githubusercontent.com/23508994/54028309-9b5ab100-4172-11e9-83c8-37a664b287c9.png">
<img width="662" alt="screen shot 2019-03-08 at 07 20 01" src="https://user-images.githubusercontent.com/23508994/54028313-9f86ce80-4172-11e9-856d-0a6b67a786e0.png">

**Comment by thuchacz** [comment]
PHS DECISION: use of "history" and "historiated" as translation is fine. Leave as is.

Problem of translation of "imprimer" on 57v_1 (sheath-maker) to be taken up in issue #195, where it is better translated as "impress" than "print."
