### ISSUE TITLE
format tables in annotations

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1340]
- NICK: add one line before/after tables
- TABLES:
- Name of each table is going outside and above the table, styles as h2
- Then may be regular text
- In GD: NO SPACE AFTER TEXT AND BEFORE TABLE
- First row is column heads
- TO DO: make table in stucco-example that meets these requirements for Nick to work
- THEN, format all tables in all annotations to match

**Comment by njr2128** [comment]
- Put “table 1” if referenced in the text itself
- Table 1: Beds
- Otherwise, just have a header above
- disclaimer about quotes from fr 640: 
   - Based on transcription and markup dated XXXX (if we have actual date like in "imitating raw nature"
or
   - transcriptions and translations from 2017 version of Ms. Fr. 640

**Comment by njr2128** [comment]
Done for all marked ready for staging

**Comment by caro27** [comment]
As a note, see Accessibility Tables for the requirements that we will need to follow for the next release.

**Comment by ps2270** [comment]
@njr2128 @caro27 
Was there a sense that we would format tables as 10-pt? I don't see it reflected in this issue, and it certainly hasn't carried over into the Staging edition (although most tables in GD essays have been formatted as 10-pt). I don't know if we care at this point. What do you think?

**Comment by ps2270** [comment]
Table formatting in essays: 
10-pt font
single spaced
no extra padding around the table in text (Nick adds the padding)
