### ISSUE TITLE
translation of "metail" (within "metal" context)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1343]
"metail" occurs twice in the manuscript and has been translated once as metal and once as _metal_. 
It is not given as an alternate spelling for _metal_ in the glossary.

See
**16v:**
...Tu pourras couler dans des moules & coquilles de fer ou de metail*
...you will be able to pour into molds & iron or _metal_*
The editorial comment is "Here <i>metal</i> means not metal in general, but an alloy of copper and tin."
![image](https://user-images.githubusercontent.com/14779727/70341445-ef3d1800-1820-11ea-9a75-c13e65e313ce.png)

**87r:**
...& jamays en ceste sorte le metail nentrera bien
...& in this way, metal will never enter the mold

QUESTIONS:
- is "metail" an alternate spelling of _metal_ and thus be added to the glossary?
- is it ok that it has been translated with two different meanings of "metal"? Or, @ps2270, do you think that 87r should also be _metal_?

**Comment by Pantagrueliste** [comment]
metail = metal , I'm adding it to the glossary.

**Comment by ps2270** [comment]
yes. metail = metal, and 16v and 87r are correctly translated, i.e., 16v = _metal_; 87r = metal

**Comment by ps2270** [comment]
@Pantagrueliste I don't see evidence in the glossary that you did this. If not, can you now do so, please!

**Comment by Pantagrueliste** [comment]
I added "metail" in the "alternate spelling" column (December 6, 3:23pm). Would you like me to add a new entry? I'm not sure this is necessary.

**Comment by ps2270** [comment]
no, this is done now. I've added it as a variant for Meaning #2 also. Better to be redundant and clear.
