### ISSUE TITLE
116r illegible?

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1359]
not sure whether `quilz s<del>ont</del> e` deserves an illegible tag.

**Comment by ps2270** [comment]
I see what you mean; it looks pretty illegible--I would say that sont was suggested by context, not by the letters on the page.  But we'd need to ask Marc, as he probably decided it.

**Comment by thuchacz** [comment]
This was reviewed by PHS, CC, and THU, and rendered as:
`qu’ilz s<del>ont</del>e<comment rid="c_116r_05"/>` with the comment "Correction in original: -s written over -ont"

Addressed in #1736 
Closing.
