### ISSUE TITLE
Markup vent as an environment--but not always

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#137]
> “vent” as environment?  How consistently have we marked it as “env”?

 **Yes but**

- “four a vent” not an environment
- “vent” in a mold not an env

**Comment by thuchacz** [comment]
molds, furnaces, luted vessels, etc. NOT tagged as <env>
mentions of wind as agents of probably environmental origin tagged as <env>
wind resulting from bellows, lungs, bottoms, etc. NOT tagged as <env>
