### ISSUE TITLE
Translation of "arrondir"

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1386]
61r_2: Where did "rounding off" come from? Arrondir = rounding or making round. Is "rounding off" a technical term for painters? Should we change throughout ?

**Comment by thuchacz** [comment]
@TillmannTaape  changed it from "rounding off" to "rounding." 
Closing.

**Comment by Pantagrueliste** [comment]
"rounding off" is still on the header though: shall I change it ?

**Comment by ps2270** [comment]
Yes

**Comment by ps2270** [comment]
CAG done
