### ISSUE TITLE
Translation of la plante des pied and spelling of ochre

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1387]
la plante des pieds is  translated as sole of the feet [not English- would be soles of the feet].  Do we care?

 we use Ochre, whereas Ocher is the more usual US spelling. do we care?

**Comment by TillmannTaape** [comment]
I suggest changing to soles.

If "ocher" is merely a more usual spelling, and "ochre" is acceptable US spelling, I don't think we need to change. But there are only 10 instances so it wouldn't take a minute.

**Comment by ps2270** [comment]
And it's actually inconsistent, so let's change all to ocher.

Let's change sole to soles. Can you please do that, Tillman?
Thanks

**Comment by TillmannTaape** [comment]
Changed 2 instances of sole**s** of the feet and 10 ochre to ocher.
