### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#139]
> Should unicode characters be marked as figures, such as the symbol for oz and dram? Markup teams continued to do this, but want to discuss this and make a decision. [It doesn’t make sense for them to be figures, some of us think]

**DECISION**:
no, unicode symbols do not need to be marked up as figures. Remove from any existing cases (thumbnail picture doesn’t have to go in)
-- see #121
**But** might need alt text tags to make sure a search for eg ‘mercury’ also picks up the symbols
See #55

Need a glossary subset of abbreviations/measurement symbols and alchemical symbols; these should also come up as a roll-over comment in the text 
 See the table of symbols in the [2018 Markup Protocol](https://docs.google.com/document/d/1DJ8BcCft5fwwMTNAImyaTuYpK--ht8JxaT2VEm-7kfk/edit)
Transferred to #122

**Comment by njr2128** [comment]
The one persistent action item of this issue has become:
Create alt text for each unicode symbol based on meaning

**Comment by tcatapano** [comment]
OK. This depends a lot on how @NickLaiacona would recommend for implementing the desired search functionality. But any solution would probably depend on having matching "labels" for each symbol. To that end we should prepare a table providing that mapping.

**Comment by njr2128** [comment]
Agreed. See csv files in https://github.com/cu-mkp/m-k-manuscript-data/tree/master/reference_docs for relevant tables

**Comment by njr2128** [comment]
Transferred to https://github.com/cu-mkp/making-knowing-edition/issues/152
Normalization/word association of symbols like "dram" or "mercury"
