### ISSUE TITLE
add part attribute to div

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1393]

**Comment by njr2128** [comment]
@tcatapano, I believe this has been done, right?

**Comment by tcatapano** [comment]
@njr2128 yes, as part of #1457 

and see:

https://github.com/cu-mkp/m-k-manuscript-data/blob/43fa7c98cb96c8e55fbc1a7b2947ee4560c33446/schema/ms-transcription.rng#L377-386
