### ISSUE TITLE
remove period after fig_p022v_2?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1403]
in all three versions, there is a period after this inline figure. 

The figure is immediately followed by "& through these notches one passes"  - the "&" could be taken to start a new sentence (hence the period). 

However, I think the sentence - while a little long - still makes sense without this period. And as it renders now, it looks a little odd:

![image](https://user-images.githubusercontent.com/14779727/70549837-dc895280-1b42-11ea-98a5-17c0363f881f.png)

@ps2270, what do you think?

**Comment by ps2270** [comment]
definitely take out the period. Thanks.

**Comment by njr2128** [comment]
Done!
