### ISSUE TITLE
tl entry at top of ann_031_fa_15_Yi_DamaskedCloth?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1425]
Is there a reason that this annotation has kept the quoted entry at the top of the essay before the text?
We have removed this quotes from all other essays

**Comment by ps2270** [comment]
For a couple of the annotations, I wanted the text at the beginning of the essay b/c it was important and not otherwise quoted in the essay.  Please leave these two or three annotations as I have edited them.
