### ISSUE TITLE
Glossary transformation to csv/json

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#143]
Work and strategy TBD.

Need to transform long VOCAB list googledoc (really a thesaurus and/or principles of translation etc.) into a form that can be used in the DCE as a thesaurus, index, glossary

**Comment by njr2128** [comment]
See also #54

**Comment by Pantagrueliste** [comment]
scope of features still need to be discussed and determined by editorial team

**Comment by njr2128** [comment]
And to SKOS? See #50 mock up SKOS version of vocab

**Comment by njr2128** [comment]
This is the current working document for the glossary in tabular form: [DCE-glossary-table](https://docs.google.com/spreadsheets/d/1qexNvJ5bG5Mr9_MtH7QHN4o0uBKG_iHw48lJ-lGwero/edit?usp=sharing) found in the GD

**Comment by njr2128** [comment]
@tcatapano to provide @NickLaiacona with either csv or json version of the DCE-glossary-table so that Nick can start testing features/interface

**Comment by njr2128** [comment]
Probable most relevant columns are with a blue header (others will likely be eliminated)
