### ISSUE TITLE
identify quote on 166r by Titus Flavius Josephus?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1441]
We do not seem to have identified the quote referred to by the AP on 166r, where he states:
> excuse yourself based on the words of the ancient Hebrews quoted by Josephe
> excuse toy sur le dire des anciens Hebrieulx recité par Josephe.

Right now ed comment c_166r_04 simply states it is unidentified.

Can we identify this quote?

**Comment by ps2270** [comment]
Delete the comment. We can leave this as low priority, but pls delete the comment.

**Comment by njr2128** [comment]
Added as an action item for me and @thuchacz.

Will keep issue open as low priority

**Comment by njr2128** [comment]
comment now reads:
>Titus Flavius Josephus, also known as Yosef ben Matityahu (1st c. CE): Jewish priest, soldier, and historian based in Rome. The quotation in Josephus has not been identified. See josephus1486

Leaving open as low priority for future identification

**Comment by njr2128** [comment]
done - other people can do this!
