### ISSUE TITLE
<del>s in TL

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1459]
FRom @Pantagrueliste 
Reading through TL made me realize the extent to which translated deletions can be problematic. They are translated inconsistently, many—if not most—of them do not provide much insight into the manuscript, and I’m concerned that the "noise” they produce will ultimately confuse, distract, and sometimes even mislead the reader. These translated deletions, moreover, seem to be based on the very questionable assumption that phonological, morphological and syntactical errors can be consistently translated from one language to another. How do we intend to justify this editorial choice?
As editors, our primary role is to establish a text. Yet if we transcribe and translate every single deletion into the TL, without explaining why, we seem to be evading this responsibility. 
While I share the enthusiasm of highlighting deletions in the TL, I think that the way we are doing it is not satisfactory, and I’m afraid that we would need, at some point, to synthesize all the information regarding deletions, in order to keep only the ones that we editors believe to be relevant for the reader. This would probably imply the deletion of `<del>` tags in TL and the addition of editorial comments whenever necessary. 

E.g., 62v partial translation with incomplete french word
>Also, to make plumb lines, which go from the top <del>to make <fr>vif</fr></del> to the bottom

**Comment by njr2128** [comment]
From 2019-12-18 meeting notes:
Future feature request:

- Different del tags for TL in order to “turn them off” and not show them at all, or signal in some other way that there is an intervention in the original
- Evaluating deletions on a case-by-case basis for what is editorially significant?
- New, different xml versions of the text available for users (in github)?

**Comment by ps2270** [comment]
I added a note about this in the Principles of Translation.

**Comment by njr2128** [comment]
Keeping open for the following thoughts:

From 2019-12-18 meeting notes:
Future feature request:

- Different del tags for TL in order to “turn them off” and not show them at all, or signal in some other way that there is an intervention in the original
- Evaluating deletions on a case-by-case basis for what is editorially significant?
- New, different xml versions of the text available for users (in github)?

**Comment by ps2270** [comment]
@thuchacz considered whether to display them in some other way.

**Comment by njr2128** [comment]
Another update: as of this posting, all "partial" deletions have been amended so that if only part of a French word is written and deleted - even if a translator could infer the intended complete word - it has been kept in French. No partial English words have been preserved from earlier translation campaigns.
e.g., if the French was 
> `<del>`lesar`</del>`

The English is NOT
> `<del>`lizar`</del>`

but instead
> `<del><fr>`lesar`</fr></del>`
