### ISSUE TITLE
Rendering/ margin block issues

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1465]
It's possible these are already known issues that have not yet been fixed, but I am logging them here
25r: bottom margin should be full width

**Comment by thuchacz** [comment]
The markup is correct: 
`<ab margin="bottom" render="full">`

We are now waiting on Nick to implement a "full" option for the "render" attribute, per [#447](https://github.com/cu-mkp/making-knowing-edition/issues/447)

**Comment by njr2128** [comment]
This has been completed
