### ISSUE TITLE
pull new element-counts comparison

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1469]
To review the work completed in #103 by THU, TT, and CAG - pull new comparison el-counts

**Comment by njr2128** [comment]
File with inconsistencies is https://github.com/cu-mkp/manuscript-object/blob/master/property_count.csv

@njr2128 to go through and correct mistakes in xml

**Comment by njr2128** [comment]
45v_tcn - about halfway down is missing "canon"

**Comment by njr2128** [comment]
To track as I go through the 

- [ ] 008v_2
- [ ] 008v_3
- [ ] 017r_1
- [ ] 020r_1
- [ ] 020r_2
- [ ] 036r_1
- [ ] 045v_1
- [ ] 045v_2
- [ ] 053v_1
- [ ] 058v_4
- [ ] 060r_3
- [ ] 081r_1
- [ ] 081r_4
- [ ] 082v_3
- [ ] 082v_4
- [ ] 084r_5
- [ ] 086v_1
- [ ] 086v_1
- [ ] 086v_1
- [ ] 092r_4
- [ ] 093r_5
- [ ] 094r_1
- [ ] 094r_1
- [ ] 094r_1
- [ ] 094r_1
- [ ] 098r_2
- [ ] 098r_3
- [ ] 098v_1
- [ ] 098v_4
- [ ] 104v_3
- [ ] 105r_4
- [ ] 105v_1
- [ ] 105v_3
- [ ] 106v_2
- [ ] 106v_3
- [ ] 107r_1
- [ ] 107r_1
- [ ] 108r_2
- [ ] 108r_2
- [ ] 110r_1
- [ ] 110r_3
- [ ] 111r_1
- [ ] 111r_5
- [ ] 114r_1
- [ ] 114r_1
- [ ] 114r_1
- [ ] 115v_1
- [ ] 115v_1
- [ ] 115v_1
- [ ] 116r_4
- [ ] 116r_4
- [ ] 116v_2
- [ ] 116v_2
- [ ] 116v_2
- [ ] 117r_1
- [ ] 118v_1
- [ ] 120v_6
- [ ] 120v_6
- [ ] 123r_1
- [ ] 124r_3
- [ ] 125r_1
- [ ] 125r_2
- [ ] 125r_2
- [ ] 126r_1
- [ ] 126v_2
- [ ] 127v_1
- [ ] 127v_1
- [ ] 139r_1
- [ ] 159r_3
- [ ] 161r_1
- [ ] 163r_1
- [ ] 164v_2
- [ ] 166r_1
- [ ] 166r_1
- [ ] 166r_1
- [ ] 166r_1
- [ ] 167r_1
- [ ] 170v_2

**Comment by njr2128** [comment]
All changes have been made except one. The only outstanding issue is #1883 as of this posting

**Comment by njr2128** [comment]
All changes have been completed.

@gschare, can you create a new count for the state of ms-xml now? I would like to make sure we caught all inconsistencies and that I did not miss or introduce mistakes.

**Comment by gschare** [comment]
I ran the property counts again. [Here is the output.](https://github.com/cu-mkp/manuscript-object/blob/master/property_count.csv)

**Comment by njr2128** [comment]
@gschare, thank you! Just completed these fixes. Can you run again?
[property_count2.xlsx](https://github.com/cu-mkp/m-k-manuscript-data/files/5129880/property_count2.xlsx)

**Comment by gschare** [comment]
I ran it again and there are no more discrepancies! First time a division-by-zero error has been a good thing!
[Proof](https://github.com/cu-mkp/manuscript-object/blob/master/projects/issue1469/property_count.csv)

**Comment by njr2128** [comment]
Marvelous! Amazing, @gschare
