### ISSUE TITLE
Assign titles and preferred folios for intro essays 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1470]
Enter in editing+revisions tab of **Intro-essays_tracking+metadata**

NJR will pull finalized info to metadata

**Comment by ps2270** [comment]
Titles done as best I can for now (without the actual essays). I will work on folios next.

**Comment by ps2270** [comment]
Folios done for all that are possible

**Comment by njr2128** [comment]
done
