### ISSUE TITLE
folio links for annotation abstracts with no explicit folios

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1477]
After finishing #1468, outstanding questions about essays that do not deal with outright folios (and thus not mentioned in the abstract) but that have been assigned associated entries (so they appear in folio view). Individual comments assigned to @ps2270 for each essay, and also logged in **annotation metadata** in "editing+revisions" tab (currently column BH).

Add references in the abstract?
Leave as is?

**Comment by ps2270** [comment]
Generally, no need to mention page numbers in the abstracts, but I'll check each one.

**Comment by ps2270** [comment]
I completed this, but will leave it to you, @njr2128, to close.

**Comment by njr2128** [comment]
Done and updated in editing+revisions.
One outstanding question move to #1487
