### ISSUE TITLE
marginal text, additions, and marks

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1480]
For subsequent campaign (i.e., after release):
skim folio by folio, assessing whether:
1. marginal text is/isn't of the status of an addition (`<add>`). For instance, is it a full sentence or a phrase meant to be inserted into the body of the text at the point of an insertion mark, as on fol. 121v or 154v? This can help us refine our "markup protocol" definition of what constitutes an "addition"
2. insertion marks linking margin text to body text have consistent editorial comments to help the reader navigate.
3. in those cases where insertion marks only exist in the body text or the margin there should be a double set of editorial comments that link the text of the insertion mark to the place of insertion. For instance, on 154v, we only have a note on the insertion mark, not on the margin text to be inserted because the A-P (forgot?) did not put a corresponding mark on the margin text.

**Comment by njr2128** [comment]
see #1577

**Comment by thuchacz** [comment]
This has been undertaken as part of the render check campaign by PHS, CC, NJR, and THU.

Closing.
