### ISSUE TITLE
Bergen essay - needs creation of correct fieldnotes page

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1502]
Katie Bergen, “Bergen Text Comparison Table - Full,” Field Notes, Making and Knowing Project, last modified November 6, 2019, 
The wrong page has been converted to fieldnotes
(WRONG PAGE: http://fieldnotes.makingandknowing.org/2018-Fall/Bergen-Annotation_Workflow_FA18/Bergen-Annotation_Workflow_FA18.html)
CORRECT GD Doc:  https://docs.google.com/spreadsheets/d/11KHfRYhJmSaWLkNTU4tf2zbfzx2tfq7DISfyYQ3GKNw/edit#gid=1393957895

@njr2128 or @caro27  can you create a fieldnotes page for the GD link above and let me know so I can link it in Bergen essay?

**Comment by njr2128** [comment]
new fieldnotes created and both essay text and bib have been updated with new URL:
http://fieldnotes.makingandknowing.org/2018-Fall/Bergen-Annotation_Workflow_FA18/FA18_FieldNotes_BergenTextComparisonTableFull.html.
