### ISSUE TITLE
change "w" to omega in bib ref of firmicus1533

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1514]
https://github.com/cu-mkp/m-k-manuscript-data/blob/29257a0189bd68af44e7dd6234f09289d273feea/bibliographies/dce-comment-tracking/dce-comment-tracking.bib#L393

We believe "Astronomicwn Lib. VIII" is not with a "w" but instead an omega

**Comment by Pantagrueliste** [comment]
Δονε
