### ISSUE TITLE
need bib reference for bib keys

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1515]
Cannot locate a reference for the key " damascenus1593" in either comments bib or glossary bib.
What is this reference?

**Comment by njr2128** [comment]
same for scriptores1490

**Comment by njr2128** [comment]
same for all of Budaeus:
bude1548
bude1574
bude1551
bude1522

**Comment by njr2128** [comment]
also norri2016

**Comment by njr2128** [comment]
also  gilson1960

**Comment by njr2128** [comment]
also polybius1582

**Comment by njr2128** [comment]
also porzio1549

**Comment by thuchacz** [comment]
also magnus1495

**Comment by njr2128** [comment]
also 
otto1515 and 
otto1569

**Comment by thuchacz** [comment]
also mercuriale1588

**Comment by njr2128** [comment]
also burchard1537

**Comment by Pantagrueliste** [comment]
OK, I'm on it.

**Comment by Pantagrueliste** [comment]
porzio1549,  polybius1582 are actually in the current version of [dce-comment-tracking.bib ](bibliographies/dce-comment-tracking/dce-comment-tracking.bib) -- trying to figure out where the other references have gone...

**Comment by thuchacz** [comment]
Okay. Great.
Since NJR is off work today and tomorrow, @Pantagrueliste, could you please send me a list of all these specific references (either pasted here or by email), formatted in footnote style, so I can insert them in the comments table before the content freeze?
Thanks!

**Comment by Pantagrueliste** [comment]
no problem

**Comment by thuchacz** [comment]
One more thing:
Could you please add an item to the bibliography for Ed Comments?
Servius1522
https://www.ustc.ac.uk/editions/862711

**Comment by Pantagrueliste** [comment]
Sure thing. servius1522

**Comment by Pantagrueliste** [comment]
Sure thing. servius1522

**Comment by Pantagrueliste** [comment]
- [x] damascenus1593
- [x] scriptores1490
- [x] bude1548
- [x] bude1574
- [x] bude1551
- [x] bude1522

**Comment by Pantagrueliste** [comment]
changed gilson1960 to gilson1969

**Comment by Pantagrueliste** [comment]
1.  Guillaume Budé, *Commentarii linguae graecae. Accurate recogniti,
    atque amplius tertia parte aucti* (Paris: Robert Estienne,
    1548).

2.  Guillaume Budé, *Epistolai hellēnikai. Epistolae graecae*, ed.
    Guillaume Plançon, trans. Antonius Pichonius (Paris: Jean Bienné,
    1574).

3.  Guillaume Budé, *Annotationes in xxiiii pandectarum libros* (Lyon:
    Sébastien Gryphe,
    1551).

4.  Guillaume Budé, *Libri v de asse, et partib. Eius post duas
    parisienses impressiones ab eodem ipso budaeo castigati, idque
    authore io. Grolierio lugdunensi christianissimi gallorum copiarum
    quaestore, cui etiam ob nostram in eum observantiam a nobis illi
    dicantur* (Venice: Torresano, Andrea; Aldo Manuzio,
    1522).

5.  Burchard of Ursperg, *Chronicum abbatis urspergensis, a nino rege
    assyriorum magno, usque ad fridericum ii.romanorum imperatorem, ex
    optimis autoribus recognitum, et innumeris mendis repurgatum*
    (Strasbourg: Kraft Müller,
    1537).

6.  Nicolaus Damascenus and Johannes Stobaeus, *Ex nicolai damasceni
    vniversali historia sev de moribus gentium libris excerpta iohannis
    stobaei*, ed. Nicolaus Cragius (Geneva: Santandreanus,
    1593).

7.  Etienne Gilson, *L’esprit de la philosophie médiévale* (Paris: Vrin,
    1969).

8.  Girolamo Mercuriale, *Liber responsorum et consultationum
    medicinalium* (Basel: Konrad von Waldkirch,
    1588).

9.  Juhani Norri, *Dictionary of medical vocabulary in english,
    1375-1550: Body parts, sicknesses, instruments, and medicinal
    preparations* (London: Routledge,
    2016).

10. Otto Frisingensis and Benedictus Chelidonius, *Rerun ab origine
    mundi ad ipsius usque tempora gestarum, libri octo. Eiusdem de
    gestis friderici primi aenobarbi caes.aug. Libri duo. Radevici
    phrisingen. Ecclesie canonici libri duo, prioribus additi, de eiusd
    friderici imp. Gestis* (Strasbourg: Matthias Schürer,
    1515).

11. Otto Frisingensis et al., *De eiudem frid. Gestis libri ii de gestis
    friderici i. Caes. Aug. Libri duo libri duo de eiusdem friderici
    imp. Gestis ligurini de gestis imp. Caesaris friderici primi augusti
    libri decem ligurinus, sive de gestis friderici, libri x. Ottonis
    episcopi frisingensis leopoldi pii marchionis austriae f.chronicon,
    sive rerum ab orbe condito ad sua usque tempora gestarum, libri
    octo. Eiusdem de gestis friderici i.caes.aug.libri duo. Radeuici
    frising.canonici de eiusdem frid. Gestis libri ii. Priorib.additi.
    Guntheri poëtae ligurinus, sive de gestis friderici, libri x. Addita
    sunt et alia, cum ad friderici, tum ad posteriorum imperatorum
    historiam pertinentia, adiectis etiam notis et indice accurato*
    (Basel: Peter Perna,
    1569).

12. Gaius Suetonius Tranquillus et al., *Caius suetonius tranquillus:
    Vitae xii caesarum. Aelius spartianus: De vita hadriani; julius
    capitolinus, vulcatius gallicanus, aelius lampridius, trabellius
    pollio and flavius vopiscus: De regum ac imperatorum romanorum*
    (Venice: Johannes Rubeus Vercellensis,
    1490).

13. Publius Vergilius Maro et al., *Vergilius cum commentariis et
    figuris p. Vergilii maronis, bucolica, georgica, aeneis cum servii
    commentariis accuratissime emendatis in quibus multa quae adhuc
    deerant sunt adiecta et graecae dictiones ac verius ubique
    restituti. Additus est etiam probicelebris grammatici in bucolica &
    georgica perutilis commentariolus recens castigatus. Nec non
    commentarii donati, mancinelli et ascensii. Insunt praeterea
    beroaldi annotationes et augustini dathi in aeneidem praefatio.
    Atque ut studiosis nihil amplius desiderent adiuncta sunt opuscula
    omnia sive lusus vergiliani tum a domitio calderino tum ab ascensio
    perspicue declarati. Res vero totius operis adeo graphice imaginibus
    exprimuntur ut non minus geri videantur quae legi possint* (Venice:
    Gregorio De Gregori; Lucantonio Giunta,
    1522).
