### ISSUE TITLE
update Ed Comments tracking sheet

### ISSUE THREAD

**Issue by caro27** [cu-mkp/m-k-manuscript-data#1519]
Search table for "Debuiche" and add Sarah Muñoz's name to the comment as an author for "Contexte toulousain" essay. ALSO back add this to sheet 2, which still contains the bibliographic keys.

**Comment by njr2128** [comment]
Done. Also backwards corrected the sheet ARCHIVE_2020-01-13_Tracking (the only one that had this reference with author names)
