### ISSUE TITLE
Bibliography--fine tuning

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1521]
Cornelius Agrippa von Nettesheim, *De occulta philosophia* (Cologne:
    Johann Soter, 1533).

  Alessandro Alessandri, *Genialium dierum libri sex, varia ac
    recondita eruditione referti, accuratius et majore fide quam antehac
    usquam impressi cum duplici indice* (Paris: Jean de Roigny, 1549).

  Appianus Alexandrinus, *Historia Romana* (Venice: Bernhard Maler;
    Erhard Ratdolt; Peter Löslein, 1477).

  Alexander Aphrodisiensis, *Problemata* (Venice: Antonius de Strata, n.d.).

  Athenaeus Naucratites, *Deipnosophistou ten polumathestaten
    pragmateian nun exesti soi es gnosis elthein* (Venice: Aldo Manuzio;
    Andrea Torresano, 1514).

  Athenaeus Naucratites, *Dipnosophistarum sive Coenae sapientum libri
    XV*, ed. Natale Conti (Venice: Andrea Arrivabene, 1556).

  Ermolao Barbaro, *Castigationes Plinianae et Pomponii Melae* (Rome:
    Eucharius Silber, 1493).

  Iunior Barbaro Hermolao and Hieronymus Wildenberg, *Naturalis
    scientiae totius compendium : ex Aristotele, & alijs philosophis*
    (Basel: Oporinus, 1548).

  Pietro Angelo Bargeo, *Petri Angelii ... Cynegetica. Item carminum
    libri II, eglogae III* (Lyon: haeredes S. Gryphii, 1561).

 Pietro Angelo Bargeo, *De aucupio liber primus* (Florence: Giunti, 1566).

 Cassianus Bassus, *Constantini Caesaris selectarum praeceptionum, De
    agricultura libri viginti, Iano Cornario medico physico interprete*
    (Basel: Hyeronimus Frobenius, 1538).

 François de Belleforest, *Les grandes annales, et histoire générale
    de France, de la venue des Francs en Gaule, iusques au regne du roy
    très-chrétien Henry III* (Paris: Gabriel Bon, 1579).

 Giovanni Nanni da Viterbo, *I cinque libri de le antichita* (Venice:
    Baldassare Constantini, 1550).

 Flavio Biondo, *Italia illustrata* (Rome: Johannes Philippus de Lignamine, 1474).

 Flavio Biondo, *Roma triumphans* (Brescia: Vercellensis, Bartholomaeus, 1482).

 Flavio Biondo, *Roma instaurata. De origine et gestis Venetorum.
    Italia illustrata* (Verona: Boninus de Boninis, 1482).

 Flavio Biondo, *Historiarum ab inclinatione Romanorum imperii
    decades* (Venice: Thomas de Blavis, 1484).

 Flavio Biondo, *Roma instaurata* (Turin, 1527).

 Marjolijn Bol, “Perspective as Practice: Renaissance Cultures of
    Optics,” ed. Sven Dupré (Turnhout: Brepols, 2019), 71–

 Philibert Boyer, *Instruction pour le faict des finances* (Paris:
    Ambroise Drouart; Guillaume Le Noir, 1581).

 George Buchanan, *Rerum Scoticarum historia auctore Georgio
    Buchanano Scoto* (Edinburgh: Alexander Arbuthnet, 1582).

 Procopius Caesariensis, *De rebus Gothorum, Persarum ac Vandalorum
    libri VII* (Basel: Johannes Hervagius, 1531).

 Vincenzo Cartari, *Les images des dieux*, ed. Antoine du Verdier
    (Lyon: Guichard Julliéron, 1584).

 Franck Collin, “Antonio Telesio de Cosenza, Petit traité des
    couleurs latines (De coloribus libellus), éd. Michel Indergand et
    Christine Viglino,” Cahiers de recherches médiévales et humanistes,
    2010, <http://journals.openedition.org/crm/12315>.

 Philippe de Commynes, *Cronicque et histoyre* (Paris: François
    Regnault; Pierre Gadoul, 1529).

 Gilles Corrozet, *Le Cathalogue des villes et citez assises es troys
    Gaulles, avecq ung traicté des fleuves et fontaines, illustré de
    nouvelles figures* (Paris: Denis Janot, 1538).

 Camille Daux, *Histoire de l’Eglise de Montauban* (Paris: Bray et Retaux, 1881).

 Philibert Delorme, *Nouvelles inventions pour bien bastir et a
    petits fraiz* (Paris: Fédéric Morel, 1561).

 Denis Diderot and Jean le Rond d’Alembert, *Encyclopédie, ou
    Dictionnaire raisonné des sciences, des arts et des métiers*, vol. 7
    (Paris: Briasson, 1770).

 Dionysius Halicarnassensis, *Antiquitates Romanae* (Treviso:
    Bernardinus Celerius, 1480).

 Rembert Dodoens, *Trium priorum de stirpium historia commentariorum
    imagines ad vivum expressae una cum indicibus, Graece, Latine,
    officinarum, Germanica, Brabantica Gallicaque nomina
    complectentibus* (Antwerp: Jan van der Loe, 1553).

 Paolo Emili, *De rebus gestis Gallorum libri IX ad historiam Pauli
    Aemylii additi, perducta historia usque ad tempora Henrici II,
    Francorum regis*, trans. Arnoul Le Ferron (Paris: Michel de
    Vascosan, 1555).

 Herodotus, *Herodoti Halicarnassei Historiæ lib. IX. et de vita
    Homeri libellus. Illi ex interpretatione L. Vallæ adscripta, hic ex
    interpretatione C. Heresbachii: utraque ab H. Stephano recognita. Ex
    Ctesia excerptæ historiæ*, ed. Lorenzo Valla and Henri Estienne
    (Paris: Henri Estienne; Ulrich Fugger, 1566).

 Sextus Pompeius Festus and Marcus Verrius Flaccus, *Quae extant. Et
    Sex. Pompei Festi De verborum significatione, libri XX. In eundem
    Festum annotationes. Index rerum obiter dictarum. Ex bibliotheca
    Antonii Augustini* (Venice: Giovanni Maria Bonelli; Giordano Ziletti, 1560).

 Julius Firmicus, *Astronomicon Lib. VIII* (Basel: Johannes Herwagen, 1533).

 Jacopo Filippo Foresti, *Supplementum chronicarum* (Venice:
    Bernardinus Rizus, 1493).

 Jacopo Filippo Foresti, *Novissime hystoriarum omnium repercussiones
    noviter a reverendissimo patre Iacobophilippo Bergomense Ordinis
    heremitarum edite: que Supplementum supplementi cronicarum
    nuncupantur. Incipiendo ab exordio mundi usque in annum salutis
    nostre MCCCCCII* (Venice: Albertino da Lessona, 1585).

 Sigebert de Gembloux, *Chronicon ab anno 381 ad 1113, cum
    insertionibus ex historia Galfridi et additionibus Roberti, abbatis
    Montis, centum et tres sequentes annos complectentibus, promovente
    egregio patre D. G. Parvo,... nunc primum in lucem emissum* (Paris:
    Henri Estienne; Jean Petit, 1513).

 Conrad Gessner, *De omni rerum fossilium genere, gemmis, lapidibus,
    metallis, et huiusmodi, libri aliquot, plerique nunc primum editi*
    (Zürich: Hans Jakob Geßner, 1566).

 Paolo Giovio, *De Romanis piscibus libellus ad Ludovicum Borbonium
    cardinalem amplissimum* (Rome: Francesco Minizio Calvo, 1524).

 Paolo Giovio, *Descriptio Britanniae, Scotiae, Hyberniae, et
    Orchadum, ex libro Pauli Iouii, episcopi Nucer. de imperiis, et
    gentibus cogniti orbis, cum eius operis prohoemio* (Venice: Michele Tramezzino, 1548).

 Paolo Giovio, *Elogia virorum bellica virtute illustrium veris
    imaginibus supposita, quae apud Musaeum spectantur. Volumen digestum
    est in septem libros* (Florence: Lorenzo Torrentino, 1551).

 Claude Guichard, *Funérailles et diverses manieres d’ensevelir des
    Romains, Grecs, et autres nations* (Lyon: Jean de Tournes, 1581).

 Jules Guiffrey, *Artistes parisiens des XVIe et XVIIe siècles:
    Donations, contrats de mariage, testaments, inventaires, etc. Tirés
    des insinuations du Châtelet de Paris* (Paris: Imprimerie nationale, 1915).

 Gaius Iulius Hyginus, *Fabularum liber eiusdem poeticon
    astronomicon, libri quatuor* (Basel: Johannes Herwagen, 1535).

 Irenaeus Lugdunensis and Nikolaus Episcopius, *Opus in quinque
    libros digestum, in quibus mire retegit & confutat veterum haereseon
    impias ac por tentosas opiniones, ex vetustissimorum codicum
    collatione quantum licuit emendatum opera Des. Erasmi Roterodami, ac
    nunc eiusdem opera denuo recognitum, correctis iis quae prius
    suffugerant. Additus est index rerum scitu dignarum.*, ed. Erasmus
    Roterodamus (Basel: Hieronymus Froben, 1534).

 Flavius Josephus, *De antiquitate Judaica. De bello Judaico.*, ed.
    Rufinus Aquileiensis and Girolamo Squarciafico (Venice: Johannes
    Rubeus Vercellensis, 1486).

 Guy Michel-Leproux, *La Peinture à Paris sous le règne de François
    Ier* (Presses de l’Université de Paris Sorbonne, 2001).

 Guy-Michel Leproux, “Quelques éclairages sur la vie et la carrière
    de Jean Cousin le jeune,” *Documents d’histoire parisienne* 12 (2011): 23–

 Titus Livius, *Historiae Romanae ab urbe condita, libri  quotquot
    ad nostram aetatem peruenerunt, cum commentariis omnium interpretum
    ad explicationem locorum difficilium, e regione insertis* (Paris:
    Jean Charron; Michel Sonnius, 1573).

 Titus Livius, *Les décades*, ed. Blaise de Vigenère, Jean Hamelin,
    and Antoine de La Faye (Paris: Jacques du Puys, 1583).

 Ambrosius Aurelius Theodosius Macrobius and Arnoldus Haldrenius
    Vesaliensis, *In somnium Scipionis, libri II. Saturnaliorum,
    libri VII. Ex variis, ac vetustissimis codicibus recogniti et aucti*
    (Lyon: Sébastien Gryphe, 1556).

 Raffaele Maffaei, *Commentariorum urbanorum octo et triginta libri,
    cum duplici eorumdem indice secundum tomos collecto* (Lyon:
    Sébastien Gryphe, 1552).

 Raffaele Maffei, *Commentariorum urbanorum Raphaelis Volaterrani,
    octo et triginta libri, accuratius quam antehac excusi, praemissis
    eorundem indicibus secundum tomos ut ab autore conscripti fuerunt:
    quibus accessit novus, res ac voces in philologia explicatas
    demonstrans, quo superiores editiones carebant hactenus. Item
    oeconomicus Xenophontis, ab eodem latio donatus* (Basel: Hieronymus
    Froben; Nikolaus Episcopius, 1559).

 Raffaele Maffaei, *Commentariorum Urbanorum octo et triginta libri*
    (Basel: Johannes Frobenius, 1559).

 Girolamo Maggi, *Cinque primi canti della guerra di Fiandra di m.
    Gierolamo Magi d’Anghiari al valoroso signor Chiappino Vitelli.
    Nuovamente dati in luce (Venezia, Comin da Trino : al segno del
    Diamante, 1551)* (Venice: Comin da Trino, 1551).

 Girolamo Maggi, *Variarum lectionum, seu Miscellanorum libri IIII.
    In quibus multa auctorum loca emendantur, atque explicantur, & quae
    ad antiquitatem cognoscendam pertinent, non pauca afferuntur (Venice: Giordano Ziletti, 1564).

 Girolamo Maggi and Giacomo Castriotto, *Della fortificatione delle
    città, di m. Girolamo Maggi, e del capitan Iacomo Castriotto,
    ingegniero del christianissimo re di Francia, libri III. Ne’ quali,
    oltra le molte inventioni di questi autori, si contiene tutto quello
    di più importanza, che fino ad hora è stato scritto di questa
    materia; con infinite cose, che da molti signori, capitani, &
    ingegnieri dell’età nostra si sono havute. Discorso del medesimo
    Maggi sopra la fortificatione degli alloggiamenti degli esserciti.
    Discorso del capitan Francesco Montemellino sopra la fortificatione
    del borgo di Roma. Trattato dell’ordinanze, ò vero battaglie del
    capitan Giovacchino da Coniano. Ragionamento del sudetto Castriotto
    sopra le fortezze della Francia* (Venice: Borgominieri, Rutilio, 1564).

 Paolo Manuzio, *Lettere volgari di M. Paolo Manutio divise in quattro libri* (Venice: Paolo Manuzio, 1560).

 Paolo Manuzio, *Antiquitatum Romanarum Paulli Mannuccii liber de senatu* (Venice: Paolo Manuzio, 1581).

 Marbodus Redonensis, *Libellus de lapidibus preciosis* (Vienna: Hieronymus Vietor, 1511).

 Nonius Marcellus, *De proprietate sermonum: jam demum innumeris locis restitutus, multis locupletatus, ope vetustissimorum codicum, & industria. Additus est in calce libellus de prisco sermone repurgatus: index vocabulorum De proprietate sermonum: jam demum innumeris locis restitutus, multis locupletatus, ope vetustissimorum codicum, & industria. Additus est in calce libellus de prisco sermone repurgatus: index vocabulorum* (Antwerp: Christophe Plantin, 1565).

 *Kompost et kalendrier des bergiers* (Paris: Guy Marchant, 1491).

 Justinus Martyr, *Τοῦ ἁγίου Ἰουστίνου φιλοσόφου καὶ μάρτυρος, Ζήνᾳ καὶ Σερήνῳ ;
Λόγος παραινετικὸς πρὸς Ἕλληνας ; Πρὸς Τρύφωνα Ἰουδαῖον διάλογος ;
Ἀπολογία ὑπὲρ χριστιανῶν πρὸς τὴν Ῥωμαίων σύγκλητον ; Ἀπολογία Β’ ὑπὲρ
χριστιανῶν πρὸς Ἀντων ῖνον τὸν Εὐσεβῆ ; Περὶ Θεοῦ μοναρχίας ; Ἔκθεσις
πίστεως περὶ τῆς ὀρθῆς ὁμολογίας, ἤτοι περὶ τῆς ἁγίας καὶ ὁμοουσίου
Τριάδος ; Ἀνατροπὴ δογμάτων τινῶν Ἀριστοτελικῶν ; Ἐρωτήσεις Χριστιανικαὶ
πρὸς τοὺς Ἕλληνας, καὶ ἑλληνικαὶ ἀποκρίσεις, καὶ τῶν αὐτῶν ἀποκρίσεων
ἔλεγχοι ; Ἀποκρίσεις πρὸς τοὺς ὀρθοδόξους περὶ τινῶν ἀναγκαίων ζητημάτων
; Ἐρωτήσεις ἑλληνικαὶ πρὸς τοὺς Χριστιανοὺς περὶ τοῦ ἀσωμάτου, καὶ περὶ
τοῦ Θεοῦ, καὶ περὶ τῆς ἀναστάσεως τῶν νεκρῶν, καὶ πρὸς τὰς αὐτὰς
ἐρωτήσεις ἀποκρίσεις Χριστιανικαί : ex Bibliotheca Regia*. (Paris: Robert Estienne, 1551).

 Justinus Martyr, *Opera non ita pridem Graece edita, nuper verò
    Latinè reddita* (Basel: Hieronymus Froben; Nikolaus Episcopius, 1555).

 Andreas Masius, *Josuae imperatoris historia illustrata atq.
    explicata ab Andrea Masio* (Antwerp: Christophorus Plantinus, 1574).

 Pietro Andrea Mattioli and Jean des Moulins, *Commentaires de M.
    Pierre André Matthiole médecin sennois, sur les six livres de Ped.
    Dioscoride Anazarbeen de la matière médicinale : avec certaines
    tables médicinales, tant des qualités & vertus des simples
    médicamens, que des remèdes pour toutes maladies, qui peuvent avenir
    au corps humain, comme aussi des sentences, mots & matières
    traictées esdicts commentaires (\[Reprod.\]) / mis en français sur
    la dernière édition latine de l’auteur par M. Jean des Moulins,
    docteur en médecine* (Lyon: Guillaume Rouille, 1579).

 Valerius Maximus, *Facta et dicta memorabilia*, ed. Oliviero
    d’Arzignano (Venice: Guglielmus de Cereto, 1491).

 Jean-Pierre de Mesmes, *La Grammaire Italienne, composée en
    Françoys* (Paris: Gilles Corrozet; Étienne Groulleau, 1548).

 Dieter Nadolski, *Les étains anciens usuels: leur aspect et leur
    fonction pendant six siècles* (Paris: Nouvelles Editions Latines, 1986).

 Jean Nagerel, *L’histoire et cronique de Normandie* (Rouen: Martin
    Le Mégissier, 1581).

 Magnus Ollaus, *Historiae de gentibus septentrionalibus libri XXII*
    (Antwerp: Jean Bellère, 1552).

 Paulus Orosius, *Historiae adversus paganos* (Augsburg: Johannes
    Schüssler, 1471).

 Bernard Palissy, *Recepte veritable par laquelle tous les hommes de
    la France pourront apprendre a multiplier et augmenter leurs
    thresors* (La Rochelle: Barthélemy Berton, 1564).

 Bernard Palissy, *Discours admirables de la nature des eaux et
    fontaines, tant naturelles qu’artificielles, des métaux, des sels et
    salines, des pierres, des terres, du feu et des émaux* (Paris:
    Martin le jeune, 1580).

 Pausanias, *Veteris Graeciae descriptio. Romulus Amasaeus vertit*
    (Florence: Lorenzo Torrentino, 1551).

 Pausanias, *Paysaniu tes hellados periegesis. Hoc est, Pausaniae
    accurata Graeciae descriptio* (Frankfurt: Claude de Marne; Johann
    Aubry; Andreas Wechel, 1583).

 Quintus Curtius Rufus, *Historiae Alexandri Magni* (Venice: Johannes Tacuinus, 1496).

 Maurice Roy, *Jehan Cousin père, sculpteur : la statue de l’amiral
    Chabot et le jubé de la chapelle de Pagny* (Sens: Duchemin, 1909).

 Maurice Roy and Paul Vitry, *Artistes et monuments de la Renaissance
    en France. Recherches nouvelles et documents inédits* (Paris: Honoré
    Champion, 1929).

 Eusebius Caesariensis, *Historia ecclesiastica*, trans. Tyrannius
    Rufinus (Mantua: Johannes Schallus, 1479).

 Girolamo Ruscelli, *Secreti del reverendo donno Alessio Piemontese*
    (Venice: Sigismondo Bordogna, 1555).

 Girolamo Ruscelli, *Les secrets de reverend signeur Alexis
    piémontois contenans excellens remèdes contre plusieurs maladies vec
    la manière de faire distillation tr. de l’italien en françois*
    (Anvers: Christophe Plantin, 1557).

 *Prattica, cioe, Nova invenzione di conteggiare : ridotta à modo
    tanto facile, che ogn’uno potrà far ogni gran conto, si in vender,
    come in comperare, sia à misura, ò a peso, ò a qual si voglia altro
    modo, ad ogni sorte di precio, & moneta, per tutte le parti del
    mondo : serve anchora a commutar scudi, & ogni altra sorte di ori in
    lire, in grossi, in soldi, e in qual altro modo si vole, & cosi per
    il contrario : serve di piu à partir ogni sorte di cosa in piu
    parti, a far compartite di compagnie, et in somma à far ogni conto
    che l’huomo, si possa imaginare* (Brescia: Sabbio, Vincenzo, 1589).

 Marco Antonio Sabellico, *Le historie vinitiane divise in tre deche
    con tre libri della quarta deca*, trans. Lodovico Dolce (Venice:
    Curzio Troiano Navò, 1544).

 Marcus Antonius Sabellicus, *Rerum Venetarum ab urbe condita in
    universum opus* (Venice, 1487).

 Marcus Antonius Sabellicus, *De rerum et artium inventoribus poema*
    (Vienna: Hieronymus Vietor, 1521).

 Marcus Antonius Sabellicus, *Historiae rerum venetarum ab urbe
    condita, libri XXXIII. Eiusdem in singulos libros epitomae. Additus
    in fine est index rerum memorabilium copiosus* (Basel: Nikolaus Episcopius, 1556).

 Ippolito Salviani, *Aquatilium animalium historiae liber primus: cum
    eorundem formis, aere excusis* (Rome: Ippolito Salviani, 1554).

 Pierre de Savonne, *Nouvelle instruction d’Arithmétique abrégée
    propre à tous les Marchands et Banquiers* (Paris: Nicolas du Chemin, 1563).

 Paul J. Smith, “Solitudo: Spaces, Places, and Times of Solitude in
    Late Medieval and Early Modern Cultures,” ed. Enenkel K. A. E. and
    Christine Göttler, vol. 56, Intersections (Leiden: Brill, 2018),
    <https://doi.org/10.1163/9789004367432>.

 Edmondo Solmi and Sergio Solmi, *Scritti vinciani: Le fonti dei
    manoscritti di Leonardo da Vinci e altri studi*, Strumenti ; 37
    (Firenze: La nuova Italia, 1976).

 Publius Papinius Statius, *Opera* (Venice: Bartholomaeus de Zanis, 1494).

 Publius Papinius Statius, *Sylvarum libri V Achilleidos libri XII
    Thebaidos libri II orthographia et flexus dictionum Graecarum omnium
    apud Statium cum accentib. et generib. ex variis utriusque linguae
    authoribus* (Venice: Aldo Manuzio; Andrea Torresano, 1519).

 Publius Papinius Statius, *Sylvarum libri V, Thebaidos libri XII,
    Achilleidos libri II* (Lyon: Sébastien Gryphe, 1547).

 Strabo, *Peri geographias. Strabo De situ orbis* (Venice: Andrea
    Torresano; Aldo Manuzio, 1516).

 Antonio Telesio, *Libellus de coloribus. Ubi multa leguntur praeter
    aliorum opinionem* (Venice: Bernardino Vitali, 1528).

 Antoine Du Verdier, *Questions enigmatiques, recreatives et propres
     pour deviner et y passer le temps aux veillees des longues nuicts,
     avec les responses subtiles, et autres propos joyeux* (Lyon: Benoı̂t Rigaud, 1568).

 Polydorus Vergilius, *De inventoribus rerum* (Venice: Christophorus de Pensis, 1499).

 Polydorus Vergilius, *Anglicae historiae libri Vigintisex* (Basel:
     Michael Isengrin, 1546).

 Marco Girolamo Vida, *Bucolica de bombyce ad Isabellam Estensem
     Marchionissam libri II, etc.* (Basel: Johann Walter, 1534).

 Juan Luis Vives, *Los comentarios de Juan Luis Vives a "La ciudad
     de Dios" de San Agustı́n*, ed. Rafael Cabrera Petit, vol. 6,
     Colección J.L. Vives (Ajuntament de Valencia, 2000).

**Comment by Pantagrueliste** [comment]
Let me known in this specific issue if there are more bugs.

**Comment by Pantagrueliste** [comment]
this is for in text citation (dce-comments)

**Comment by njr2128** [comment]
Work for the bugs listed here is complete. For any new instances, a new issue should be made. Closing now
