### ISSUE TITLE
essays: remove duplicate folio assignments

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1530]
As of this posting, showing icons for more than one essay per annotation is not supported.

For public release 1.0, solution will be on the data side as detailed below. Open feature request in https://github.com/cu-mkp/making-knowing-edition/issues/350

TO DO: choose one essay per entry only and remove duplicate assignments in metadata

**Comment by ps2270** [comment]
done.

**Comment by njr2128** [comment]
annotation-metadata.csv updated
