### ISSUE TITLE
annotation-metadata updates

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1531]
- Update missing ann_333 info
- Update folio references for multiple essays #1530 
- Check status of all essays (staging, publish, etc)
- Prompt nick to pull thumbnails and refresh annotation-metadata info

**Comment by ps2270** [comment]
done 1st 2 bullets
Update missing ann_333 info
Update folio references for multiple essays #1530

**Comment by njr2128** [comment]
annotation-metadata.csv updated
