### ISSUE TITLE
change fig size

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1539]
Figure sizes for last 3 images on fol. 115r - they are all too big

(taken from **DCE-bug-reports** and https://github.com/cu-mkp/making-knowing-edition/issues/364)

@Pantagrueliste @TillmannTaape @thuchacz @ps2270 - whoever made this note, please suggest the size they should be (x-small, small, medium/default, large)

**Comment by thuchacz** [comment]
Done.
