### ISSUE TITLE
106 v transcription error

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1544]
1st margin block, 1st word: "Quant" should be "Quand"

**Comment by TillmannTaape** [comment]
@njr2128 please assign to me and add to consistency project (I currently don't have access to do this).

**Comment by ps2270** [comment]
@njr2128  Can @TillmannTaape do this now?

**Comment by njr2128** [comment]
like #1343 and #1533, PLEASE DO NOT TOUCH ms-xml until we give the ok

**Comment by Pantagrueliste** [comment]
done on TC and TCN
