### ISSUE TITLE
explore bulleted list rendering in essays

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1549]
Some essay bullet lists seem to render acceptably, but others do not. 

Look at source data (GD essay text docs) and determine if styling within GD is the same for all instances.

If not, change to styling that renders in acceptable fashion.
If they are, determine how "bad" the rendering is and prioritize diagnosis/fix with digital team (open new issue in https://github.com/cu-mkp/making-knowing-edition)

**Comment by ps2270** [comment]
can we use dashes instead? That seems to work?

**Comment by ps2270** [comment]
added to stylesheet:
do not use bulleted lists with more than one level of indent - it will not render on the site. Instead either use a numbered list, or the following sample construction: 
⇐For the reconstruction, we scaled the ratio down to:

- 200 ml of wax 
- 100 ml of charcoal  
- 12 ml of sulfur
