### ISSUE TITLE
capitalize "catholic"

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1553]
in fol. 20r. the adjective "catholic" is not capitalized.

**Comment by ps2270** [comment]
would it be capitalized in TCN:  de chappeau à la catholicque, ?

**Comment by Pantagrueliste** [comment]
Yes but, in the English version, the grammatical function of the word has changed: it's an adjective, and if we follow the rules of modern English grammar, it should be capitalized.

**Comment by ps2270** [comment]
That's fine. Please capitalize.

**Comment by Pantagrueliste** [comment]
done
