### ISSUE TITLE
fol. 83v - problematic rendering of marginal heading

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1555]
Fol. 83v has a heading in the left margin, but it is rendering center - before I make an issue in Nick's repo, @njr2128 and @thuchacz, is this markup fixable?

**Comment by thuchacz** [comment]
The markup is fine—there is a position attribute in the header. This is part of the "known" issue by which, at some point in late January, Nick's code lost the ability (which it firmly had, a few months ago) to render headers in the margin.

**Comment by thuchacz** [comment]
fixed by a recent update to the code.
