### ISSUE TITLE
Nosebleed one word

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1556]
"nose bleed" on fol. 38v should be one word. Check throughout ms for consistency.

Changed to "nosebleed" in quotation from 38v in Reich, Dragon's Blood.

**Comment by Pantagrueliste** [comment]
How do we tag this? <md><bp>nose</bp>bleed</md> or <md><bp>nosebleed</bp></md>?

**Comment by ps2270** [comment]
Good question. The second option is correct. Thanks.
