### ISSUE TITLE
inline figures missing on fol. 65r

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1565]
the little pentagony-type-thing in the "Umbres" / "Shadows" entry is rendering as a dot.

**Comment by thuchacz** [comment]
And the diagonal lines illustration from "Carnations" / "Flesh colors" on 65r is also rendering as a dot.

**Comment by njr2128** [comment]
fixed by https://github.com/cu-mkp/making-knowing-edition/issues/411

**Comment by njr2128** [comment]
This seems to now be fixed - I can see in all versions.
Perhaps also a fix as a result of https://github.com/cu-mkp/making-knowing-edition/issues/411
