### ISSUE TITLE
add ed comment for cont symbol: 15r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1577]
On 15r, under foundry casting entry: there are is "+" mark that indicates a continuation in the margins with another "+" 
Add editorial comment like other continuation marks

![image](https://user-images.githubusercontent.com/14779727/77463673-5a185c00-6ddc-11ea-8fd9-aaae7be2a639.png)

**Comment by njr2128** [comment]
to be done during next xml sprint

**Comment by thuchacz** [comment]
Addressed in #1727 
Closing.
