### ISSUE TITLE
make fig_p062v_2  "small" and change position

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1592]
no size is currently there in any version. 
Also, perhaps change position to "left-middle" to bump up to the text block it appears to rather than where it is now which is the one below it.

Make small as it renders very large:
![image](https://user-images.githubusercontent.com/14779727/78371083-7d3dcb00-7595-11ea-9829-950482e71a80.png)

Needs to be done for tc, tcn, and tl

**Comment by thuchacz** [comment]
Done
