### ISSUE TITLE
94v: two captions not rendering in tcn and tl

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1594]
The captions for the two figures labeled "c" and "d" are not rendering in the tl and tcn, despite being there as captions in the xml.

![image](https://user-images.githubusercontent.com/14779727/78388854-bc791580-75af-11ea-9275-323daa14a7c9.png)

**These are fine in tc:**
![image](https://user-images.githubusercontent.com/14779727/78389008-fb0ed000-75af-11ea-9620-9a0682cb0543.png)

**Comment by thuchacz** [comment]
for the record:
if a figure is inside an `<ab>`, then the caption won't render
if a figure is outside an `<ab>`, as a lone element within a `<div>`, then the caption will render, below and centered

**Comment by thuchacz** [comment]
94v is satisfactorily resolved. The prose captions are rendering. The 'a' 'b' captions are not—it would cause too much trouble on the page for too little payoff. 
Closing.
