### ISSUE TITLE
convert attribute-like elements to attributes

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#161]

**Comment by tcatapano** [comment]
@njr2128 @NickLaiacona : see https://github.com/branch /cu-mkp/m-k-manuscript-data/tree/added_attrs

* converted most recent version of transcription files ( v.0.2.2)
* under ms-xml directory
* updated schema accordingly

**Comment by njr2128** [comment]
@tcatapano, can this be closed?
