### ISSUE TITLE
review txt versions of xml pages

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1613]
txt derivative files are to be provided as raw-ish data for others to analyze as textual information.

What tags need to be signified? These should only be things that the author himself has on the page and characterizes as different types of info.
How should they be rendered (as the only allowable rendering is by insertion of special characters)?

**Comment by gschare** [comment]
@njr2128 What should we do with `<ill/>` tags? Those are being removed as usual in the txt version, but they frequently appear inside of `<del>` tags, and I'm wondering if we should still add the `<-->` around them.

**Comment by njr2128** [comment]
@gschare, good catch. I think it is actually important that we capture ALL `<ill>` tags as they usually represent entire missing words or phrases that could not be deciphered which I think is important for the txt versions. @tcatapano and Greg, please feel free to present a counterargument.

I suggest that we actually render these in the same way we do in the DCE (edition640):
`<ill/>` --> 
`[illegible]`

Thus, deleted `<ill/>`s would render as: `<-[illegible]->`

**Comment by njr2128** [comment]
This made me think of a similar tag `<gap/>` which is used to indicate large blank spaces between words within a sentence, often when there is no missing word that we know of (we think this may be due to the possible intention of adding something, just a mistake in spacing, or sometimes it appears in sections written by the scribe where he missed a word or was waiting to come back and add a word that did not need the full empty space).

This, I believe, is a candidate NOT to be included in the txt (ie continue ommiting it completely as is done in the post processing now) because it does not add the kind of information one would look for in using the txt formats for analysis. If someone is interested in the occurrences of this tag, they should be using the encoded XML versions. 
@tcatapano and @gschare, agreed?

**Comment by gschare** [comment]
Should this also be how we represent properties in `entry-metadata.csv`?
E.g. entry 007r_4 has the following property:
  ``` "music" : "quiternier<ill/>"```
_(guitar maker)_
Should this be represented in entry-metadata as `quiternier[illegible]` or just `quiternier`?

**Comment by njr2128** [comment]
@gschare good catch again! Yes this should be included in entry-metadata as you suggest:
`quiternier[illegible]`

**Comment by njr2128** [comment]
add
corr []
del
emph
exp {}
gap
ill
sup []
underline
emph
superscript

--> need to create a three column list of element name, rendition in DCE, and rendition in txt
AND confirm use and rendition in entry-metadata
WANT: entry-metadata to align with txt, but there are exceptions that we should identify (eg del in heads in entry-metadata are just removed while they are indicated in the txt)

table can be adapted from https://github.com/cu-mkp/edition-webpages/blob/master/docs/resources/principles-encoding.md

**Comment by gschare** [comment]
Rough version here:

Element name | Rendition in DCE | Rendition in txt | Notes
-- | -- | -- | --
Addition | `<add>TEXT</add>` |  
Correction | `<corr>TEXT</corr>` | `[TEXT]` | 
Deletion | `<del>TEXT</del>` | `<-TEXT->` | Excluded from entry-metadata headings
Emphasis | `<emph>TEXT</emph>` |  | 
Expansion | `<exp>TEXT</exp>` | `{TEXT}` | 
Gap | `<gap/>` |  | 
Illegible | `<ill/>` | `[illegible]` | 
Superscript | `<superscript>TEXT</superscript>` |  | 
Supplied text | `<sup>TEXT</sup>` | `[TEXT]` | 
Underline | `<underline>TEXT</underline>` |

**Comment by njr2128** [comment]
Table in previous comment contains complete behavior for these editorial tags for DCE render, txt files, and the entry-metadata extraction

**Comment by njr2128** [comment]
As of this release - this is now in place: https://github.com/cu-mkp/manuscript-object/releases/tag/v2.0.0
