### ISSUE TITLE
fol 10r translation change

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1617]
"You know, as with scrapings of the said horn, the roses can be imitated"

change to

"You know how, with scrapings of the said horn, roses can be imitated"

**Comment by TillmannTaape** [comment]
@njr2128 please assign to consistency project

**Comment by thuchacz** [comment]
As of July 15, xml seems to have been only partially fixed. It reads:
You know how, as with scrapings of the said horn, roses can be imitated. 

Fixing this. And changing punctuation in TCN to match.
