### ISSUE TITLE
Div tags with no identity

### ISSUE THREAD

**Issue by matthewkumar** [cu-mkp/m-k-manuscript-data#1623]
Folios 120v, 125r, 129v, and 162r contain div tags with no entry ID

**Comment by Pantagrueliste** [comment]
041r_02, 041r_03, 041r_04 instead of 041r_2, 041r_3, 041r_4

**Comment by tcatapano** [comment]
Yes, there are `<div>`s that do not have id attributes. These are not considered entries. What are the consequences of this in the update.py code?

**Comment by gschare** [comment]
These are all the entries with completely empty divs that I could find:
- 029v
- 064v
- 088v
- 105v
- 109v
- 115v
- 120r
- 120r
- 124v
- 125r
- 127v
- 129v
- 129v
- 141r
- 157r

There might be more. I believe that any `<div>`s with no id attributes do not get written, which I expect is what we want. I would like to try to track this down, though, and see exactly what code is preventing them from being written.

**Comment by gschare** [comment]
Also see #1696.

**Comment by gschare** [comment]
> 041r_02, 041r_03, 041r_04 instead of 041r_2, 041r_3, 041r_4

Should we raise this as a separate issue?

**Comment by gschare** [comment]
The code that prevents divs with no ID from being written is in `update.py` under the `update_entries()`:
```
# Write new files with manuscript object
    for identity, entry in manuscript.entries.items():
      if identity: # TODO: resolve issue of unidentified entries
        # TODO: ask for a naming convention
        filename_txt = f'{txt_path}/{version}_{entry.identity}.txt'
        filename_xml = f'{xml_path}/{version}_{entry.identity}.xml'
```
So entries are only written if they have an identity. If they don't, they're just skipped.

**Comment by njr2128** [comment]
Confirming that these divs with no ids should be in place - ie they are in fact divs that are not entries and have been inserted for rendering purposes only. Thus, code treats them correctly (desired effect) and no change is necessary.

Issue about div id numbers for 41r has been opened in #1894
