### ISSUE TITLE
Glossary item update for terra merita

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1625]
Current glossary entry:
Terra merita (mod. curcuma): n.(f) turmeric [dalechamps1653]

Necessary updates:
- 2 additional variants
-- terre emerita
-- terra emerita
- we don't translate "terra merita" (we keep in "french"), so make clear that "turmeric" is not the/our translation
- [148r](https://edition-staging.makingandknowing.org/#/folios/148r/tc/148r/tl) = AP gives "terra merita" as "racine de cucurme"

**Comment by ps2270** [comment]
PHS added variants and revised the definition as follows:
"turmeric; "terra merita" defined on fol. 148r as "racine de cucurme." NB: left in French in the Edition's English translation

Do you think that's clear, @thuchacz ?

**Comment by ps2270** [comment]
We are not sure that all terms left in French in the TL are noted as such in the Glossary.

**Comment by njr2128** [comment]
NB is fine. 
work completed
