### ISSUE TITLE
Investigate Error reported by Travis

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1628]
See: https://travis-ci.org/github/cu-mkp/m-k-manuscript-data/builds

1256: https://travis-ci.org/github/cu-mkp/m-k-manuscript-data/builds/684739881
1255: https://travis-ci.org/github/cu-mkp/m-k-manuscript-data/builds/684739490
1254: https://travis-ci.org/github/cu-mkp/m-k-manuscript-data/builds/684738212

**Comment by matthewkumar** [comment]
This was actually because the two repos were not in sync. We have to make sure that we pull from `manuscript-object` and then commit to master. Please check out the PR
