### ISSUE TITLE
fol. 79 ed comment

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#1630]
Ed comment on "darac" should be changed to "Correction in original: da Rac written over da Rage", and the asterisk should be moved to after "da Rage", which should be changed to "da Rac"

In TL, the whole phrase "sang daRage darac" should presumably be in French tags?

**Comment by TillmannTaape** [comment]
@njr2128 please add to consistency project

**Comment by thuchacz** [comment]
This was addressed in #1734 
Closing.
