### ISSUE TITLE
Github email - what does it mean?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1632]
@tcatapano @njr2128 What does this email I got from Github mean, and does it apply to others on the team?:
Hi @ps2270,

On April 24th, 2020 at 20:29 (UTC) you used a password to access an endpoint through the GitHub API using curl:

https://api.github.com/user/orgs

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team

**Comment by njr2128** [comment]
No longer an issue
