### ISSUE TITLE
Perspective tool, fol. 62r - an essay note?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1633]
@thuchacz  Is there something salvageable from your work with Casa and Ariana on the perspective tool: see here: https://drive.google.com/drive/folders/0BwJi-u8sfkVDaEZWTzFuR1lfU1E and here: https://drive.google.com/drive/folders/0BwJi-u8sfkVDSG5oQWljdjJWblk

**Comment by njr2128** [comment]
This has been completed - it is an annotation in progress (ann_516_ad_20_M+K_Perspective-Tool)
