### ISSUE TITLE
Correction in comment tracking sheet

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1639]
I corrected line 556 from
This entry describes a processes for coloring lifecast plants and thus is a recipe for painting on metal.
to
This entry describes a process for coloring lifecast plants and thus is a recipe for painting on metal.

Just fyi @njr2128 and @thuchacz

**Comment by thuchacz** [comment]
THU reviewed this. Looks good, PHS!
