### ISSUE TITLE
normalise spelling of terms kept in French in the translation?

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#167]
Issue raised by Heather and Soersha: should terms kept in French in the translation be normalised in terms of spelling?

E.g. "entredeux" in (f. 144v) has been kept in French, and it is spelled in two different ways on the same folio.   

Would need to pull all French tags and collate them into an alphabetic list, then normalise variants.

DECISION: not a priority for now, but can re-visit if there is time.

**Comment by caro27** [comment]
This could be done as part of ontology work, but not a priority now.

**Comment by njr2128** [comment]
@thuchacz has done the opposite of this issue, making sure all French words in TL are the same as TCN - this is consistent throughout the entire ms.
