### ISSUE TITLE
127r - translation typos

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1675]
Lanimal de cire
sattaqueroit & se romperoit & ne laurois jamays parfaict

is translated as
the wax animal would attaches itself & break & you would never have it perfect. 
CHANGE TO:
the wax animal would attach itself & would break & you would never have it perfect.

**Comment by thuchacz** [comment]
CHANGED TO:
the wax animal would attach itself & would break, & you would never have it perfect.
