### ISSUE TITLE
editorial comment update for "estelle"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1685]
estelle - update editorial comment from glossary entry
@Pantagrueliste will update reference info. in glossary
@ps2270 to compose final text for editorial comment
@thuchacz to format content into comment and update comment-tracking

**Comment by ps2270** [comment]
The current comment on "estelles" - on 95v only (shouldn't it be on 95v and 96r, the only instances of this term?) currently reads, "a kind of rod." It should be changed to "Thin laths, usually made of beech wood, used to make sword sheaths."
@thuchacz ready for you to change

**Comment by ps2270** [comment]
I changed in Comment Tracking table to : Thin laths, usually of beech wood, used to make sword sheaths. 
Sorry for change in directions...
