### ISSUE TITLE
Check translation of "assiette" esp in context of painting

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#170]
Two possible translations:

- **Assiette (f.) = “layer,”** could be “ground layer” of a painting, but not always. 
fol. 29v refers to an "assiette" of gold which would be surprising for an underlayer at that period of time. Therefore "assiette", also refers to the layer that is visible in the fond of a painting in a broader sense as opposed to the preparation underlayer (eg : layer of gold in the fond of an icon). Nicolas Misery 2015.  Reply: L. de la Verpilliere 06/07/15: In our case I think it specifically meant ‘underlayer’. But I think there would be no contradiction to understand this term as you do since this underlayer was often visible as the "painting’s background" at the time. (see Velasquez’s backgrounds for instance, re-using the painting’s underlayer with light touches of another color)

- **Assiette (f.) = “plate"** - like on p004r, p005v

Seems to be especially problematic on 4r

**Comment by thuchacz** [comment]
**THU RECOMMENDATIONS:**

- CAG: find dictionary support for “assiette” as “ground layer” (i.e., preparatory layer) or “layer” in general
- Note: “assiette” on its own seems to comfortably translate to “ground layer.” Where qualified, as “premiere” or “derniere,” there is a temptation to drop “ground” and say “first layer” or “last layer.” We need to see what CAG finds.

<img width="663" alt="screen shot 2019-03-08 at 07 10 09" src="https://user-images.githubusercontent.com/23508994/54027931-3c486c80-4171-11e9-8cd4-48a73e75f621.png">
<img width="662" alt="screen shot 2019-03-08 at 07 11 16" src="https://user-images.githubusercontent.com/23508994/54027973-639f3980-4171-11e9-9800-2b5c51b7f1e0.png">
<img width="656" alt="screen shot 2019-03-08 at 07 13 06" src="https://user-images.githubusercontent.com/23508994/54028055-a95c0200-4171-11e9-810b-12e7f97d4243.png">

**Comment by thuchacz** [comment]
@Pantagrueliste 
Can you please find any kind of dictionary support for the translation of "assiette" as either "layer" or "ground layer"?
