### ISSUE TITLE
106v move Plaster div above Tuiles div

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1711]
The order in the xml files right now is Tuiles (106v_3) then Plaster (106v_2) which is in the margin. This means that Plaster is rendered too low on the page. If we change the order, it should bump Plaster up again.
![image](https://user-images.githubusercontent.com/14779727/84928762-ec0ec880-b09c-11ea-8434-1809755a83d3.png)

**Comment by thuchacz** [comment]
Done.
