### ISSUE TITLE
Improve bibliography

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#1716]
- [x]  add doi and permalinks to bibliographic entries when relevant
- [ ]  add a new consolidated bibliography for intro essays
  - [ ] parse intro essay bibliographies
  - [ ] consolidate and correct
  - [ ] add doi and permalink when relevant
- [x] design a new Bibliography landing page

**Comment by njr2128** [comment]
We think complete. If not complete, good enough!
