### ISSUE TITLE
Meaning of "recuire" as heating method

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#172]
- Recuire = This means to reheat, probably in a furnace or oven, rather than over an open flame (although we are not positive about this).  

- Should we do a search for “recuire” vs “chauffer”??
recuire needs to be looked at through the whole text - not reheated but thoroughly cooked or brought up to the right temperature. 

- Definition on 111r and 118v

**Comment by thuchacz** [comment]
Decision: PHS to write definition for 1) cuire/recuire and 2) chauffer for Translation Protocol. Fol. 20v (a  form of regimen) uses both terms in distinction.

**Comment by ps2270** [comment]
Clement will begin a draft definition for glossary; phs will edit.

**Comment by Pantagrueliste** [comment]
I wrote a first draft in the vocabulary list.

**Comment by Pantagrueliste** [comment]
Make an annotation with histogram.

**Comment by ps2270** [comment]
ps needs to sign off on the glossary entry.

**Comment by ps2270** [comment]
PHS has revised the glossary entries for "recuire", "cuire", and chauffer.  Closing this entry now and then dealing with it in the read through campaign to keep in mind the meanings of recuire as to "refire" as in brick, recook, reheat, and anneal.
