### ISSUE TITLE
16r figure size = large (render wide)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1738]
Fol 16r has a figure we would like to push in to the main text colum:
![image](https://user-images.githubusercontent.com/14779727/87571635-587ae880-c698-11ea-8521-7862ebf2ed05.png)

"render=wide" seems to be accommodated for figures in divs. Here, we seem to just need to set figure size to large and it should push into the main text block column

**Comment by thuchacz** [comment]
Done.
