### ISSUE TITLE
Translation of "Moule de noyau"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#174]

**Comment by njr2128** [comment]
Moule de noyau (m.) = we are translating as “noyau molds.”  

It may mean “core molds,” but we need to determine this. 

Need to search and change once we have determined this.

**Comment by ps2270** [comment]
PHS and CAG resolved all translations for noyau in whatever form.  Moule de noyau became mold of noyau.
Glossary entry for Moule de noyau was deleted and incorporated into the longer entry on "noyau".

**Comment by ps2270** [comment]
See also #175; same resolution.
