### ISSUE TITLE
annotation on 1r placement

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1761]
Find a div where this can be properly anchored and rendered

![image](https://user-images.githubusercontent.com/14779727/87731105-a4f91d80-c797-11ea-9829-c8c47264853d.png)

**Comment by njr2128** [comment]
In edition-dev, this is actually totally fine:
![image](https://user-images.githubusercontent.com/14779727/87797663-057c6f00-c819-11ea-8ce4-4e7a40a7a118.png)

So I think this is related to "right-margin" issues currently under work (https://github.com/cu-mkp/making-knowing-edition/issues/173).
Going to wait on making any changes until update there

**Comment by thuchacz** [comment]
YAYYYYYYYYY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
:)

**Comment by thuchacz** [comment]
This is a non-issue so long as 1r has the "three-column" layout attribute—which is the default—not "four-column".

Closing.
