### ISSUE TITLE
ae ligatures

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1762]
In the TCN, there are:
45 æ
30 ae

In the TC, there are:
57 æ
19 ae

In the TL, there are:
2 æ (inside strings within `<fr>` tags)
35 ae

??

**Comment by ps2270** [comment]
Transcription protocol: The æ ligature (but not the œ ligature used in modern French), a form used specifically for Latin and for the Latinate spelling of the prefix præ- in French, has been maintained.
I think we were checking for oe ligatures?

**Comment by thuchacz** [comment]
Searching the TCN, while most of the æ are in præ- words, a sizable group are not (e.g., adhære, cærulée, læsion, ænigmatiques). Did someone actually go through and check the facsimile for the ca. 60 instances of ae/æ in the Ms.? Or was this applied programmatically?

on fol. 1r (which accounts for 22 of the 60 ae/æ in the Ms), the application of æ is inconsistent from TC to TCN to TL.

**Comment by ps2270** [comment]
@Pantagrueliste Sorry to bother you, Clement, but can you please let us know what you did in the case of ae ligatures?

**Comment by thuchacz** [comment]
Update from Clément via email:
"I remember that we left the ligature consistency campaign unfinished and postponed it for the very end, as the task is rather massive, and we were still changing the manuscript code quite frequently. If I remember well, there were still some disagreements on how to proceed. One school of thought defended a case per case examination of the manuscript to reproduce exactly the ligature in TC and TCN, a rigorous yet time-consuming approach. The other supported a homogeneous rendering of ligatures in TC and TCN."

DECISION:
As there are only 76 instances in which there is either an "ae" or "æ" in the TC, we will have someone look at all the instances to ensure the transcription is accurate. Next steps with the TCN can be determined from there, perhaps in consultation with Marc.

The 76 instances are all summarized in the following [table in the GD](https://docs.google.com/spreadsheets/d/1sv-u1j1bKWSi5joKvpLfQUciIbCH_U6lCE5QbHLJGto/edit?usp=sharing).

@ps2270 Please assign this when ready.

**Comment by thuchacz** [comment]
Implemented.
