### ISSUE TITLE
Capitalization of titles on 1r, 170v

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#1767]
There are a few instances in which Latin (and perhaps French) titles have been given full capitalization or no capitalization in some versions of the Ms. text, e.g., 

Fol. | TC | TCN | TL
---- | ---- | ---- | ----
170v | Reru{m} scoticarum historia | Reru{m} Scoticarum Historia | Rerum Scoticarum Historia
170v | de stirpium historia | de stirpium historia | De stirpium historia

It's a rare occurrence, and 1r looks pretty good, but it's worth a quick once over.

**Comment by njr2128** [comment]
corrected
