### ISSUE TITLE
add "layout" attribute to ms-xml root element

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1784]
values are:

* "three-column"
* "four-column"

(default is "three-column")

**Comment by thuchacz** [comment]
Travis scolded me when I added:
layout="four-column"
to the root element of 72v (TC/TCN/TL) and 94v (I only wanted it on TC for the moment)

I removed this so that I could push. @tcatapano please advise.

**Comment by tcatapano** [comment]
Was this from Travis or in oXygen? I cannot replicate it. See PR

https://github.com/cu-mkp/m-k-manuscript-data/pull/1808

for which I added a layout attribute to 72v:

https://github.com/cu-mkp/m-k-manuscript-data/pull/1808/commits/40eb2cda75fb34e00858abc08763ef2dbf95f573

And Travis did not complain:

https://travis-ci.org/github/cu-mkp/m-k-manuscript-data/builds/711213941

**Comment by thuchacz** [comment]
Ha! You have to go back 7 hours earlier:
[https://github.com/cu-mkp/m-k-manuscript-data/commit/f213a95969d1270071f38370fe223d5676bc9d4c](https://github.com/cu-mkp/m-k-manuscript-data/commit/f213a95969d1270071f38370fe223d5676bc9d4c)

**Comment by thuchacz** [comment]
Do you want me to try again? I can...

**Comment by tcatapano** [comment]
OK. I think I see what is wrong. That branch does not include the latest schema file. Here's the code from the one in the issue1774 branch (https://github.com/cu-mkp/m-k-manuscript-data/blob/issue1774/schema/ms-transcription.rng)

https://github.com/cu-mkp/m-k-manuscript-data/blob/46d6b6aeadbf73a74dbcda0029102bdd50e15841/schema/ms-transcription.rng#L7-L28

and here's the one in the master branch (https://github.com/cu-mkp/m-k-manuscript-data/blob/master/schema/ms-transcription.rng)

https://github.com/cu-mkp/m-k-manuscript-data/blob/28f8394ba1ff6574a8b23eedb8a883cc824ea87a/schema/ms-transcription.rng#L7-L28

**Comment by thuchacz** [comment]
Amazing. Okay. So... this error could have happened because I might not have pulled from master after you made the schema changes? Since I've definitely pulled from master since this morning's failed "four-column" implementation, then I should be fine to re-insert these now, no?

**Comment by tcatapano** [comment]
Yes, create a new issue branch from current master and add the layout attrs. 

BTW,  and if @njr2128 is listening, this is a case where `git merge` or `git rebase` could be used to bring the latest commits from master into the issue1774 branch. `merge` would add the missing commits to the issue branch, whereas `rebase` would add in the missing commits from the master branch *before* commits made in the issue1774 branch so that the commit history is retained. At least that's what I understand from this explanation: https://www.atlassian.com/git/tutorials/merging-vs-rebasing @thuchacz if you are adventurous, we could try one of these.

**Comment by tcatapano** [comment]
Also interesting to me and relevant to #1787 is that xmllint *is* sensitive to attributes on an element, but not to the attributes defined values.

**Comment by thuchacz** [comment]
My current branches were created for my own (conceptual / task-division) convenience, and I'm about to close them out. I've been keeping track of where I need to add "four-column," so I'll just do that work in a new branch.

Read: If this was not my penultimate day of work, I would feel more adventurous.

**Comment by tcatapano** [comment]
Totally understand. There is great wisdom in refraining from adventure in penultimacy.

**Comment by njr2128** [comment]
Closing but see #1787
