### ISSUE TITLE
question about committing a deletion

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#18]
Terry, we deleted newProject.xpr from my local repo, and I haven't staged or committed it b/c I don't know the ramifications of doing so.  Should I just do so? thanks for your help

**Comment by tcatapano** [comment]
Try a `git pull --rebase` and we'll see what happens.

**Comment by ps2270** [comment]
I did that several times, but I get the error msg: 
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

**Comment by tcatapano** [comment]
Try git stash. That will make git ignore whatever local changes you have so
you can pull.

**Comment by ps2270** [comment]
worked thanks.
