### ISSUE TITLE
Translation of "Blanchiment" (when used of silver)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#180]
Blanchiment (when used of silver) = now trans. as “whitening” rather than bleach--check across ms.  Probably refers to “pickling” - dipping in a hot salt-vinegar solution to remove tarnish.

Do not use “bleach”, but decide what to do--seems that this is technical interpretative/ ? or translate as “whitening” with an editorial note

**Two actions:**

1. check that "whitening" has been used instead of "bleach" across the ms

2. decide that this is the decision we want

**Comment by Pantagrueliste** [comment]
* no instance of bleach in the TL
* 41 references to whiten* in the TL

**Comment by Pantagrueliste** [comment]
I suggest an editorial note. Any thoughts on this? @TillmannTaape @thuchacz @ps2270 ?

**Comment by TillmannTaape** [comment]
Agree. Translate 'whitening' which is very literal, and put an editorial note to say that this technique was known as 'pickling' in English at the time (if that is the case), with a reference to the source of this info.

**Comment by Pantagrueliste** [comment]
Deliberation: add to Glossary.
