### ISSUE TITLE
Translation of "poue"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#181]
poue 121r - put it in a “pone” (changed from pove) or a corner of earth
figure this out

**Comment by TillmannTaape** [comment]
Cannot find a meaning other than "corner" which makes any sense. The word in the ms reads "co(i)" and the rest is more or less hidden under the paper so it might not in effect be "coin".

@Pantagrueliste do you have any other ideas what this could be?

**Comment by TillmannTaape** [comment]
Decision: awaiting clarification of transcription of the word under the paper strip.

**Comment by thuchacz** [comment]
"coi" are visible
what follows really doesn't look like an "n"
"r" (most likely) or "s" (less likely) or "t" (but it would be a pretty droopy, limp t...)

**Comment by ps2270** [comment]
Problem resolved with editorial comment.
