### ISSUE TITLE
add ed comm to 71

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1828]
Add same ed comment as appears on 69r about spacing between entries:

c_069r_04 | x |   |   | TT           phs | The blank space between entries here may give clues to authorial intent and composition of the text.
-- | -- | -- | -- | -- | --

![image](https://user-images.githubusercontent.com/14779727/88389064-bcca3600-cd83-11ea-90ca-5a04e5c455e3.png)

**Comment by thuchacz** [comment]
Done.
