### ISSUE TITLE
Translation of "crampon" as "cramp" not "clamp"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#183]
- For  crampon(s) - make sure in all instances it is translated as cramps, not clamps

- what are cramps?? 

- do we mean “crampon” which is an english word?

- TT: a crampon is something like a grappling hook which is not the meaning here. Cramp is an English word, meaning a metal bar with bent ends used to hold things together (esp. masonry), sometimes with a movable screw for tightening; it is sometimes used synonymously with clamp (see OED: http://www.oed.com/view/Entry/43768?rskey=bh4sFP&result=2&isAdvanced=false#eid#).

**Comment by TillmannTaape** [comment]
@ps2270 Do you want to just make a decision on this?

I am sure that 'crampon' is not the right translation; it should be 'clamp' or 'cramp' – the latter  seems slightly more accurate (see my notes above), but if it is too obscure (which I don't have a good sense of), 'clamp' would give people the right idea I think.

**Comment by ps2270** [comment]
Let's translate it as "clamp." From an internet search, it seems that "cramp" is british and australian, while clamp is U.S., so "clamp."

**Comment by TillmannTaape** [comment]
Search term: cramp

Changed all instances to 'clamp' in TL and added tool tag where missing.

Searched TL for 'cramp' to double check.
