### ISSUE TITLE
ed comment on 120v in dif places across TL, and TC + TCN

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1852]
## In TC and TCN:
![image](https://user-images.githubusercontent.com/14779727/88437839-5a9a2100-cdd5-11ea-97ee-b01b4d7dce86.png)

## But in TL it is in front of "Siscitatio dubia." Also has an extra space in TL
![image](https://user-images.githubusercontent.com/14779727/88437521-a0a2b500-cdd4-11ea-876d-31fb23cbd967.png)

**Comment by thuchacz** [comment]
Ah, yes. It used to be in both places on all three, and I was meant to remove the duplicate from the marginal note, but it seems I missed the one on the TL. Good catch @njr2128 !

**Comment by thuchacz** [comment]
Done.
