### ISSUE TITLE
Use of "naturel"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#186]
Information about use provided in Isabella Lores-Chavez annotation on imitation jasper (FA17)

Two actions:

1. Based on annotation, need to decide how to translate this word by context
2. Add material from Isabella’s annotation to the glossary OR add as editorial note? 
See also issue #143 VOCAB list transformation

**Comment by Pantagrueliste** [comment]
#241

**Comment by thuchacz** [comment]
Changes made according to this document:
[Issue 186 & 241 ps notes.docx](https://github.com/cu-mkp/m-k-manuscript-data/files/3098724/Issue.186.241.ps.notes.docx)
