### ISSUE TITLE
set up users to run update.py

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1868]
Identify all requirements and dependencies (e.g., installing python 2.7 or 3.7)

**Comment by njr2128** [comment]
From Terence Catapano to Everyone:  05:11 PM
>sudo apt install python3.8
sudo apt install python3-pip
sudo apt update

**Comment by njr2128** [comment]
then
>python3.8 -m pip install pandas
 
run pip under 3.8

**Comment by njr2128** [comment]
to get manuscript-object within manuscript-object
> git submodule update --init --recursive

**Comment by njr2128** [comment]
FOR FUTURE:
To run update.py, always make sure you are in manuscript-object submodule, in MASTER branch (it will often just go to last commit), and then separately git pull / git fetch manuscript-object

**Comment by njr2128** [comment]
Then to run update.py, run:
> git pull --recurse-submodules

**Comment by gschare** [comment]
To use virtual environments (do this BEFORE installing packages):
Go to your project directory.
```
python3.8 -m pip install --user virtualenv
python3.8 -m virtualenv .venv
```
(here, `.venv` is the name of the folder where we will keep our virtual environment. You can name it whatever you want)
```
source .venv/bin/activate
```
Now you're in the virtual environment and you can use `python3.8 -m pip install [PACKAGENAME]` to install packages in the virtual environment.
Type `deactivate` to exit out of the virtual environment.

**Comment by njr2128** [comment]
Log of yesterday's session with Terry, Greg, and Naomi on Naomi's windows10 linux subsystem:
[2020-08-17_manuscript-object-update-py.docx](https://github.com/cu-mkp/m-k-manuscript-data/files/5091085/2020-08-17_manuscript-object-update-py.docx)

**Comment by njr2128** [comment]
https://github.blog/2016-02-01-working-with-submodules/

**Comment by njr2128** [comment]
manuscript-object as a submodule has now been removed. As per https://github.com/cu-mkp/manuscript-object/issues/28, paths will be updated.

Going forward, the plan will be to run update.py from manuscript-object, then update m-k-manuscript-data and add/commit etc. in the correct branch

**Comment by njr2128** [comment]
this has all been documented in https://github.com/cu-mkp/manuscript-object/blob/master/README.md by @gschare
