### ISSUE TITLE
entry-metadata: treatment of <del>

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1873]
For each heading, we have been just stripping `<del>` tags and displaying their text along with the rest of the heading.

NEW request: remove all words within `<del>` tags so that we are left with "clean" headings for entry-metadata.

## E.g., Currently, list of entries has:
![image](https://user-images.githubusercontent.com/14779727/90686980-2120ce00-e23a-11ea-8d60-2f4db9b95570.png)

## For the heading:
![image](https://user-images.githubusercontent.com/14779727/90687029-34339e00-e23a-11ea-8982-8c40f1b0f8d0.png)

**Comment by njr2128** [comment]
Deleted words are still appearing in entry-metadata as of this posting. Need to re-implement in the generation of entry-metadata in https://github.com/cu-mkp/manuscript-object

**Comment by gschare** [comment]
[Should be fixed now](https://github.com/cu-mkp/manuscript-object/issues/84). When I tested regenerating `entry-metadata.csv` it worked.
