### ISSUE TITLE
fol. 52r - correction to TL and TCN needed

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1875]
TC has
le (germe) voy)

TL and TCN
the (germ see)
and
le (germe voy)

This is very confusing and not "correct" as we don't know the meaning of these paragraphs (as the ed comment makes clear).

@njr2128  
Please change TL and TCN to match TC
Thanks,
P

**Comment by njr2128** [comment]
done. (the first time this was done in commit ...ead1a20, I needed to discard the changes due to work on #1890
