### ISSUE TITLE
36r - translation adds extra word and <tl>

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1876]
From #1469 

The translation has added the word "ball" in place of "it," I believe to clarify the meaning. However, this goes against our translation policy of sticking as close to the original as possible, adding an extra word as well as an extra `<tl>`

https://edition640.makingandknowing.org/#/folios/36r/tcn/36r/tl

TCN:
`Puys levant le  <m>cuir</m>, elle semble<lb/> estre celle mesme, combien que ce soit la creuse. Puys tu la<lb/> recouvres &amp; luy commandes qu’elle se fasse invisible.`

TL:
`Then, when lifting the <m>leather</m>, the <tl>ball</tl> seems to be the same, although it is the hollow one. Then you cover it again &amp; command it to become invisible.`

@ps2270, can you advise? My inclination is to chage "ball" to "it" and then if really necessary, add an ed comment clarifying that it is the ball

**Comment by ps2270** [comment]
Let's change "ball" to "it". "It" certainly is more confusing than "ball", and the feminine ball is clearly indicated by the French, but I agree that it goes against our protocols.
Thanks for catching this.

**Comment by njr2128** [comment]
done
