### ISSUE TITLE
124r_3 - inconsistent markup; TL meaning dif?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1881]
From #1469
There is markup difference between the two french versions and the translation, which also potentially changes the meaning of the sentence. We have:
> `<m>`paper`</m>`, `<tl><m>` glued....

or
> `<tl><m>` paper glued....

**EXCERPTS:**
https://edition640.makingandknowing.org/#/folios/124r/tcn/124r/tl
English:
`One makes around it an edge of <m>paper</m>, <tl><m>glued to the <fr>quarton</fr></m></tl> &amp; one casts with <m>tin, very little alloyed with lead</m>.`

French:
`On fait aultour un bort<lb/> de <tl><m>papier collé sur le quarton</m></tl> &amp; on gecte d’<m>estaim bien peu allié<lb/> de plomb</m>.`

**Comment by ps2270** [comment]
Here's my suggestion, which makes a tool of the "edge of paper" which does seem to me to be the tool here:

`One makes around it an <tl>edge of <m>paper</m></tl>, glued to the <m><fr>quarton</fr></m> &amp; one casts with <m>tin, very little alloyed with lead</m>.` 

French:
`On fait aultour un <tl>bort<lb/> de <m>papier</m></tl> collé sur le <m>quarton</m> &amp; on gecte d’<m>estaim bien peu allié<lb/> de plomb</m>.`

**Comment by njr2128** [comment]
agreed!

**Comment by njr2128** [comment]
done
