### ISSUE TITLE
166r_1: translation of "inventeurs"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1883]
From #1469

The translation for the following sentence changes "inventeurs" from a noun to a verb (and in the process loses a `<pro>` tag). One option would be to add `<pro>` to "invented" but this does not make for as close a translation and creates inconsistency for other "invent"-as-a-verb occurrences within this same entry (not to mention the ms at large).

https://edition640.makingandknowing.org/#/folios/166r/tl/166r/tcn
TCN: 
> Pythagore* & aultres de Tyanée ont aprins par leurs peregrinations les disciplines desquels ilz se sont dicts inventeurs
en leur pays, &[c]. 

TL:
> Pythagoras* & others from Tyana learned by their travels the disciplines which they claimed to have invented in their country, &c.

What do you recommend, @ps2270

**Comment by ps2270** [comment]
TCN:

    Pythagore* & aultres de Tyanée ont aprins par leurs peregrinations les disciplines desquels ilz se sont dicts inventeurs
    en leur pays, &[c].

TL:

    Pythagoras* & others from Tyana learned by their travels the disciplines of which they called themselves inventors in their country, &c.

**Comment by njr2128** [comment]
done
