### ISSUE TITLE
Meaning and translation of "mine"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#189]
The meaning of "mine" throughout the manuscript is unclear and makes a consistent translation difficult. Need to determine and make decision.

Check translation of “mine”.  All occurrences in ms: https://docs.google.com/document/d/1yPyNCaDrxDnOESAZfp-HOw7ZhfKSbwlAdXcAC0CUT58/edit?usp=sharing

Other notes:
11r: Ou qui est par alambic distillee par des pierres mineralles dazur ou cuivre
110r
118r

**Comment by ps2270** [comment]
7r: leave in FR (as it is now), add an editorial note that says "A variety of minium?"
43r: change translation to English minium.  PHS to put in a glossary definition.
110r: change mine to "mineral" in both cases
118r: change mines to minerals, and change "even" for unie to uniform.
125r: mine needs to changed twice to ore.

**Comment by Pantagrueliste** [comment]
all done
