### ISSUE TITLE
tagging of symbols/marks

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#19]
from @TillmannTaape 

> Quick question as Tianna and I are doing markup today: should we tag all unicode symbols with the figure tag? Is that what you use to pull the figure metadata, or was that done manually?

**Comment by tcatapano** [comment]
You should not tag symbols as `<figure>`. Symbols for which unicode characters are being used have been tagged as `<figure>` but these will be automatically converted to `<mark>`. We really dont have any specs as to how this tag is going to used right now, so its a very low priority.

**Comment by TillmannTaape** [comment]
Excellent, thank you!

TT

--

Dr. Tillmann Taape

Lecturer in History
Postdoctoral Scholar, The Making and Knowing Project

Book reviews editor, Ambix

Columbia University
511 Fayerweather Hall, MC 2509
1180 Amsterdam Avenue
New York, NY 10027

tillmann.taape@cantab.net
