### ISSUE TITLE
translation of “lien”

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#190]
More information required to make decision about translation of “lien” 

- tied bundle?

- current vocab entry: Lien, “à lien” = keep in french with `<fr>` tags. A unit of measure describing a quantity for sale. Cotgrave calls a "lien" a cord, but on f. 20r the MS describes a "lien" as composed of three "tables" of glass. (SM and MBR)

**Comment by TillmannTaape** [comment]
"Ligamina, ligacai, lyen. Rose-Villequey 1971, p. 195. rapporte que 'Les feuilles de verre étaient réunies à ö'aide de liens en viorne, en liane, ou en osier, pour la commodité du maniement', 'ce fardeau de trois vitres se nommait donc Lien de Verre" cited in [Guidini-Raybaud, Pictor et veyrerius: le vitrail en Provence occidentale, XIIe-XVIIe siècles, p. 150, n. 119.](Pictor et veyrerius: le vitrail en Provence occidentale, XIIe-XVIIe siècles).

Indeed this seems to be a common measure for glass panes, see here:
http://www.verre-histoire.org/colloques/verrefenetre/pages/p307_02_herold.html

BUT [Dictionnaire universel François et Latin, vulgairement appelé ..., Volume 5](https://books.google.com/books?id=3B17mnRSY1IC&lpg=PA523&ots=jqry4BLYNo&dq=%22lien%20de%20verre%22&pg=PA523#v=onepage&q=%22lien%20de%20verre%22&f=false), says that one lien comprises six tablets, not three (p. 523).

**Comment by ps2270** [comment]
"Cords" would seem the translation On 134v: 
Pour gect dor en grand
ouvraige
Il fault non seulement bien cramponer les moules
Mays les fortifier de bons liens de fil de fer ou
petites bandes faictes a propos

On 20r: a "bundle" with an editorial note?

**Comment by TillmannTaape** [comment]
"cords" is fine on 134v; perhaps better still "ties" which is more generic.

On 20r, "bundle" with editorial note seems our best option; I simply cannot find and English equivalent, which may be because this is particular to Lorraine glass and how it was sold.

**Comment by TillmannTaape** [comment]
I've translated "ties" on 134v and "bundle" with note on 20r.
