### ISSUE TITLE
Meaning/translation of "loppe" in "loppe de fer"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#191]
translation of “loppe” as in “loppe de fer” - a measurement or a material or a piece?

**Comment by Pantagrueliste** [comment]
It's a piece of iron of undetermined size. Is this a Markup problem?

**Comment by thuchacz** [comment]
No—it's a translation problem. What would be a suitable word?

**Comment by ps2270** [comment]
is it an ingot or a measurement, do you think?

**Comment by Pantagrueliste** [comment]
It's a tricky question, and I notice that the meaning of the term has raised questions in the past...

* In 1812 "La sidérotechnie", footnote 2 page 6, the author proposes two possible etymologies, and defines it as a "masse de fer affinée."  A 2011 archeological inventory quotes a 1515 text mentioning a 25 pounds "loppe de fer" used as an instrument, a sort of crowbar.  

> Il note une dépense de « six gros monnoie à Jehan Doulx, chien (citoyen) de Besançon, le XVIII° dudit mois de décembre 1515 pour paiement d'une loppe de fer pesant XXV livres que l'on prinst (prit, acheta) devers luy pour employer au rompre la roche à force de pouldre de bastons à feugz, devant la porte de Charmont, laquelle rompit en plusieurs pierres que volarent en l'air, et ne scait l'on (l'on ne sait) que d'adviennent lesdites pierres ».

* The _Dictionarium Teutonico-Latino-Gallicum_ translates it as _Hamerslagh_  (any idea @TillmannTaape ?)  

* The term *loppe* evolved in *lopin*,  which in the context of (presumably modern) metallurgy means "Morceau de fer prêt à être forgé", or "Morceau de fer obtenu par la réunion de plusieurs autres morceaux soumis au travail de la forge." 


I am inclined to think that, in this context, the meaning is closer to ingot.

**Comment by ps2270** [comment]
interesting.  So it sounds like re-used iron scale (which is iron oxide--Fe304 [sorry no subscript])...hmmm...how to express this...with an editorial note.  to be continued

**Comment by TillmannTaape** [comment]
Hammerschlag means scales or scoria. This seems to me to make more sense in context than an ingot or measurement as it is always mentioned together with or as an alternative to other powdered substances:

49r.: mentioned together with calcined oyster shells
106r: loppe de fer as a substitute for crocum ferri
127r: fais des sables de crocum d'escaille de fer, de loppe de fer, d'esmeri
128r: Loppe d’argent sophistiqué is said to vitrify – i.e. could be powder of mixed metals used for enamelling?

The problem then would be how to translate this to distinguish it from "ecaille de fer" which we are already, and more literally, translating as "iron scales", especially since both appear next to each other as ingredients for sand on 127r.

**Comment by ps2270** [comment]
Continuing our conversation from class: I don't think it's powdery, given the passage Clement found: "pour paiement d'une loppe de fer pesant XXV livres"
It must be a substance that could be found in metalworking texts in English...

**Comment by TillmannTaape** [comment]
I think we need to be looking for "loupe".

E.g. DMF: "Masse de minerai mal fondu présentant des scories"

"bloom" or "loop", see this wikipedia article: https://en.wikipedia.org/wiki/Shingling
NB OED has both "bloom" and "loop" with this meaning.

See description here of [artisanal smelting](http://www.metallurgie-forge-coutellerie.fr/metallurgie-artisanale/)

This website (which doesn't look authoritative) suggests "bloomery iron" for "loupe de fer"
https://termbank.com/en/french-english/loupe%20de%20fer

So perhaps
"loppe de fer" = "iron bloom/loop" or "bloomery iron", and
"loppe d'argent sophistiqué" = "bloom/loop of unadulterated silver"

**Comment by Pantagrueliste** [comment]
> Quelques métallurgistes font dériver le nom de loupe, que l'on donne aux masses
de fer affinées, accumulées dans le fond du creuset, du latin barbare luba; c'est de ce
mot qu'est dérivé le nom de loupe, donné en médecine à des excroissances charnues,
à des tumeurs enkystées; c'est encore de luba qu'a été formé le nom de loupe, donné
en botanique à des excroissances ligneuses. Cependant il paraît, d'après Swedemborg,
que l'on pourrait aussi dériver du suédois, loppe le nom que l'on donne aux masses de fer affiné.

**Comment by TillmannTaape** [comment]
Or, apparently, from Old Frankish "luppa" or "lopp"...

**Comment by Pantagrueliste** [comment]
Loupe, loppe: "masse de fe affinée qu'on passe au marteau (seit ca. 1450)"
_Französisches Etymologisches Wörterbuch_:

**Comment by Pantagrueliste** [comment]
![loupe de fer](https://upload.wikimedia.org/wikipedia/commons/7/74/Iron_bloom.jpg "loupe de fer")

**Comment by TillmannTaape** [comment]
Great, with that reference we can definitely read "loppe" as "loupe".

I'd suggest translating "loop" rather than "bloom" because it's closer to the original. "bloom" is perhaps slightly less obscure, but this term probably needs an editorial note in any case so we might as well go for "loop".

**Comment by Pantagrueliste** [comment]
Decide between loop and bloom
