### ISSUE TITLE
treatment of parted divs in allFolios

### ISSUE THREAD

**Issue by gschare** [cu-mkp/m-k-manuscript-data#1919]
When a div has a part and is continued later on down the page, how should this be treated in allFolios? Should the original order be kept, or should divs with the same ID be grouped together?

Entry ID 170r_6 is a good example of this.
### ms-xml
Separated in original manuscript
https://github.com/cu-mkp/m-k-manuscript-data/blob/392c5d560782d4314f06ee3454a5c9bf189918cf/ms-xml/tl/tl_p170r_preTEI.xml#L21-L38

Second part continues later:
https://github.com/cu-mkp/m-k-manuscript-data/blob/392c5d560782d4314f06ee3454a5c9bf189918cf/ms-xml/tl/tl_p170r_preTEI.xml#L98-L102

### allFolios
Divs grouped together
https://github.com/cu-mkp/m-k-manuscript-data/blob/392c5d560782d4314f06ee3454a5c9bf189918cf/allFolios/xml/tl/all_tl.xml#L19451-L19484

**Comment by njr2128** [comment]
As per conversation with @tcatapano and @gschare:
- for entries/, all parts should be consolidated together 
- for allFolios/ in both txt and xml version, we want to try and duplicate the layout of the physical pages as much as possible. This would concatenate each of the individual xml files one after the other. 
     - one particular place where this already strays from the physical page is the treatment of marginal notes. These, which are impossible to display as they would on the physical page (ie left-middle, etc), appear at the end of an entry's div. In other words, a folio will look something like:
> [entry 1]
[entry 1 marginal notes]
[entry 2]

- So, similarly, parts would appear:
> [entry 1 part 1]
[entry 2]
[entry 1 part 2]
Add this information to the READ.ME

**Comment by gschare** [comment]
Fixed in cu-mkp/manuscript-object#41

**Comment by gschare** [comment]
Confirmed fixed with most recent release of `manuscript-object`.
