### ISSUE TITLE
Meaning of capital “K” on 167r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#193]
167r: capital “K” - what is meaning of this abbrev?
TT: there was a suggestion hidden in the defunct vocab list; it’s now in the PW18 translation protocol.

**Comment by ps2270** [comment]
Tillmann, can you please show me this K?  I can't find it.

**Comment by ps2270** [comment]
See issue #493 
resolved in that issue.  Closing this now.
