### ISSUE TITLE
decrease size of sandbox DO droplet

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#1932]
down to 5GB droplet

**Comment by njr2128** [comment]
image-rotation droplet has been destroyed (with snapshot taken so it can be re-created). The image has been retained and can be used to create a smaller droplet in future once the image-rotation task is needed again. 

NOTE: the important thing here is that every time this task is needed, the droplet should be created, the task should be run, and then droplet should be immediately destroyed to avoid runaway costs
