### ISSUE TITLE
travis CI migration to ".com"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1942]
from #1927 (and #1939)
prompted by message on travis's site as detailed in #1927 
and a build that never left the "queries" zone:
![image](https://user-images.githubusercontent.com/14779727/106530324-1ab9a200-64ba-11eb-8eb7-f056ac0b3f00.png)

figure out what on earth is going on with travis (org vs com)
- check yahoo M&K email
- re-check all settings

TRAVIS UPDATE DOCUMENTATION: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
see also https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com
and https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by njr2128** [comment]
perhaps just switch away from using travis

**Comment by tcatapano** [comment]
see: https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works

https://github.com/mondrake/drudbal/issues/189

**Comment by njr2128** [comment]
UPDATE: travis is no longer seeming viable. It will now likely require payment with additional increased fees and other potential headaches. 

DECISION: remove travis from this repository

Look into Github Actions instead
