### ISSUE TITLE
Fol. 59r_1 translation change? and typo

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1945]
In fol. 594_1, there is a space before the editorial comment asterisk in tc, tn, tl [perhaps it's intentional, if in all three?]
Also,
Jo and Marika suggest translation change, which makes some sense to me:
Ombres
Il fault que les premiers umbres qui sont plus pres du
jour soient clairs & fort adoulcis & puys les derniers fort
obscurs pour faire bien relever *Les italiens font communement
trois umbres le premier du jour fort cler le second plus obscur & les tiers bien
fort puys rassemblent ces trois umbres en hachant despuys le plus
obscur jusques au plus cler

Shadows
The first shadows which are closer to light need to be clear & thoroughly softened & then the last ones very dark to give relief well. *The Italians commonly make three shadows, the first one, of light, very clear, the second one darker & the third ones quite strong, then blend these three shadows together by hatching them from the darkest to the clearest.
Change to
The first shadows which are closer to light need to be clear & thoroughly softened & then the last ones very dark to give relief well. *The Italians commonly make three shadows, the first one, of light, very clear, the second one darker & the third ones quite strong, then blend these three shadows together by hatching them from the darkest to the LIGHTEST.

**Comment by njr2128** [comment]
DECISION: actually leave as "clearest" (not change to "lightest") but perhaps link Kirby/Spring essay to this entry for their discussion of this.

Also, check typo and fix if necessary

**Comment by njr2128** [comment]
Typo: not a typo. It looks like an extra space but it is because the comment is anchored to the beg of the second sentence rather than the end of the previous sentence. This is the correct placement
![image](https://user-images.githubusercontent.com/14779727/107569879-cea3e700-6bb6-11eb-9c5c-514dd176f419.png)
