### ISSUE TITLE
Fol. 93v_2 Translation change?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1946]
Kirby & Spring information on 93v_2:
Le plus
delie est le meilleur pour travailler Il se subtilie en
 le lava{n}t
“The most delicate is the best for working. It is refined by washing it.” This last phrase highlights some challenges in translation; “Il se subtilie” is here translated as “It is refined” and in the digital edition as “It is thinned,” but the literal translation “It is softened” is hard to understand. An English treatise of 1573 in similar archaic language is helpful in this respect. The author advises to choose smalt “which is bright of colour, and not harshe, but softe betwene the fingers.” Marshall Smith, too, a century later states “the best Smalt is the deepest and soft like Butter between the Fingers.”

Based on this information, we should consider changing the translation.

**Comment by njr2128** [comment]
Perhaps best version: "It is made finer by washing it"

**Comment by njr2128** [comment]
subtilie used as a verb -- to be translated as "make finer" -- should be reconsidered throughout the ms

**Comment by njr2128** [comment]
search for `subtil*` in oxygen as a start

**Comment by njr2128** [comment]
@ps2270, I found the instructions we have for finding the associated TL for a TC/TCN file. For future reference, to do that kind of search, the info is in the GD doc: `**2019 DCE Sprint Workflow + oxygen**`

**Comment by njr2128** [comment]
From review by NJR and PHS of other instances and further input from Jo Kirby and Marika Spring, we will translate here as "It is made finer by washing it."

This is consistent also with the [glossary](https://edition640.makingandknowing.org/#/folios/1r/f/1r/glossary): 
```
Subtil, adj.: 1. delicate 2. fine (as in finely ground), see also →subtilier
Subtilier, v.: 1. to grind finely, or to make thinner 2. to disintegrate
```

**Comment by njr2128** [comment]
done.
