### ISSUE TITLE
Meaning of "impression"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#195]
“Impression”: does this mean “mark”, “drawing”, print, or priming? 

Decide, then check throughout the ms.

**Comment by thuchacz** [comment]
GLOSSARY ENTRIES NOW:

**Empraindre** (v., mod. empreindre) = “to imprint” ; different from imprimer = “to print”
Cotgrave: empreindre: “to print, stampe, set, presse, or thrust hard in; also, to assaile, or set on with violence.” 
Cotgrave: imprimer: “to print, imprint, make an impression; to stamp, seale; set, or thrust, hard in.” p057v_1 (CD TT)

**Empraint** (m., mod. empreinte f.) = “imprint”
F. 156r. CHECK for consistency. MHS THU SJP 2018.

**Impression** (f.) (U) = “priming layer” (e.g., fol. 56v, 65v_1), or mark (in the sense of drawing, as perhaps on fol. 60v_5). If meaning is unclear, keep Fr. for now (PHS 2017)
Discussion: previously thought to mean underlayer or underdrawing MHS 06/18/16: 2016, but DMF has “empreinte, marque”, and no dictionaries define it as a layer of priming (PHS 2017).

**Comment by thuchacz** [comment]
THU DECISION: compile all instances of "impression," "empraindre/emprainct," and "imprimer" for comparison

**Comment by ps2270** [comment]
I have gone through this today 4.14.19, and will try to send back the document with my answers, but in the meantime, please think about about whether "impression" in the sense of primer is better translated as  "priming" or "priming coat" [and WHICH ONE?], as acc to OED this is used 16th-c in English, whereas "primer" is only later.

**Comment by ps2270** [comment]
also: "priming COAT" or priming LAYER??

**Comment by thuchacz** [comment]
Decision: impression (in context of painting) = priming
Glossary updated.
[Impression Decisions.pdf](https://github.com/cu-mkp/m-k-manuscript-data/files/3086253/Impression.Decisions.pdf)
