### ISSUE TITLE
Editorial Comments - revision

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1950]
In light of Jo & Marika's essay, the editorial comment on fol. 11r_1 should be changed from 

Cendre (ash), fleur (flower), and le plus subtil (the subtlest part) are grades of a blue pigment, likely azurite or perhaps smalt. See Spring and Kirby, "Ms. Fr. 640 in the World of Pigments in sixteenth-century Europe," https://edition640.makingandknowing.org/#/essays/ann_321_ie_19.
TO
Cendre (ash), fleur (flower), and le plus subtil (the subtlest part) are grades of a blue pigment, such as azurite or, as is most likely here, smalt. See Spring and Kirby, "Ms. Fr. 640 in the World of Pigments in Sixteenth-Century Europe," https://edition640.makingandknowing.org/#/essays/ann_321_ie_19.

**Comment by njr2128** [comment]
done
