### ISSUE TITLE
fol. 87r_1 typo - extra "is"

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1962]
Remove second "is" from bolded portion:

Sand from Thoulouse
The usual good one is the one which is found in a vineyard near Puy David, but the one which is most excellent **is the one is** from the Touch, near Sainct Michel & toward Blagnac, in a vineyard that is quite high up. The latter is thinner & a little fatter than the other, & better for small works. It does not want to be reheated too much.

**Comment by njr2128** [comment]
done
