### ISSUE TITLE
Fol. 87r_1 translation change needed

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1963]
The following use of "delie" has been translated as "thin":
Cestuy est plus delie & un peu plus gras que laultre 
The latter is thinner & a little fatter than the other, 

This doesn't really make sense and is in contrast to mostly of the other places where it is translated as "fine," "delicate" 
SO, I think it should be translated
"The latter is **finer**...
It also makes sense in terms of how the sand felt ...

**Comment by njr2128** [comment]
done
