### ISSUE TITLE
archive repo releases through zenodo

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1966]
From #1964: In the past, Terry has archived one of our repos in zenodo, which also assigns the version a DOI. See and review: https://zenodo.org/record/1197521#.YDfP4JNKjeQ

TO DO: see of it is possible to create archive of past releases. If so, archive all past releases of this repo

Guide for working with zenodo+github:https://guides.github.com/activities/citable-code/ and https://guides.lib.berkeley.edu/citeyourcode; also consider AC as per conversation with Libraries

**Comment by njr2128** [comment]
https://guides.github.com/activities/citable-code/
> By default, Zenodo takes an archive of your GitHub repository each time you create a new Release

**Comment by njr2128** [comment]
Need to create user in Zenodo for the Project

**Comment by tcatapano** [comment]
* created new Github user "mkp-admin"
* added "mkp-admin" to cu-mkp organization's team "ownerz" with admin privileges for all cu-mkp repos
* created makingandknowingproject@gmail.com zenodo account

next:

* set up zenodo archiving of m-k-manuscript-data repo
* prepare release of repo for archiving
* badge repo with zenodo issued doi

**Comment by tcatapano** [comment]
<a href="https://zenodo.org/badge/latestdoi/94773520"><img src="https://zenodo.org/badge/94773520.svg" alt="DOI"></a>


[![DOI](https://zenodo.org/badge/94773520.svg)](https://zenodo.org/badge/latestdoi/94773520)

**Comment by njr2128** [comment]
Trial of zenodo badges:

<a href="https://zenodo.org/badge/latestdoi/94773520"><img src="https://zenodo.org/badge/94773520.svg" alt="DOI"></a>

[![DOI](https://zenodo.org/badge/94773520.svg)](https://zenodo.org/badge/latestdoi/94773520)

![run-ci](https://github.com/cu-mkp/m-k-manuscript-data/workflows/run-ci/badge.svg)

**Comment by njr2128** [comment]
at the time of the previous comments, the badges were showing up as missing images, but are now appearing - this seems to be due to time.

All good now
