### ISSUE TITLE
Translation of "cave"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#197]
“cave” still is not really satisfactorily translated by “cavity”

@tcatapano is checking for co-occurrences of cave and creux; creulx; creuse; creuses
@ps2270 went through all these and decided: creux is definitely “hollow”; “cave” means cavity, hollow, concave, or the female or negative mold.

Still need to make translation decision

**Comment by TillmannTaape** [comment]
Did we decide on this? We have "creux" = hollow above, but which of the many possibilities for "cave" should I use? All or them according to context? It would seem best to avoid "hollow" for "cave" if possible so as not to conflate the two.

**Comment by ps2270** [comment]
We need Clement's text editor b/c "cave" should be translated according to context.

**Comment by TillmannTaape** [comment]
tcn_p005r_preTEI	gecte en moule & se faict rond,	cave		, convexe & comme on veult pour representer diverses formes. Prens
	tcn_p005r_preTEI	frottés l’ung contre l’aultre, soict	cave		ou plat, & ainsi tu en poliras deux ensemble. Et
	tcn_p008v_preTEI	plus delié que tu pourras, & le	cave		au milieu. Mectés y la huictiesme partye de ☿ au &
	tcn_p012r_preTEI	, nette & belle. Tu peulx faire	cave		d'animaulx de chimolée & i gecter du plomb. left-middle Il
	tcn_p012r_preTEI	le recuire. Quand tu moules & fais	cave		de chimolée, ne presse pas à coup mays doulcem ent,
	tcn_p012r_preTEI	fin est le meilleur. Et quand le	cave		est bien nect, comme de soufre ou chimolée cuitte, il
	tcn_p012r_preTEI	sur le mabre. Aprés avoyr præparé ton	cave		de soufre ou aultre & l'avoir huilé & entourné d'un
	tcn_p012v_preTEI	de relief, & ainsy tu auras un	cave		où tu pourras gecter du plastre, papier pilé ou terre chimolée
	tcn_p015v_preTEI	veuilles fayre fort legere, fais en un	cave		de plomb, puys estands sur iceluy du clinquant ou des lames
	tcn_p029r_preTEI	Estant ainsy præparée, frottés d'huile le	cave		au u avecq une broisse affin que l'huile penetre partout pour
	tcn_p030v_preTEI	avecq la main s au bord du rond	cave		, & doulcem ent le conduisent jusques au centre du rond.
	tcn_p042r_preTEI	en le relief dont tu veulx avoyr le	cave		, comme si le voulois paindre. Et il se fera une
	tcn_p042r_preTEI	corps et force. Aprés, dans le	cave		de la cire, tu gecteras aussy ton plastre pour avoyr le
	tcn_p050r_preTEI	esté, Et l’hiver pource que la	cave		s dans une cave, et l'hiver mectés vos bouteilles dans
	tcn_p050r_preTEI	hiver pource que la cave s dans une	cave		, et l'hiver mectés vos bouteilles dans un panier garny de
	tcn_p050r_preTEI	de la pone seroit trop froide si la	cave		n'est bien chaulde, car il fault que l'eau soit
	tcn_p068v_preTEI	s’il ne te plaist, parfumer le	cave		de fumée de soufre ou de p à la pointe de la
	tcn_p076v_preTEI	de verre, & les gardés en la	cave		ou au ltr e lieu humide par l'espace de huict ou
	tcn_p081r_preTEI	mm e tu l'auras moulé dans le	cave		, pose ung linge dessus & par derriere, frotte avecq une
	tcn_p083r_preTEI	tout ensemble, puys le mettés dans une	cave		cave ou lieu humide. Et de ceste paste moullés ce qu'
	tcn_p083r_preTEI	ensemble, puys le mettés dans une cave	cave		ou lieu humide. Et de ceste paste moullés ce qu'il
	tcn_p083v_preTEI	, et puys quand tu auras moulé le	cave		dans le sable, laisse la figure de metal que tu s
	tcn_p083v_preTEI	sans la remuer pource que, si ton	cave		n'est pas moulé bien net, tu luy peulx remectre justem
	tcn_p084r_preTEI	pulverisé & mis sur un mabre dans une	cave		, & il se desseichera en recuisant le moule & luy donnera
	tcn_p085v_preTEI	de relief, & de l’aultre de	cave		, & de l’espesseur d’une piece de quarante sols.
	tcn_p086r_preTEI	fort net de relief d'un costé &	cave		de l'aultre, tant figure que les l ett res.
	tcn_p088v_preTEI	papier & posés sur un mabre dans une	cave		. Dans une nuict, ilz ont esté assés moictes d'eulx
	tcn_p089r_preTEI	la nuit ou à l'humeur de la	cave		. Et n'en ay point trouvé qui despouille plus net que
	tcn_p089v_preTEI	. Il suffist de l'humecter dans une	cave		ou au serain ou, pour avoyr plustost faict, dans une
	tcn_p090r_preTEI	estre humectés au serain, ou en la	cave		, ou aultrem ent avecq la serviete, & il despouille fort
	tcn_p091r_preTEI	, trasse premierem ent le moule & le	cave		avecq un trancheplume pour faire voye à la medaille, & puys
	tcn_p092r_preTEI	un plat d'estaim fin. p092r_2 Mouler	cave		d'un costé et de relief de l'aultre Et pour cet
	tcn_p093r_preTEI	Le mesme de pierre vive deffaicte en la	cave		faict mieulx.
	tcn_p096r_preTEI	puys avecq une petite plane estroicte on la	cave		& recure demy pied vers le bout du talan, et le
	tcn_p102v_preTEI	, moule la seulem ent dun costé &	cave		d'un costé s'il est possible, en ceste sorte tu
	tcn_p104v_preTEI	moule la avec de la cire, soict	cave		ou relief, pource que elle preste estant molle & obeist,
	tcn_p104v_preTEI	se faict faulx. Quand tu as le	cave		de cire, tu y peulx gecter de l'ardille fort doulce
	tcn_p104v_preTEI	à l'aise. Puys tu feras un	cave		là dessus ave de plomb ou estaim, dans tu lequel ce
	tcn_p120r_preTEI	ou medaille, & puys en faire un	cave		de letton ou cuivre. Ou bien le frapper le mouler de
	tcn_p120r_preTEI	les lames de foeilles de pierrerie moulé en	cave		pour lesards & c. p120r_2 Sable pour gecter en or Prens
	tcn_p121r_preTEI	quaisse dans le puys, ou dans la	cave		, dans une pone ou ung coin de terre plein d'eau
	tcn_p130r_preTEI	tiré. Aprés on luy mect dans le	cave		des yeulx des balles de plomb ou de cire peincte selon le
	tcn_p130v_preTEI	, et ayant oingt de beurre ton le	cave		de ton premier moule cave, adaptes y la paste, et
	tcn_p130v_preTEI	beurre ton le cave de ton premier moule	cave		, adaptes y la paste, et puys fais dessus le second
	tcn_p140v_preTEI	. Avecq icelle aussy, on prend le	cave		d'un relief & puys on gecte dans ce cave du sable
	tcn_p140v_preTEI	un relief & puys on gecte dans ce	cave		du sable destrempé qui represente derechef le relief fort nettem ent.
	tcn_p140v_preTEI	Et puys tu peulx sur iceluy gecter le	cave		d’iceluy en cuivre, or et argent, et fayre des
	tcn_p143v_preTEI	costé estant rehaulssés d'ardille ce qui est	cave		, & puys on les descouvre de l'aultre & on faict
	tcn_p152v_preTEI	qui aye laissé quelque fosse ou chose trop	cave		, regrate cela avecq un burin et encoche aultour du bort,
	tcn_p153r_preTEI	btv1b10500001g / f311. image p153r_1 Mouler en	cave		pour cachets ou aultre Esbauche premierem ent ta figure en cire sur
	tcn_p153r_preTEI	ton sable d’eau chaulde. Ayant le	cave		, gecte le en plomb allié en la forme que les aultres
	tcn_p153r_preTEI	relief de plomb, & tu auras un	cave		fort net dans la cire, qui vient tres net sur le
	tcn_p153r_preTEI	sur le plomb. Aprés, dans le	cave		de cire, gecte ton sable destrempé, qui te fera un
	tcn_p153r_preTEI	un relief, sur lequel tu gecteras ton	cave		d’argent ou d’aultre metal pour cachet. Mays note qu’
	tcn_p153r_preTEI	note qu’il ne fault pas faire ton	cave		avecq cire fondue, ains seulement eschaufée dans de l’eau chaulde
	tcn_p153r_preTEI	faço net & reparé, emprains dessus ton	cave		de cire, & puys dans iceluy gecte ton sable, qui
	tcn_p153r_preTEI	relief, sur lequel aprés tu gecteras ton	cave		pour cachet ou aultre ouvrage. Tu pourrois bien gecter un cave
	tcn_p153r_preTEI	aultre ouvrage. Tu pourrois bien gecter un	cave		sur le principal de relief de metal & mesme de plomb &
	tcn_p153r_preTEI	en noyau ceste piece de cire qui est	cave		co mm e ton cachet, & ton noyau le rendra moulé
	tcn_p153r_preTEI	. Et ayant faict prise & rendu ton	cave		fort net, ayes de la pate de fine
	tcn_p153v_preTEI	& tanvre. Puys aplique la sur le	cave		de ton moule, et presse dessus avecq du coston, &
	tcn_p153v_preTEI	, de relief d’un costé & en	cave		de l’aultre. Ce faict, oingts avecq un pinceau trempé
	tcn_p153v_preTEI	fondu la partie de la paste qui est	cave		. Puys coupe le su r perflu de la paste qui surpasse
	tcn_p153v_preTEI	r perflu de la paste qui surpasse le	cave		du moule H. Oincts aussy d’huile d’olive ton moule
	tcn_p156r_preTEI	p156r_1 Mouler prompteme n t et reduire un	cave		en relief Tu peulx empraindre de cire colorée le relief d'une
	tcn_p156r_preTEI	d'une medaille, & tu auras un	cave		, dans lequel tu pourras gecter en noyau un relief de ton
	tcn_p156r_preTEI	ton sable, sur lequel tu feras un	cave		de plomb ou d'estain, dans lequel tu gecteras un relief
	tcn_p156r_preTEI	ceste cire tu feras ton moule en noyau	cave		, pour y gecter le relief d'or & d'argent ou
	tcn_p156r_preTEI	as haste, fais le premier empraint &	cave		de mie de pain preparée co mm e tu sçais, qui
	tcn_p169v_preTEI	carton. p169v_2 Reduire une figure ronde en	cave		Il te la fault premierem ent mouler avecq du plastre, co
	tcn_p169v_preTEI	de plomb, et elle tu auras le	cave		bien net. Adapte aprés le cave de cire en forme quarrée
	tcn_p169v_preTEI	le cave bien net. Adapte aprés le	cave		de cire en forme quarrée co mm e il te playra avecq
	tcn_p169v_preTEI	platte & unie d’un costé & en	cave		de l’aultre. Et ayant nettoyé ce cave & mis au
	tcn_p169v_preTEI	de l’aultre. Et ayant nettoyé ce	cave		& mis au blanchem ent, s’il est d’argent,

**Comment by ps2270** [comment]
creux and cave can be synonyms, and the a-p uses both to indicate a female (concave) mold, so it's not a problem to translate them both as hollow.
I think, however, that cave in most cases to do with casting should probably be translated "hollow form".  In order to determine this, we have to do a cost-benefit analysis of the following:
1. PHS go thru all the entries above and figure out what's best--I've done about 4, and it's taken me hours, and I have found all kinds of other translation issues in the process, 
2. We have a working hypothesis, e.g., "mostly hollow form, but sometimes concavity, or hollow, or concave," and we have this in front of us while we do the translation campaign.
3. Someone constructs for me a Tianna-style 2-column facing tcn/tl contextual list, and I go through them one by one.  This would be faster for me than 1. above, but still really time-consuming. Tianna could tell us how long it takes to construct this.

Once we decide which is less time-consuming, we do that.  Let's discuss briefly tomorrow.

**Comment by TillmannTaape** [comment]
TT to work on this and report to PHS; collate problematic instances to be reviewed by PHS to make a decision.

**Comment by TillmannTaape** [comment]
@ps2270 I've created [two spreadsheets](https://docs.google.com/spreadsheets/d/19_XckZt4cgZ8U5aZD2cN-FlbpybjkLh1NSwi6igOiOY/edit?usp=sharing) (see tabs at the bottom): one listing changes I have made to the TL, for you to review (and perhaps look at those entries that are flagges as "noyau"-related), and another Tianna-style table of the more problematic instances, namely where the verb is "mouler (de/en) cave, for you to make a decision. Please put what you think the TL should be in column C and I will make the changes.

**Comment by ps2270** [comment]
Please see the spreadsheet--I've entered a few corrections on the translation report sheet 1. 
Thanks!

**Comment by TillmannTaape** [comment]
I made the changes according to PHS handwritten notes on sheet 2, and corrections from sheet 1 (green highlights). 

Query @ps2270: "wet" and "wetted" are apparently both correct past participles of "wet" – I left "wetted" as  I thought it might be clearer in context but let me know if I should change that.

**Comment by ps2270** [comment]
Ok to leave wetted for now, but we will have to make a decision for the translation campaign, as THU and I found wettened and wetted and changed them both to wet.
I'll open a new issue about this.

**Comment by TillmannTaape** [comment]
Closing this issue since the "wet" discussing is being moved to a new issue.
