### ISSUE TITLE
delete unused S3 bucket "makingandknowingmanuscript.org"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1978]
After review by digital team, the AWS S3 bucket titled "makingandknowingmanuscript.org" is an unused bucket with content that is no longer needed. Its exact history and purpose are unclear, but we believe it to be a vestige of work by the Project in summer 2015, most likely with Bingyan and Terry. The bucket predates Naomi and seems to contain uploads to the M&K wordpress site made up until ~Aug 5, 2015. The wordpress site does not use reference these items from S3 in any way, so we are confident it can be removed.

A zip of all contents has been created and will be added to the M&K external backup drives in the unlikely event that the content is actually needed sometime in the future.

**Comment by njr2128** [comment]
For record, here is a partial screenshot, where each of these directories seems to hold one item, e.g. pdf, dox, or jpg: 
![image](https://user-images.githubusercontent.com/14779727/114750698-4363e080-9d22-11eb-909a-afee46471912.png)

**Comment by caro27** [comment]
moved to backup drive!

**Comment by njr2128** [comment]
Done! Screenshots proving as such:
<img width="944" alt="2021-04-20_AWS-bucket-deletion1" src="https://user-images.githubusercontent.com/14779727/115449208-8c1b0e00-a1e8-11eb-985d-324e991b2f0d.PNG">
<img width="819" alt="2021-04-20_AWS-bucket-deletion2" src="https://user-images.githubusercontent.com/14779727/115449223-8fae9500-a1e8-11eb-84d3-61710e274881.PNG">
