### ISSUE TITLE
Translation of becquet” or “bequet” (fol. 152v)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#198]
What is the translation of the “becquet” or “bequet” of the goldsmith, fol. 152v?

**Comment by ps2270** [comment]
perhaps "bracket", for it is "where one files".  So, it's perhaps the vise, where one would place an object to be filed, or a bracket to hold the vise.

**Comment by ps2270** [comment]
PHS adding a glossary entry: bequet = literally "a small beak," used on 152v as an attachment -- probably a type of vise -- to a goldsmith's table "where one files."
CAG: will add editorial note to 152v:  Keep in french as it is now on 152v, and add an editorial note, saying "literally "a small beak," a tool used in metalworking, here as an attachment, probably a vise, for a goldsmith's table "where one files."

**Comment by ps2270** [comment]
PHS has added a glossary entry.

**Comment by Pantagrueliste** [comment]
added comment
