### ISSUE TITLE
Essay done, but missing after most recent release

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#1981]
Taape, Body and the Senses: ann_302_ie_19_Taape_Body-and-Senses
says "under revision" after most recent release.

**Comment by ps2270** [comment]
The same problem for:
ann_028_fa_15_Estrades_JasperImitationOnHorn

**Comment by njr2128** [comment]
From April 27 email exchange:
> NJR: I took a closer look at this and discovered there was actually something wrong within our Google Drive - both essays' folders were suddenly missing their "Text_" files (see attached screenshots) and when I accessed the files separately from their folders, they appeared to be unorganized in the Drive (see other screenshots). I cannot see what seems to have caused this. Hopefully there are no other instances of this.

>PHS: Actually the activity log does explain this much - Camilla Shulman removed in Aug 24, 2020. hers was one that I made viewer from editor just now. A Google Drive syncing issue? (don't know how this would happen exactly)

SOLUTION: Permissions for all users modified so that edit access is only for those who require it.
