### ISSUE TITLE
Translation of "lanterne" in weapons entries

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#199]
WEAPONS - How should “lanterne” be translated? See 18v. It has been translated as “linstock” which seems appropriate for this context, but vocab list and weapons glossary do not have this word anywhere. 
TT: Jonathan suggested linstock but I now wonder if this is correct; it seems to refer to the staff holding a match, not a measure for powder.

**Comment by TillmannTaape** [comment]
I think I now remember Jonathan saying that a linstock was often a tool with a match on one end and a powder measure on the other end.

**Comment by TillmannTaape** [comment]
I was wrong about the linstock having a match on one end and ladle on the other. 

Update from Jonathan: where 'lanterne' indicates a measure of powder, or the tool used to load a gun with powder, it should be 'ladle', not 'linstock'.

**Comment by TillmannTaape** [comment]
Search term: lanterne

Changed tl to 'ladle' where it referred to the gunner's tool (as opposed to a lantern as on 10r and 68r).
