### ISSUE TITLE
Review CUL domain assignment and masking for the DCE

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#1991]
From meeting notes with Michelle, Columbia University Libraries (CUL):

- second level domain vs. first level domain
- want to ensure that configuring domain assignment and masking for the full edition640.makingandknowing.org domain will work on the libraries servers, and with their security certificates
- basically, can we get our site on their servers with our domain? - make sure there aren't any rerouting issues (so that they don't get rerouted to makingandknowing.org itself since edition640 is a second level domain)
- concern is that CU's unix system and security certificates may reroute any subdomains back to main domain (makingandknowing.org
- will likely need to get sysadmin group involved soon to test in a dev environment
- if we want Libraries to manage our domain name, Michelle is the mediator. We give her access to Bluehost and she grabs all CNAME records, and will add to CU's holdings. This is usually done with some masking due to how the servers, security certificates, but this may not need to happen for our more “contained” site

Reach out to Ben, Stuart, others(?) at CUL

**Comment by tcatapano** [comment]
I dont think we want CUL to manage the M&K domain. Instead, we can have the relevant subdomains be pointed to them for management using Cloudfront from which they can point the subdomains to wherever they want.

**Comment by njr2128** [comment]
To compose next week (@tcatapano and @njr2128 )
Questions for CUL:
- M&K plans to continue handling our own domain
- our architecture uses Cloudfront to point the domain to the content in S3
- Will the Libraries do this, too?
- If not, what can be done?
- Are there added complications due to Libraries systems or certificate manager?

**Comment by tcatapano** [comment]
This is all well documented here: 

edition640+fieldnotes_DNS+deployments:

https://docs.google.com/document/d/1i5FyJumJxU8LdG2_obS6UaX8gDqvLxLnOhxiHe4Bggs/edit

**Comment by njr2128** [comment]
To lay out: 
- get sizes of each bucket
- workflows for updates to DCE components (like update to fieldnotes)
     - Follow up on this another time

**Comment by njr2128** [comment]
Email sent to Ben & Michelle 8/20/21
