### ISSUE TITLE
Add GD urls to annotations md table

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#20]

**Comment by tcatapano** [comment]
Added sheet to google drive with data on annotations from Nick's lizard-scan.log for merging into annotations metadata table

https://docs.google.com/spreadsheets/d/19VIGQMl6Li5CLn1XQJdw8D9YAT_I3rz8aAjJ5D1lMsY/edit?usp=sharing

**Comment by njr2128** [comment]
I am working in the Google Drive Folder, DCE digital admin and metadata (https://drive.google.com/open?id=12WYudkum6jtZO2j_z2o_o5ZKbldO3i4b) where most master metadata sheets live (or will live) in GD

**Comment by njr2128** [comment]
Current status:
Information was taken from "Copy of annotations_log_data" (https://docs.google.com/spreadsheets/d/1mhlUrhYdU3Kq5xMginKrFTiTDvFx8K8QEss2aC-MzNo/edit?usp=sharing) to "Annotation tracking and metadata" (https://docs.google.com/spreadsheets/d/100gc0_Fue9KdNmqNtGpmaWGWGNnOMjEe_rWgxEOocmE/edit?usp=sharing).

Three values were migrated: 1) text_folder, 2) annotation_file, and 3) UUID.
As info was copied over, I changed the color of the rows in "Copy of annotations..." to help keep track.

There are ~15 annotations that are not in the log. I am investigating possible reasons for why they are throwing errors for Nick.

**Comment by njr2128** [comment]
Information for missing annotations has been entered manually when possible in "Annotation tracking and metadata" (https://docs.google.com/spreadsheets/d/100gc0_Fue9KdNmqNtGpmaWGWGNnOMjEe_rWgxEOocmE/edit?usp=sharing).

Issues have been logged for any problems (see #22, #23, #24, #25, #26, #27, #28, #29, #30, #31, #32)

**Comment by njr2128** [comment]
Column added to metadata sheet that records whether information was present in "lizard logs" or whether info was entered manually, as well as brief description of issues (that have been logged in the issue tracker)

**Comment by njr2128** [comment]
All UUIDs have been verified for ones that exist and are clear.

"GD folder URL" have been added for all annotations in metadata sheet.  
"GD text URL" added for those that exist and are clear (and cross-checked with UUIDs)

Annotation tracking and metadata:
https://docs.google.com/spreadsheets/d/100gc0_Fue9KdNmqNtGpmaWGWGNnOMjEe_rWgxEOocmE/edit?usp=sharing
