### ISSUE TITLE
Translation of "rendre", "rompre" and "fendre"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#200]
rendre, rompre and fendre all translated as “break” – this ok or translate as “to rend” and “to split”, for example?

**Comment by thuchacz** [comment]
![image](https://user-images.githubusercontent.com/23508994/54029789-b0860e80-4177-11e9-8c82-561d362061f6.png)
THU used regular expression ^[Rr]end* to search for variants of “rendre” (16/24 relevant)
THU used regular expression ^[Rr]omp* to search for variants of “rompre” (20)
THU used regular expression ^[Ff]endr* to search for variants of “fendre” (9)

**THU question**: can we provisionally decide on translations that I can test against as I search?

- Rendre = rend. I question how many of these there will be since the sense of splitting is not the most common sense of “rendre” and is not recorded in Cotgrave
- Rompre = break. Cotgrave: “burst, break”
- Fendre = split? Cotgrave: “cleave, slit, rive, divide, or cut, asunder”

**Comment by thuchacz** [comment]
I used faulty regular expressions in my first search. ^[Rr]end* to search for variants of “rendre” (16/24 relevant) only gave “R/rend” at the beginning of a line. 
\s[Rr]end* gave 172 hits
\s[Rr]omp* gives 101 
\s[Ff]endr* gives 62 (including “fente” as a noun)

**THU REPORT**
"Rendre" was variously translated as becomes, makes, renders (often passive), renders up, gives off
"Se rendre" = render itself; return
_It was never used in the sense of the English word "rend"_

"Rompre" was translated consistently as "break," except in the context of grenades and petards, where it was translated as "burst"

"Fendre" was inconsistently, and without apparent reason, translated as break, split, cleave, crack. See table below.
I also looked at the noun "fente" as a point of comparison, which was translated as either crack or cleft. See table below

**THU RECOMMENDATION**

"Fendre" should be translated as crack. Cleave is too ambiguous. Break should be reserved for "rompre."

**Comment by thuchacz** [comment]
**FENTE (n.)**
<img width="693" alt="Screen Shot 2019-03-13 at 06 45 33" src="https://user-images.githubusercontent.com/23508994/54273148-a68b5380-455b-11e9-9b40-d0c36d67dd72.png">

**Comment by thuchacz** [comment]
**FENDRE (v.)**
<img width="655" alt="Screen Shot 2019-03-13 at 06 50 57" src="https://user-images.githubusercontent.com/23508994/54273727-df77f800-455c-11e9-9833-df146cac8ded.png">
<img width="658" alt="Screen Shot 2019-03-13 at 06 51 20" src="https://user-images.githubusercontent.com/23508994/54273737-e43cac00-455c-11e9-9a27-1b4f30d26c61.png">
<img width="661" alt="Screen Shot 2019-03-13 at 06 52 05" src="https://user-images.githubusercontent.com/23508994/54273746-e7d03300-455c-11e9-87e1-1ef01463ca3f.png">
<img width="655" alt="Screen Shot 2019-03-13 at 06 52 44" src="https://user-images.githubusercontent.com/23508994/54273758-ec94e700-455c-11e9-8c45-2534e3471cf5.png">
<img width="657" alt="Screen Shot 2019-03-13 at 06 53 58" src="https://user-images.githubusercontent.com/23508994/54273775-f1599b00-455c-11e9-84a1-ccdee91ef165.png">
<img width="654" alt="Screen Shot 2019-03-13 at 06 54 23" src="https://user-images.githubusercontent.com/23508994/54273785-f61e4f00-455c-11e9-83a4-40f83ab6f357.png">

**Comment by ps2270** [comment]
Tianna, can we just go down this list when we are next together and we can change the ones that need it?
1. crack good for painting
2. cleft grafting good
3. I need to check some of the molding ones.
For the stick - a cleft stick?
To be continued in person together, or I will send recommendations.
thanks

**Comment by thuchacz** [comment]
Yes, Pamela. Let's do this when we're next together.
T.

**Comment by thuchacz** [comment]
Fendre: crack (esp. of molds); occasionally, split, slit, or cleave depending on context.
