### ISSUE TITLE
Translation of "sestier"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#202]
sestier = currently leave in Fr., but OED has English word ‘septier’ for the French unit of measurement. Use this instead? 

Also consistify in Assis Annotation FA2018.

**Comment by Pantagrueliste** [comment]
Septier for sestier, and put it in the glossary.

**Comment by Pantagrueliste** [comment]
*Septier* is good.

**Comment by ps2270** [comment]
Go ahead with this.
