### ISSUE TITLE
Editorial note correction - fol. 169r, 4v, 5r, 6v, 104r

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#2025]
The editorial comment on "Engraving with aquafortis..." is wrong. It is a comment that is on 4v.  The comment on 169r should read: Engraving here involves a process now known in English as "etching." 
Ah, and there is another comment on 4v (Vernis...) that has the same problem. It also should read: Engraving here involves a process now known in English as "etching."
I see what happened now.  On the Comment tracking sheet, there are two different entries with the same ID: c_004v_02.
@njr2128 we need to go over this together because there may be more of these.

**Comment by njr2128** [comment]
I thought Tianna and I had caught these all, with another pass from you and the postdocs during the full readthrough, but alas it will never be perfect! 

I will fix the instance of the duplicate c_004v_02 (I can see from the comment sheet that it was the comment about etching was added at some later point)

**Comment by njr2128** [comment]
These are all instances of this comment anchor, with short excerpts from the TL (corresponding ones exist for TC and TCN)

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

folio | description
-- | --
004v | harnesses<comment rid="c_004v_02"/> or removing the bands from
004v | <head><m>Varnish of <pro>iron engravers</pro></m><comment rid="c_004v_02"/></head>
005r | <ms><tmp>hours</tmp></ms> &amp; it will be engraved.<comment rid="c_004v_02"/> But if you should
006v | <ab render="wide">Engrave<comment rid="c_004v_02"/> with <m>aquafortis</m> on <m>iron</m> or <m>copper</m>
104r | <head>For engraving<comment rid="c_004v_02"/> on <m>iron</m></head>
140r | in place of <m>varnish</m> to engrave<comment rid="c_004v_02"/></ab>
151v | engraving<comment rid="c_004v_02"/> on it afterward, for varnishing <wp>sword guards</wp> tawny. And could
169r | Engraving<comment rid="c_004v_02"/> with <m>aquafortis</m> on <m>silver</m><lb/>


</body>
</html>

**Comment by njr2128** [comment]
The comment about blackening metal has been changed to c_004v_03 and updated across all 3 versions. The rest, which all discuss engraving/etching, have been left as c_004v_02
