### ISSUE TITLE
MHS: use of "&" as etcetera 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#203]
THU: 142r (3rd page of a long entry on molding crayfish—entry p141_1). The marginal note along the very top gives a list of possible tools to use, and it ends (puzzlingly) in an ampersand (and a strip of paper). We would want this to be an etcetera. Thoughts?
 
MHS: Needs to be checked in situ. Either there is a word under the paper, or that & stands for &c and should be transcribed "&<exp>c.</exp>" (see below).

2.11.19: we need to contact Marc about doing the transcribing under the strips of paper

**Comment by thuchacz** [comment]
UPDATE:
MHS says that this ampersand needs to become an etcetera. His suggestion: leave as ampersand in TC, do whatever our current markup protocol requires to make it an &c. in the TCN and the TL.

There is the same problem on 146r:
```
Aprés use<lb/>
de <tl>sayes de <al>porceau</al></tl>,<lb/>
d’un bout de <tl><m>fil de<lb/>
fer</m></tl> &amp;<lb/>
```
There is only an ampersand in all three versions and the TCN and TL need to become an etcetera.

**Comment by TillmannTaape** [comment]
Changed in both instances: & in TC, &<sup>c.</sup> in TCN, &c. in TL.
