### ISSUE TITLE
Regularize use of <man> tags

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#205]
Use of  <man> and how its markup should be regularized (inside `<ab>`s, instead of, etc.)
See https://github.com/cu-mkp/making-knowing-edition/issues/63 (for Nick about this)
See also #41 (identify elements not in schema)

**Comment by ps2270** [comment]
#12 might be relevant here.  We will discuss on May 17.

**Comment by tcatapano** [comment]
closing. To be resolved by #643
