### ISSUE TITLE
Use of  <exp>c.</exp> to mean "etcetera"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#206]
**Use of `<exp>c.</exp>`**

- THU:  In the tcn for 146r, in the second marginal note, near the end it said 
"Aprés use`<lb/>`
de `<tl>`sayes de <`al>`porceau,`</al></tl>`,`<lb/>`
d’un bout de `<tl><m>`fil de`<lb/>`
fer`</m></tl>` &amp; `<exp>`c.`</exp>`”
We have removed the following tag `<exp>c.</exp>` after the ampersand. It is not in the manuscript nor the tc.

- MHS: Keep <exp>c.</exp>. That is how all &s standing for "etcetera" have been transcribed. But I forget whether it applies to tc and tcn or just tcn, please check instructions for transcription.

- From Markup protocol:
 exp tags should be used in both tc and tcn.
When abbreviation mark is missing in ms, use <exp> element within <corr> tags, both in tc and tcn
i.e. DECISION NEEDED here: do we take & to be an abbreviation for “etc.” as well as “and” – i.e. expand as follows: &amp; <exp>c.</exp> – OR
do we only allow & to stand for “et” and the c becomes an editorial addition, i.e.: &amp; <corr><exp>c.</exp></corr>

- phs:  most recent protocol:
The use of & to mean “etc” rather than “et” (determined by context) will henceforth be left as is (just &) in the tc, and in tcn &amp;<sup>c</sup>.  Previously it was &[c]. In tl, it will be written &amp;c [Previously, it was &[c]

**Comment by TillmannTaape** [comment]
@ps2270 Last point in last comment above: in the instructions for the tcn, the c after the ampersand is superscript – I imagine this is an accident of html rendering of github comments, and that it should read "&<sup>c</sup>". Can you confirm please?

**Comment by ps2270** [comment]
The actual text of the entry in the PW Markup Protocol is below, and it is different in 2 points (not just 1, as you seem to mean) from what you have above, so maybe both are the html rendering of Github, so please, which will probably happen again once I comment.
So, please see PW18 Markup Protocol to confirm the protocol [IT IS IMPORTANT TO CONFIRM THIS]: https://docs.google.com/document/d/1DJ8BcCft5fwwMTNAImyaTuYpK--ht8JxaT2VEm-7kfk/edit

"The use of & to mean “etc” rather than “et” (determined by context) will henceforth be left as is (just &) in the tc, and in tcn &amp;<sup>c</sup>.  Previously it was &[c]. In tl, it will be written &amp;c [Previously, it was &[c]"

**Comment by ps2270** [comment]
Yes, it rendered them wrong again, so be sure to see the protocol: 
https://docs.google.com/document/d/1DJ8BcCft5fwwMTNAImyaTuYpK--ht8JxaT2VEm-7kfk/edit

**Comment by TillmannTaape** [comment]
Great, thank you for clarifying. I’ve just discovered that you can use the ‘insert code’ button on GitHub to avoid html rendering.

**Comment by TillmannTaape** [comment]
`The use of & to mean “etc” rather than “et” (determined by context) will henceforth be left as is (just &) in the tc, and in tcn &amp;<sup>c</sup>.  Previously it was &[c]. In tl, it will be written &amp;c [Previously, it was &[c]`

**Comment by ps2270** [comment]
Yes.

**Comment by TillmannTaape** [comment]
In TC: searched for "c" (whole words only) and where the c of &c was supplied, I eliminated it.

In TCN: searched for "c" (whole words only) where the c of &c was supplied I checked against tc, ensured that it was marked `&amp;<sup>c</sup>` (often this had to be changed from `&amp;<exp>c</exp>`), and checked that the TL is `&amp;c` without a sup  tag.
