### ISSUE TITLE
commas missing from TL on fol.1v?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#2064]
There are clarifying commas in the TCN that are not present in the TL. Is there a reason for this?
The translation of this entry on 1v is confusing to an English user because of the wording (though it matches the French as closely as possible - our translation principle), but adding these commas may help a reader too.

![image](https://user-images.githubusercontent.com/14779727/167909438-ca4fbbb1-6218-4614-8397-a598f9b645a5.png)

**Comment by ps2270** [comment]
Yes, I am ok with this. Thank you
