### ISSUE TITLE
add doi to "cite as" of lifecasting essay

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#2069]
https://doi.org/10.7916/ym8m-r917 -- "cite as" is missing DOI info
https://edition640.makingandknowing.org/#/essays/ann_511_ad_20

**Comment by ps2270** [comment]
In the 'Cite as' for this essay, we need to delete from the author field' 'and the Making and Knowing Project'

**Comment by njr2128** [comment]
Done in annotation-data https://github.com/cu-mkp/m-k-annotation-data/commit/56dcee88b7eff244c96774d48f84cfd05fe94fe4
