### ISSUE TITLE
check multcloud backup

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#2071]
From email notifications, last backup seems to have been 7/31/2022 -- check that this is still working

**Comment by njr2128** [comment]
Logged in and went to "task  list." Next to Google-Drive-2020, the button circled in red below said "resync," so I pressed it and it is now calculating size:
![image](https://user-images.githubusercontent.com/14779727/190665812-2e7c7a89-9c18-4288-940b-a04a6b2e5247.png)

**Comment by njr2128** [comment]
It may be possible that multcloud has not registered our annual renewal, which usually happens in July each year. I was charged by them on 7/28/22, but no email confirmation was sent, which has happened previously -- see attached example from last year
[2021-07-27_Multcloud_Gmail - Fwd_ Pay successfully.pdf](https://github.com/cu-mkp/m-k-manuscript-data/files/9585114/2021-07-27_Multcloud_Gmail.-.Fwd_.Pay.successfully.pdf)

**Comment by njr2128** [comment]
The "resync" seems to have worked in jumpstarting a new backup (see notification attached - this is what we usually get 1/week when running properly - failure notifications). Check and/or wait to see if this jumpstarts weekly scheduled runs
[2022-09-16_Gmail - Fwd_ MultCloud Sync Notification (Failure).pdf](https://github.com/cu-mkp/m-k-manuscript-data/files/9587253/2022-09-16_Gmail.-.Fwd_.MultCloud.Sync.Notification.Failure.pdf)

**Comment by njr2128** [comment]
In the midst of trying rclone as a backup option for GD

**Comment by tcatapano** [comment]
for flickr backup see: https://github.com/tgerla/flickr-s3-backup

**Comment by njr2128** [comment]
completed enough for now. New strategy in place
