### ISSUE TITLE
missing transcription on 17r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#2078]
Thank you, @thuchacz for noticing! As she notes:
>there's an aborted marginal note right at the edge of the top left of 17r. It's struck through and partly obscured by the paper strip. "Le cou__ canon" (court? that seems grammatically weird.)

![image](https://github.com/cu-mkp/m-k-manuscript-data/assets/14779727/142827fa-8fe2-4346-a0e8-fe98078c737e)

@TillmannTaape and @Pantagrueliste , could you take a look?
https://edition640.makingandknowing.org/#/folios/17r

**Comment by Pantagrueliste** [comment]
Tillmann is right. It’s double. The fourth letter is a b, and the fifth looks like an l. Moreover the author-practitioner never places adjectives “court" or “long” before a noun

Tillmann is right. That was fun.

Greetings from France.

Clément.

**Comment by njr2128** [comment]
Thank you, all!

I will transcribe as follows:
`<ups><del>Le <wp>double canon</wp></del></ups>`

and translate as follows:
`<ups><del>The <wp>double canon</wp></del></ups>`

**Comment by njr2128** [comment]
Decision from NJR/THC: this looks to us like it is the first marginal note of the "On the gunner" entry, so we are going to associate it with this div - `p017r_1`

**Comment by njr2128** [comment]
done
