### ISSUE TITLE
Use of `<corr>` tags and action item

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#217]
`<corr>` tags were used for in the following ways:
In the TC and TCN
1. For expanded abbreviations in tc and tcn, we used `<exp>` element; E.g.,
subtillem`<exp>`ent`</exp>`
In cases where M&K has corrected where the author has forgotten the abbreviation  is indicated by `<corr><exp>text</exp></corr>`
Be sure to use <exp> element within `<corr>` tags, both in tc and tcn :
WE ARE HAPPY WITH THE RENDERING OF THESE INSTANCES

2. In the TCN and TL ONLY
-For editorial corrections in tcn (places where the M&K team member is correcting a mistake on the part of the original writer), use `<corr>`; E.g.,
Garrant in the ms becomes: Garan`<corr>ce</corr>`
-For corresponding corrections in the English Translations,
the `<corr>` tag encloses the entire word, even if it is only a part of the word that has been corrected.
WE ARE HAPPY WITH THE RENDERING OF THESE INSTANCES

This second instance includes where `<corr> is used with the <del>` tag to show that the M&K team believes the a-p forgot to delete a word.
In this last instance, THE RENDERING IS DIFFICULT, therefore the decision is hereby to have an editorial note that says something like "a-p likely forgot to delete this word". So, we'd need to change these `<corr> tags to <comment>` tags. There seem to be 53 instances of this in the tcn and fewer in the tl.

**Comment by TillmannTaape** [comment]
All `<corr><del>` tags removed from TC; see #215

**Comment by TillmannTaape** [comment]
<corr><del> is often used for individual letters of a word or for several words, so this would require a custom comment each time to describe the deletion. This will often be awkward.

E.g. 1r. Caresariensis [comment: "sic., correct: Caesariensis"]
E.g. 19r si on tire de balle de fer de fer[comment: "the author-practitioner likely forgot to delete the repeated 'balle de fer'"] de poincte en blanc
NB this would also require a different comment for the translation.

Are we sure we want this every time? It would be a lot of work, but more importantly, perhaps not a very elegant solution. Perhaps something could be done with rendering after all. Shall we table this until we've played around and thought more about the details of markup rendering?

**Comment by TillmannTaape** [comment]
DECISION: We want to to express corr del with rendering.

Render as follows:

<corr> = square brackets
<corr><del> = Square brackets with strikethrough
<exp> = curly braces

**Comment by njr2128** [comment]
> DECISION: We want to to express corr del with rendering.
> 
> Render as follows:
> 
> ```
> <corr> = square brackets
> <corr><del> = Square brackets with strikethrough
> <exp> = curly braces
> ```

Rendering issue created in making-knowing-edition repo (issue 151)
