### ISSUE TITLE
FA14 "Calcined Oysters"- need to identify most complete text file

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#22]
ann_006_fa_14 
 "Calcined Oysters," fol. 84v (Cataldo, Visco)

There is more than one document in the text file folder. Need to determine which one is the most complete.  See GD folder: https://drive.google.com/open?id=0BwJi-u8sfkVDZ1hJTzFnbUY2T2c

**Comment by ps2270** [comment]
The most complete annotation version is this one: https://docs.google.com/document/d/1rVBQIZCi0jVluY_BYl7i644D0hQ3OWqcq6_-6uY4vco/edit (correctly named, and edited by Hannah).  PHS moved incorrect version to Annotation archive. PHS moved Captions from bottom of essay to Captions folder.

**Comment by njr2128** [comment]
Updated metadata
