### ISSUE TITLE
FA14 "Sands and binders"- need to identify most complete text file

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#23]
ann_011_fa_14
"Sands and Binders," fol. 82r, 84v (Cataldo, Visco)

**Comment by ps2270** [comment]
The text is https://docs.google.com/document/d/1z482cCWwR01kpNY8sDanRED_TMQcsxsKrtXjBhb89Xs/edit
PHS moved the superseded  files to the relevant folder. PHS moved the captions into their own folder/file.

**Comment by njr2128** [comment]
Updated metadata
