### ISSUE TITLE
Inconsistent markup across versions in 103v_4

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#236]
@ps2270 and @TillmannTaape 

It appears that the tc and tcn have a `<bp>` tag around "teste" while the tl equivalent does not, as follows:

> ...le passe par l'`<m>`escume de l'urine`</m>` qui se faict
volontiers`<lb/>` par ceulx qui ont mal de `<bp>`teste`</bp>`

and 

> ...you pass it through the `<m><bp>`foam of urine`</bp></m>`, which is readily made by
those who have a headache

Please advise whether tag should be carried over to the tl "headache" or  removed from "teste" in tc and tcn

**Comment by TillmannTaape** [comment]
Thanks Naomi. I would say definitely carry over the <bp> tag to the TL.

All best,
Tillmann

--

Dr. Tillmann Taape

Lecturer in History
Postdoctoral Scholar, The Making and Knowing Project

Book reviews editor, Ambix

Columbia University
Center for Science and Society
511 Fayerweather Hall, MC 2509
1180 Amsterdam Avenue
New York, NY 10027

tillmann.taape@cantab.net

**Comment by njr2128** [comment]
See #130
