### ISSUE TITLE
Translation of "naturel" and "le naturel"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#241]
Decision pending from PHS on translation of "le naturel" and "naturel." Glossary needs to be updated and clear workflow for consistency work defined here below.

**Comment by njr2128** [comment]
From PW18 tracking:


p118r_5 | p118r | Sel armoniac | Sal ammoniac | casting | p118r
-- | -- | -- | -- | -- | --
SD, PHS slightly reworked on the 7/2/2018, for "naturelle" translation                     Title checked and updated by PHS - 7/11/2018



p118v_1 | p118v-p119r | Gect en chassis p2 | Casting in a frame p2 | casting | p119r
-- | -- | -- | -- | -- | --
7/3/2018 "aspalt" here seems to mean "spat," PS,SD left in French and translated as "spalt." "naturel" trans. as "nature"           Title checked and updated by PHS - 7/11/2018

**Comment by thuchacz** [comment]
see #186 for decisions
