### ISSUE TITLE
Organization of FA15 Imitation Gemstones annotations

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#248]
FA15 Imitation Gemstones was written within organization of one annotation, but there are actually 3 separate annotations. 

General organization of these files and their contents is needed, and, specifically, @ps2270 please:

- Make any appropriate folders (additional captions, illustrations, etc)
- Check the listed folio entry listed for everything (illustrations, captions, file/folder names, etc) - there is inconsistent use of 100r, 100v, 101r, etc
- Go through the illutrations to divide them among the three texts
- Check the captions

**Comment by njr2128** [comment]
Text folders have been created, and appendices have been separated out by annotation into those folders. 

NOTE: folio entries cited still need to be checked in file/folder names

NOTE: the 3 text folders each contain an appendix, a second gdoc

**Comment by njr2128** [comment]
Once complete, annotation metadata needs to be updated

**Comment by ps2270** [comment]
The 3 gemstone folders can now be separated, but Gen Ed needs to make folders for captions and illustrations within each folder.  The folio span of each annotation is now correct FOR THE TEXT FILE NAME ONLY, but all other files need to be properly renamed. The captions files in Piererrie and Ruby need to be downloaded and uploaded to change ownership to Gen Ed.

**Comment by njr2128** [comment]
"Pierrerie," fol. 100r-101r (Kremnitzer, Shah)

- updated all file and folder names to correct folios (100r-101r), including all figures

- Downloaded and reuploaded Captions file, and moved original file owned by Kremnitzer to Instructor Files Archive. Links to figures in this file (which are extraneous anyway) still point to the correct files in GD

- All other files and folders created (Abstract, bibliography, etc)

- block quote copied into a comment was cut off by GD character limit. Updated to include all quoted entries

**Comment by njr2128** [comment]
"Emerald," fol. 100v (Kremnitzer, Shah)

* updated all file and folder names to correct folios (100v), including all figures
* All other files and folders created (Abstract, bibliography, etc)
* block quote copied into a comment was cut off by GD character limit. Updated to include all quoted entries

**Comment by njr2128** [comment]
"Ruby," fol. 100v-101r (Kremnitzer, Shah)

* updated all file and folder names to correct folios (100v-101r), including all figures
* Downloaded and reuploaded Captions file, and moved original file owned by Kremnitzer to Instructor Files Archive. Links to figures in this file (which are extraneous anyway) still point to the correct files in GD
* All other files and folders created (Abstract, bibliography, etc)
* block quote copied into a comment was cut off by GD character limit. Updated to include all quoted entries

**Comment by njr2128** [comment]
Annotation metadata updated for all three annotations

Three annotations moved into larger Fall 2015 annotations folder, and original "Imitation Gemstones" folder deleted
