### ISSUE TITLE
SP15 "Powder for hourglasses"- problems in GD text folder

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#25]
ann_021_sp_15
“Powder for Hourglasses,” fol. 10r (Marris, Pope)

Annotation text folder contains text, appendix file, and a pdf

**Comment by ps2270** [comment]
The annotation text is here: https://docs.google.com/document/d/1xsKy_5wTQ0T_MFow2VG2vL2Sw-Be8wdxHd5ElTTwnnE/edit

The other files in the text folder need to stay there for annotation editing.

**Comment by njr2128** [comment]
Note added to metadata about additional files. Metadata already updated

**Comment by njr2128** [comment]
PDF titled "sandurmacher" was contained in file but not owned by General Editor. Reuploaded and original deleted
