### ISSUE TITLE
FA15 "Brushes" text folder and file does not exist in BnF folder

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#26]
Annotation text is still in Student Files, needs to be finalized and organized, then moved to BnF when ready

**Comment by ps2270** [comment]
Annnotation is here: https://docs.google.com/document/d/1WuEruktTYEbJGAGvMgOgowBkO4IKOWbNGKPMqWWbD38/edit

**Comment by njr2128** [comment]
Updated metadata
