### ISSUE TITLE
Reconsider tool tag use in weapons

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#262]
Not a priority, but possibly important and of interest.

Use of tool tag has been conservative in these entries.

PRO of not tagging: entries are so technical that tagging would seem abundant and overwhelming
CON of not tagging: larger understanding of the tools available/known to the A-P will be lacking

Reconsider the entries as a whole group by the entire M&K team

**Comment by Pantagrueliste** [comment]
`<wp>`

**Comment by Pantagrueliste** [comment]
Could not find weapons tagged as tools. closing issue.
