### ISSUE TITLE
Revisit tagging "lute" as a tool

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#263]
Review the ways in which "lute" is used, especially in the casting recipes, and whether they should indeed be tagged as "tools".

See also closed issue #116 "Check consistency of lute/luting"

**Comment by TillmannTaape** [comment]
Search term: luth* (RE)

TC: lute/luter never tagges as tool; tagged as material in about 60% of cases.
TCN: lute/luter never tagged as tool; tagged as material in about 80% of cases .

TL (search term "lute"): Never tagged as tool; tagged as material in about 90% of cases.

**Comment by TillmannTaape** [comment]
Decision: tag as tool and material.

**Comment by TillmannTaape** [comment]
Search term in TC and TCN: luth* (RE)
Search term in TL: lute

All tagged `<m><tl>lute</tl></m>`
