### ISSUE TITLE
"boutteure" translate as boiling

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#265]
When "boutteure" is used in French, translation should be a form of boiling in the English.
See related #82 "boutter" verb use

**Comment by TillmannTaape** [comment]
Godefroy: eau préparée dont les orfèvres se servaient pour blanchir l’argent, les monnayeurs pour blanchir les pièces de monnaie.
So it could be 'pickle', the pickling solution used to whiten silver, but this should be determined in context. E.g. on 12v and 104 it is not clear that the ap uses 'boutteure' in this way.

**Comment by thuchacz** [comment]
on 104r, leave it as "gentle boutteure" and add an editorial comment saying:
"Boutteure" could mean either boiling liquid or silversmiths' pickle for removing tarnish. See glossary.

on 12v, change to "goldsmiths' bouteure" and add same comment as above.
