### ISSUE TITLE
"balle" = "ball" in artillery context

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#273]
In the context of guns/artillery, "balle" should be translated as "ball" for both handguns and larger cannon, not "bullet" or "cannonball".

**Comment by TillmannTaape** [comment]
NB vocab says: If talking about different ammunition and their weight, use “shot”

**Comment by ps2270** [comment]
Do you mean there are only 3 instances in the whole ms?  I think you are right that we should translate as ball if it is really only 3 instances in whole ms.

**Comment by TillmannTaape** [comment]
Yes, only three overall. I'll change it to "ball" throughout.

**Comment by ps2270** [comment]
Good

**Comment by TillmannTaape** [comment]
Search terms: balle, bale
