### ISSUE TITLE
SP16 "Azure enamels" - folder contains text and notes file

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#28]
ann_033_sp_16
"Azure Enamels," fol. 11r, 59r, 61v, 93v (Chang, Clemens)

Possibly the cause of errors in "lizard logs". To rectify, notes file would need to be removed. The actual text of the annotation is the doc "AnnotationSpring2016_ChangClemens_AzureEnamels_11r59r61v93v" (see text folder https://drive.google.com/open?id=0BwJi-u8sfkVDMHN2LWtpNnE5cGc)

Wait to re-organize folder until consensus reached with M&K team about workflow

**Comment by ps2270** [comment]
This is the annotation text: https://docs.google.com/document/d/1YNRGZTID5NGXX3vT5NqRzA7UxT1DW03OSXqLl6cc28U/edit
The  File of notes needs to stay in the folder until annotation editing is complete.

**Comment by njr2128** [comment]
Note added to metadata table about additional files. Metadata already updated

**Comment by njr2128** [comment]
Notes file is owned by Le Pouesard

**Comment by ps2270** [comment]
This is a file that is just for the revision of the annotation, so does it matter that it is owned by Emma?  I would say no, it doesn't.  What do you say?

**Comment by ps2270** [comment]
this essay was abandoned and usable content moved to other essays
