### ISSUE TITLE
Identify annotations with appendices, in what form, and standardize

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#282]
To be added to Annotations metadata:
* Record which annotations have appendices
* Identify what form the appendix is in (e.g. separate doc or sheet in annotation text folder; or text at the end of annotation text file

Determine what best form is and implement across all annotations

**Comment by njr2128** [comment]
For example,
> FA15 Ruby - separate gdoc file within text folder
> FA17 Imitating Nature - separate gsheet in illustrations folder
> SP16 Or Mat - appendices appear at the bottom of the text

**Comment by caro27** [comment]
- [X ] Fall 2018
- [ ]
- [ ]
- [ ]
- [ ]
- [ ]

**Comment by caro27** [comment]
@njr2128 - for tables that are in the annotation text, should I move those to the end of the annotation and label as an appendix? Some students have categorized tables as an appendix and some keep them in the text. Or is this not even a big issue?

**Comment by caro27** [comment]
@njr2128 - Should I check the Amsterdam annotations as well? Sorry to bother you!

**Comment by njr2128** [comment]
> @njr2128 - for tables that are in the annotation text, should I move those to the end of the annotation and label as an appendix? Some students have categorized tables as an appendix and some keep them in the text. Or is this not even a big issue?

It appears that some students have tables inline, some as appendices, and some as both. If some have both, there thus seems to be a distinction between an inline table and an appendix, so we should keep them separate for now and not standardize.

Additionally, Nick does not seem to have problem with the rendering of inline tables or appendices (in progress), so it should not affect that either. 

If anything, this is a potential editorial question of the meaning and use of tables in annotations at large. DECISION FOR NOW: leave as they are

**Comment by njr2128** [comment]
> @njr2128 - Should I check the Amsterdam annotations as well? Sorry to bother you!

No, no need. Amsterdam annotations will be dealt with separately. Thanks!
