### ISSUE TITLE
SP16 "Or Mat" - multiple files in text folder

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#29]
ann_041_sp_16
“Or mat,” fol. 66r-v (Ndungu)

Annotation text folder contains 3 text files: the annotation plus 2 notes docs

**Comment by ps2270** [comment]
The additional files in this text folder are necessary for the annotation editing work, and also for the markup b/c they have to do with order (and rendering) of marginalia. Files must be left in the GD until annotation finalization is completed.

**Comment by njr2128** [comment]
Note added to metadata about additional files. Metadata already updated

**Comment by njr2128** [comment]
Files also not owned by General Editor. Transfer of ownership needed from Ndungu and Boulboulle
