### ISSUE TITLE
SP15 Ox Bone, Wine, and Elm Root Sandcasting needs bibliography

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#299]
Does a bibliography exist for SP15 “Ox Bone, Wine, and Elm Root Sandcasting,” fol. 84v (Marris, Pope)?
It is not present at the end of the text file, and another file cannot be located in the GD

**Comment by ps2270** [comment]
need to construct one during annotation editing phase.
