### ISSUE TITLE
Text file of "Too Thin Things," fol. 142v (Fu, Zhang)?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#309]
Please identify the text files in "Too Thin Things," fol. 142v (Fu, Zhang) - there are 2 files; which is the primary annotation? What is the other one?

**Comment by ps2270** [comment]
PHS corrected this annotation completely, and the file in the annotation folder is correct:
https://docs.google.com/document/d/1_Gp4XYI22JVCx73vXxpcRvJAgWkB65PVldcApUQ5OC0/edit

**Comment by njr2128** [comment]
Metadata updated to reflect this information.

Bibliography should still be checked (GD comment left)
