### ISSUE TITLE
Use of "thusly" in translation

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#318]
Do we want to use the word "thusly"?  I don't think this is acceptable English (but can be persuaded otherwise).

**Comment by TillmannTaape** [comment]
I am quite strongly agains "thusly" – "thus" is already an adverb and nothing but an adverb, so the suffix is superfluous. The OED has it as 'colloquial'. To me it sounds downright satirical: "and he spake thusly..."

**Comment by ps2270** [comment]
Me too. Any other input?  If not, let's make it a consistency issue.

**Comment by TillmannTaape** [comment]
Decision: change all "thusly" to "thus"

**Comment by TillmannTaape** [comment]
Two separate case-sensitive search and replace in TL:
thusly ➛ thus
Thusly ➛ Thus

All instances checked in preview before replacing.
