### ISSUE TITLE
SP17 "Reconstructing cures" - need to identify number of annotations 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#32]
ann_058_sp_17
"Reconstructing Cures," fols. 46r, 47r, 66v, 103r (Liu)

More than one annotation is contained in this folder. There is no "text" folder - the files are loose in the larger folder.
Folder: https://drive.google.com/open?id=0BwJi-u8sfkVDQUNhNmlob2pEMG8

**Comment by ps2270** [comment]
PHS & NJR have added these multiple annotations to the SP17 annotation folder and archived the superseded folders.

**Comment by njr2128** [comment]
Metadata updated
