### ISSUE TITLE
Review use of empty figures <figure/>

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#332]
There are ~44 occurrences of `<figure/>`

These should either be converted to marks or a cropped image should be created and linked as with other figures,

A few examples that were investigated showed `<figure/>` used to represent horizontal lines across the page (166v), scribble or pen leak in margin (162r), or special characters (93v)

**Comment by thuchacz** [comment]
Entry | TC | TCN | TL |   |  
-- | -- | -- | -- | -- | --
93v_2 Azur | Y | Y | Y | en   le couchant premierem<exp>ent</exp> de long<lb/>   puys de travers <figure/> | Vertical Hashes \|\|\|\| and    Horizontal ones=== to show   directino of application FIGURE
94r_1 on 94v | Y | Y | Y | 5 empty figure tags:   1) cluster of 4 sketches   2) sketch marked a   3) sketch marked b   4) sketch marked c (with   caption)   5) sketch marked d (with   caption) | ALL need to be made FIGURES
105r_4 | Y | Y | Y | Puys   fais diligement dans le bois tendre <del>s</del> et qui est   en<lb/>   sabe sur lequel tu veulx hanter deulx traits ainsy <del>de</del>coupes<lb/>   <figure/> puys fais au   milieu une fente ainsy | This sketches the first   step in a 2-part grafting cut; second step is already an inline figure (not   rendering). This needs to be made a FIGURE
114r_1 on 115r | Y | Y | Y |   | FIGURE   Image already exists:   p115r_1.png
115v_3 | Y | Y | Y | 2 empty figure tags:   1) <ab> <margin>left-middle</margin>   <figure/>   Ne retire pas<lb/>   tes <tl>moules recuits</tl>       2) a sketched symbol (of   continuation) | BOTH FIGURES   (I think)   A long curved line from the   header up and over a marginal block that starts above and to the left, to   indicate that it belongs to 115v_3 (HOW   TO SHOW THIS????). Second is unproblematic and already exists as   p115v_2.png
118v_1 | Y | Y | Y | pour   en couvrir la<lb/>   medaille<comment>c_118v_01</comment>   <figure/>   </ab>   <ab>   <margin>left-middle</margin>   Pour medailles &amp;<lb/> | Horizontal line demarcating   the bottom of the margin block from the beginning of the one below it   IS THIS A FIGURE??   NB: do <man> tags   render outside an <ab>? That’s how they are here... (and they don’t yet   render...)
120v_6 | Y | Y | Y | <head>Garder   fleurs seiches en mesme<lb/>   <figure/> estat   <tmp>toute lannee</tmp></head> | Capital I rotated 90 deg.   (like an I-beam)   INLINE FIGURE
127v_1 | Y | Y | Y | <ab>   <margin>left-bottom</margin>   Recuits en <tl>four<lb/>   de reverberation</tl></ab>      <figure/><comment>c_127v_03</comment>      <ab>   <margin>left-bottom</margin> | Horizontal line demarcating   the bottom of the margin block from the beginning of the one below it   IS THIS A FIGURE??       Cf., 118v_1,   where the figure is INSIDE an <ab>   Which is correct?
152r_1 | Y |   |   |   | Whatever we decide for   118v_1 and 127v_1 will be applied here   3 times and across all versions
162r_1 | Y | Y | Y |   | Horizontal line between   main text of two entries   Is there a responsive horizontal line we can use?
166v_1 | Y | Y | Y |   | Horizontal line between   carry over main text from previous folio and main text of first entry on 166v   Is there a responsive horizontal line we can use?
