### ISSUE TITLE
Reconsider margin position assignment on 10r to render closer to facsimile

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#339]
In both edition and staging-edition using margin view, a marginal note appears ABOVE counterfeit jasper heading which should come right below. 

Is there a better way to mark this up in order to render more closely to facsimile?

**Comment by thuchacz** [comment]
This was fixed (can't remember when) by converting the marginal note to an `<add>` placed right before the beginning of the main text. PHS signed off on this.
