### ISSUE TITLE
Perform first pass quality control of comments tracking

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#345]
Comments have been entered into a tracking index through crowdsource methods. A first pass of ~accuracy, anchors, which versions (tc, tcn, tl), placement (e.g., before/after punctuation), etc.

A first pass is needed to just check on this and clean up before additional work is done.

**Comment by njr2128** [comment]
Proposed workflow: side-by-side in teams of two; one person working in oxygen, the other in the spreadsheet and the DCE to visualize.

With the following aims:

- check placement
- assign category
- check which versions it applies to
- highlight comments that need rewording
- highlight comments that should be deleted
- NEXT STEP: from the survey, create guiding principles for editorial commentary

NOTE: Leave out folios like 1r where commentary is more complex and different to most of the others

**Comment by thuchacz** [comment]
REVISED WORKFLOW:
Once Nick has given the comments basic rendering in the staging edition, we will do a group read through, folio by folio, assessing the comments to determine:
- whether a given comment will be kept
- which folios it will apply to
- what category it belongs to
- whether the comment anchor is properly placed

PRINCIPLES TO GUIDE THIS WORK:
- there will be multiple categories of comments
- we will define the categories in the process of the read-through
- we will limit proliferation of categories, focusing on “niche interests” (e.g., material properties of the page, navigation points in the text, historical persons, links to other texts/authors)

**Comment by njr2128** [comment]
Simultaneous task:
@ps2270 will begin review and edit of comment content. A new column, "Comment-edit", in DCE comment tracking spreadsheet has been created for any changes, revisions, formalizations, edits, etc. to the original comment.

If there are comments that @ps2270 thinks can be deleted, she will color the whole row in red for @thuchacz and @njr2128 (among others) to review.

To consider as Pamela works on this:
We may want to touch base about other possible changes Pamela may want to record, such as whether a comment should or should not be carried across all three versions; what category it should be given, whether other resources should be included (like links or pictures or references), etc.

**Comment by njr2128** [comment]
New column has been added "Include-DCE" to facilitate eventual workflow by @NickLaiacona 

This column will serve as a form of status indicator, indicating whether a comment should definitely be rendered in the DCE. If there are ones still under review or dispute, they will not hold up display workflow

**Comment by njr2128** [comment]
UPDATE: comments rendered in the DCE have been generated from https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/DCE_comment-tracking-Tracking.csv
For any updates to this content (and to see them render in the DCE), @njr2128 (or other M&K team member) will commit updated version periodically

**Comment by njr2128** [comment]
Completed
