### ISSUE TITLE
Organize annotations that are secondary, external, or additional

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#348]
Gather all known annotations of this nature (ones not written by CU students as part of Lab Seminar) to understand full scope.

Organize and then begin assessing level of intervention, amount of revision work needed, and how to be included in DCE.

Resources to consult:

- DCE datasets
- RPT collaborations
- Meeting notes

**Comment by njr2128** [comment]
This also includes items in GD Student Files, BnF folder, Instructor Files

**Comment by njr2128** [comment]
See list compiled by NJR, PHS, THU in GD DCE annotations folder, Additional annotations working document

**Comment by ps2270** [comment]
Additional Annotation Working Document: [https://docs.google.com/document/d/1omnS0I-AjFdAYCQnmr59TZUhGYewlWjDt15k0g5mQ1c/edit]

**Comment by njr2128** [comment]
Additional annotations have been identified and are in the processes of being worked through:

1. ann_500_ad_20_Demeter_Mr-Toad-Wild-Ride
2. ann_501_ad_20_Lacey_Expert-Maker
3. ann_502_ad_20_AnantharamanSmith_Drying-Animals
4. ann_503_ad_20_Julien_Toulouse-Sand
5. ann_504_ad_20_Noirot_Black-Wax-EN
6. ann_505_ad_20_BoydPalframanSmith_GoldRun
7. ann_506_ad_20_BoydPalframan_Cuttle-Fish
8. ann_507_ad_20_PalframanBoyd_Gold-Color
9. ann_508_ad_20_Amsterdam_Incuse-Reverse-Cast
10. ann_509_ad_20_Amsterdam_Spat
11. ann_510_ad_20_McFarlane_Molding-Diverse-Materials
12. ann_511_ad_20_M+K_Lifecasting
13. ann_512_ad_20_Mukherjee_Varied-Transmuted-Wine
14. ann_513_ad_20_V+A_Varnish
15. ann_514_ad_20_Price_Pigments
16. ann_515_ad_20_McClure_Dyeing-Wood
17. ann_516_ad_20_M+K_Perspective-Tool
18. ann_517_ad_20_UchaczRosenkranz_Varnishes-Rain

Any others should be identified by opening new issues
