### ISSUE TITLE
Identify outstanding resources and annotations to be prepared by M&K team 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#349]
See also #348 "Organize secondary, external, additional..."

What additional annotations should be prepared for DCE launch of Dec 2019 by M&K team?
What form will they take?

**Comment by njr2128** [comment]
To be completed:
- cuttlefish casting (#350)
- lifecasting photo essay?

**Comment by ps2270** [comment]
We have identified the annotations.
