### ISSUE TITLE
Create cuttlefish casting "additional" annotation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#350]
We need a set of photos on cuttlefish casting in lieu of an actual annotation. We can use some of the many images we have from the various times we’ve done it. I also have great images for a 1581 object from the Rijksmuseum that shows the patterning of the cuttlefish bone, so demonstrating that this was a technique used at exactly the time of 640. we need to find photos from the Andrew Lacey residency and other flickr folders

**Comment by ps2270** [comment]
Also, Jef Palframan and Emily Boyd's unfinished annotation on making gold run deals with cuttlefish casting - @ps2270  revise this essay.

**Comment by njr2128** [comment]
This is now in progress here: ann_506_ad_20_BoydPalframan_Cuttle-Fish
