### ISSUE TITLE
Gather student demographics for annotations

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#351]
Master metadata is needed for student demographic info that will be associated with every annotation "author".

This should include:

- name
- degree
- degree year at time of annotation creation
- department
- sub-field (as possible?)
- semester and year of participation

Resources to work from:
- Project stats table
- Student rosters (in GD) from each semester

**Comment by caro27** [comment]
Alright! I will get as much info as I can!

**Comment by njr2128** [comment]
@caro27, I have created the base table in GD under M+K-2019-DCE > DCE - Annotations and Essays > Annotation-author-metadata

Work can now be begun (though degree and year will need conferring with PHS)

**Comment by caro27** [comment]
@njr2128 - Completed! A couple of questions are marked with red boxes.

**Comment by njr2128** [comment]
@njr2128 to do:
- insert pipe character between annotation IDs
- create author ID
- update red boxes/questions from caroline
- get year at time of class

**Comment by njr2128** [comment]
> @njr2128 to do:
> 
> * insert pipe character between annotation IDs
COMPLETED, @NickLaiacona 
> * create author ID
COMPLETED, @NickLaiacona @tcatapano - can you advise on ID format/notation?
> * update red boxes/questions from caroline
In progress
> * get year at time of class
In progress - entered for many known students, but still need to update 2014-15, and some 2016

UPDATE:
* Created additional column H "Author-type" that details whether person was a student, independent scholar, postdoc, etc. and from which institution. 
* Because there are authors who were not students at time of class, perhaps we can introduce a default that if the word "student" appears in the "Author-type" column, then the information from columns like "Degree" and "Year" etc. would be displayed. If the word "student" does not appear, then that information is omitted (as it does not exist)

**Comment by njr2128** [comment]
Still remaining to do:
* Consult with @ps2270 about author "year-at-time-of-class"
*Decide if "current year" is information we want to supply as part of author demographics
* Review Department and Subfield sections with @ps2270

**Comment by ps2270** [comment]
I filled in what I could for "year-at-time-of-class"
We do NOT want current year as part of author demographics...this will get outdated very quickly.
Reviewed dept and subfield sections--not sure about some of them.

**Comment by njr2128** [comment]
DONE. NJR and PHS have gone through and updated all years at time of participation in lab seminar (confirming some info with students themselves).
PhD students get year, but MA students do not
