### ISSUE TITLE
Translation of "saulmon"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#358]
(from PW18 tracking sheet)
To mean unprocessed, raw metal - check consistency. 
Especially for tin and lead.

See p028v_1 "Pintiers"/"Pewterers"

**Comment by TillmannTaape** [comment]
Yes this is consistently kept in Fr. Should it have an editorial note? 
@ps2270 ?

**Comment by ps2270** [comment]
Yes, it should have an editorial note.

**Comment by TillmannTaape** [comment]
Added ed. note to glossary (but not as comment in TL):

 “saulmon” refers to a large ingot or mass of raw, unprocessed metal straight from the furnace. See DMF.

@ps2270 please review.

**Comment by ps2270** [comment]
Ok. Approved

**Comment by TillmannTaape** [comment]
searched for "saulmon" in tl and added ed. comments to first instance in each entry.
