### ISSUE TITLE
Translation tag for translating from other languages than French into English

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#36]
Our tentative solution is to make a comment at this point (make this in GD ms pages, with an anchor, and in spreadsheet) with the word or phrase and a note saying that original is in the other language.  But, @tcatapano is there a better solution?  an example is 55r.

**Comment by tcatapano** [comment]
A sequence of `<trans>/<orig>` might be a solution too. E.g.,

```
<head>For shooting a <trans><orig><it>schioppo senza rumore</it><orig>gun without noise</trans></head>
 
```

This would require some specific logic to handle the rendition properly that might be more complicated than relying on the general comment/note functionality to get the same effect.

**Comment by tcatapano** [comment]
see also #125

**Comment by ps2270** [comment]
German tag (or whatever) needed on 118r "stuf" and 119v "spat"

**Comment by thuchacz** [comment]
DECISION: stick with language tags around foreign strings and use editorial comments (via comment anchors) to translate
