### ISSUE TITLE
Translation of "grille"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#360]
(from PW18 tracking)

Keep in French to describe a form? 
For tin in which it is then separated and sold.

See p028v_1 "Pinitiers"/"Peweters"

**Comment by TillmannTaape** [comment]
Cannot find English equivalent.

Suggestion: keep in Fr., with ed. note saying "this is likely a smaller type of ingot than the 'saumon', and more convenient to sell. See eg. Dictionnaire universel de Commerce (1742), which likens "grile" to "saumon", although to the AP these are clearly different (on fol. 28v)."

@ps2270 ok?

**Comment by ps2270** [comment]
ok.

**Comment by TillmannTaape** [comment]
Made sure "grille" where referring to an ingot is left in Fr. and has the above ed. note. Also added this to the glossary.

Some instances of "grille" meaning "grate" (e.g. in a furnace) were mistranslated "grill" or kept in Fr.; I changed all to "grate" as per Cotgrave.
