### ISSUE TITLE
Translation of "bonnes villes"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#362]
(from PW18 tracking)

No translation exists. Needs a decision and update to vocab list

See p028v_1 "Pinitiers"/"Peweters"

**Comment by TillmannTaape** [comment]
"bonne ville" was a privileged status conferred by the king in ancien régime France, also  connoting a certain size and state of fortification. See Gérard Mauduech, "La 'bonne' ville: origine et sens de l'expression," Annales. Histoire, Sciences Sociales, No. 6 (Nov. - Dec., 1972), pp. 1441- 1448.

It doesn't seem to get translated in English scholarship, see e.g. Gerhard Dohrn-van Rossum, [History of the Hour: Clocks and Modern Temporal Orders, p. 298.](https://books.google.com/books?id=xYhlNoUu-toC&lpg=PA298&ots=o3WEyyrywo&dq=historical%20meaning%20%22bonne%20ville%22&pg=PA298#v=onepage&q=historical%20meaning%20%22bonne%20ville%22&f=false).

Suggestion: keep in Fr., with editorial note: "A status conferred by the French king, granting privileges and financial aid in exchange for military manpower and taxes. "Bonne ville" thus usually referred to a city of a certain size and degree of fortification."
Could include link to Wikipedia article?
https://fr.wikipedia.org/wiki/Bonne_ville_(France)#Bibliographie

**Comment by TillmannTaape** [comment]
DECISION

keep in Fr. and add ed. note. Incl. wikipedia link in glossary but not ed. note for the time being.  Make glossary entry for bonne ville.

**Comment by TillmannTaape** [comment]
Placed ed. note in glossary and also added a comment in the TL on 28v and 90r.
