### ISSUE TITLE
Translation of "curielx"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#366]
(from PW18 tracking)

For most instances, this should be "careful".

This has been largely completed already for casting recipes in FA18: translating "curieux" as "careful" (rather than scrupulous or curious).

Do a quick check to see if this is consistent.

See for example: p062r_4, p084r_1, p085v_4, p141r_1, p157r_3

**Comment by TillmannTaape** [comment]
Search term: curieu

Translated as "careful"/"carefully" in all instances except 107v where "scrupulous" seems apt:

do not be so scrupulous an observer of the
mixture put here that sometimes you would
not diminish the quantity of alum de plume
