### ISSUE TITLE
Translation of "argent de billon"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#367]
(from PW18 tracking)

 "argent de billon" = a coin of alloyed silver in which there is less silver than other metal. 

Left in Fr; is there an English trans? 

See p119v_2

**Comment by TillmannTaape** [comment]
"billon" is in the OED, with instances from the 18th c. 

Suggestion: remove fr tags and put editorial note: "A mixed metal used in coinage, consisting of gold or silver with a preponderating admixture of a baser metal. (from OED)"

**Comment by TillmannTaape** [comment]
DECISION

Translate as "billon silver" and make glossary entry.

**Comment by TillmannTaape** [comment]
Searched "billon" and checked it's translated "billon"; translated "argent de billon" as "billon silver"
