### ISSUE TITLE
Markup for author-practitioner "/" character

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#37]
Fol 15r_2 has a forward-slash--like mark right before the addition. Until this morning, it appeared only in tc, but this has since been updated to appear in all versions. There is no markup associated with this mark/ character.
Please advise about whether any tagging should be applied, such figure, etc

**Comment by tcatapano** [comment]
To be safe, why dont we tag as `<mark>`. This would be the first one. We're still looking to convert marks tagged as figures at some point, but this will give @NickLaiacona something to work with until we do.

**Comment by thuchacz** [comment]
Inserting a <figure>/</figure> in TCN and TL within branch 59 that deals with #59
