### ISSUE TITLE
Translation of "verrier" vs. "vitrier"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#370]
(from PW18 tracking)

Verrier = glassmaker
Vitrier = glazier

Check how these are translated now, and confirm that this distinction makes sense in each case.

See p120r_2

**Comment by thuchacz** [comment]
ISSUE: verrier vs. vitrier
PW18Vocab suggestion: Vitrier = glazier ; verrier = glassworker

**TLFi: VITRIER**, subst. masc.
A.
1. Fabricant, marchand de verre à vitre. 
2. Vx. Ouvrier qui peignait le verre. 
B.
1. Ouvrier poseur de vitres.

**DMF: VITRIER**, subst. masc.
"Celui qui fait les vitres et les pose aux fenêtres"

**TLFi: VERRIER, -IÈRE**, subst. masc. et adj.
I. − Subst. masc.
A.
1. Celui qui fabrique du verre, des ouvrages de verre.
2. Celui qui réalise des verrières, des vitraux. Synon. vitrier.
3. Vieux
a) ,,Celui qui vend des ouvrages de verre (...).
b) ,,Vitrier`` (Rob. 1985).

**DMF: VERRIER**, subst. masc.
A. - "Celui qui fabrique des ouvrages en verre"
B. - "Vitrier"

____

Soersha Dyon:
Verrier: A profession which produces glass objects, as contrasted with the older profession of “vitriers” who make flat plate glass and stained glass windows and do painting on glass (for stained glass). In 1583, the Statutes of Paris record that the “Verriers” are authorized to make flasks, bottles, and other objects in glass and crystal.  Before this, they were not listed as a separate profession, and, even after this, they are listed with the enamel makers.

____
<img width="670" alt="Screen Shot 2019-04-01 at 10 28 29" src="https://user-images.githubusercontent.com/23508994/55335576-51ab7080-5469-11e9-949b-0fddd59237d9.png">
<img width="668" alt="Screen Shot 2019-04-01 at 10 29 10" src="https://user-images.githubusercontent.com/23508994/55335597-5bcd6f00-5469-11e9-8b82-98be8c2f8966.png">
<img width="666" alt="Screen Shot 2019-04-01 at 10 29 48" src="https://user-images.githubusercontent.com/23508994/55335605-60922300-5469-11e9-9ef6-490b427a532d.png">
<img width="668" alt="Screen Shot 2019-04-01 at 10 30 23" src="https://user-images.githubusercontent.com/23508994/55335614-6556d700-5469-11e9-85de-badee6e866a0.png">

**Comment by thuchacz** [comment]
updated glossary entries for "vitrier" (=glassworker) and "verrier" (=glassmaker) with DMF definitions
consistified
