### ISSUE TITLE
Translation of "de travers"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#374]
(from PW18 tracking)

"de travers" has been kept in fr for the moment.

Need to look into a possible translation

See p143r_2

**Comment by thuchacz** [comment]
2 INSTANCES of molding "de travers" — both associated with Foix:

p143r_2
<head><pro>Mouleurs</pro> de <pl>Foix</pl></head>
<ab>Ceulx qui **moulent de travers** font leur sable de <m><la>crocum</la></m><lb/>
&amp; d'<m>ardoise calcinée</m>

<head><pro>Molders</pro> from <pl>Foix</pl></head>
<ab>Those who **mold <fr>de travers</fr>** make their sand with <m><la>crocum</la></m> &amp; <m>calcined slate</m>
____
p090r_2
<head>Sable</head>
<ab>Les <pro>mouleurs</pro> de <pl>Foix</pl> qui **gectent les medailles de<lb/>
travers** usent de <m><la>crocum ferri</la></m> et <m>ardoise calcinée</m>. C'est pour<lb/>
chose fort platte.</ab>

<head>Sand</head>
<ab><pro>Molders</pro> from <pl>Foix</pl> who **cast their medals from the side**, use <m><la>crocum ferri</la></m> and <m>calcined slate</m>. It is for very flat things.</ab>
____

For "Travers. De travers. (Adverb.)" Cotgrave gives "across, crossly, overthwartly; whence"

**Comment by thuchacz** [comment]
DECISION:
Translate as "crosswise." Add Cotgrave's full definition to the glossary. Seems a particular form of casting related to the direction of placement of the gate. Seems to be something specific to Foix.
Add editorial comment to both instances about precise technical meaning being unclear.

**Comment by thuchacz** [comment]
translated "de travers" as "crosswise" on 90r_2 and 143r_2
added "travers, i.e., de travers" to glossary
added editorial comment to all three versions of 90r_2 and 143r_2
