### ISSUE TITLE
Translation of "étrier" (and editorial note needed?)

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#376]
(from PW18 tracking)

Review translation of "étrier", particularly in the case of:
p160r_1 "Presses pour les grands moules"/ "Press for large molds"
>We translated "étrier" literally as "stirrup" even though that's a bit unusual for a screw to turn into because the figure above shows a piece attached to the upper metal plate that looks a good bit like a stirrup

**Comment by njr2128** [comment]
Check with @ps2270 about the scope of this work

**Comment by ps2270** [comment]
This translation is the only one in the ms, and it makes sense. Nothing further needs to be done to the translation.  It should have an editorial comment.

**Comment by TillmannTaape** [comment]
Added comment in all three versions:

"étrier" (= "stirrup") refers to the metal bracket which is attached to the bottom of the screw and fixed to the upper plate of the press.
