### ISSUE TITLE
Fat/Lean, Sweet/Sour

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#377]
Explain the overlapping dichotomies (Fat/Lean, Sweet/Sour) in the introductory essay (Fatty Sand). Add an entry in the glossary.
see #173

**Comment by ps2270** [comment]
@TillmannTaape @Pantagrueliste : I want to add a brief explanation of fat/lean, sweet/sour in the glossary, but I am unsure of the format (in parentheses? a separate sentence?)
thanks for letting me know.

**Comment by njr2128** [comment]
UPDATE:
fat/lean is now covered in ann_009_fa_14_Lee_Magistry and is in glossary
sour/sweet is only in glossary.

@ps2270 - still TBD: essay about sour/sweet? Another resources about this and/or fat/lean?

**Comment by ps2270** [comment]
phs added to Fat, Lean, Sweet, Sour.
