### ISSUE TITLE
Editorial comment needed for p049v_3 "Birds"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#379]
Content of note:
"Bénaris" has been left in French (with modernized spelling) because it is a specific bird--a kind of ortolan--that only lives in the Languedoc

**Comment by njr2128** [comment]
I see conflicting information in the tracking sheet:

c_049v_07 | x | x | x | delete | TT | Occitan name for the ortolan or bunting (a migratory bird). | no longer needed | tc tcn tl
-- | -- | -- | -- | -- | -- | -- | -- | --


@ps2270 and @TillmannTaape , can you confirm? Is this an editorial note that needs to be made?

**Comment by TillmannTaape** [comment]
This can be deleted: Benaris has been translated as ortolan, and the glossary has the information previously contained in the ed. note.

**Comment by njr2128** [comment]
Unless otherwise noted by @ps2270 (who has finished her pass through the tracking sheet and did not make any changes), we will leave this deleted.
