### ISSUE TITLE
Translation of "arantelles" and editorial note needed

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#381]
(from PW18 tracking)

"arantelles" has been left in French because it is just an alternate way of saying "toile d'araigné," or spiderweb; may be a dialect difference.

DECISION: translate into English and add editorial comment saying that it is not the usual French and it may indicate a different dialect.

See p071v_3

**Comment by thuchacz** [comment]
Only one instance of "arantelle" (71v_3)
THU translated "arantelles" as "cobwebs." Does this really necessitate an editorial comment?

C'est pourquoy aulcuns<lb/>
<pro>riches</pro> d'<pl>Angleterre</pl> font leurs planchers de ce <m>boys</m>, &amp;<lb/>
par ce moyen ils n'ont jamays **d'arantelles** &amp; toiles<lb/>
d'<al>iraignée</al>.</ab>

This is why some of the <pro>rich</pro> from <pl>England</pl> make their ceilings from this
<m>wood</m>, &amp; by this method, they never have **cobwebs** &amp; spiderwebs.</ab>

**Comment by thuchacz** [comment]
PHS signed off on this
