### ISSUE TITLE
Translation of "visme" and editorial comment needed

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#382]
(from PW18 tracking)

"visme" has been left in French because this is a Languedoc word for "brin d'osier" 

DECISION: Translate to English -  maybe as withy willow? @ps2270 
and add editorial comment saying that it is occitan

See p088r_4

**Comment by Pantagrueliste** [comment]
It's in p088r_1. 
Visme appears to be the name given to Osier (Salix viminalis, Salix vitellina, Salix purpurea, etc.) in the area of Bordeaux. See Arnauld Landric, _Advertissement et manière d'enter asseurément les arbres en toute saison de l'année, la vigne sur son sarment, planter sauvageaux et autres_, 1580.
*Basket willow* is perhaps a better translation.

**Comment by Pantagrueliste** [comment]
Translate as Willow, wicker twigh
Editorial note: regional, Occitan, bordeaux, garonne, often used for making baskets.

**Comment by Pantagrueliste** [comment]
Make sure it's tagged as occitan in all versions.
