### ISSUE TITLE
Translation of "armol"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#383]
(from PW18 tracking)

English translation has not yet been determined - @Pantagrueliste, can you research some possibilities?

Once determined, make consistent across manuscript

See p105r_4

**Comment by Pantagrueliste** [comment]
Editorial Note: *Atriplex Patula*

**Comment by njr2128** [comment]
For _Atriplex:_ see https://eol.org/pages/37674/names
and for _Atriplex patula_: https://eol.org/pages/587146

**Comment by njr2128** [comment]
Additional resources: 
- https://www.bgci.org/plant_details.php?plantID=40486
- https://plants.jstor.org/search?genus=Atriplex&species=hortensis
- http://www.tropicos.org/Name/7200081

**Comment by Pantagrueliste** [comment]
Decision: translate as orache
