### ISSUE TITLE
Translation of "hoqueton"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#385]
(from PW18 tracking)

Check translation of "hoqueton," perhaps consulting with weapons experts (Jonathan Tavares)

See p104v_3 "Goldsmith"

**Comment by TillmannTaape** [comment]
This was already resolved: we're translating "haqueton" which is in the OED, and there's an editorial  comment in the TL.

There's a typo in the TL, though, which I will fix on this branch.
