### ISSUE TITLE
Translation of "Estaindre" = extinguish

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#388]
(from PW18 tracking)

"Estaindre" = extinguish - change across ms and versions

See 

p003r_3 | p003r-p003v | Gros vernis pour les planchers p1 | Thick varnish for floorboards p1
-- | -- | -- | --

**Comment by thuchacz** [comment]
Searched for "estaind" (2 instances) "estaint" (2) "estains" (1) "estainc" (1) "etei" (0) "estei" (0)

Ensured all were translated as "extinguished."
