### ISSUE TITLE
Translation of "figuier"=fig tree

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#389]
(from PW18 tracking)

"figuier"=fig tree

Change all instance to fig tree in context

See

p012r_3 | p012r | Papier | Paper
-- | -- | -- | --

**Comment by thuchacz** [comment]
All 8 instances of "figuier" translated as "fig tree"
Also consistified "pelures de figuier" as "peelings of the fig tree" and "lait de figuier" as "milk of the fig tree".
