### ISSUE TITLE
Translation of "tirer" and "coup"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#391]
(from PW18 tracking)

Regularize "tirer" (to shoot) and "coup" (a shot); because in past tense they are the same and appear in the same sentence as "shot a shot" several times.

Check what translation have been used and determine best words for consistency. Note that this was reviewed in the most recent translation campaign, so things should not be too off.

See

p017r_1 | p017r-p019r | Du canonier p2 | On the gunner p2
-- | -- | -- | --

**Comment by TillmannTaape** [comment]
Search terms: tire, tira (whole words), tirant (whole words), tiras (whole words), tiront; coup (whole word), coups (whole word).

"tirer" in the context of artillery mostly translated "fire", except in "shooting a ball" ("firing a ball" doesn't seem quite right), and in "shooting true".

"coup" in artillery context consistently translated as "shot"
