### ISSUE TITLE
Translations of biron, viron, guimbelet, and foret

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#392]
(from PW18 tracking)

Figure out the translation of biron, viron, guimbelet, and foret - particularly in weapons entries.

Issues: What words to use, esp as words from different languages or dialects.

See 

p024v_1 | p024v-p025r | Pour mener le canon en pays p1 | To bring a cannon over terrain p1
-- | -- | -- | --

and

p167r_1 | p167r-p168v | Mortiers p1 | Petards p1
-- | -- | -- | --

**Comment by TillmannTaape** [comment]
Here's our (fairly robust) protocol for translating the various kinds of drilling tool:

foret = borer
taraire = auger
vibrequin = wimble [ed. note: boring tool like a gimlet]
guimbelet = gimlet
viron/biron = gimlet

Question: do "gimlet" and "auger" need ed. notes or is it sufficient to have them in the glossary?

viron/biron is Occitan, so the question is how to render than in the TL. Options:

1) "<oc>gimlet</oc>"
2) "gimlet" with editorial note stating the original term and that it' in occitan, different from "guimbelet"
3) keep in Occitan, i.e. "<oc>viron</oc>" with editorial note translating this as "gimlet"

**Comment by TillmannTaape** [comment]
Checked consistency of foret, taraire, vibrequin, guimbelet; waiting for decision on viron/biron.

**Comment by TillmannTaape** [comment]
DECISION

Translate as "gimlet" with glossary entry (and potential ed. note):

viron (also biron, reflecting Gascon pronunciation) = Occitan term, referring to a gimlet, i.e. a small boring tool for which the author-practitioner elsewhere uses the French term "guimbelet". The word is not unknown in northern French, but rare and archaic (one example from Flanders 1396 in DMF, unrecorded in TLFi), and the “biron” form is clearly regional.

@ps2270 please review this glossary entry and I will transfer it to the glossary under viron and biron.

As per our discussion today, I am NOT at this stage creating an editorial comment.

**Comment by TillmannTaape** [comment]
search terms:
biron
viron, virons (whole word)

All translated as gimlet.

**Comment by ps2270** [comment]
Glossary entry good.
Weren't we going to have an editorial comment that just says "Occitan" at each instance?  Not a definition, but just noting that it's Occitan (or, if we can tag it as Occitan, we can do that instead, but we haven't figured out how to do that).

**Comment by TillmannTaape** [comment]
I think the variant spelling and info that the a-p elsewhere refers to the same thing using the French term would be useful to include in the ed. note as well.

I am anchoring  the following ed. note as a comment:

"Viron" (also "biron," reflecting Gascon pronunciation) is an Occitan term, referring to a gimlet, i.e. a small boring tool for which the author-practitioner elsewhere uses the French term "guimbelet".

If we decide we only want "Occitan" as the comment then that will be easy enough to change in the comment tracking spreadsheet.

I've also consistently added oc tags in tcn and tl (as we discussed, we may or may not decide to display them in the tl).

**Comment by ps2270** [comment]
good decision.
