### ISSUE TITLE
Translation of "gomiche" as "gum"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#393]
(from PW18 tracking)

See

p076v_2 | p076v | Pour faire goumiche noyre | For making black goumiche
-- | -- | -- | --

Where PW identifies gomiche = gum.

Is this correct?

If yes, check other instances and make consistent

**Comment by ps2270** [comment]
one instance of "goumiche:, not "gomiche" and it's left in French, which is correct, and PHS has corrected the glossary
