### ISSUE TITLE
Translation of "grais" and "moullée" + "ferraille" = "ironware"?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#394]
(from PW18 tracking)

See 

p079r_1 | p079r | Pour faire boys gris | For making grey wood
-- | -- | -- | --

"grais" and "moullée" as in 73r + "ferraille" = "ironware"?

Check other instances

**Comment by TillmannTaape** [comment]
I can't figure out what the issue is here. @ps2270 in the index tracking it says PHS checking on "grais" and "moullée" as in 73r + "ferraille" = "ironware" – do you remember what this was about and whether it was resolved?

**Comment by ps2270** [comment]
I couldn't figure it out either; I explored it last night, but need to go back to it.  I will work further on it.

**Comment by ps2270** [comment]
grais in 28v means acc to Cotgrave, a type of potters' clay or earth for making vessels.
73r: where grais Cruze has been trans as "hollow sandstone"  I think it must mean a hollow vessel made of this kind of potters' earth
30r potters' earth
8v trans as "stoneware", but I think it must mean a vessel made of "grais"
So 28v and 30r = a type of potters' earth
8v and 73r = a vessel made from a type of potters' earth
Not sure whether to translate them this way, or just to have glossary entry or editorial comment

**Comment by ps2270** [comment]
79r: powder of potters' earth

**Comment by ps2270** [comment]
feraille = ironware on 79r (already trans that way)

Ok, so for this issue, the problem seems to be whether and how to trans. "grais".  Let's discuss tomorrow.  It could be left in French, as it is now, although then 8v and 73r would need revising and I think translating

**Comment by Pantagrueliste** [comment]
editorial comment: 8v, 28v, 30r, 73r, 79r.

**Comment by Pantagrueliste** [comment]
8v --> the most delicate stoneware ...
73r --> hollow stoneware vessel

**Comment by ps2270** [comment]
Decision: left in French, and we put editorial comments in all relevant entries.  And, we finalized glossary entry.
