### ISSUE TITLE
Review/fix structural markup of text blocks (w/o IDs) of p108v

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#397]
(from PW18 tracking)

Structural markup has not been signed off by most recent PW

p108v | Lardille | Clay
-- | -- | --

p108v | Alum de plume | Feather alum
-- | -- | --

**Comment by thuchacz** [comment]
Unclear to me if we want to treat "L'ardille" and "Alum de plume" as rubrics (as they are now) under the larger heading of "Spalt" that begins on the previous page and continues above, or if these two should be elevated to entries of their own. Waiting on PHS verdict from #565 #395 #396

**Comment by ps2270** [comment]
See and resolve in discussion of #12

**Comment by thuchacz** [comment]
Decided on June 10, 2019 that "L'ardille" and "Alum de plume" would remain in` <rub>` tags under the "Spalt" entry that begins on the previous page.
