### ISSUE TITLE
Use of "febve d'estaim de glace"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#402]
(from PW18 tracking)

@ps2270 - can you elaborate on the issue? Is this a translation or markup issue?

See

p118v_1 | p118v-p119r | Gect en chassis p2 | Casting in a frame p2
-- | -- | -- | --

**Comment by ps2270** [comment]
This seems to have been a note carried over in the PW18 Tracking sheet since 2017, and is no longer relevant.  Therefore I am closing this.
