### ISSUE TITLE
Translation and markup of "or de paillelle"

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#405]
(from PW18 tracking)

See 

p148v_1 | p148v | Mouler tortues | Molding turtles
-- | -- | -- | --

What is this?
How should it be translated?
How should it be marked-up?

**Comment by thuchacz** [comment]
Cotgrave gives "or de paillole" as "spangle gold." For discussion of those who seem to have panned for "or de paillole" around Toulouse, see [Traité de la Cour des monnoyes, 1658](https://bit.ly/2Oza1TC).

In DMF, "paillole" (n.f) = "paillette" (Cotgrave: spangle, sparkle; mod. speck)
In OED, "spangle" = "A small or minute glittering particle, esp. of a mineral substance."
"spangle gold" defined as "gold in the form of smooth flat scales" in [The Gold Fields and Mineral Districts of Victoria, 1869](http://bit.ly/2CMz418)

A-P goes on to call this "electre" (= "ambre" in DMF; see also OED for the obsolete "electre" 2: "An alloy of gold and silver" and the still current "electrum" 2: "A naturally occurring alloy of gold and silver containing trace amounts of copper and other elements"; see also OED for "amber" III.6: "An alloy of four parts of gold with one of silver.")

On the A-P's suggestion that a cup made of this substance reveals the presence of poison, see Heinrich Khunrath's 1597 manuscript, Consilium de Vulcani magia fabrecatione armorum Achilles_ (Ms. Rål 4, 1597 (43), National Library of Sweden), offered "to Duke Charles, later Charles IX, on
the topic of the armour of Achilles, thought to be made of electrum, i.e., a mix of gold and silver. Such an armour would, supposedly, make its bearer invincible and, furthermore, a cup made of this electrum would signal if any liquid was poisonous." (Susanna Åkerman, DOI:10.1163/9789004325968_054).

THU suggestion:
"or de paillole" as "spangle gold"
"electre" as "electrum"

**Comment by thuchacz** [comment]
DECISION:
THU translation suggestions accepted. Dump as much info as is here into the VocabList.

**Comment by thuchacz** [comment]
149v_1: "electre" now translated as "electrum"
Searched for "elec"—no additional instances.
Updated glossary for "paillelle" "or de paillelle" and "electre"
Fixed <def> tags around "electrum" to <df> on all three versions.

Searched for "smear" in TL and fixed the 4 outstanding "oindre" variants from #100 on 23r, 109r, 110v, 152r
