### ISSUE TITLE
Check use of <sup> across an entry spanning p055r-v

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#407]
(from PW18 tracking)

`<sup>` tag used at the end of 

p055r_4 | p055r-p055v | Onenev elbirro tnaut is no encram rus enu elbat no neirtse p1 | Onenev elbirro hcihw sllik fi eno spets no a draob ro a purrits p1
-- | -- | -- | --

and beginning of

p055r_4 | p055r-p055v | Oneneu elbirro tnaut is no encram rus enu elbat no neirtse p2 | Onenev elbirro hcihw sllik fi eno spets no a draob ro a purrits p2
-- | -- | -- | --

Is use ok?

**Comment by tcatapano** [comment]
resolved with markup solution
