### ISSUE TITLE
identify elements in use but not in schema

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#41]
see also #14, #15, and #16, #17

**Comment by njr2128** [comment]
As of 1/14/19, these are all the tags potentially in use:


**Semantic markup**
ab
cont
div
figure
head
id
image
lb/
man
add><man
margin
page
rub


**Phrase-level tags**
al
bp
cn
df
env
fr
gk
it
la
m
md
ms
mu
oc
pa
pl
pn
po
pro
sn
tl
tmp

**Editorial markup**
add
corr
del
exp
gap
sup
unc

**Comment by njr2128** [comment]
-  `<def>` --> supposed to be `<df>`
- `<lt>` = latin
- `<po>` = poitivoin 
- `<superscript>`
-`<temp>` --> probably supposed to be `<tmp>`
-`<tk>` --> probably supposed to be `<tl>`

**Comment by tcatapano** [comment]
Closing see: #333 and #334

**Comment by tcatapano** [comment]
see #330
