### ISSUE TITLE
Check p060r_3 for AP explanation of walnut oil

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#411]
(from PW18 tracking)

Does this explain white walnut oil from earlier entry? @ps2270 

p060r_3 | p060r | Huile | Oil
-- | -- | -- | --

**Comment by ps2270** [comment]
60r needs better translation--it's a mess.  But I do not know what the "white walnut oil" from a prior entry is. We may need to rediscover in translation campaign.

**Comment by thuchacz** [comment]
check if 60r_3 gives an AP definition, and go back to the untranslated "huile de noix blanche" in the varnish recipe (must find that varnish recipe again).

**Comment by thuchacz** [comment]
Translated "huile de noix blanche" as "white walnut oil" in 31r_3 and added editorial comment directing reader to 60r_3.

removed <la> tags from "palma christi" on 58r and 60v (it's in the OED!) and gave it <pa> tags instead. Removed a comment that is no longer relevant
