### ISSUE TITLE
Markup of "balle" with <ms>

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#412]
(from PW18 tracking)

"balle" should be tagged <ms> if used to indicate cannon proportions

See

p017r_1 | p017r-p019r | Du canonier p5 | On the gunner p5
-- | -- | -- | --

**Comment by TillmannTaape** [comment]
Search term: "balles*" in TXM to create list of instances, then decided which ones to should be tagged as measurement, and made changes in oxygen (by searching again for RE "balles*" to navigate to the relevant entries).

I tagged expansively, e.g. 

`the <ms>thickness of four balls at the breech and two in front</ms>`
