### ISSUE TITLE
<ms> tags for escutcheon/escusson

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#414]
(from PW18 tracking)

See related #78 "escusson..." about translation and losing `<fr>` tags.

When indicating a measurement, such as "up to the escutcheon" , tag with `<ms>`.

See

p022v_1 | p022v-p023v | Orgues p1 | Orgues p1
-- | -- | -- | --

**Comment by thuchacz** [comment]
Ensured <ms> tags around “up to the escutcheon” when describing cannon powder loading on TC/TCN/TL
Noticed that <cn> tags were missing around “ecus” on 170v; added to TC/TCN/TL
Noticed that most markup was missing from 170v_1 (the receipt of rent entry)
- added <cn>, <tmp>, <pn>, and <pl> tags to items. 
- <x> tag updated to <sup> tag — do we want this to stay??
- Sr expanded w <exp> in TCN, TC, but given as “Sr.” in TL — expand??
- “[sols]” in TC/TCN is implied (under the paper strip) but given outright in the TL — ??

ALSO updated 159r_4 w a translation tweak by TT

**Comment by thuchacz** [comment]
Per conversation w PHS:
170v_1
- tweaked translation to remove `<sup>` tags in TL
- Sr. expanded to Sieur in TL
- put [ ] around "sous" in TL; final protocol for words under paper strip TBD and referenced in #509 
46r_1
- added comma to header in TL to make consistent with TC, TCN
