### ISSUE TITLE
Render of p028r_1 caption not working?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#415]
(from PW18 tracking)

Note from PW: @THC We are translating here, but this caption is not rendering. We're not touching this mark-up (same across all versions), since it looks like you and Nick are working on figure/text/caption rendering.
See

p028r_1 | p028r | La mesure du qualibre des pieces | The measure of the caliber of the pieces
-- | -- | -- | --

**Comment by tcatapano** [comment]
@njr2128 Is this still an issue?

**Comment by tcatapano** [comment]
changed to ab in right margin so displaying, but incorrectly in right marging see  https://github.com/cu-mkp/making-knowing-edition/issues/173
