### ISSUE TITLE
Markup of OC biron, viron, FR guimbelet, and FR foret

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#416]
(from PW18 tracking)

See related #392 "Translation of biron..."

Need to correctly tag these terms with language tags and any other tags

See

p167r_1 | p167r-p168v | Mortiers p1 | Petards p1
-- | -- | -- | --

**Comment by TillmannTaape** [comment]
Search terms TC/TCN: viron, virons (whole words only); biron
 – Made sure all are tagged <tl> and <oc>

Search terms TC/TCN: foret, guimbelet, taraire, vibrequin
 – All tagged <tl>

Search term TL: gimlet
 – tagged as <tl> throughout, and <oc> where the original word was viron or biron

Search term TL: borer, auger, wimble
 – all tagged <tl>
