### ISSUE TITLE
"bave" needs to be made "fins" not "flaws"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#418]
Inconsistent in text due to late change in translation policy.

**Comment by ps2270** [comment]
Tianna, 
bave is the casting defect in which metal "froths" or "foams" out of the mold and is known in English as flashing, flash, or fins.
I'm looking at the translations we've made of it as "fins" and it's so opaque to the non-specialist reader, I'm worried.  I will write a glossary entry, but I've decided we should instead translate as "flashing".
I'm sorry, but there are only 20 of them...

**Comment by ps2270** [comment]
Glossary entry:
Bave (f.) = foam, froth, slaver. In metal casting it denotes a defect in which metal “froths” or “foams" out of the mold, especially at the joint where two parts of the mold meet. In English this is known as flashing, flash, or fins. We have translated as “flashing.” 

The following part of the entry has been left for now in glossary, but may be deleted in time:
or as in fol. 66r below (See 152v) — JB: fol. 66r baves “tiny flakes of gold leaf that did not adhere to mordant in or mat gilding” (We think the best translation for "tiny flakes" is "burr"; Jose found the modern definition of "bave" in Spanish and it is the same sense: a piece of metal left over after a process of cutting that renders it unsmooth") (MBR). When talking about an organic substance, use “slime”. (SD/HW 9/15/2018, p. 165v). [2019: we settled on “slaver”]

**Comment by thuchacz** [comment]
@ps2270 
Hi Pamela,
Two things: 
1) I ensured that "bave" was "flashing" in all instances where that made sense. Here are two entries where I'm less sure about the meaning of "bave" (NB: the first entry is referenced in the old "bave" glossary note (see your comment above) that you suggest we eventually erase—are you fine with burrs here?)
<img width="836" alt="Screen Shot 2019-04-07 at 16 19 33" src="https://user-images.githubusercontent.com/23508994/55689317-05709c80-5951-11e9-9a42-b29b03fc8a7f.png">

2) I realized that "barbe" is translated in the glossary as "flashing." It only occurs (in the context of casting and 3D flaws) in 3 instances: 118r, 140r, 155v. I want to translate these as "barb" and update the glossary to that effect. Would that be okay?

**Comment by ps2270** [comment]
bave in 66r and 116v- both seem to be extensions of the idea of flashing to other media. I.e., Places where there is an unwanted protrusion of some sort--a rough edge or ridge, or roughness, or irregular or rough surface.  
In 66r, it could be translated "so no rough places remain", and "gather the irregularities and the small flakes".  Yes, I think that's it.
116v: here it should be trans as "ridges" .  I can explain what is happening in this process on Monday

barbe definitely not flashing.  "barb" doesn't seem quite right.  DMF has "Toute pilosité ou villosité ou amas de matériau ressemblant à une barbe" which may be what it means (sort of like flashing, but not leaking out of the edges of a mold).  But can we say "beard"?  Let's decide on Monday

**Comment by ps2270** [comment]
66r use protusions twice
116v: protrusion

barbe = barb
