### ISSUE TITLE
"fin" = "fine" or "pure"?

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#421]
Need to search and make decision. Comment from PHS (from issue #98):

I think "crude" is better than coarse. I hate to raise this, but this brings up once again the problem of whether fin is better translated in this case by pure. The "finest" metal one can find is rather different than the "purest". This entry seems pretty clearly to mean the purest metal (in the sense of copper alloy "metal", not generic metal), because it goes on to say that finest means a larger amount of copper. I'm not sure how to deal with this. Have we used pure to translate "fin" in the case of silver and tin? I'm pretty sure we have, but it's worth searching selectively.

**Comment by ps2270** [comment]
If this is still a question.  We made a decision: translate as "fine"

**Comment by ps2270** [comment]
Tillmann, if you are doing this, I think we discussed this thoroughly.  Can you pls check the meeting notes from Monday and record our decisions. Thanks!

**Comment by TillmannTaape** [comment]
I've assigned myself to this so it's clear who is doing it. There's nothing on this in any meeting notes from 2019, but your comment above suggests that we decided on "fine". If that sounds right, I'll go ahead and check/make changes.

**Comment by ps2270** [comment]
That's right.  Go ahead.  Thanks.

**Comment by TillmannTaape** [comment]
search term: fine* (RE); ignored things like "affin", "enfin" etc.
All instances of "fin(e)" qualifying a material translated as "fine", except "black cloth is thin" (fol. 83v) was left as "thin" because the point here was that it is cheap, i.e. presumably not of the "finest" quality.
