### ISSUE TITLE
translation of "grosserie"

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#423]
"grosserie" of goldsmiths (often paired with "vaisselle", i.e. plate) is variously translated as "wholesale" or "grand work". Any ideas what this means and how to translate?
@Pantagrueliste ? @ps2270 ?

**Comment by Pantagrueliste** [comment]
He could be referring to silverware. 
```(a) Technol. ,,Nom générique des gros ouvrages que font les taillandiers`` (Ac. 1835-1932). En partic. Ouvrage important d'orfèvrerie et, notamment, vaisselle d'argent. Nous ne pouvons que nous limiter aux orfèvres proprement dits, chargés de la « grosserie » en métaux précieux (GRANDJEAN, Orfèvr. XIXe s., 1962, p. 22). b) Vx. Commerce de gros. Marchand qui fait de la grosserie (LITTRÉ). ```

**Comment by TillmannTaape** [comment]
3 instances

123r: ceulx qui travaillent de vaissele & grosserie
"who work in plate and to/in quantity"?
"who work in plate and in bulk"?

149v: Les orfevres qui travaillent de grosserie et vaisselle
"who work to/in quantity and in plate"?

154r: les orfevres qui travaillent de grosserie

**Comment by ps2270** [comment]
does this mean tableware? Is that implied by plate.  TBC

**Comment by ps2270** [comment]
Decision: 
translate as "in plate and in quantity"

**Comment by Pantagrueliste** [comment]
see also #441

**Comment by ps2270** [comment]
Decisions: 
123r: ceulx qui travaillent de vaissele & grosserie
"who work in plate and in quantity"


149v: Les orfevres qui travaillent de grosserie et vaisselle
"who work in quantity and in plate"

154r: les orfevres qui travaillent de grosserie
the goldsmiths who work in quantity

**Comment by thuchacz** [comment]
A goldsmith working “in plate” risks “plate” being interpreted as the raw format of the metal (or in gold plating...)

**Comment by TillmannTaape** [comment]
@thuchacz I see what you mean, but I think it's a small risk and one we can take unless we want to  sup or put an ed. note. So I'm still inclined to go with @ps2270's decision above. 

@Pantagrueliste, as resident vaisselle expert in #441, does "plate" work for "vaisselle" throughout?

**Comment by Pantagrueliste** [comment]
Cellini's use of *Grosseria* in his *Trattato dell'oreficeria*  might be helpful. Its English translator (Ashbee) defines it as:
> metal work of the larger sort, as opposed to *minuteria*. Our term, hammered hollow ware, would partly express it. It mainly included the beating of large vessels into shapes, but it did not exclude the processes of casting.

**Comment by Pantagrueliste** [comment]
> @Pantagrueliste, as resident vaisselle expert in #441, does "plate" work for "vaisselle" throughout?
affirmative

**Comment by Pantagrueliste** [comment]
Goldsmiths who work in plate and large wares.

**Comment by TillmannTaape** [comment]
All three instances of "grosserie" translated as "large wares".
