### ISSUE TITLE
Terms for consideration during translation read-through

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#431]
#152 il faut (que)

#355 translation of “bien”

#172 recuire (see spreadsheet of instances in DCE - TT folder) and chauffer in association with it. Keep in mind the various meanings of recuire to "refire" as in brick, recook, reheat, and anneal.  Chauffer should be "heat" or "heat up".

**Comment by Pantagrueliste** [comment]
#102  métal

**Comment by thuchacz** [comment]
Look out for medical symptoms, indications, counter-indications, cure/curative effects, negative effects, procedures (but not more general instructions). See #124

**Comment by TillmannTaape** [comment]
destremper #551

**Comment by TillmannTaape** [comment]
gecter = "cast" rather than "throw" with plaster; although "throw" is ok for ingredients etc.

**Comment by njr2128** [comment]
Size and position of figures

**Comment by njr2128** [comment]
Entry categories, esp wax process, wood coloring

**Comment by ps2270** [comment]
For Glossary: when we come across stand-out variant spellings, we may check glossary and see if they are included.

**Comment by njr2128** [comment]
What 84v_2 continues, see #730 (and associated editorial comment)
