### ISSUE TITLE
use separate elements for marks and symbols?

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#44]
If so, what are the criteria to distinguish whether something is a mark or symbol? Is this an important distinction?

**Comment by njr2128** [comment]
Possible definitions:
"mark" - drawing-like mark made by the AP such as a "+" , "/" or "*"
"symbol" - unicode or similarly-accepted character such as the ones used for dram, the alchemical symbols like mercury or silver, etc.

**Comment by njr2128** [comment]
See also #43, #37, #19, #121, #165
