### ISSUE TITLE
Check consistency of "Vaisselle"

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#441]
see #136

**Comment by Pantagrueliste** [comment]
The translation of Vaisselle is not consistent.
```
	tcn_p028v_preTEI	de rosette sur un quintal pour rendre la	vaisselle		sonnante. Pour mouler de plats & escuelles, ilz les font
	tcn_p030r_preTEI	net que le grais, pource que la	vaisselle		y vient sans baves & bien unye. Mays c'est pour
	tcn_p030r_preTEI	du gect & aulx moules de grais La	vaisselle		se peult marteler mar pour estre plus vendable. Mays elle n'
	tcn_p044r_preTEI	les chaudroniers. Cela faict plus sonner la	vaisselle		, & n’est pas si rompante. left-middle Cest estaim s’
	tcn_p079v_preTEI	est celuy duquel les pintiers usent pour faire	vaisselle		, qui est composé de 9 ou dix dix lb de plomb
	tcn_p149v_preTEI	pieces Les orfevres qui travaillent de grosserie et	vaisselle		font tourner au tour telle forme de bois qu'il leur plaist
```

**Comment by Pantagrueliste** [comment]
definition: 

> [Du Moy. Âge au XIXe s.] Ensemble des pièces en métal précieux, souvent ouvragées, composant le service de table des seigneurs et constituant une richesse monnayable.

**Comment by Pantagrueliste** [comment]
Usually translated as vessel, except in f.28v, f.79v, f.123r, f.149v

**Comment by ps2270** [comment]
Thanks for that, Clement.  Let's talk about this in an hour, but here are some first thoughts:
TRANSLATIONS DECISIONS.  These could be "plate" or "table service"
tcn_p028v_preTEI	de rosette sur un quintal pour rendre la	vaisselle		sonnante. Pour mouler de plats & escuelles, ilz les font
"to render plate resonant" [not sure what the trans now is, but I remember discussing it intensively]
	
tcn_p030r_preTEI	net que le grais, pource que la	vaisselle		y vient sans baves & bien unye. Mays c'est pour
probably "plate" or 
	
tcn_p030r_preTEI	du gect & aulx moules de grais La	vaisselle		se peult marteler mar pour estre plus vendable. Mays elle n'
here "plate"
	
tcn_p044r_preTEI	les chaudroniers. Cela faict plus sonner la	vaisselle		, & n’est pas si rompante. left-middle Cest estaim s’
	tcn_p079v_preTEI	est celuy duquel les pintiers usent pour faire	vaisselle		, qui est composé de 9 ou dix dix lb de plomb
"plate"

tcn_p149v_preTEI	pieces Les orfevres qui travaillent de grosserie et	vaisselle	font tourner au tour telle forme de bois qu'il leur plaist
already responded
