### ISSUE TITLE
Metadata for all images and captions per annotation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#45]
Can we semi-automatically populate a list of all figures and their captions per annotation?
To be used for status of image permissions etc. by editorial team
Perhaps part of lizard logs?

**Comment by tcatapano** [comment]
By when is this needed?

**Comment by njr2128** [comment]
Columns desired:
- annotation ID
- annotation title
- name of the file (e.g. Figure01...)
- URL to GD file in Illustrations folder 
- associated caption

**Comment by njr2128** [comment]
This has been undertaken in the GD spreadsheet **media-full-list** but without captions. That is ok for now
