### ISSUE TITLE
Remove <x> tags and replace with appropriate tag

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#463]
`<x>` is an old tag left over from prior markup campaigns which should no longer be in use. There are a few instances still remaining across all three versions (tc ,tcn, tl). The appropriate current tag should be determined and then replace the `<x>`

(see #40 clarify use of `<x>` tags)

**Comment by TillmannTaape** [comment]
Searched for "<x>" and checked against manuscript page to verify appropriate tag (which was <sup> in all cases).
