### ISSUE TITLE
Flesh out Amsterdam Annotations tab of the Annotation tracking and metadata sheet

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#465]
In the Amsterdam tab of the [Annotation tracking and metadata](https://docs.google.com/spreadsheets/d/100gc0_Fue9KdNmqNtGpmaWGWGNnOMjEe_rWgxEOocmE/edit?usp=sharing) sheet:

1) match up the links to the columns
2) create additional metadata columns (esp. for entry IDs, etc.) and fill out

**Comment by njr2128** [comment]
EXPIRED
