### ISSUE TITLE
Update annotation-metadata with illustration folder url

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#482]
New column has been added for URL of GD illustrations folder for each annotation.

Add the url for each annotation in the corresponding cell

**Comment by caro27** [comment]
[Annotation Metadata](https://bit.ly/2Pe58Qc) is updated, including url for captions.  Some annotations don't have captions or illustrations. That is marked with N/A. For those that are missing one of the folders, that has been noted. Still waiting on Celine and Baris's images.
