### ISSUE TITLE
Fol. 156r translation revisions

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#483]
[156r_1 translation changes.docx](https://github.com/cu-mkp/m-k-manuscript-data/files/3092009/156r_1.translation.changes.docx)

**Comment by TillmannTaape** [comment]
@ps2270 I changed the translation thus:

Molding promptly and reducing a hollow form to a relief</head>

<ab>You can imprint the relief of a medal in <m>colored wax</m>, &amp;
you will have a **hollow form**, in which you can cast <fr>en noyau</fr> a relief
<add>of your sand</add>, on which you will make a hollow form of <m>lead</m>
or <m>tin</m>, in which you will cast a <m>wax</m> relief. And then on
that <m>wax</m> you will make your <tl>mold</tl> with a hollow
<fr>noyau</fr>, to cast **there** the relief of <m>gold</m> &amp;
<m>silver</m> or any other <m>metal</m> you like. But to hasten your
work if you are in a hurry, make the first imprint &amp; hollow form in
<m>bread pith</m>, prepared as you know, which will mold very neatly.
And **into that**, cast <m>melted wax</m>, which will give you a beautiful
relief, on which you will make your <fr>noyau</fr>.</ab>

1) I translated "hollow form" which is how "le cave" has nearly always been translated as per our  most recent discussion
2) I did not insert "And into that cast **there**" as you tentatively suggested – it sounded much more clunky than in the French

Let me know if I should make further changes.

**Comment by TillmannTaape** [comment]
re point 2., perhaps "And into that, cast **in** melted wax" might be an option. Keeps the redundance but is slightly less disturbing.

**Comment by ps2270** [comment]
Yes, let's translate as you suggest in your last comment.

**Comment by TillmannTaape** [comment]
Done.
