### ISSUE TITLE
inconsistent hyphenation with various kinds of makers

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#491]
TL gives framemakers, but OED says frame-makers.
TL gives glassmakers and glass-makers. What do we want? What standard?
**TO DO:**
Check Chicago Manual of Style for general rule.
Make decision and consistify.
Notify Celine of decision for her pref-label work.

**Comment by thuchacz** [comment]
check also workers, perhaps cutters, engravers, etc.

**Comment by ps2270** [comment]
CMS: SEE 7.89 on hyphenation: 
noun + noun, single function, first noun modifies second noun = closed compound (but this is not a hard and fast rule). It gives the following examples:
shipbuilder
gunrunner
copyeditor

DECISION:
we use closed compounds in many cases, but not all:
e.g., framemaker
glassmaker
gem cutter
glassworker

I honestly think either (consistently) open or closed is fine, but hyphenated is NOT ok.

If you disagree with this decision, don't hesitate to let me know.

**Comment by thuchacz** [comment]
searched for variant spellings informed by [Celine's work on a controlled vocabulary for the <pro> tags](https://docs.google.com/spreadsheets/d/1PbStFr0zbr5__W1l-AMTMV7Y69p9nONzu7OoS0QWUzE/edit?usp=sharing) 

pastry-makers = pastry makers
glass-button makers = glass button makers
white-limers = white limers
guitarmakers = guitar makers
sheath-makers = sheath makers
framemakers = frame makers
NB: glass-maker was already consistified as glassmakers per #370
