### ISSUE TITLE
Help with "K" on 167r

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#493]
167r:  note in PW18 protocol about “K” as an abbreviation on 167r:  is this "K" actually on 167r, somewhere else, or nowhere?

**Comment by TillmannTaape** [comment]
Case-sensitive oxygen search for "K" – 2 instances

**<id>p086v_1</id>**
<head>Sable excellent pour <m>plomb</m>,<lb/>
<m>estain</m>, et <m>cuivre</m></head>
[...]
Je y gectay deulx foys<lb/>
<m>cuivre</m> allié de <m>☾</m> co<exp>mm</exp>e
<m>vieulx K</m>.

**id>p147v_1</id>**

<head><mark>+</mark> Gect de <m>cuivre</m> allié de
<m>☾</m><lb/>
qui est co<exp>mm</exp>e <m>soubdure fort basse</m> <mark>/</mark>
ard <ill/><comment>c_147v_01</comment><lb/>
et <m>vieulx K</m> et quelque R<ill/><comment>c_147v_01</comment> sur
xii</head>

**Comment by TillmannTaape** [comment]
In both cases, "vieulx K" is associated with a silver-copper alloy.
This is typical of a billon alloy, so perhaps K could refer to a coin?
The medieval écu had the initial K for Karolus (Charles VI), but it was made of gold and I think no longer in circulation in 1580s.

**Comment by TillmannTaape** [comment]
The German Kreuzer was abbreviated K and made of a silver-copper alloy in C16 (from C17 it was mostly made from copper alone).

See [Wikipedia](https://de.wikipedia.org/wiki/Kreuzer_(Münze))

**Comment by ps2270** [comment]
Interesting.  We need to have an editorial comment on these two "K"s, with the hypothesis that it is a coin or some other alloyed object used in the process.  Please do that. Thanks!

**Comment by TillmannTaape** [comment]
Ed. note:

"vieulx K" occurs twice in the manuscript (fol. 86v and 147v), and both instances are associated with a silver-copper alloy. One of its uses was in minting coins, where it was known as billon. The abbreviation K could thus stand for a coin, perhaps the German Kreuzer which was abbreviated K and was made of silver-copper alloy up until the the seventeenth century. 

@ps2270 Please review

Ed. note added to glossary and anchored in TL.

**Comment by ps2270** [comment]
A few revisions--which I have entered in the ed note in glossary: 
"vieulx K" occurs twice in the manuscript (fol. 86v and 147v), and both instances are associated with a silver-copper alloy. Silver-copper alloy was used in minting coins, where it was known as billon. The abbreviation K might thus indicate a coin, perhaps the German Kreuzer which was abbreviated K and was made of silver-copper alloy up until the seventeenth century.

**Comment by TillmannTaape** [comment]
Thanks, I updated the note in the comment tracking sheet.
