### ISSUE TITLE
Past participle of "to wet"? 

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#495]
We have found "wettened", "wetted", and "wet".  Which of "wetted" or "wet" should we use?  Once we decide which we prefer, we can search and replace, or carry out during translation campaign.

**Comment by ps2270** [comment]
We prefer "wetted".

**Comment by ps2270** [comment]
@thuchacz

**Comment by ps2270** [comment]
@thuchacz, are we doing search and replace on this, or doing during readthrough #431

**Comment by Pantagrueliste** [comment]
I cannot find "wettened" in TL. Has it been replaced already?

**Comment by TillmannTaape** [comment]
I replaced a few as I came across them, so it's possible that I caught them all.
