### ISSUE TITLE
mock up SKOS version of glossary

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#50]

**Comment by TillmannTaape** [comment]
Sorry wrong commit message; should have been '#57'

**Comment by njr2128** [comment]
https://www.w3.org/TR/swbp-skos-core-guide/

**Comment by njr2128** [comment]
This is the current working document for the glossary in tabular form: [DCE-glossary-table](https://docs.google.com/spreadsheets/d/1qexNvJ5bG5Mr9_MtH7QHN4o0uBKG_iHw48lJ-lGwero/edit?usp=sharing) found in the GD

**Comment by njr2128** [comment]
Will likely never do this, closing for now. Can always reopen or create new issue
