### ISSUE TITLE
Gecter translated as "to throw"

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#505]
I've come across some instances of "gecter" having been translated as "to throw", rather than "to cast" in what are clearly cases of casting plaster or wax into a mold.  
There are many correct instances of gecter being use as "to throw" in ingredients which we can leave.
I'm not sure it's worth going through the 80+ instances (although it would be relatively quick) of "throw".  WE could just keep our eyes open for it during translation campaign.

**Comment by ps2270** [comment]
#431

**Comment by TillmannTaape** [comment]
Decision: things like "throwing plaster" which ring false will be easy to spot during the read-through. This has been added to the terms to look out for in #431.
