### ISSUE TITLE
MHS paper strip queries

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#509]
List for things we would like Marc to look at under the paper strips

**Comment by TillmannTaape** [comment]
170v_1 supped "sols", in receipt entry.

121r "coin"? hidden under paper strip. See #181

**Comment by TillmannTaape** [comment]
115v last line: "moules des fleurs" rather than "moules des ferriers" as was previously transcribed? I certainly cannot see two Rs, and it looks a lot like the word "flowers" on 116r. This would also make much more sense in context: molds of flowers need to be heated twice to burn the flowers.

I've provisionally changed this the current tc, tcn and tl but please check.

**Comment by njr2128** [comment]
At the top of p054v, entry p054v_1 seems to begin with no heading, only a figure of a barrel.
There is ink residue from writing at the top of this page
 - Is the title under the top paper strip? What is the ink residue on the top paper strip?
@thuchacz

**Comment by thuchacz** [comment]
170v_1 supped "sols" has been resolved with new in-line figure (found under the paper strip) and an editorial comment.
121r is its own issue now and MHS will do some dictionary work
115v has been resolved
054v_1 REALLY IS an entry without a heading.
