### ISSUE TITLE
well formedness errors in xml files

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#515]
There are a number of files under ms-xml which are not well-formed XML.

```
ms-xml/tc/tc_p019r_preTEI.xml:35: parser error : Opening and ending tag mismatch: ab line 12 and ms
balle</ms> a la culasse</ms> &amp; en ostent quelque fois sur le
                            ^
ms-xml/tc/tc_p019r_preTEI.xml:40: parser error : Opening and ending tag mismatch: div line 6 and ab
que lon leur baille</ab>
                        ^
ms-xml/tc/tc_p019r_preTEI.xml:212: parser error : Opening and ending tag mismatch: root line 1 and div
</div>
      ^
ms-xml/tc/tc_p019r_preTEI.xml:213: parser error : Extra content at the end of the document
</root>
^
ms-xml/tc/tc_p170v_preTEI.xml:27: parser error : Opening and ending tag mismatch: div line 6 and ab
un tiers <del>sur qu</del></ab>
                               ^
ms-xml/tc/tc_p170v_preTEI.xml:34: parser error : Opening and ending tag mismatch: root line 1 and div
</div>
      ^
ms-xml/tc/tc_p170v_preTEI.xml:36: parser error : Extra content at the end of the document
<div>
^
ms-xml/tcn/tcn_p147v_preTEI.xml:16: parser error : Opening and ending tag mismatch: head line 10 and m
et <m>vieulx K</m></m><comment>c_086v_03</comment> et quelque R<ill/><comment>c_
                      ^
ms-xml/tcn/tcn_p147v_preTEI.xml:17: parser error : Opening and ending tag mismatch: div line 6 and head
xii</head>
          ^
ms-xml/tcn/tcn_p147v_preTEI.xml:39: parser error : Opening and ending tag mismatch: root line 1 and div
</div>
      ^
ms-xml/tcn/tcn_p147v_preTEI.xml:41: parser error : Extra content at the end of the document
<div>
^
ms-xml/tl/tl_p093r_preTEI.xml:68: parser error : Opening and ending tag mismatch: tl line 68 and m
<ab> <del><m>Ashes</m></del> <m>well <tl>pulverized tallow</m> molds</tl> &amp;
                                                              ^
ms-xml/tl/tl_p093r_preTEI.xml:68: parser error : Opening and ending tag mismatch: m line 68 and tl
<ab> <del><m>Ashes</m></del> <m>well <tl>pulverized tallow</m> molds</tl> &amp;
                                                                         ^

```

As a reminder, please fix any well-formedness files before closing files. Well-formedness errors are indictated by red bars on the sidebar of oXygen. 

Well-formedness validation can also be performed by doing the following (https://www.oxygenxml.com/doc/versions/20.1/ug-author/topics/checking-xml-well-formedness.html#checking-xml-well-formedness__check_for_wellformedness)

* Select the Check Well-Formedness (Ctrl + Shift + W (Command + Shift + W on OS X)) action from the Validation drop-down menu on the toolbar (or the Document > Validate menu).
*  A selection of files can be checked for well-formedness by selecting the Check Well-Formedness action from the Validate submenu when invoking the contextual menu in the Project view.

**Comment by thuchacz** [comment]
@tcatapano 
All of the xml files are currently well-formed. I'm not sure what this is referring to.

T.

**Comment by tcatapano** [comment]
@thuchacz  strange. This line in a file currently in the master branch, for example, contains a well-formedness error and should be detected in oXygen:

https://github.com/cu-mkp/m-k-manuscript-data/blob/3861d0717e0ab00ced33152288630157c284155d/ms-xml/tl/tl_p093r_preTEI.xml#L68

(i.e., overlap of the `<m>` and `<tl>` tags)

Is this not throwing an error for you?

**Comment by thuchacz** [comment]
That's so interesting!
I'm getting that error today, but yesterday, when you opened this issue and
I "checked well formedness" in the xml folder (and then the TC, TCN, and TL
folders within, just to be sure), I got no errors back at all.

Hmm. Well, in any case, I'm fixing the overlap on 93r as part of a branch
I'm on. I'll push in an hour or so, and when you approve my pull request,
it should disappear.

T.

**Comment by tcatapano** [comment]
Great. I hope to fix the others soon.  BTW the well-formedness errors block the processing of derivative xml formats and metadata which have not been refreshed in a long time.

**Comment by tcatapano** [comment]
Still getting well formedness errors for files under ms-xml/:

xmllint --noout ms-xml/*/*.xml 2>&1 | grep error | cut -d':' -f1 | sort  | uniq -c
   4 ms-xml/tc/tc_p115v_preTEI.xml
   5 ms-xml/tc/tc_p127v_preTEI.xml
   5 ms-xml/tcn/tcn_p123r_preTEI.xml

**Comment by tcatapano** [comment]
well formedness errors persist in updated and merged files. When submitting pull requests please perform a well formedness check on all the xml files in your branch and resolve them before submitting the pull requests. 

As mentioned above (https://github.com/cu-mkp/m-k-manuscript-data/issues/515#issue-437752149):


Well-formedness errors are indictated by red bars on the sidebar of oXygen. 

> Well-formedness validation can also be performed by doing the following (https://www.oxygenxml.com/doc/versions/20.1/ug-author/topics/checking-xml-well-formedness.html#checking-xml-well-formedness__check_for_wellformedness) : 

> * Select the Check Well-Formedness (Ctrl + Shift + W (Command + Shift +  W on OS X)) action from the Validation drop-down menu on the toolbar (or the Document > Validate menu). 

> * A selection of files can be checked for well-formedness by selecting  the Check Well-Formedness action from the Validate submenu when  invoking the contextual menu in the Project view.
--
