### ISSUE TITLE
Principles of editorial commentary 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#517]
Functionality, form, and characterization into types of editorial comments have not yet been fully formalized.

Principles to be implemented for the digital critical edition 2019 release:

- comments will be categorized into multiple comment types (e.g. translation, textual, facsimile note, informational)
- no proliferation of categories; instead, “niche interests” as listed below might be the most important [decide this on comment read-thru]
> - ”niche interests”, e.g., material properties of the page, navigation, points in the text, historical persons, links to other texts/authors.
> - These would be selectively rendered, and particular categories might be drawn to different pages.
> - pull out lists elsewhere, rather than at the symbolic indicator on the folio page itself?  Or: have the category indicated once you click?
- Yes to indication of different categories, don’t know yet whether at level of symbol or content in the popout window
- Particular categories would be pulled out into another area (e.g., translation ones might be appended to “Principles of Translation”)

Also to consider: different separate area of DCE that filters all comments

**Comment by ps2270** [comment]
There is variation in editorial comment reviewers placing translations of Latin and other languages on all three versions or just on tcn and tl.  Can all let me know quickly what each of you think about this question. I can see good reasons just to place them on tcn and tl, but why not on all 3 versions (more work to place anchors, for one)?

**Comment by thuchacz** [comment]
I'm in favor of erring on the side of putting comments on all three versions, unless we develop a clear logic for why foreign language translations are only relevant to English speakers.

**Comment by ps2270** [comment]
Ok, sounds good. I'm going through the ed comm sheet and adding other versions as appropriate.
