### ISSUE TITLE
120v and <rub> <man> issues

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#529]
After the main text of 120v_3, we get this:
```
<rub>See</rub> the second leaf following.

<ab><man>
<margin>left-middle</margin><del>
Doubtful
<corr>question</corr></del></man><comment>c_120v_07</comment></ab>
```
The `<man>` block is rendering, but not in the margin, as its margin location tag should indicate. And the markup for `<rub>` leaves "the second leaf following" in no block beyond the overarching `<div>`, and neither the text between the `<rub>` tags nor the text following is rendering at all. Surely, this can't be how `<rub>` works. Or is it?

**Comment by tcatapano** [comment]
created issue https://github.com/cu-mkp/making-knowing-edition/issues/149 as this has to do with rendition, which is currently un/under-specified for man and rub. I have to take a deeper look to set create some rules for `<man>` and `<rub>` usage which can be validated

**Comment by ps2270** [comment]
See #12. We will discuss this on May 17.

**Comment by njr2128** [comment]
Covered by 
cu-mkp/making-knowing-edition#149 
#205Regularize use of <man> tags 
https://github.com/cu-mkp/making-knowing-edition/issues/162
