### ISSUE TITLE
Assign entry categories to annotations

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#539]
Current model: each annotation has been associated with the yearly theme in which it was written. These themes include Metalworking and Moldmaking, Colormaking, Practical Knowledge, Ephemeral Art, and Impressions.

Proposed new model: match each annotation to the categories assigned to manuscript entries (see #280 Integrate entry category/group assignments)

To be completed after #280

**Comment by njr2128** [comment]
DECISION:
Assign essays same entry categories as the entry they deal with most
Take from DCE_entry-category-metadata

**Comment by ps2270** [comment]
I have finished defining entry categories.  
next step: @njr2128 @thuchacz , please examine and make revisions.  After that, ask @TillmannTaape and @Pantagrueliste  to examine.

**Comment by njr2128** [comment]
@ps2270 
columns added to annotations metadata table.

Based on "status-phs" column (which pulls phs sign-off details from editing+revisions sheet), NJR is adding entry categories

**Comment by njr2128** [comment]
will be continued as annotations are finalized by PHS
