### ISSUE TITLE
Translate "pinceau" and "broisse"?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#540]
Do we want to translate pinceau as pencil and broisse as brush, or as paintbrush and brush?  Does this express successfully the possible difference intended between these two types of brushes (which is the reason we left them in French)? I don't think a consistent difference in meaning is intended, but may instead show a difference in source.  N-gram would be interesting here.
fol. 4v, broisse is the alternative to a feather; while on other folios, there is a clear difference intended betw pinceau and broisse.

**Comment by thuchacz** [comment]
See the list of terms here: #556 

Broisse = brush
Pinceau = paintbrush

**Comment by TillmannTaape** [comment]
Will be done as part of #556
