### ISSUE TITLE
qc of comments csv

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#541]
see also #345 

check that ids in comments table correspond to comment elements in ms-xml, and vice versa

**Comment by tcatapano** [comment]
using this XPath expression over ms-xml:

```
//comment[ not(. = doc('../../metadata/comment_ids_srt.xml')//id )]
```

I get these ids used in the xml files which are not in DCE_comment-tracking-Tracking.csv 

c156v_1
 c157r_1
 c_002v_06
 c_009r_03
 c_013v_02
 c_043r_01
 c_053r_02
 c_055r_04
 c_055r_05
 c_108r_02
 c_118r_011
 c_123r_02
 c_148v_01
 c_160r_01
 c_162r_08
 p002r_2
 p009r_1
 p009r_2

Ive posted the HTML report here:

https://htmlpreview.github.io/?https://github.com/cu-mkp/m-k-manuscript-data/blob/master/qc/comment_ids_not_in_table.html

(also in repo here:  https://github.com/cu-mkp/m-k-manuscript-data/blob/master/qc/comment_ids_not_in_table.html)

**Comment by njr2128** [comment]
Info recorded and done in #952. Closing this issue
