### ISSUE TITLE
destremper

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#551]
I have seen several instances of destremper being translated as "soak(ed)."

Current translation protocol says:

“mix”, “temper”, sometimes “dilute,” “wet,” (all according to context). Most often, “mix”; do not use “moisten” unless you must, and not “soak” (although Cotgrave gives this as the first definition, and does not translate it as “temper”). 

@ps2270 please can you confirm this – I will then search and destroy "soaked" in the tl, or perhaps even do a larger campaign of checking all 218 instances of "destremp" if time allows.

**Comment by ps2270** [comment]
I think we should NOT be strict about not using "soak".  I do think we should have  a larger campaign of checking the translation, but it would be difficult to do this quickly or with little contextual reading of the recipes.
I think we should keep in mind for translation campaign.  Do you agree?

**Comment by TillmannTaape** [comment]
Sounds good, we'll keep an eye out for it during the readthrough. I'll add it to our list.

**Comment by TillmannTaape** [comment]
However, can we come up with a consistent translation of destremper when it relates to sand (destremper sable, sable destrempé etc.)?

Wetted sand? Tempered sand (e.g. currently 137v–1)?

**Comment by ps2270** [comment]
137v is a good example of how hard it is to translate this. But, after much searching around, I think 
Wetting probably works ok, although I am not super happy with it.  Cotgrave emphasizes soaking and wetting, and, while DMF also defines it as soaking or wetting, it also emphasizes mixing and diluting. If you look at the (archaic) definition of "temper" in the OED, it really works well for many uses of both tremper and destremper in the ms.
@TillmannTaape , we need to discuss this and make a collective decision.
