### ISSUE TITLE
take powder symbol as mark in 124v

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#557]
use:

```<mark>🝋</mark>```

**Comment by thuchacz** [comment]
@tcatapano 
On 124v, I substituted the desired `<mark>` for the `<figure>`. I also fixed some margin position markers. In that process, I discovered that there were 3 `<cont/>` tags in the final entry—which does, in fact, continue to the next page. I removed one. Now, I want to remove another, but I want to double check which to remove: the one that can be found at the end of the main text block of 124v_3, within the `<ab>`, or the one that comes just before the close of the `<div>`? My instinct is the latter. Please confirm.

**Comment by thuchacz** [comment]
removed the tag from within the `<ab>` and left the one right before the `<div>`
