### ISSUE TITLE
Terms in Latin in the TL

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#561]
Tianna has made a [spreadsheet of Latin terms.](https://docs.google.com/spreadsheets/d/1KhS7yAaQnq2F5A_Q7MG6xqRyStNZwUSfhyJp9aOUSUQ/edit?usp=sharing)

Any changes should be made with reference to this issue.

**Comment by TillmannTaape** [comment]
@thuchacz can we close this?

**Comment by thuchacz** [comment]
I want to look it over again over the next few days. I'll close out before
next Wed.

**Comment by thuchacz** [comment]
Okay. I went through the table, added all the missing Ed comments to the tracking sheet, and anchored them in all three versions of the text. 3 outstanding terms for translation (see #1174).

Closing.
