### ISSUE TITLE
Entries on 106v — additional <div>s and <id>s required

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#565]
@ps2270 
Please look at 106v in the staging edition and let me know how many distinct entries you think there are on this page. Right now, the whole page is grouped into one `<div>` (i.e., one entry) under the header: `<head>Gecter en <m>or</m></head>`. There are other non-entry-level designations in the markup: 
There is one manchette: "Plastre" in the top left corner. 
There are four rubrics: Tuiles; Le plastre; L'alum de plume; Le crocum ferri.

This doesn't seem right to me.

**Comment by thuchacz** [comment]
FYI: In PW18 BnF Ms. Fr. 640 Index Tracking, "Tuiles" (now a rubric) and "Plastre" (presumably the manchette in the upper left corner) have been treated as entries, but **do not have entry ids yet**.

**Comment by ps2270** [comment]
Plastre in upper left (now marked as manchette) should be made an entry and given an entry id.  Tuiles in the center text (now marked as rubric) should be made an entry and given an entry id.  NB: the div tags will have to change also on this page.
Additionally, on 107r, the "continued" mark must go on margin block rather than in the div.
PLEASE NOTE: WE ARE NOT CONTINUING THE PLASTRE ENTRY ON 107R (after Catching snakes)

**Comment by njr2128** [comment]
Updated in Index Tracking, these are the div-id assignments. Markup should updated accordingly

p106v_3 | p106v | Tuiles | Tiles | casting
-- | -- | -- | -- | --
p106v_2 | p106v-p107r | [Plastre]  p1 | Plaster p1 | casting
p106v_2 | p106v-p107r | [Plastre]  p2 | Plaster p2 | casting

**Comment by ps2270** [comment]
Resolve in discussion of #12

**Comment by njr2128** [comment]
> Updated in Index Tracking, these are the div-id assignments. Markup should updated accordingly
> 
> p106v_3	p106v	Tuiles	Tiles	casting
> p106v_2	p106v-p107r	[Plastre] p1	Plaster p1	casting
> p106v_2	p106v-p107r	[Plastre] p2	Plaster p2	casting

@thuchacz, please add entry ids to xml for these 3 instances

**Comment by thuchacz** [comment]
RECAP REFINED DECISIONS of June 10:
"Plastre" in top-left margin of 106v is elevated to the status of a heading (as is "tuiles, less problematically). "Plastre" continues down the margin, cuts across at the horizontal line beneath "tuiles," where it picks up with three `<rub>`s: "Le plastre," "Lalum de plume," and "Le crocum ferri". At the hash tag in the body text, the thread jumps to the margin (at the corresponding hash), and continues to the two circles at the lower right. Those symbols reappear on 107v, where the entry continues."

Add an editorial comment adjacent to the `<head>` of the newly entry-fied "Plastre" that suggests that this may be a continuation of the discussion of Plaster of Paris at the end of the previous entry.

**Comment by thuchacz** [comment]
page restructured
<comment>c_106v_07</comment> added to heading "Plastre"
2 new issues created re: problematic rendering in Nick's repository
