### ISSUE TITLE
"piler" to be translated as "to pestle"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#57]
Check TL for consistency
"piler" "pile" "piles" "pilez" "pilent" etc.
"piller"? Other spellings? Try "pil*"

**Comment by TillmannTaape** [comment]
Search terms: pile, pille, pilhe

**Comment by TillmannTaape** [comment]
Search is accent specific. Now searching for additional terms:
pilé
pillé

40 occurrences, checked translation and inserted missing <tl> tags
