### ISSUE TITLE
Resin/Rosin translation

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#571]
If we assume that resin/pitch is liquid, and rosin is the solid form of this resin, created by heating resin to drive off the volatile liquid components, then we should search for "resine," "rousine," and decide whether they should be translated as resin or rosin.  On 98r, "rousine" should definitely be translated "rosin" instead of "resin" (I have learned from Celine's annotation).  On 3r, both rousine and resine are used, and in at least one case, we have translated rousine as resin when it actually should be rosin.

**Comment by ps2270** [comment]
Decisions for resine:
4v: change "resin" to "pitch resin" (as we have translated poix resine that way in all other instances)

Decisions for rousine:
94r: change from resin to rosin
95v: all instances of rousine should be trans as "rosin" rather than "resin"
98r: all instances of rousine should be trans as "rosin" rather than "resin"
120r: change to rosin 
49r: change to rosin
57v: change to rosin
116v: change to rosin
110v: change to rosin
119r: correct the translation from "two or three grains, like pitch rosin" to "two or three grains of something like pitch rosin"
131v: change to rosin
139r: change to rosin
150r: change to rosin

**Comment by TillmannTaape** [comment]
Made changes as indicated above. 

Also amended TL on 98r: "tu le frotteras" was translated as "you will hit it" – I changed this to "you will rub it"
