### ISSUE TITLE
Check on semantic tags that span across folios

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#575]
When a phrase to be tagged spans across more than one folio, we encounter a few problems and there is the possibility that there has not been a consistent solution.

For example, on 18v-19r, "pieces de campaigne" is an entire phrase to be tagged as `<wp>`
>18v
>....`<wp>`pieces`</ab>`
>19r
> de campaigne`</wp>` ...

In order to prevent well-formedness errors, 2 approaches have been taken:
1. add closing and opening weapon tags to each part of the phrase, i.e.
>18v
>....`<wp>` pieces `</wp></ab>`
>19r
>`<wp>` de campaigne `</wp>`... 
2. add `<sup>` tags to the first section and removing `<wp>` from the second part

TO DO:
- Check what has been done to see if this has been done consistently (and whether it matters)
- For controlled/normalized vocabulary, these decisions need to be taken into consideration for term lists as they may create confusing or incomplete entries

**Comment by njr2128** [comment]
@tcatapano, can you weigh in here?

**Comment by tcatapano** [comment]
How many times does this occur? If only a few times, an ad hoc/case by case solution may be preferable to spending much time on this now. As for a general solution, I'd recommend simply splitting the phrase into two tagged segments to maintain well-formedness. (example 1) Use a comment to indicate that the phrase is split and we can judge the importance/significance of the splitting and develop any necessary solution later.

**Comment by tcatapano** [comment]
used this xpath to find all tags which have no following text in the last ab with a following cont in the last div of a folio

```
//div[position() = last()]/ab[not(following::ab)][following::cont]/*[position() = last()][not(following-sibling::text())]
```

found 11 occurrences:

```
System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p003r_preTEI.xml
Description: grosse tourmentine commune
XPath location: /root[1]/div[3]/ab[1]/m[5]
Start location: 236:35
End location: 236:68

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p004v_preTEI.xml
Description: esponge
XPath location: /root[1]/div[3]/ab[1]/tl[2]
Start location: 173:49
End location: 173:65

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p068v_preTEI.xml
Description: 
XPath location: /root[1]/div[1]/ab[1]/lb[33]
Start location: 110:6
End location: 110:11

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p069r_preTEI.xml
Description: vitriol calciné
XPath location: /root[1]/div[3]/ab[3]/m[1]
Start location: 144:1
End location: 144:23

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p079r_preTEI.xml
Description: 
XPath location: /root[1]/div[4]/ab[1]/corr[1]
Start location: 100:1
End location: 100:30

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p090r_preTEI.xml
Description: sable de
XPath location: /root[1]/div[3]/ab[1]/m[5]
Start location: 96:1
End location: 96:32

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p094v_preTEI.xml
Description: 
XPath location: /root[1]/div[1]/ab[14]/figure[5]
Start location: 150:1
End location: 154:39

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p108v_preTEI.xml
Description: 
XPath location: /root[1]/div[1]/ab[4]/hr[1]
Start location: 165:49
End location: 165:54

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p115v_preTEI.xml
Description: 
XPath location: /root[1]/div[3]/ab[5]/figure[1]
Start location: 238:1
End location: 243:10

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p141v_preTEI.xml
Description: c_141v_02
XPath location: /root[1]/div[1]/ab[7]/comment[1]
Start location: 209:19
End location: 209:47

System ID: /Users/terry/Github/m-k-manuscript-data/ms-xml/tcn/tcn_p166r_preTEI.xml
Description: “ pœma  imitatus est, nam cum  sic prius exorsus esset: Iram cane,  dea, frugiferentis, ita reddit : Iram cane, dea, .” In , circa princip.
XPath location: /root[1]/div[1]/ab[4]/la[3]
Start location: 101:51
End location: 111:28

```

all resolved by @thuchacz

**Comment by tcatapano** [comment]
@thuchacz decided 90r is not a problem after all. Closing.
