### ISSUE TITLE
Review markup protocol and better define tags

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#576]
`<wp>`, `<ar>`, `<mark>` have not been defined.
The whole protocol needs to be reviewed for accuracy and thoroughness.

**Comment by njr2128** [comment]
https://docs.google.com/spreadsheets/d/1QDzo48chr7P3NqNIQwb-UQIP9YM2QBDFE4NP3hmhafg/edit#gid=0

**Comment by ps2270** [comment]
I have added "description and use" to each tag in the spreadsheet (and I have left questions in the "issues" column: 
https://docs.google.com/spreadsheets/d/1QDzo48chr7P3NqNIQwb-UQIP9YM2QBDFE4NP3hmhafg/edit#gid=0
Next step: @thuchacz , please go through them and make edits to the descriptions

**Comment by ps2270** [comment]
See Principles of Markup:
https://docs.google.com/document/d/1OL7YjYUS39bhQTOPrpwqqCRrqJQXK7w1kt1-5Zeuu5Y/edit

**Comment by njr2128** [comment]
This has been completed and integrated into the Edition at https://edition640.makingandknowing.org/#/content/resources/principles-encoding
