### ISSUE TITLE
Translation of chappe

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#578]
check and translate as cap or crust

**Comment by ps2270** [comment]
Two translations:
85v: should be translated "cope" = the covering of a mold for a bell. (cotgrave) (Figurative use, from the shape of a ecclesiastical cope (a type of robe)
98v: cope
The other meaning is a covering, coating, film. DMF has the meaning of a thin covering such as over a nut kernel.  OED has one meaning of "cope":  9. A superficial deposit considered as a covering or coating of the stratum beneath: cf. coping 
1631   G. Markham Inrichm. Weald of Kent (new ed.) ii. i. 7   Some of them [marls] have over them a cover of ground, which we call Cope.
1631   G. Markham Inrichm. Weald of Kent (new ed.) ii. i. 7   A cold stiff and wet clay, which is either the Cope of the Marl or lieth near unto it..commonly called The Marl Cope ground.
This is the meaning of the remaining instances in Ms. Fr. 640- something like "superficial deposit," but I think we should go with "film". It is a good early modern word, and seems to encompass all these meanings, thus
8v: film
154r: film
15r: film
147v: film
86v: film

@Pantagrueliste , can you please search and change, if you think this is an acceptable translation.
thanks!

**Comment by Pantagrueliste** [comment]
done

**Comment by ps2270** [comment]
We are now moving to translate this as crust.  Not yet a decision, but almost.  This would necessitate most "chape", "chappe", "cappe" being translated as "crust".  Not 85v and 98v.

**Comment by njr2128** [comment]
Updated in glossary, decided on crust.

@Pantagrueliste - can you check that this was done across the board?

**Comment by ps2270** [comment]
@Pantagrueliste I found that chappe was not translated as crust on 86v.  Can you check that your commit worked way back 2 weeks ago?

**Comment by Pantagrueliste** [comment]
done
