### ISSUE TITLE
Backwards writing appears to be Spanish—not the Italian we thought it was

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#589]
**TCN:**
```
<id>p055r_4</id>
<head><md><it>Onenev elbirro</it></md><comment>c_055r_03</comment> <md>tnaut is no ehcram<lb/>
rus enu elbat uo <del>ueirse</del> ueirtse</md></head>
```
**Which gibberish is backwards for:** venone orrible tuant si on marche sur une table ou estrieu

But "venone orrible" seems to be a Spanish string, not an Italian one. Time for an `<sp>` tag?

@Pantagrueliste @TillmannTaape @ps2270

**Comment by ps2270** [comment]
interesting, altho' wouldn't horrible in Spanish have an "h"?  Although, spelling was no doubt fluid. But venone does seem to be spanish.  Anyway, Spanish tags...ok `<sp>` seems reasonable.

**Comment by Pantagrueliste** [comment]
It's actually veneno, Tianna's autocorrect must have changed the word inadvertently. "Veneno orrible" is most likely Spanish (the h is not used consistently at that time).

**Comment by thuchacz** [comment]
switched `<it>` to `<sp>` tags.
Created request to add `<sp>` to schema. See #593
