### ISSUE TITLE
Is the word "ana" really Greek?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#590]
**HELP!!! There are 2 instances where "ana" has been given Greek tags (`<gk>`):**

```
<id>p092v_2</id>
<head>Congellation de <m>mercure</m></head>
<ab>Il se congelle, co<exp>mm</exp>e j'ay essayé le faisant bouillir une<lb/>
<ms><tmp>heure</tmp></ms> ou deulx dans une assés grande <tl>cassolle de <m>fer</m></tl>, y mecta<exp>n</exp>t<lb/>
pour <ms>℥</ms> de <m>☿</m>, ii <ms>℥</ms> de <m>verdet</m> <del>de</del> et de <m>vitriol de salpestre</m><lb/>
<ms><gk>ana</gk></ms>, avecq suffisante quantité d'<m>eau vielle des <pro>mareschaulx</pro></m>.</ab>

<ab>It congeals, just as I tried, by boiling it one or two
<ms><tmp>hours</tmp></ms> in a rather large <tl><m>iron</m> posnet</tl>,
putting in, for an <ms>℥</ms> of
<m>☿</m>, ii <ms>℥</ms> of
<m><fr>verdet</fr></m> <del><fr>de</fr></del> and <m>vitriol of
saltpetre</m>, <ms><gk>ana</gk></ms>, with sufficient quantity of <m>old
water from <pro>farriers</pro></m>.</ab>
```
In this instance, "ana" has been given a measurement tag. "Ana" can be used as "per" in Greek (e.g., μέτρα **ανά** δευτερόλεπτο (metra **ana** defterolepto) = meters **per** second; or χιλιόμετρα **ανά** ώρα (hiliometra **ana** ora) = kilometers **per** hour. Is that what you think is meant here? 

___

```
<id>p083r_1</id>
<head><m>Sable</m> pour le <m>plomb</m></head>
<ab><la>R<exp>ecipe</exp></la> <m>suye grise du fourneau des <pro>argentiers</pro></m>, <m>chaulx vive</m>, et<lb/>
<m>farine</m> <ms><gk>ana</gk></ms><comment>c_083r_03</comment>, humecté selon l'art, estant le plus subtilié qu'il te sera<lb/>
possible.</ab>
```
For what it's worth, that editorial comment on 83r reads: 
"possibly from 'farina ana' = old/aged flour; e.g. cited as ingredient in Antidotarium speciale by Johann Jacob Wecker (Basel, 1581), p. 540."

___

My job is to give translations in editorial comments for foreign terms/strings. I'm not yet convinced this is Greek transliteration.
@Pantagrueliste @TillmannTaape @ps2270 — Please advise.

**Comment by ps2270** [comment]
I doubt this is greek, but since we cannot know, we should not use Greek tags.  We can have an editorial comment on 92v that says "meaning unclear. perhaps to be compared with 83r, where it might mean "old" or "aged"."
You can keep the editorial comment on 83r as is, but take off Greek tags.

**Comment by thuchacz** [comment]
Great—I'll do as you suggest for 83r.
And I will switch the 92v Greek tags to French tags, remove the measurement
tags, and add your suggested edcomment

**Comment by Pantagrueliste** [comment]
- The word used in many recipes see [Colour Context](https://arb.mpiwg-berlin.mpg.de/search/site/ana)

- It's a Greek preposition, but it's also used in Latin. See [Logeion](http://logeion.uchicago.edu/ana)
I would suggest a Latin tag as it never made its way to the vernacular.

**Comment by thuchacz** [comment]
And if we were to give it a Latin tag, then how would we translate it?
What do you think about the two instances in this issue? And what about the
idea that it might be "old"?

**Comment by ps2270** [comment]
Interesting, and even makes sense in these recipes:
1 ana [ἀνά] , at the rate of. b in an equal quantity (with). c (sb.) equal quantity.

Ok, so tag as Latin, w/ new editorial notes, linking to Logeion, and meaning "at the rate of," or "in an equal quantity (with)"

Thanks, Clement!

**Comment by ps2270** [comment]
83r: chaux vive et farine ana (in equal quantity)
92v: `same` `ii <ms>℥</ms> of
<m><fr>verdet</fr></m> <del><fr>de</fr></del> and <m>vitriol of
saltpetre</m>, <ms><gk>ana</gk></ms>,`  ana = in equal quantity

**Comment by thuchacz** [comment]
Fantastic! So it gets Measurement tags after all!

Thanks, Clément and Pamela.

**Comment by thuchacz** [comment]
switched from <gk> to <la> and added following editorial note: "Latin: in equal quantity. See http://logeion.uchicago.edu/ana"
