### ISSUE TITLE
Glossary entries for "spat" "spalt" and "stuf"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#591]
I've given `<ge>` tags to all three of these terms (TC/TCN/TL).

1) I've added the info from Reut's annotation about "stuf" to the glossary. Please clean up the entry as you see fit. I've placed the following editorial comment in the DCE after the single instance of the term: german variant of "stüf," a kind of granular limestone, or tufa.

2) the "spat" and "spalt" entries could use some clean up too. I would like to have a pithy translation/explanation for each that I can use for their editorial comment. Please reply with ideas or decisions.

**Comment by ps2270** [comment]
A pertinent question here is whether we tag these terms as definitely another language when we are not absolutely sure that they are. An editorial note, without German tags, and an entry in the glossary, would be an alternative solution.  What do you think?

**Comment by ps2270** [comment]
I cleaned up glossary entries for Stuf, Spat, and Spalt. 
Should we leave passages in the glossary in languages other than English untranslated?

**Comment by thuchacz** [comment]
To your question about omitting German tags:
Well, this will be a flip-flop on our earlier decision that came in response to a problem you raised about the need to tag German terms. If we're not sure than ANY of these (stuf, spat, spalt) are German, then we've wasted a bit of time/effort here. In any case, most of these were not marked up as "fr" in the TL either, so we do need to do something either way since they're not English terms.

Pro to using `<ge>` tags: it shows the A-P may have been conversant with German artisanal terms
Con to `<ge>` tags: these words may not be German. Well, if they're French, we can't prove that either, and I think Reut's "stüf(e)" dictionary find is pretty compelling.

**Comment by ps2270** [comment]
Yes, I agree that there is compelling evidence for these being German, but I meant are we absolutely certain, as we are certain that some of the passages are Italian or Latin? No, we aren't, b/c these are isolated words.  And, in the "ana" case, it seems rather far-fetched that Greek became a solution, although I don't know Greek, but it seems a weak case.
Anyway, I think in the case of Spat, Spalt, and Stuf, we can tag them as German, as you did, with an ed comment and a glossary entry.
Pithy entry for Spat and Spalt: an earth, apparently from around Augsburg in Germany, used in making molds.

**Comment by thuchacz** [comment]
Yeah. I get what you're saying about the uncertainty. I'll flag that uncertainty it in the editorial comments—and thank you for working up the pithy entry

**Comment by thuchacz** [comment]
first instance of spat and/or spalt on each folio got the following comment:
Spat / spalt is likely a German word referring to an earth, apparently from around Augsburg in Germany, used in making molds

**Comment by TillmannTaape** [comment]
Reopening because this is still not clear in the glossary. Are spat and spalt synonymous?

NB in the TL on 108r "spat" is translated "spalt" – there is no rationale for this in the current glossary entries.

@ps2270 please review

**Comment by ps2270** [comment]
I don't see "spat" translated "spalt" on 108r. If I missed where it is, it should in any case be changed.

For glossary, they seem to mean the same thing, altho' we are not sure about that. They should be entered separately in the glossary.
@TillmannTaape can you please enter in glossary and check to see if I missed it on 108r?

**Comment by TillmannTaape** [comment]
I'm talking about the beginning of the third paragraph. It is actually correct in github, but in the edition it shows up as 'spalt' which is is odd.

I've updated the glossary as best I can, with all due diffidence, but I'll keep the issue open until we've figured out why it still says "spalt" where it should say "spat" on 108r in the edition.

**Comment by ps2270** [comment]
In the edition on my screen it says "spat"!  Did you try refreshing?
Thanks,
P

**Comment by TillmannTaape** [comment]
Ah it's spat in the staging but spalt in the stable, which is perhaps less of a problem.
