### ISSUE TITLE
translation (?) of "aloé"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#596]
**2 instances of "aloé" in the TCN:**

on 57r, it has been translated as "aloe":
```
<m>White varnish of <m>turpentine</m> or of <m><pa>spike lavender</pa>
oil</m> and <m>turpentine</m></m> is colored with <m>pulverized
<fr>terra emerita</fr></m>, making it boil together. It gives agold
color on <m>silver</m> and more beautiful if it is burnished. It is dry
in <tmp>a quarter of an hour</tmp>. <pa><m>Aloe</m><pa> would make brighter
color, but it takes long to dry &amp; the other is dry in <tmp>a quarter
of an hour</tmp>, <tmp>in winter</tmp> as well as
<tmp>summer</tmp>.</ab>
```
on 149v, it has been left in `<fr>` tags:
```
<id>p149v_2</id>
<head><m>Gold</m> <m>solder</m></head>

<ab>They take, on a <cn><m>gold</m> <fr>denier</fr></cn>, a
<ms><fr>grain</fr></ms> of the <m>fine <fr>aloé</fr></m>, like <cn>old
<fr>douzains</fr></cn> are.</ab>
```

Here's our glossary entry:
Aloé, aloy, alloy (m.) = Leave in Fr.; Cotgrave: The allay of gold, or silver, coyne; the (mixed) matter, or mettal whereof it is made; also, fine bell-mettall. See 149v where the author refers to a "grain d'aloé" like that in sous (gold coins). (MBR SM)

@ps2270 
Is there anything to make consistent here? Or are these two very different materials? We don't have an entry for "aloe" in the sense of aloe vera in the glossary, but it is one of the definitions given by Cotgrave.

**Comment by ps2270** [comment]
@TillmannTaape 
Please translate
aloe on 149v as alloy

**Comment by ps2270** [comment]
PHS changed the glossary entry

**Comment by thuchacz** [comment]
THU changed the translation on 149v to "alloy"

**Comment by ps2270** [comment]
@TillmannTaape .  Please add to the glossary that aloe can also denote a type a plant.
Then close this issue, please.

**Comment by TillmannTaape** [comment]
Wherever those alternate spellings come from, they're not in the ms, so I deleted them. I've added the second meaning as: aloe (a group of plants secreting bitter juice used in medicine; may also refer to the juice itself). From the OED it looks like it's roughly the same family as Aloe vera etc., although Cotgrave's "houseleeke" is now in a different genus, Sempervivum.
