### ISSUE TITLE
inconsistent apostrophes: important for searching and grouping tagged contents

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#598]
In trying to make sure that all instances of "esmail d'azur" and "azur d'esmail" were within `<fr>` tags, I hit a bug.

Some instances of the string had been input (in the Google Docs?) using a flat apostrophe (**'**) and some with a smart (curly) apostrophe (**’**). Searching for one in Oxygen does not render instances of the other. In the end, I changed them all to the smart/curly one, just so I could be sure that I had consistent instances of the French strings in the TCN and TL.

We need a dedicated search to replace one for the other across the TCN and the TL. But which would we prefer to use?

***Also, anyone who has been working on a consistency issue that involves apostrophes should be aware that they may have missed terms in their work.

@ps2270 @TillmannTaape @Pantagrueliste @njr2128

**Comment by TillmannTaape** [comment]
Thanks Tianna! I don't think any of my search strings involved apostrophes.

For searching purposes, the TC is your friend since it doesn't have them, but I agree we should consistify which apostrophe we use in the TCN.

**Comment by tcatapano** [comment]
Please convert any curly single or double quotes to their low ascii equivalent (i.e., ' and ")

**Comment by thuchacz** [comment]
@Pantagrueliste I'm assigning this to you, Clément. It will be your favourite—a search and replace. But you'll have to locate the low ASCII characters, and find a way to catch the curly punctuation.

**Comment by tcatapano** [comment]
The characters for the replacement apostrophe and double quote are located easily. They should be the ones on your keyboard.

U+0027:
```
'
```

U+0022:
```
"
```

**Comment by Pantagrueliste** [comment]
Do the opposite (form curly to straight) but wait for the end to do so.

**Comment by njr2128** [comment]
@Pantagrueliste will do this search/replace campaign now

Then it will need to be done again closer to launch to make sure we have not introduced any more curly quotes, apostrophes

**Comment by njr2128** [comment]
@njr2128 to do another campaign soon, and then leave this issue open as this needs to be done any time there are significant changes to the xml in case errors are introduced

**Comment by Pantagrueliste** [comment]
Done: see pull request #1862
