### ISSUE TITLE
terre cendrée

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#603]
@TillmannTaape 
I want to translate "terre cendrée" as "ashed earth," largely to make sure that anyone looking in the glossary doesn't confuse "`<fr>`cendrée`</fr>` earth" with the entry for "cendrée," which does not apply here. The fact that the A-P picks up the thread of ashes in the very next `<ab>` seems to support my proposed translation.

70r:
```
<ab>La <m>terre cendrée</m> moule fort net.</ab>
<ab>La <m>cendre</m> n'ha pas assés de corps pour soubstenir le<lb/>
<m>cuivre</m>.</ab>

<ab><m><fr>Cendrée</fr> earth</m> molds very neatly.</ab>
<ab><m>Ashes</m> do not have enough body to withstand
<m>copper</m>.</ab>
```
Cendrée in the glossary:
- Cendrée (f.) = 40v_3 keep Fr. Here it refers to a separation of a tin alloy, likely referring to a method of melting and purifying metals in ashes (see Cotgrave).
Editorial note: Cendrée here likely refers to a method of melting and purifying metals in ashes (see Cotgrave).

**Comment by TillmannTaape** [comment]
I'm slightly hesitant to translate terre cendrée. There are many different uses of cendres/cendrée in  the ms, and it's hard to know what he's referring to here.

Speaking of which, looking for cenrdree in the glossary, I saw the following note by @ps2270 under the cendree d'azur entry:
"Both the calcine chalk and charcoal that crucibles are made of, and shop sweepings (dross etc) in a goldsmith’s shop and it is purified by this method. (PHS)."
I assume that this is in the wrong place and belongs with the entry on cendree above – Please could you check?

**Comment by TillmannTaape** [comment]
I'd say `<fr>cendrée</fr> earth` as per my suggestions in #602

**Comment by ps2270** [comment]
I've moved the comment to the correct entry for cendree.
 and I approve of the `<fr>cendrée</fr> earth`

**Comment by thuchacz** [comment]
TL = <fr>cendrée</fr> earth
PHS fixed glossary
