### ISSUE TITLE
à destrempe

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#605]
This has been translated (and marked up) VERY inconsistently.

"in distemper" (e.g., 32r_3)
"in <m>distemper</m>" (e.g., 32r_2)
"damp" (e.g., 9v_1)
"<fr>à destrempe</fr>" (e.g., 11r_1)

**SCOPE OF WORK**
1) find all instances. 
NB: I have had a hard time finding "à destrempe" as a string, because of line breaks and I think the accent character, which may be throwing up similar problems to the apostrophe problem.
2) assess range of meanings
3) decide on a translation protocol and make a glossary entry that is either specific to this string or several that are nested under other appropriate glossary headings
4) change translation in TL and assure markup is consistent across TC/TCN/TL

@ps2270 Please weigh in.
I have assigned this issue to Tillmann. 
@TillmannTaape If you are too swamped, pass along to CAG.

**Comment by thuchacz** [comment]
Also, on 43r, there is a complicated string:
```
Il fault donner quattre couches de <m>colle</m> à destrempe des<lb/>
<pro>painctres</pro> sur le portraict de <m>plastre</m>

<ab>One needs to give four layers of <pro>painters</pro>' <m>glue</m> in
distemper on the <m>plaster</m> portrait,
```
I wanted to find a "colle à destrempe" in here, but it has been translated differently. What do you think? For what it's worth, we do have a "colle à destrempe" on 66r (as opposed to "colle de destrempe" which we find slightly more commonly, i.e., on 3v and 60r) that has been left in French as a material

**Comment by TillmannTaape** [comment]
"painters' colle a destrempe" would work if we want to leave it in French as on 66r.
