### ISSUE TITLE
Editorial comments to be made

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#614]
Found from PW18 meeting notes:

Fol. 170r - sideways margin
Fol. 170v - upside down page (this commentary has to be nested at the level of the folio, not the entries)

**Comment by thuchacz** [comment]
Fol. 170r - sideways margin  
   **this is already indicated with c_170r_01**

Fol. 170v - upside down page (this commentary has to be nested at the level of the folio, not the entries) 
   **this is already indicated with c_170v_12; also, we can't have comments outside of ABs or HEADs**
