### ISSUE TITLE
Thumbnail Images

### ISSUE THREAD

**Issue by caro27** [cu-mkp/m-k-manuscript-data#617]
CMS creating annotation [thumbnail meta-data table](https://docs.google.com/spreadsheets/d/1xSqGL-8d5QNvGtDSE6bIogeKu5NAw_bbJN6OK-8q9zc/edit#gid=0). Will photos be automatically cropped and the orientation standardize? Or should I be cropping to the desired object ratio? What image would we like to use for annotations without images?

**Comment by caro27** [comment]
People have been assigned just to get their opinions/input on this matter! No need to do anything now.

**Comment by caro27** [comment]
@NickLaiacona - annotation thumbnails have all been cropped and stored in a folder [thumbnail folder](https://drive.google.com/drive/folders/1bXb-QumwBh94O6g72f2i-EQFXlS7QCpg). Let me know if you need anything else! 

@njr2128 - do you think I should run these by Pamela and the editorial team?

**Comment by njr2128** [comment]
Choices are great, and Nick is moving forward with integration in https://github.com/cu-mkp/making-knowing-edition/issues/210
