### ISSUE TITLE
Coquille

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#621]
Usually, translated as "shell"
Glossary says: 
Coquille (f.) = keep Fr., i.e. a measure containing five spoonfuls (Cotgrave)
**1. Glossary needs updating with usual translation**

**PROBLEM**
There is only ONE instance where "coquille" has been left in French: 075v
NB: other instances where "coquille" has been tagged as a measurement are more precise, describing a "coquille de noix"
```
<id>p075v_3</id>
<head>Pour <m>dorer</m> d’<m>or moleu</m></head>
<ab>Fault prandre une <ms>coquille</ms> d’<m>or</m> et, auparavant
q<exp>ue</exp> en vouldrés<lb/>
travailher, vous la mectrés tramper avecq de l’<m>eaue de gome</m>

<head>For <m>gilding</m> with <m><fr>or moulu</fr></m></head>
<ab>One needs to take a
<ms><fr>coquille</fr><comment>c_075v_02</comment></ms> of <m>gold</m>
and, before you want to work with it, you will soak it with <m>gum water</m>
```

The comment attached to this instance reads as follows:
"JKR: ""a measure containing five spoonfuls"" (Cotgrave)
JB: see entry ""or on coquille"" = gold ground into microscopic particles from pulverised gold leafs, ground in a mortar with honey or gum water in: Bernard Guineau, Glossaire des matériaux de la couleur et des termes techniques employés dans les recettes de couleurs anciennes, Brepols, 2005. p. 519"

**BUT...** On the previous page (075r), there is a recipe to prepare "or moulu" that ends by having you store it in a "coquille":
```
<id>p075r_5</id>
<head><m>Or moulu</m></head>
<ab>Prenés <m>fin or</m> &amp; le mectés sur le <del>bu</del>
<tl><m>marbre</m></tl> bien nect, &amp; mectés<lb/>
de l'<m>eaue fort</m> &amp; commancés à broyer. Puys prenés du
<m>selpestre</m> &amp;<lb/>
du <m>sel armonial</m> et le mectés en une <tl>coquille</tl>
q<exp>ui</exp> soit grande &amp; lavée,<lb/>
comme assuré.</ab>

[...]
Then take <m>saltpetre</m> &amp; <m>sal
ammoniac</m>, and put it into a <tl>shell</tl> which should be large
&amp; washed, to safeguard it.

```

THU: I don't think this is as complicated as it looks. I THINK WE SHOULD TRANSLATE AS: "shell of <fr>or moleu</fr>" and perhaps have an editorial comment that points back to the recipe on 075r

**Additional question...** what should the glossary entry actually look like? Is there any need for this Cotgrave spoonfuls thing? Or the info that JB included in the editorial comment?

**Comment by ps2270** [comment]
I approve of translating as shell in all instances, with an editorial comment on 75v that points back to 75r, as you suggest.  Can you please do this, @thuchacz ?  
Glossary entry (@TillmannTaape , please do this) should be:
 Coquille (f.) = shell, and, cf. Cotgrave, a measure containing five spoonfuls. And, "or on  [phs: en?] coquille"" is gold ground into microscopic particles from pulverised gold leafs, ground in a mortar with honey or gum water, see Bernard Guineau, _Glossaire des matériaux de la couleur et des termes techniques employés dans les recettes de couleurs anciennes_, Brepols, 2005. p. 519.

Do we need editorial comments making clear the use of coquille as a measurement in each instance, or not?

**Comment by thuchacz** [comment]
No need for measurement clarifications since those instances have "ms" tags.

**Comment by thuchacz** [comment]
And yes—I'll make that change to the TL and the comment tracking sheet now.

**Comment by thuchacz** [comment]
@TillmannTaape  Could you update the glossary and close out?

**Comment by TillmannTaape** [comment]
Updated the glossary. @Pantagrueliste can you please make sure that we have Guineau in the bibliography, and create a citation ID and insert it in the reference column?

**Comment by thuchacz** [comment]
CAG did this
