### ISSUE TITLE
Cristallin

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#624]
Glossary entry:
Cristallin (m.) = keep Fr.
But PHS says it means cristallo glass, like that made in Murano, i.e. clear glass. GC/HW. Fol. 68r, 06/23/2016.

There are 8 instance in the Ms, of which only FOUR have been given `<fr>` tags:
57r, 58r, 64r, 65r, 65v, 68r (x2), 99v

Consider this excerpt from 68r—does it help define "cristallin"?:
```
Le <m>verre <tl>pilé</tl></m> se peult faire en <m>sable de verre commun, touteffois<lb/>
le cristallin</m> est plus excellent, car le commun ne tient que du
<del><m>verre</m></del><lb/>
<m>sel de salicor</m>, mays le <m>cristallin</m> tient du <m>sel de
tartre</m> &amp; de <m>salicor</m><lb/>
tout ensemble,

<m><tl>Pestled</tl> glass</m> can be made from <m>common <m>glass sand</m>, however cristallin</m> is more excellent, for <m>common glass</m> contains
<del><m>glass</m></del> <m>salt of saltwort</m> only, but <m>cristallin</m> contains both <m>salt of tartar</m> &amp; <m>saltwort</m> all together,
```

**How to treat these?? All "keep in fr"? or translate as cristallo glass?**

**Comment by ps2270** [comment]
Translate as cristallo glass. 
See the following article, which we should probably add as an annotation on 68r.  Cristallo glass has a lower iron content because the ashes used to make glass were purified of their iron content.
[Spring, Marika, glass in paintings_2012.pdf] (https://github.com/cu-mkp/m-k-manuscript-data/files/3209184/Spring.Marika.glass.in.paintings_2012.pdf)

**Comment by thuchacz** [comment]
Snag: "cristallo" is an Italian word. Not in the OED. The English equivalent (see OED; also Spring PDF) is "crystal glass."
@ps2270 Would this be okay? 
@TillmannTaape If so, can you update the glossary?

**Comment by ps2270** [comment]
Thanks for finding that!  Yes, substitute "crystal glass" and @TillmannTaape please update the glossary.
Thanks!

**Comment by thuchacz** [comment]
TL is updated. @TillmannTaape, you can close this issue once you update the glossary.

**Comment by TillmannTaape** [comment]
Glossary updated.

**Comment by Pantagrueliste** [comment]
From WGM2019 consolidated points: 

> ACCEPTED: cristallin (leave as original, as this could be imported crystal from Venice, or it could be a general term for “nice glass” or vitrum blanchum - basically - white and clear - if it’s white, it has manganese and can be a drier.
