### ISSUE TITLE
Sel de Langlois de armonic

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#625]
**This excerpt is inconsistently marked up across the three versions:**

TC
```
Le <m>sel appelle de <pl>langlois</pl> de armonic</m> est <m>sel
mineral</m> qui semble <m>pierre de<lb/>
mabre</m>...
```

TCN
```
Le <m>sel appellé de <pl>Langlois</pl> de armonic</m> est <m>sel
mineral</m> qui semble <m>pierre de<lb/>
mabre</m>...
```

TL
```
The <m>salt called <df><fr>de
Langlois de armonic</fr></df></m> is a <m>mineral salt</m> that
resembles <m>marble stone</m>...
```

**PROBLEMS**
1) should Langlois have `<pl>` tags (NB: only 2/3 versions have them now)
2) should the TL `<fr>` string be: "**de** Langlois de armonic" (as it is now) or "Langlois de armonic"?
3) I will extend the `<df>` tags to all three versions (only in TL now)
4) Glossary entry needs updating:
Sel de Langlois (m.) (U) = keep in Fr., i.e. ?
Should this be "Sel de Langlois de armonic"??

**Comment by TillmannTaape** [comment]
To complicate this further, have we actually identified Langlois (which the TL so confidently capitalises) as a place name? I can't find one. 

Instead, perhaps it means "de l'anglois" i.e. "by the Englishman" or "by the English language". I've looked for all kinds of variant spellings of "armonic" and "armonie" in conjunction with salt but drawn a blank.

@ps2270 @Pantagrueliste Any ideas?

**Comment by thuchacz** [comment]
do you think it's a mistype "sel armoniac" of the English?

**Comment by TillmannTaape** [comment]
Very possibly. Or perhaps "armoric" as in Armorica.

**Comment by ps2270** [comment]
Could it plausibly be translated as "called by the Englishman"?  
If so then, can we agree to translate as:
`The <m>salt called by the Englishman [or English???] <df><fr>de armonic</fr></df></m> is a <m>mineral salt</m> that resembles <m>marble stone</m>...`

As for marking up:
Is Englishman a profession or a place?

Glossary entry should define "Sel de armonic"

Is that all clear?

**Comment by TillmannTaape** [comment]
Yes, we're going with "by the English".
