### ISSUE TITLE
125r add <hr> to simulate boxed text

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#629]
At the top of the 125r, there is text that has been boxed off.
Solution for rendering this now is to insert `<hr/>` before and after the the block of text in the box.

Determine best placement and where in the text block the 2 `<hr/>`s should go and insert

**Comment by njr2128** [comment]
CONFIRMED: two `<hr>`s is the best solution for now (after consulting with digital team again)

**Comment by thuchacz** [comment]
done
