### ISSUE TITLE
66r "or mat" entries markup and render

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#630]
In 2017, JBB created a mockup markup document that suggests text block relations and markup suggestions.

Find the doc (likely in the 66r ms pages folder OR in the Or Mat annotation folder) and consult. Implement any necessary changes.

**Comment by ps2270** [comment]
Here is the suggested markup revision: https://docs.google.com/document/d/1do8wjDuFA97X46QTPmX8rikf47SonbiMLrq8uNey6C8/edit

See the annotation folder for Or Mat: https://drive.google.com/drive/folders/0BwJi-u8sfkVDNzhfV3dVSEpyaGM
