### ISSUE TITLE
Doulce

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#631]
**PROBLEM 1**
On 140r (a continuation of 139v's "Cast of wax to represent an animal that one has not
got"), we find the ONLY untranslated instance of "doulce," as opposed to "doux:"

```
But it is good to soak it one <ms><tmp>night</tmp></ms> or one
<ms><tmp>day</tmp></ms> before casting in it, in order that it be well
imbibed. The same must be done for fruits of <m>sugar</m>. This <m>wax</m> is very
<fr>doulce</fr> &amp; amiable &amp; pliant as <m>copper</m>, and if it is strong 
because of the <m>sulfur</m>, which renders it melted
```
**PROBLEM 2**
If "doulce" is distinct from "doux," we should note that. There is no definition of "doulce" in the glossary, though it and its derivatives (e.g., doulcement, doulces, doulceur) have all been translated.

**Thoughts?** Can this be "soft" or "malleable"? Or should we walk back all the other "doulce" instances and keep them in French?

**(unrelated) PROBLEM 3**
Also, what about this translation (which includes a "doulce") from 12r_2 that describes "terre chimolée:"
```
TCN: Elle est fort<lb/> doulce, nette &amp; belle.
TL: It is very malleable, clean &amp; fine.
```
Since neither "belle" nor "beau" is in the glossary, I'm curious—what was the policy? I would have assumed it be translated as "beautiful."

**Comment by ps2270** [comment]
Decision:
Problem 1  on 140r: translate doulce as soft

Problem 3 on 12r: this translation needs to be changed:
& la recuire a feu doulx de loing
ISN'T this better translated as
  & reheat it on a gentle, indirect fire, 
[now it is &reheat it gently on a low, indirect fire"

Elle est fort
doulce nette & belle 
Translate as: "it is very soft, neat, and beautiful"

**Comment by thuchacz** [comment]
@ps2270  As with Doulx — hold off on all of these doux-related decisions. I am in the middle of making you a GIANT doux table with all of the instances. There is much inconsistency.
