### ISSUE TITLE
Adoulcir as "make <fr>doulx</fr>"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#632]
I don't like the translation below.
Glossary says:
Adoulcir (mod. adoucir) = “to soften”; also “to sweeten”, of metals. 

**If we've said that "adoulcir" is "to sweeten" in metals, then can we simply use "adoulcir" instead of "make doulx"?**

```
<id>p153v_2</id>
<head>Adoulcir l’<m>or</m></head>
<ab>Quelquefois il y ha de l’<m>or</m> si sec qu<del>’il</del>e le <m>ciment</m><lb/>
ne <m>antymoine</m> ne le peuvent adoulcir. Mays le seul<lb/>
<m>verdet</m> le rend doulx.</ab>

<head>Making <m>gold</m> <fr>doux</fr></head>
<ab>Sometimes, there is <m>gold</m> so dry <del>it</del> that neither
<m>cement</m> nor <m>antimony</m> can make it <fr>doux</fr>. Only
<m>verdet</m> can render it <fr>doulx</fr>.</ab>
```

**Comment by ps2270** [comment]
DECISION: Change translation as below.  [I could see the logic of "sweeten" here--what do you think @TillmannTaape ??
`<id>p153v_2</id>
<head>Adoulcir l’<m>or</m></head>
<ab>Quelquefois il y ha de l’<m>or</m> si sec qu<del>’il</del>e le <m>ciment</m><lb/>
ne <m>antymoine</m> ne le peuvent adoulcir. Mays le seul<lb/>
<m>verdet</m> le rend doulx.</ab>

<head>Softening <m>gold</m></head>
<ab>Sometimes, there is <m>gold</m> so dry <del>it</del> that neither
<m>cement</m> nor <m>antimony</m> can soften it. Only
<m>verdet</m> can render it soft.</ab>`

**Comment by TillmannTaape** [comment]
I like "sweeten", but I think "soften" is much clearer and more intuitive here for the uninitiated reader. Let's see what Tianna's giant "doulx" spreadsheet tells us and decide on that basis if we can have a consistent translation of doux-related words.

**Comment by ps2270** [comment]
Here is a similar puzzle for you:
53r:
Cuivre
Si au fœu & a la fonte il touche le fer Ce fer sera apres
si aigre quil ne se pourra forger 

We have translated as 
If, in the fire &melting, it touches the iron, this iron will be so brittle afterwards that it cannot be forged.

But I could imagine translating aigre as sour here also.

**Comment by ps2270** [comment]
Probably the translation should also be revised to read:
If, in the fire _& in the melt,_ it touches the iron, this iron will be so brittle [sour?] afterwards that it cannot be forged.
