### ISSUE TITLE
Douls

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#633]
19 instances of "douls" in the TCN.
The first instance and the last 5 instances of "douls" in the manuscript have been left in French. The first 14 have been translated, mostly as "soft," from what I can tell.

Some of those 14 clearly need to be in `<fr>` tags, such as:
"estaing douls" on 84v = "soft tin"

**SCOPE OF WORK:**
PHS or TT to go through 13 instances of "douls" in TCN and decide which need tags:
28v (x2), 30r, 37r, 38r, 63r, 65r, 68v, 69v, 71r, 84v, 108v, 119v

**Comment by ps2270** [comment]
All of these seem to have been changed to soft already 
DECISION: 84v change to soft

**Comment by thuchacz** [comment]
Wait a minute (or overnight). I'm in the middle of compiling a GIANT doux/doulx/doulce table for you.
