### ISSUE TITLE
Doulx

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#634]
There are 48 instances of "doulx" in the TCN
There are only 18 instances that have been left in French in the TL; everything else was translated.

What do you want to do here, @ps2270?

My preference would be for you to go through all of these, just like with the 19 "douls" to see which others might need FR tags. I could make you a THU-style word table, if you want.

**Comment by ps2270** [comment]
Yes, please do make me a table and I'll go through them. Thanks!
