### ISSUE TITLE
Dragée

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#635]
Normally, we translate this as "hail shot" — thanks to Cotgrave, Jonathan, and Pascal.

BUT... there is an instance of "dragée" on 53v in the "silkworms" recipe:

```
Willingly they begin to unskin themselves <tmp>around holy week</tmp>. And to do
this, one puts them in a <tl><pa>fir</pa> box</tl>, like those where one
puts <fr>dragée</fr>, warmly among <tl>feather cushions</tl>.
```

Why is this also not "hail shot"? Would hail shot NOT be kept in fir boxes? This question might need outsourcing or additional DMF / Google research to see if "dragée" could refer to anything else.

**Comment by TillmannTaape** [comment]
Cotgrave also has digestive powder, or more generally "sweetmeats" – I think this is perhaps more likely here. Suggestion: translate "sweetmeats".

**Comment by thuchacz** [comment]
@ps2270  What do you think?

**Comment by ps2270** [comment]
I'm not sure how we can decide between sweetmeats and hail shot. We do not know what was kept in fir boxes, however, I see that DMF has friandise (normally eaten at dessert) which is an obsolete English word meaning dainties or delicacies.  So, I guess sweetmeats it is.
DECISION: translate in this instance as sweetmeats

**Comment by TillmannTaape** [comment]
Done.
