### ISSUE TITLE
(eau) magistra

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#636]
Glossary says:
- Eau magistra, see: Magistra. 
- Magistra, magistre (f.), eau magistra (f.) = “magistry” (or keep French?) - PHS 06/05/16: decide 2016), i.e. a liquid used to bind the sand in sand molding. See also: Orme. On 84v, 87v, one possible recipe for it. 

5 instances of "magistra" in TL (no fr tags): 68r, 69r (x2), 69v, 87v
2 instances of "eau magistra" in TL (with fr tags): 84r, 84v

Despite glossary, NO INSTANCES of "magistry" in the TL.

@ps2270 Glossary needs a decision here and these 7 occurrences need updates for consistency.

**Comment by ps2270** [comment]
OED does not have magistry (at least to mean this), so I think we should keep both magistra and eau magistra in French.
Glossary should read:
Eau magistra, see: Magistra.
Magistra, magistre (f.), eau magistra (f.) = a liquid binder used in sand molding

**Comment by TillmannTaape** [comment]
Transferred to glossary.
--

Dr. Tillmann Taape

Lecturer in History
Postdoctoral Scholar, The Making and Knowing Project

Book reviews editor, Ambix

Columbia University
Center for Science and Society
511 Fayerweather Hall, MC 2509
1180 Amsterdam Avenue
New York, NY 10027

tillmann.taape@cantab.net

**Comment by thuchacz** [comment]
all instances of "magistra" and "eau magistra" in TL in `<fr>` tags.

Closing.
