### ISSUE TITLE
grille

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#637]
13 instances in TCN of "grille." Cursory glance suggests problems with consistent translation and markup.

Glossary says:
Grille = “grate” (in a furnace or similar). See Cotgrave.
Grille [referring to an ingot] = keep Fr., i.e. a shape or form (?) in which tin is melted in order to be easily separated and sold later. 
f. 28v, 48v, 92r.
	editorial note: “this is likely a smaller type of ingot than the 'saumon', and more convenient to sell. See eg. Dictionnaire universel de Commerce (1742), which likens "grile" to "saumon", although to the AP these are clearly different (on fol. 28v).”

**TO DO:** 
1) go through all 13 instances and decide if TL should be "grate" or "`<fr>`grille`</fr>`"
2) if "grate" then also give `<tl></tl>` tags. If "`<fr>`grille`</fr>`", should this get a measurement tag? It's an ingot size...

**Comment by ps2270** [comment]
I don't think it should get a measurement tag, as we are not sure whether the a-p is using it to mean a particular size of ingot, right?

**Comment by thuchacz** [comment]
All consistified except for the following:

**83v_3**
```
<ab>To melt with <tl>bellows</tl>, &amp; hasten your melt,
&amp; also cast hotter <del><fr>po</fr></del>, do not place your
<tl>bellows</tl> at the bottom near the foot of the <tl>furnace</tl>,
for fear that some <m>charcoal</m> might <del>you</del> enter it, put
them almost under the <tl><fr>grille</fr></tl>. It is good that your
<tl><fr>four à vent</fr></tl> be in an <env>aerated place</env> so that the
<env>wind</env> might make it heat better,
```
```
Pour fondre à <tl>souflets</tl> &amp;<lb/>
advancer ta fonte &amp; gecter
aussy plus chault<lb/>
<del>po</del> ne pose pas tes<lb/>
<tl>souflets</tl> bas vers<lb/>
le pied du <tl>fourneau</tl>,<lb/>
de peur que quelque<lb/>
<m>charbon</m> n’y <del>tu</del> entre,<lb/>
mets les presque<lb/>
dessoubs la <tl>grille</tl>.<lb/>
Il est bon que ton<lb/>
<tl>four à vent</tl> soit<lb/>
<env>en lieu airé</env>,
```
@ps2270 @TillmannTaape  When we translated this entry on bellows, did we decide that the "grille" here was a grate in the furnace or the "grille" kind of ingot? If the former, I will translate. If the latter, I will remove the `<tl>` tags

**Comment by TillmannTaape** [comment]
I think definitely the grate (keeping the bellows just below the grate rather than on the bottom of the furnace seems to make sense that way).

**Comment by ps2270** [comment]
Decision: translate as grate.

**Comment by TillmannTaape** [comment]
Done.
