### ISSUE TITLE
Eau de roche

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#639]
Glossary says keep in Fr. but it is currently translated "rock water". I think that's fine but I'd need to change it in the glossary.

@thuchacz have you come across it in your keep in Fr campaign?
@ps2270 what do you think?

**Comment by thuchacz** [comment]
There is no "eau de roche" in the FR consistency table (and a quick search
for "roch" in the TL turns up only "Rochelle"). So, "rock water" it is.

**Comment by ps2270** [comment]
Tillmann and I looked at this and decided to leave it as "rock water" on 11r.
