### ISSUE TITLE
Eau de ...

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#641]
The glossary still has

Eau de… (f.) = “essence of …”, i.e. a distillation
Use this unless English has a better expression, according to material (see below).

which is not right and in fact has not been done in the TL (the only instances of "essence" in TL correspond to "essence" in French). 
@thuchacz did you do this as part of #114? And have instances of "eau de ..." been treated as per the glossary?

I still don't see why we make a distinction between distilled waters and other waters, as in water **of** sal ammoniac, when we have gum water, starch water, etc.

**Comment by thuchacz** [comment]
There were an instance or two of "essences" in #114. You and I got rid of
them together. @pantagrueliste was meant to address the "sal ammoniac
water" inconsistency in another issue. I think he changed them all AWAY
from "water of sal ammoniac" TO "sal ammoniac water" per PHS. So, if
there's nothing left of this "essence of" = "eau de", then remove it from
the glossary.

**Comment by TillmannTaape** [comment]
Thank you, I will change the glossary accordingly.

**Comment by ps2270** [comment]
Yes, change the glossary.  Thanks.

**Comment by TillmannTaape** [comment]
Done.
--

Dr. Tillmann Taape

Lecturer in History
Postdoctoral Scholar, The Making and Knowing Project

Book reviews editor, Ambix

Columbia University
Center for Science and Society
511 Fayerweather Hall, MC 2509
1180 Amsterdam Avenue
New York, NY 10027

tillmann.taape@cantab.net
