### ISSUE TITLE
rub and caption and man as part of entry index

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#642]
There has been inconsistent use of `<man>`s, `<rub>`s, and `<captions>`, particularly in their relation to entries.

In creating an index of entries, should these be included?
Decision from #12 is that `<man>`s should not.
Need decision for `<rub>`s and `<captions>`.

@tcatapano, can you pull a list of all `<rub>`s and `<captions>` with their folio occurrences? 
 THEN, M&K team go through this list and decide if they are correctly assigned these designation or if they should not instead be entries (rather than `<rub>`s and `<captions>`).

Then decide whether `<rub>`s and `<captions>` should be listed in the entries page   somehow anyway?

**Comment by njr2128** [comment]
Once decisions have been made, the following from issue #12 should be either removed from Index Tracking, or Index Tracking should be updated with additional rubs and captions:

Div ID | Folio # | Entry title transcription
-- | -- | --
rub | p108v | Lardille
rub | p108v | Alum de plume
rub - marginal note instead? | p028v | Va au cinquiesme foeillet
caption - listed in entry list? | p026r | Balle de canon
caption - listed in entry list? | p026v | Balle de couleuvrine
caption - listed in entry list? | p027r | Balle de bastarde
caption - listed in entry list? | p027r | Balle de moyene
caption - listed in entry list? | p027r | Piece de campagne
caption - listed in entry list? | p027v | Faulconeau
caption - listed in entry list? | p027v | Faulconeau de 4 quintals autrement passevolants tire 8 pans
caption - listed in entry list? | p027v | 3 quintals tire de long 9 pans
caption - listed in entry list? | p027v | 2 quintals tire de long une cane qui sont 8 pans de monpelier
caption - listed in entry list? | p027v | 1 quintal tire six pans et demy
caption - listed in entry list? | p027v | 1 quintal et demy tire 7 pans et demy
caption - listed in entry list? | p027v | mousquet de 60 livres tire 5 pans de long ou 6
caption - listed in entry list? | p027v | 5 quintals tire onze pans et demy

**Comment by tcatapano** [comment]
see https://docs.google.com/spreadsheets/d/1ugPegKCc4wwnsaNysgP3oTPA_SW-PeRewJfCgbC87eY/edit?usp=sharing

for lists of rub and caption occurrences by folio

**Comment by njr2128** [comment]
DEFINITIONS:
>Manchette: a word or phrase in the margin, usually in italic script, that indicates something in the text block. It is not a heading (although sometimes it looks like it), but rather explains something in the text block, e.g., within “Pierrerie,” there is a in the margin that indicates where he mentions “Esmeraulde.”

and
>Rubric: A word or phrase in italic script in the body of the text that is not a new div, heading, or or `<ab>`

**Comment by njr2128** [comment]
DECISIONS have been recorded in rub+caption+man_occurrences (https://docs.google.com/spreadsheets/d/1ugPegKCc4wwnsaNysgP3oTPA_SW-PeRewJfCgbC87eY/edit?usp=sharing).

man and rub to be eliminated (see #719), markup to be updated - if not already - according to decisions in spreadsheet.
