### ISSUE TITLE
Editorial comment for "Secret" on 125r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#644]
create editorial comment: This is in the same script and centered location on the page as the headers, but has no entry content underneath it. It is unclear what it is referring to. Could be to the entry before "hearing from afar", "plaster", the marginal note about plaster/casting, or the entry on the next page about snakes (which has its own title). Could be heading for entry that never got written.

**Comment by thuchacz** [comment]
Done
