### ISSUE TITLE
foeu de fusion

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#645]
We have translated "fusion" as either "fusion" or "casting," depending on context.
However, on 108v (a continuation of "Spalt" on 108r), there is the following excerpt:

Cela<lb/> <corr>s</corr>e fait ou dans la <tl>forge des <pro>orfevres</pro></tl>,
dans un <tl>countour de<lb/>
<m>briques</m></tl>, ou dans un <tl>fourneau à vent</tl> à **fœu de fusion**, de sorte<lb/>
que le <del><m>sable</m> demeure <tmp>assés long temps</tmp></del>
<add><tl>creusel</tl> demeure un <ms><tmp>quart dheure</tmp></ms></add> rouge.

This is done either in the
<tl><pro>goldsmith</pro>’s forge</tl>, <tl>surrounded with
<m>bricks</m></tl>, or in a <tl><fr>fourneau à vent</fr></tl> with
`<fr>`**foeu de fusion**`</fr>`, so that the <del>sand remains <tmp>long enough</tmp></del> 
<add><tl>crucible</tl> remains red for a <ms><tmp>quarter hour</tmp></ms></add>.

**Can we translate "foeu de fusion" as either "casting fire" or "fusion fire"??**

**Comment by ps2270** [comment]
Well, I really don't know what that means, but I think "fusion fire" is ok...a really hot fire?
NB it should be "goldsmiths' forge" not singular.

**Comment by thuchacz** [comment]
Changed translation to "fusion fire" and closed.
