### ISSUE TITLE
Translation of "fonte"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#646]
Glossary:
Fonte (f.) = to found, founding, the action of melting, the (metal) melt
La fonte = “the founding” (of cannons), 17v

**There are 5 instances (out of 22) of the word "fonte" that have been left in French in the TL. Can we translate them all as "melt"??**

36v_3 "Glassworkers' glass"
Then, having set this long, cleft bubble on a <tl><m>stone</m></tl> or
large <tl>platine</tl> that is in the <tl>furnace</tl>, a little less
warm than the `<fr>fonte</fr>`, it is left to expand.

69r_2 on fol. 69v "Sable"
Some mix in <m>lead</m> with the
`<fr>fonte</fr>`, but it is for large works &amp; not for small ones.

83v_3 "Bellows"
To melt with <tl>bellows</tl>, &amp; hasten your `<fr>fonte</fr>`,
&amp; also cast hotter <del><fr>po</fr></del>, do not place your
<tl>bellows</tl> at the bottom near the foot of the <tl>furnace</tl>

98v_5 "`<fr>Fonte<fr>`"
The <m>putty</m> is made of <m>burnt earth</m> which was
used in the `<fr>fonte</fr>`, this is <m>earth <fr>bourre bolvene</fr></m>
in which one has melted it.

**Comment by TillmannTaape** [comment]
Suggestions:

36v "melt" (which I think is the correct term for glass – @ps2270?)

69v "melt" (metal this time)

83v "melt" or "melting" (depending on whether we think the material "melt" is being hastened along, or the process of melting. Both are plausible I think)

98v "founding" (he is talking about the earth used for founding, rather than the melt)

**Comment by ps2270** [comment]
first 3 are "melt".
The 4th one is confusing because of the "this is earth bourre bolvene
in which one has melted it." But I think Tillmann is correct, and we should translate both "fonte" as "founding" in this one.

**Comment by thuchacz** [comment]
Implemented and closed.
