### ISSUE TITLE
four des barbiers

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#647]
**Glossary**:
Fours de barbiers (m.) = keep Fr. (provisionally). 
Apparently “barbers’ ovens” used for heating towels.

**Are we keeping this in French? Only one instance (12r)...**

**Comment by ps2270** [comment]
@thuchacz Please translate as "barbers' ovens" with an editorial note that says:
"apparently used for heating towels"
Thanks!

**Comment by thuchacz** [comment]
Done
