### ISSUE TITLE
fresil

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#648]
**Glossary**:
Frésil (U) = ? on 94v, keep in Fr., it is defined as iron scales

**NB**: Term ONLY occurs on 94v (Furbishers)—and occurs twice there, in different forms (see below)

**TO DO:**
1. make decision about how/whether to translate or keep in Fr. and update glossary
2. accent aigu?? It's listed in the glossary as "frésil" but the TCN only gives "fresil" 
3. what about the "fresil" v. "fresiller" issue? "baston à fresiller" is translated as "fresil stick"—are we okay with that?

TCN:
```
<ab>Le <tl>baston à <m>fresiller</m></tl> est de <m><pa>saule</pa></m>,
qui est pour desrouiller les<lb/>
armes avecq du <m><df>fresil</df></m>, qui est ceste <m>escaille de fer</m> 
tombant a la<lb/>
<tl>forge des <pro>mareschaulx</pro></tl>.</ab>
```
TL:
```
<ab>The <tl><m><fr>fresil</fr></m> stick</tl> is of <m><pa>willow</pa>
wood</m> which is to clean the rust off weapons with
<df><m><fr>fresil</fr></m></df> which is the <m>iron scale</m> falling
at the <tl><pro>farriers</pro>' forge</tl>.</ab>
```

**Comment by TillmannTaape** [comment]
I see no problem here. It's only used on this one folio, where it is also defined, so I think it makes sense to leave it in French (fresil stick is fine). The glossary entry has the a-p's definition.
@ps2270 ?

**Comment by ps2270** [comment]
Decision: leave both fresil and "baston à fresiller" in French.
Take off accent.

**Comment by TillmannTaape** [comment]
Taken off the accent in the glossary.
