### ISSUE TITLE
time for a decision about "fustée"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#649]
**Glossary**:
Fustée (U) = Keep in Fr. (PB JT) 
Consider replacing with or glossing as “burnishing tool”
(94r, 94v)

**6 instances total, all in `<fr>` and `<tl>` tags**:
94r, 94v (x4), 95r

**Comment by ps2270** [comment]
I see that the fustee is used to furbish--acc. to the OED to remove rust, polish, burnish. It is not a burnisher in the same way that the agate stone is a burnisher, but we have translated fourbisser as furbish, not burnish, so I guess we could call it a furbishing tool, but there is also another furbishing tool called a felin which we are leaving in French on 95r. So I think we leave fustee in French to differentiate it from these other furbishing tools.
On 95r, please correct FURNISH TO FURBISH IN "Having put the oil, they furnish the sword again on the chameau ..."

**Comment by TillmannTaape** [comment]
Agree re leaving in French. I changed the glossary entry to "a tool for furbishing (i.e. polishing and removing rust from sword blades)" and made the change on 95r.
