### ISSUE TITLE
"cotton" to be translated as "cotton"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#65]
NB: this translation refers not to the plant but to the general wadding/stuffing material

**Comment by Pantagrueliste** [comment]
All instances of *cotton* have been translated as *cotton*

**Comment by Pantagrueliste** [comment]
See with PHS

**Comment by ps2270** [comment]
Go ahead with markup of this.

**Comment by thuchacz** [comment]
Translation Protocol updated
All instances of cotton tagged as material only; instance in 016v_2 also tagged as plant and given editorial comment
Tweaks to "Fountain maker" 105v_2
