### ISSUE TITLE
gaillard(ise)

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#650]
"gaillard" in 39r_2 translated as "vigorous"
"gaillardis(s)e" on 49v and 50v (x2) is left in French. It refers to a bird disease that generates an impostume on the tails of Calendra larks. I spent some hours looking into this a few weeks ago, and couldn't find veterinary or natural history sources supporting this in order to suggest a better translation, so I generated an editorial comment (see below).

**TO DO:** update the glossary and tweak my editorial comment as you see fit.

**Glossary**:
Gaillardise (f.) = keep Fr., provisionally
(p049v)… otherwise meaning lustiness, liveliness, cheerfulness (Cotgrave). 

**Editorial Comment c_049v_06**
"Gaillardise" usually connotes joy, vigorous health, and sensuality; here the term may relate to the Middle French "galle" (f.) and its association with parasitic growths and skin conditions.

**Comment by ps2270** [comment]
good solution.

**Comment by thuchacz** [comment]
Noted PHS sign-off in glossary and un-highlighted line in table.

Closing.
