### ISSUE TITLE
Gip — needs a decision

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#651]
2 occurrences, both on 161r, both in `<fr>` tags in the TL:
"gip mat" and "gip de <la>lateribus</la>"

**Glossary**:
Gip (m., mod. gypse) (U) = “plaster”
NB plaster has been used elsewhere for plastre: differentiate? - MHS 06/17/16: 2016

**TO DO:**
1. decide whether or how to translate "gip" (in distinction from plaster?) and implement decision
2. update glossary

**Comment by ps2270** [comment]
Decision:
leave in French with FR tags
Glossary should read: Gip (m., mod. gypse) = a type of plaster

**Comment by thuchacz** [comment]
Updated glossary.

Closing.
