### ISSUE TITLE
Correct a translation? - fol. 170r

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#662]
170r
Medailles courantes
On faict les poincons de relief dacier non trempe puys
on le trampe & avecq cy on frappe sur des matrices non rougies
au foeu comme quelques ungs pensent Mays sur du fer
acerre recuit & adoulcy quon trampe apres

Current medals
One makes the relief puncheons of untempered steel, then one tempers the[m], & with [these] one strikes on matrices, not reddened in fire, as some think, but on steeled iron, reheated & sweetened, which one has afterwards tempered.

Should Medailles courantes be trans "current medals"

**Comment by Pantagrueliste** [comment]
I'd rather translate it as "common" or "ordinary" medals.

**Comment by thuchacz** [comment]
TT changing to "common"
