### ISSUE TITLE
Advanced analysis or queries using xml markup 

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#664]
Searching features
Examples:

- Items that are tagged both material and plant vs just a plant
- Entries with both a profession and a place
- Entries with tools but no materials
- Continued entries, return count of tag terms
- Entries that have margins on right side

**Comment by njr2128** [comment]
- material tags that have the word "iron"
- plants that contain the word "rose"

**Comment by matthewkumar** [comment]
All of these are possible with the use of the digital manuscript in a jupyter notebook
