### ISSUE TITLE
translation policy on "grain"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#669]
**GLOSSARY:**
Grain = keep Fr., as a unit of measurement
“Unité d’évaluation de la pureté de l’argent et de l’or” (DMF) (SM).

**PROBLEM:**
Only 7 instances of "grain" have been left in French in the TL. All of them occur when "grain" is used as a measurement (and thus, they have `<ms>` tags as well) and has something to do with metal.
However, there are other instances of "grain" used as a measurement that have NOT been kept in French (e.g., 116v: "throw in two or three `<ms>`grains`</ms>` of `<m>`rosin`</m>`" or 104r: "about four `<ms>`grains`</ms>` of `<m>`sal ammoniac`</m>`, &amp; six
`<ms>`grains`</ms>` of `<m>`sublimate`</m>`")

**ISSUES TO RESOLE**
1. Update glossary entry. Is there anything more to say about "grain" as a measurement? And is our policy to keep in French ALL instances in which "grain" is used as a measurement, or only those related to metals? 
NB: there is room for some discretion here, since "grain" is sometimes used as an indeterminate format for a material (e.g., take a grain of wax, and using a hot iron wire...), and I don't think this should get an `<ms>` tag

2. Update the xml files as necessary. There are 77 instances of "grain" in the TCN to review, 85 in the TL.

**Comment by TillmannTaape** [comment]
At a quick search of the ms, I don't see any uses of grain as a measurement for purity of gold or silver, although I could have missed something. If it is indeed only used as a measurement of weight, I don't see that we need to keep it in French at all; it's in the OED as a measurement (via French).

@thuchacz from your (more detailed) search, did you see it used as a measurement of purity of metals?

**Comment by thuchacz** [comment]
Yikes. It's been 5 weeks since I looked at this and I don't remember anything more than what I laid out above.

Point being: if the 7 instances that remain within `<fr>` tags (all of which have to do with metalwork in some way) can be translated effectively as the English "grain," then the most consistent thing to do is to remove the `<fr>` tags and update the glossary (or simply remove the term from the glossary, if we think it is easily understood).

**Comment by TillmannTaape** [comment]
Yes I think we can translate grain in all cases, sometimes as a measurement, sometimes more in the sense of "bits" as you suggest, as in "some grains of gold" on 101r.

I've removed all fr tags.

I'm 99% sure the grains on 128r–v I think refer back to the secret flux for silver described on 123–v (also described as "grains"), and I've added an editorial comment to that effect.
