### ISSUE TITLE
huile de petrol(le)

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#670]
**GLOSSARY:**
Petrolle (m., mod. pétrole) = keep Fr.
Cotgrave: Naphte, "held to be liquid, or soft, Bitumen (or the strayning thereof, is in truth) a soft, & sulfurous earth, or mould"; DMF does not have "petrol" but does have "bitumen," as does the OED, with first usage in the 15th c. (MBR 6/27/2017)

**PROBLEM:**
4 instances of "petrol(le)" that are all dealt with differently in the TL:

- CURRENT: "huile de petrolle" 73v = "petroleum oil" 
**THU wants:** "oil of `<fr>`petrolle`</fr>`"
- CURRENT: "huile petrolle" 77v (x2) = "`<fr>`huile petrolle`</fr>`" 
**THU wants:** "`<fr>`petrolle`</fr>` oil"
- CURRENT: "huile de petrol" 127r = "oil of petrol" 
**THU wants:** "oil of `<fr>`petrol`</fr>`"

**TO DO:**
Approve THU suggestion or make alternative suggestion.
Implement change.

**Comment by TillmannTaape** [comment]
I like THU's suggestions; I don't think we can confidently translate this.
@ps2270 ?

**Comment by ps2270** [comment]
I agree, keep in French.

**Comment by thuchacz** [comment]
Done
