### ISSUE TITLE
Translation of "12 lignes pied de roy"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#671]
On 22v, there is the image of the crossed out cannon ball with the following caption:

```
<caption>A little too big, see the one <del>of</del> that
follows.</caption>
<caption><wp>Cannon</wp> ball, weighing 40 <ms>lb</ms>, having 12 <fr><ms>lignes
pied de roy</ms></fr>.</caption>
```

We translate "lignes" as "lines" and "pied de roy" as "king's foot". Is there a reason here to leave "lignes pied de roy" in French? Can we just say "lines king's foot"? Given that the caption has line breaks between the two measurements, can we put a comma between them in the TCN and the TL? That might make a bit more sense for the reader, as it would then look like this: "having 12 lines, king's foot."
@TillmannTaape, what do you think?

**Comment by TillmannTaape** [comment]
That makes a lot of sense to me — if we’re translating ligne and pied de roy we should also translate the compound. The comma in TCN and TL would help.
