### ISSUE TITLE
Editorial comment for leaving "masse" in French?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#672]
Pamela, we leave "masse" in French below—do you have a sense of what is meant here? Can you craft the text for an editorial comment? Or do you want to leave this unaddressed?

```
<div>
<id>p157r_4</id>
<head>Disposer l'herbe ou fleur pour<lb/>
gecter</head>
<ab>Mets tousjours <oc>à l'enssus</oc><comment>c_157r_03</comment> le principal envers de la chose<lb/>
pource qu'il vient mieulx et plus net que le bas.<lb/>
Fais le gect large &amp; que le <df>supraplus</df> (qui est la
masse<lb/>
aulx <pro>fondeurs</pro>) de grand gect, <del>Et</del>
mesmem<exp>en</exp>t pour l'<m>argent</m> qui veult<lb/>
le <tl>moule</tl> bien chault &amp; estre gecté fort chault.<lb/>
Les choses fort tanvres veulent estre gectées fort chault.</ab>
<ab>
<margin>left-middle</margin>
Quand tu<lb/>
cognois que la<lb/>
tige d'une fleur<lb/>
bruslée dans<lb/>
le <tl>moule</tl> qui<lb/>
ne s'ouvre point<lb/>
est bien reduicte<lb/>
en <m>cendre</m>,<lb/>
c'est signe que<lb/>
le reste est bien bruslé.</ab>
</div>
```
```
<div>
<id>p157r_4</id>
<head>Arranging plants or flowers for casting</head>
<ab>
Always put <oc>à l'enssus</oc><comment>c_157r_03</comment> the principal side of the thing, because it comes
out better and neater than the bottom. Make the gate wide &amp; make sure that
<sup>there is</sup> <df><fr>supraplus</fr></df> (which is the
<fr>masse</fr> for <pro>founders</pro>) for a large gate,
<del><fr>Et</fr></del> especially for <m>silver</m>, which wants the
<tl>mold</tl> quite hot &amp; to be cast very hot. Very thin things want
to be cast very hot.</ab>
<ab>
<margin>left-middle</margin>
When you know that the stem of a flower, burned in a <tl>mold</tl> which
does not open, is reduced well into <m>ashes</m>, it is a sign that the
rest is well burned.</ab>
</div>
```

**Comment by ps2270** [comment]
@Pantagrueliste Can you please look at the DMF on masse:
http://atilf.atilf.fr/scripts/dmfAAA.exe?LEM=MASSE1;MENU=menu_dmf;AFFICHAGE=2;ISIS=isis_dmf2015.txt;MENU=menu_recherche_dictionnaire;OUVRIR_MENU=1;ONGLET=dmf2015;OO1=2;OO2=1;OO3=-1;s=s13032ef0;LANGUE=FR;XMODE=STELLa;FERMER

It seems to refer to the amount of metal used to make a vessel or object--a technical term for metal working.  See within the entry especially:
_Masse de_ 
and
_Une même masse_
Thanks

**Comment by Pantagrueliste** [comment]
Masse + de or adj. is the substance of something. In the DMF examples, it refers to undetermined quantities of something. (Same in Frantext 16th century). So, supraplus (the surplus) is the quantity (of something) for the founders.

**Comment by ps2270** [comment]
So I guess the English would be:
make sure that
<sup>there is</sup> <df><fr>supraplus</fr></df> (which is the
quantity for <pro>founders</pro>) for a large gate,
@thuchacz can you please change this?
Thanks

**Comment by thuchacz** [comment]
Aaack! I can't mark this up. The "masse" has been revised by Marc because of a `<ups>` situation. See #755 for the latest state of affairs.
