### ISSUE TITLE
Massicot — keep in Fr?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#673]
**Glossary:**
Massicot (m.) (U) = keep Fr. “massicot”, i.e. lead-tin yellow
See MinDat. DMF: chaux de plomb de couleur jaune ; Cotgrave: oaker (i.e. ochre) made of ceruse or white lead.
	See Kirby et al., Pigment Glossary: (Note that the word ‘massicot’ today refers to a pale yellow lead monoxide; in earlier times it referred to lead-tin oxide.)

There are 15 instances of "massicot," but only 2 have been kept in Fr in translation campaigns. Is it not enough to translate it and make the note about its historical composition in the glossary? It is in the OED from 1472 via French. 

@ps2270 ?  @TillmannTaape ?

**Comment by ps2270** [comment]
@TillmannTaape YES, pls do that, i.e., TRANSLATE with the note (with wording as above) in the glossary

**Comment by thuchacz** [comment]
I have removed the `<fr>` tags, so now TL has "massicot" (as an English word) throughout. 
@TillmannTaape you can close this when you update the glossary.

**Comment by TillmannTaape** [comment]
Glossary updated.
