### ISSUE TITLE
"mects à pestrir"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#674]
@TillmannTaape and @Pantagrueliste — does this mean "rotting food"? Can you suggest a translation? I don't think we need to leave this in French. It is in the "Catching nightingales" entry on 105v:

TCN:
Aproche doncq faisant semblant de chercher en terre quelque<lb/>
chose. Et ayant des <al>vers</al> qui viennent dans les vielles farines<lb/>
ou dessoubs les **mects à pestrir** ou aulx moulins, do<corr>nt</corr> il est fort<lb/>
friand, mects en sur ton <tl>chapeau</tl> quelqu'un attaché avecq un <tl>espingle</tl><lb/>
ou aultrem<exp>ent</exp>, affin qu'il se remue.

TL:
Therefore approach making as if searching the ground for
something. And taking some <al>worms</al> which come from old meal or
from beneath **`<fr>mects à pestrir</fr>`** or mills, <corr>which</corr> the
<al>nightingale</al> is fond of, put some on your <tl>hat</tl> attached
with a <tl>pin</tl> or otherwise, in order that it wiggles.

**Comment by thuchacz** [comment]
@TillmannTaape @Pantagrueliste 
Forget my earlier suggestion.

Looks like it is something more like "(yet-to-be-worked) kneading troughs" (Cotgrave: mect/met = kneading trough; pestrir = knead, work with the hands)

**Comment by TillmannTaape** [comment]
I think "kneading trough" is fine, although it elides the over-determination in the original.

**Comment by ps2270** [comment]
Yes, it should be kneading trough.

**Comment by thuchacz** [comment]
Done.
