### ISSUE TITLE
Retranslation of "bellows of the forge" and definition of bellows-related vocab

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#675]
```
<div>
<id>p109r_4</id>
<head><tl>Souflets</tl> de la <tl>forge</tl></head>
<ab>Il est mieulx que par le portevent ils soient enchassés dans
quelque<lb/>
bout de membreure, <del>q</del> car ilz en sont plus asseurés, aprés tu
les<lb/>
peuls legerem<exp>ent</exp> asseurer par hault. Il fault que les tuelles
soient<lb/>
4 <ms><bp>doigts</bp></ms> sur la sole de la <tl>forge</tl>.</ab>
</div>
```

```
<head><tl>Bellows</tl> of the <tl>forge</tl></head>
<ab>It is best that they be fixed in on some piece of
<fr>membreure</fr>, through the <fr>portevent</fr>,
<del><fr>q</fr></del> for they are more secure, next you can lightly
secure them from above. It is necessary that the <fr>tuelle</fr> be 4
<ms><bp>fingers</bp></ms> on the sole of the <tl>forge</tl>.</ab>
```
**PROBLEM**
1) Translation of "Bellows of the forge" entry on 109r is not quite right (syntax). 
2) There is vocab related to bellows that we haven't quite figured out—here and throughout the Ms.
- portevent
GLOSSARY: Portevent = technical term for the pipe that directs the air from the bellows through the tuelle and up into the furnace
- membreure (=membrure)
NOT in the glossary, though kept in French in the TL
"[membrure](https://www.littre.org/definition/membrure)," and refers, in carpentry, to a thicker plank of wood in which you can embed/set thinner planks.
- tuelle 
GLOSSARY: Tuelle (f.) = keep Fr.?, i.e. the opening at the bottom of the furnace or kiln, through which the bellows’ pipes are inserted. 
Defined by a picture with the “tuelle” labelled on fol. 16r.  Fol. 109r (“soufflets de la forge”) says the tuelle must be four fingers on the floor of the furnace.

Please consult this PDF (in French!) on the restoration of (historic) [bellows](https://www.lesforgesdemontreal.org/site/wp-content/uploads/Re%CC%81paration-de-soufflet-1.pdf). Search for "portevent" and you'll find it given as synonymous with "tuyere"—perhaps a hint at the meaning of our yet mysterious "tuelle"? "membrure" is in this document as well.

See also this excerpt from Heuer's [_Technological Dictionary_
](https://clio.columbia.edu/catalog/13300919) that translates "porte-vent" and "tuyere" (tuelle??) as "blast pipe":
<img width="226" alt="Screen Shot 2019-05-31 at 07 48 35" src="https://user-images.githubusercontent.com/23508994/58704076-cbcc7880-8378-11e9-808f-f17e288d2a16.png">
Considere also that "tuyere" is a word in the OED(!!)

See especially this 1798 English encyclopedia entry on German furnaces for mining ([p 162](https://books.google.com/books?id=pPF_btvWjc4C&pg=PA162&dq=blast+pipe+bellows+furnace&hl=en&sa=X&ved=0ahUKEwiIgJ732sXiAhVMwVkKHUNHA28Q6AEILzAB#v=onepage&q=blast%20pipe%20bellows%20furnace%20tuyere&f=false)), which discusses the anatomy of the bellows (using the term "tuyere") and has an illustrated plate ([ccccvi, fig. 74](https://books.google.com/books?id=pPF_btvWjc4C&pg=PA162&dq=blast+pipe+bellows+furnace&hl=en&sa=X&ved=0ahUKEwiIgJ732sXiAhVMwVkKHUNHA28Q6AEILzAB#v=onepage&q=ccccvi&f=false))

**TO DO:**
1. Can we fix the syntax in the first sentence of 109r, especially?
2. Can we find a translation for the words listed above, and/or tweak the glossary entries?

**Comment by ps2270** [comment]
Changed tuelle to blast-pipe in all cases
changed portevent to blast-pipe in all cases
Glossary entry for both which indicates meaning and sources THU found above
Glossary entry for membreure (=membrure)
"membrure," and refers, in carpentry, to a thicker plank of wood in which you can embed/set thinner planks.
