### ISSUE TITLE
untranslated instances of "mine"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#676]
There are 4 in the TL.
NB: there are 35 instances of "mine" in the TCN. So, 31 have been translated. I can make a table to check consistency of these translations after I get a verdict on the instances below.

**GLOSSARY**
NEW DEFINITION: according to Cotgrave and DMF: a measure of grain and dry goods between 110-120 English pounds or half a setier. Cotgrave: a measure of land (mine de terre); a mine, a cave dug in the ground, a vein of metal. Cotgrave: mine de plomb = an orange, tawny mineral used by painters; plomb de mine = black lead.  DMF: a mine, source, quarry, ore, mineral, a mineral specimen. DMF: mine de plomb = lead ore. Also minium, see “Minium.”

___
**1) MINE DE PLOMB**
on 63r, translated as "lead ore". On 7r, left in French. Resolve.

TCN 63r
```
<id>p063r_3</id>
<head>Gect</head>
<ab>Les <pl>Allemans</pl> usent du <m>plomb de <pl>Flandres</pl></m>, pource qu'il est fort<lb/>
douls. Et pour mieulx gecter ilz prennent de la <m>mine de plomb</m> &amp; le<lb/>
fondent,
```
TL 63r
`[...] And to cast better they take <m>lead ore</m> &amp; melt it,`

TCN 7r
```
<id>p007r_1</id>
<head>Pour dorer d’<m>or couleur</m> et d’<m>or bel</m></head>
[...] Puys,<lb/>
avecq l’<m>huile</m> ainsi gras, broye un peu de <m>blanc de plomb</m>, de<lb/>
<m>massicot</m> &amp; de <m>mine de plomb</m> <del><ill/></del> à
discretion, aultant d’un<lb/>
que d’un aultre.
```
TL 7r
```
Then, with the <m>oil</m> thus made fatty, grind a little <m>lead white</m>, <m>massicot</m> &amp; <m><fr>mine de plomb</fr></m> comment>c_007r_04</comment>
<del><ill/></del>, at discretion, as much of one as of the other.
```
NB: comment content: "A variety of minium."
___

**2) MINE D'ANGLETERRE** 
"mine d'Angleterre" and "mine" (referring to the "mine d'Angleterre) on 43r. Translate? Adjust to "`<fr>`mine`</fr>` of England" and ""`<fr>`mine`</fr>`"??

TCN 43r
```
<id>p043r_4</id>
<head>Bronzure blanche</head>
<ab>Donne noir à <m>colle</m>, co<exp>mm</exp>e est dict, sur la
medaille, puys <m>vernis</m>.<lb/>
Estant sec, racle de la <m>mine d'<pl>Angleterre</pl></m> dessus avecq un<lb/>
<tl>pinceau</tl> ou avecq le <bp>doigt</bp>. Ladicte <m>mine</m> raclée embellit<lb/>
les medailles de <m>plomb</m>.</ab>
```
```
<ab>Apply black with <m>glue</m>, as was said, on the medal, then <m>varnish</m>. Once dry, grate <m><fr>mine d'<pl>Angleterre</pl></fr></m> on top with a <tl>paintbrush</tl>
or a <tl><bp>finger</bp></tl>.  The said grated <m><fr>mine</fr></m>
embellishes <m>lead</m> medals.</ab>
```
___

**3) SABLE COMMUN DE MINE**
in the header on 132v. Is this not just "Common mine sand"??

TCN 132v
```
<id>p132v_1</id>
<head><m>Sable commun de <env>mine</env></m></head>
<ab>En <tl>chassis</tl> si on gecte chault il soufle, partant<lb/>
il ne le fault que desseicher.</ab>
```
TL 132v
```
<head><m>Common sand from the <env><fr>mine</fr></env></m></head>
<ab>In a <tl>frame</tl>, if one casts hot, it becomes porous, therefore
one only needs to dry it out.</ab>
```

**Comment by thuchacz** [comment]
Just saw this in the glossary, a few lines down:
Mine (m.) = “minium”; but cf. Mine above, according to context
See DMF (definition 4), given as f., but unsubstantiated by citations (MHS). See also: “Or mat” annotation Spring 2016. See also: Minium. **Mine d’Angleterre on 43r, we translated as English minium (4.15.19).**

If this was a decision, it was not implemented.

**Comment by ps2270** [comment]
see #189, done and closed by @Pantagrueliste 
My directives:
7r: leave in FR (as it is now), add an editorial note that says "A variety of minium?"
43r: change translation to English minium. PHS to put in a glossary definition.
110r: change mine to "mineral" in both cases
118r: change mines to minerals, and change "even" for unie to uniform.
125r: mine needs to changed twice to ore.

**Comment by ps2270** [comment]
on 132v:
I am not sure whether to use "mine" here or "quarry".  When he talks about sand from "the mine", he seems mainly to be talking about the mine near Toulouse, which should probably be translated quarry.  I need to check further on this

**Comment by ps2270** [comment]
There seems to have been a branch merge problem with #189. See also #473.  Maybe this explains the untranslated instances?

**Comment by ps2270** [comment]
@Pantagrueliste .  Please fix these:
69r: for cavernes des rochers translate as rock **caverns**, rather than caves

PHS will add a Glossary entry addition for pierrerie, meaning quarry.

7r: Change comment content on "mine de plomb" to "Possibly lead ore, or a variety of minium."

43r: translate "mine de Angleterre"  to English minium, and "mine" in same entry to "minium"
. PHS to put in a glossary definition.
132v: take Fr tags off "mine"

**Comment by thuchacz** [comment]
THU has updated the comment on 7r

**Comment by Pantagrueliste** [comment]
done
