### ISSUE TITLE
mollet(t)es

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#677]
**GLOSSARY**
Molettes (f. pl.) = keep Fr.PHS 06/26/2017, i.e. “pincers” 
(Cotgrave) p129v FP GC

**PROBLEM**
6 instances of the term in TCN. However, in the TL:
72r: kept in FR
107v: translated as "pincers"
112v: translated as "small soft" — interpreted adjectivally here (and it makes sense; pincers are not meant)
128r (x2): first instance, kept in French. Second instance (2 lines later), translated as "pincers" 
128v: translated as "pincers"

**TO DO**
1. decide whether this can be translate as "pincers" consistently
2. update glossary
3. implement decision

**Comment by TillmannTaape** [comment]
Yes, pincers makes sense in all cases, except the "soft filaments" as you say (on 107v, not 112v), and I've changed the TL accordingly.
