### ISSUE TITLE
pastel — translation and markup inconsistencies

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#687]
If you'll recall, this whole conundrum grew out of an infelicity:  
FR "pastel" = EN "woad"
FR "guesde" = EN "woad" 

On 15r, the AP distinguishes "pastel" and "guesde" (or uses them synonymously? We thought not...) We decided that we would also distinguish these terms, using "pastel woad" and "guesde woad." 
_For what it's worth, "pastel" is much more common in the MS. "guesde" is only used once on 15r; "guesdre" used once on 76r. Also, NB: "pastel" is both a modifier (e.g., "fleurs de pastel" / "pastel flowers") and modified  (e.g., "pastel pur d'escarlate" / "pure scarlet pastel")_

**PROBLEM:** Tag complications relating to `<fr>` and `<pa>` tags and their placement.

`<fr>` issues:
- Some of the "pastel" have been put in `<fr>` tags in the TL, though most have not
- "guesde" and "guesdre" have not been put in `<fr>` tags
**QUESTION: does "pastel" and/or "guede" need `<fr>` tags?**

`<pa>` issues:
- sometimes we get `<pa>pastel</pa> woad`
- sometimes we get `<pa>pastel woad</pa>`
**QUESTION: what should be the extent of the `<pa>` tags?**

**Comment by ps2270** [comment]
Do not use French tags for pastel; it is an English word.  Guesde and guede are French, so I guess it should have French tags.
`<pa>` tags should be around both terms in pastel woad and guesde woad.
