### ISSUE TITLE
pierre morte

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#691]
**GLOSSARY:**
Pierre morte (f.) = “stoneware”

Not sure where that translation came from or if it's valid—no extra info in glossary.

"Pierre morte" only comes up ONCE in the Ms, and it is with a deletion in the middle (he wrote "pierre porte" and then realized he meant "pierre morte," so we get "pierre `<del>`porte`</del>` morte"). NB: it's left in French in the TL:

28v_1 (Pewterers)
```
To mold platters &amp; dishes, they make them out of <m><fr>pierre
<del><fr>porte</fr></del> morte</fr></m>, that is from
<m><fr>grais</fr></m>, &amp; they shape &amp; polish <del>around</del>
them on the <tl>wheel</tl>.

```
**QUESTION:**
Do we want this left in French? Or translated as "stoneware"? If the latter, how about "`<m><del><fr>porte</fr></del> stoneware</m>`" as markup?

**Comment by ps2270** [comment]
Leave in French with ed note that says possibly limestone.
