### ISSUE TITLE
"plat(t)eforme"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#693]
**NO ENTRY IN GLOSSARY**

10 instances in TCN of "plat(t)eforme"
21r (x2); 24v (x4), 25r, 82r (x3)

The 3 instances on 82r have been kept in French because they seem to designate a particular tool of clockmakers.
Otherwise, all other instances appear in the context of cannon transport and use; it has therefore been translated as EN "platform"

**TO DO**
- add an entry to the glossary

**Comment by TillmannTaape** [comment]
Added to glossary:
1. platform (in artillery)
2. in clockmaking, this refers to a device for scoring cogs evenly

I think we could translate the clockmaking instances as "platform", too, since that is the meaning of the word, and it is explained in some detail in the entry what is meant by this.

**Comment by thuchacz** [comment]
translated 3 instances on 82r as "platform"
