### ISSUE TITLE
rocaille / roquaille — better translation?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#696]
**GLOSSARY:**
Rocaille (f.) = “rock pieces” MHS/PHS 2018
F. 32v. Cotgrave (rochaille): rockes, rockiness ; DMF: terrain rocailleux, rocky terrain. Only used in Fr. 640 in the Vitrier entries, 32v, 37v.

**PROBLEM:**
This definition is too generic. "Rock pieces" has been used for the 2 entries using "rocaille" (32v, 37v) but not for "roquaille" (31v). All instances of "rocaille" / "roquaille" occur in the context of glasswork. Consider the entry from this [1727 technical dictionary](https://books.google.com/books?id=MVpZ4zxi3sgC&pg=PP244&lpg=PP244&dq=rocaille+vitrier&source=bl&ots=6_F1qPTk-8&sig=ACfU3U2W0I6ESWyo2Kk4wAuoBgb7oqEZkQ&hl=en&sa=X&ved=2ahUKEwjt6o_Ry9PiAhVtU98KHWcmDvgQ6AEwCHoECAYQAQ#v=onepage&q=rocaille%20vitrier&f=false), which draws on an entry in this [dictionary from 1680](https://books.google.com/books?id=AME-AAAAcAAJ&pg=RA3-PA322&lpg=RA3-PA322&dq=rocaille+vitrier&source=bl&ots=39Z93Oyuec&sig=ACfU3U1_MZnAZ1U-is4RyEHeulZRk8oS6w&hl=en&sa=X&ved=2ahUKEwjt6o_Ry9PiAhVtU98KHWcmDvgQ6AEwCnoECAgQAQ#v=onepage&q=rocaille%20vitrier&f=false):
<img width="466" alt="Screen Shot 2019-06-05 at 20 24 52" src="https://user-images.githubusercontent.com/23508994/58998724-4873b280-87d0-11e9-954c-5e4ac3d0cbed.png">
Consider also this entry in a [1774 manual on painting](https://books.google.com/books?id=YwlYAAAAcAAJ&pg=PA108&lpg=PA108&dq=rocaille+vitrier&source=bl&ots=j7q3RjTzEd&sig=ACfU3U0YLAtafhbcVHZU8_E8oW9_nKrowA&hl=en&sa=X&ved=2ahUKEwjt6o_Ry9PiAhVtU98KHWcmDvgQ6AEwDXoECAkQAQ#v=onepage&q=rocaille%20vitrier&f=false) that indicates that "rocaille" is added to make the glass "fondant" — is rocaille a flux??

**TO DO:**
come up with better translation and implement on 31v, 32v, 37v

**Comment by TillmannTaape** [comment]
The definition of rocaille as a glass colorant makes sense in all instances in Ms. Fr. 640.

Rocaille is in the OED, not with this meaning, but with the sense of glass beads, which may be similar. So I'd suggest translating "rocaille" with an editorial note that it likely refers to small beads of glass colorant, citing the two dictionaries above as a reference.



Translate as "rocaille" which is in the OED. Two meanings:
1)

**Comment by TillmannTaape** [comment]
changes made in TL

**Comment by thuchacz** [comment]
<comment>c_031v_02</comment> added to 31v, 32v, and 37v
