### ISSUE TITLE
Fol 16v, Title extension "Contre Go{norrhee}

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#698]
Fol. 16v contains an entry titled "Contre Go.".  We have extended it to read Contre Go{norrhee}
We are not sure this is actually what the abbreviation indicates, although it is likely.  I do not think we should include the extension in the title.  Instead we should leave it abbreviated as it is written, and make an editorial comment in all three versions that reads
"Go. may be an abbreviation for Go{norrhee}. See fol. 7v and the annotation by Nicole Basile, "The Riddle of G."
@Pantagrueliste, can you please do this?  Thanks.

**Comment by Pantagrueliste** [comment]
Done in TC, TCN and TL.
