### ISSUE TITLE
translate abbreuvoir as trough or feeder according to context

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#70]
_Abbreuvoir_ (m.): a trough for watering or feeding (animals) (DMF). **According to context**: use **trough** or **feeder**

**Comment by thuchacz** [comment]
Searched for "abre" (relevant results: abreuv* (11 hits) / abrev* (4 hits).

**Comment by thuchacz** [comment]
used "feed(er)," "trough," "imbibe," and "saturate," depending on context. Added "saturate" as a possible sense of "abreuver" to the vocab list.
