### ISSUE TITLE
93r_1 Translation correction needed

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#700]
Olives
They are spoiled if once per month one does not refresh their salt water, and one ought not to touch with their hands, for this makes them spoils.

Olives
Elles se gastent si une foys le moys on ne leur rafreschist leur eau sel, qu’il ne fault pas toucher des mains car cela les faict gaster.

They are spoiled if once per month one does not refresh their salt water, [which should not be touched by the hands for it makes them spoil] --is that a better translation?
If so, please correct, @TillmannTaape

**Comment by ps2270** [comment]
and change "per" to "a":  ..."if once a month"...

**Comment by thuchacz** [comment]
Done
