### ISSUE TITLE
59v_1 Translation correction needed

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#701]
59v_1
suggestions for revision in [ ]

Paincture darmes
Le noir de charbon mesle dun peu de blanc de plomb est
fort propre pour faire les armes y meslant si tu veux un
peu de dazur Le noir de charbon de soymesme est co{mm}e bluastre

Painting [Picturing?] of armory [armor]
Charcoal black mixed with a little lead white is very appropriate to make armory [armor], mixing in a little [delete of] azure if you wish. Charcoal black by itself is as if bluish [could this be "is like bluing?--like the blueing of arms?]

@TillmannTaape and @Pantagrueliste let's discuss this one

**Comment by thuchacz** [comment]
Done
