### ISSUE TITLE
6v_2 and 7r_2 translation consistency

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#702]
"estampes" is translated "stampings" on 6v, altho it has an editorial note saying that we decided to translate as "stamped ornaments".  It is trans as "stamped ornaments" on 7r_2.

I am re-thinking my decision to trans as stamped ornaments, and I now think we should probably translate as "stampings" with an editorial note that indicates what is meant--similar to the ed note that is there now, but without translation decision info.

@TillmannTaape let's discuss this.

**Comment by thuchacz** [comment]
I should confess: I changed the translation for 6v to "stampings" last week
out of frustration with the less-than-optimal translation on 6v. I meant to
create an issue but forgot. Glad you caught this, Pamela.

**Comment by ps2270** [comment]
DECISION: In case it wasn't clear: change 6v and 7r both to "stampings" with ed note, as above.

**Comment by thuchacz** [comment]
TT & THU DOne
