### ISSUE TITLE
Check consistency of grand métaux/grand métal and tag as a material

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#71]
_grands metaulx_ / _grand metal_ 

Whole phrase should be **tagged as a material**, and check that this is translated consistently.

**Comment by TillmannTaape** [comment]
There are no occurrences of 'grand metal' in the TCN.
There are two occurrences of 'grands metaulx' (85v and 156r); both are translated 'great metals'

@ps2270 is this the correct translation? The vocabulary does not offer a translation.

**Comment by ps2270** [comment]
I don't know what it means. I think we should compile a list of words for Sarah and Colin to tell us whether they have come across in reading all the metalworkers sources

**Comment by TillmannTaape** [comment]
From Sarah: “Grands metaulx” is the name of the common metals. This category includes iron, copper, lead, tin, zinc, and mercury :
https://books.google.fr/books?id=ZHxCAAAAcAAJ&pg=PA182&dq=%22grands+m%C3%A9taux%22&hl=fr&sa=X&ved=0ahUKEwjYl8Lqu8vgAhVDz4UKHf-pAbUQ6AEIPDAD#v=onepage&q=%22grands%20m%C3%A9taux%22&f=false

**Comment by TillmannTaape** [comment]
Decision PHS and TT: we don't know what this means. It seems unlikely that it is the 'common metals', it's in fact more likely to refer to gold and silver. Leave "grand metals", without a note, for others to figure out eventually.
