### ISSUE TITLE
create elements for text formatting

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/m-k-manuscript-data#719]
may help us get out of man/rub issues. Just use `<i>` ,`<emph>`, `<bold>`, etc...

**Comment by tcatapano** [comment]
create generic `<emph>`  element

**Comment by NickLaiacona** [comment]
@njr2128 I'm trying to find a folio that uses emph tag, can you point out an example for testing purposes?

**Comment by njr2128** [comment]
> @njr2128 I'm trying to find a folio that uses emph tag, can you point out an example for testing purposes?

A few cases:
001r
125r
140v - second best option
162r - might be best testing option

**Comment by njr2128** [comment]
emph is only one in use and the only one added to schema.

This has been done, so I am closing. @tcatapano , reopen if untrue.
