### ISSUE TITLE
question about "A" in figure of 145r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#721]
MHS + @thuchacz: is this in fact an "A" or is it part of figure?
Is it a caption (this will display best)?
Or something else?

**Comment by thuchacz** [comment]
MHS is certain this is an A. Perhaps the A-P copied the illustration from somewhere, where it might have had an "A".

**Comment by thuchacz** [comment]
I am leaving "A" as a caption.
