### ISSUE TITLE
Check that <sup> tags are necessary in TC, TCN, TL

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#724]
Below is a summary of where `<sup>` tags occur. They rarely occur across the three versions. Verify that they are 1) necessary, and 2) on the correct versions, pulling across to other versions as needed.

TC | TCN | TL
-- | -- | --
  | 4v |  
45r | 45r | 45r
  | 46v | 46v
  | 46v | 46v
  | 50v |  
  | 53r |  
  | 55v |  
  |   | 59r
60v |   |  
  |   | 61r
  |   | 66v
  | 72r |  
  | 82r |  
97r | 97r |  
  | 107v | 107v
  | 120r |  
156v | 156v |  
156v | 156v |  
  |   | 157r
  | 166r |  
  | 170v |  
TOTAL 5 | TOTAL 16 | TOTAL 8

**Comment by ps2270** [comment]
Go through the 54 sup tags and decide which are necessary, and how to indicate in all 3 versions. 
@thuchacz is pulling out a table.

**Comment by thuchacz** [comment]
Up-to-date table of <sup> tags in MS:
[https://docs.google.com/spreadsheets/d/1RMHu2KA-KlpIp0yxUF6Pg2XvwQTn7CnKWexf2Kx0kGg/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1RMHu2KA-KlpIp0yxUF6Pg2XvwQTn7CnKWexf2Kx0kGg/edit?usp=sharing)

**Comment by ps2270** [comment]
@TillmannTaape is responsible for implementing the decisions in the table above

**Comment by TillmannTaape** [comment]
Done, closing.
