### ISSUE TITLE
Change captions markup

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#727]
Implement changes to existing `<captions>` according to table below. Update index tracking as necessary

note-action | caption_text | folio
-- | -- | --
not heading-like: just ab (margin center top to render properly) | Un peu trop grande voy celle de qui suict | 022r
heading with entry id with figure in div | Balle de canon poisant 40 lb ayant 12 lignes pied de roy | 022r
heading with entry id with figure in div | Balle de canon | 026r
heading with entry id with figure in div | Balle de colevrine | 026v
heading with entry id with figure in div | Balle de bastarde | 027r
heading with entry id with figure in div | Balle de moyene | 027r
heading with entry id with figure in div | Piece de campagne | 027r
heading with entry id with figure in div | Faulconeau | 027v
heading with entry id with figure in div | Faulconeau de 4 quintals autrement passevo lants tire 8 pans | 027v
heading with entry id with figure in div | 3 quintals tire de long 9 pans | 027v
heading with entry id with figure in div | 2 quintals tire de long une cane qui sont 8 pans de monpelier | 027v
heading with entry id with figure in div | 1 quintal tire six pans et demy | 027v
heading with entry id with figure in div | 1 quintal et demy tire 7 pans et demy | 027v
heading with entry id with figure in div | mousquet de 60 lb tire 5 pans et demy ou 6 | 027v
heading with entry id with figure in div | 5 quintals tire onze pans et demy | 027v
not heading-like; should remain caption | de cuir | 036r
not heading-like; should remain caption | le banc des fourreaux | 094v
not heading-like; should remain caption | a | 094v
not heading-like; should remain caption | b | 094v
not heading-like; should remain caption | D le baston a felinder | 094v
not heading-like; should remain caption | c le flin ou pierre de fouldre | 094v
not heading-like; should remain caption | Cest la forme des crampons | 115r
not heading-like; should remain caption | Moule en noyau | 117r

**Comment by thuchacz** [comment]
Done
