### ISSUE TITLE
sel blanc/sol blanc

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#738]
We have not found information on "sel blanc". 
In bot instances (52v and 159v), it looks much more like "sol blanc" to me.

Two sources identify sol blanc as a white, chalky earth from Saxony (see glossary doc). 
I feel this makes better sense to me in the two entries.

Question: change to "sol blanc" in TC and TCN and leave in Fr. in TL, with an ed note "a white, calcareous earth mined particularly in Saxony"?

**Comment by TillmannTaape** [comment]
@ps2270?

**Comment by TillmannTaape** [comment]
TT has written to MHS

**Comment by ps2270** [comment]
any word from Marc?

**Comment by TillmannTaape** [comment]
Nope

**Comment by ps2270** [comment]
Marc's answer:
I believe I answered this one. The text clearly says sel, not sol. If you think the actual meaning is sol (soil) not salt, then it's the author's mistake, which would mean he is not quite familiar with that material.

Decision: leave as sel blanc with an ed note in all three versions that reads:

"Perhaps should read "sol blanc," a white, calcareous earth mined particularly in Saxony."

**Comment by ps2270** [comment]
CAG & PHS decided to translate as white salt, and have completed the glossary entry.  If you have a different opinion, please reply here.

**Comment by ps2270** [comment]
We changed sel blanc on 52v and 159v, the only two instances in the ms.
