### ISSUE TITLE
Search <sup> tags in TL and determine whether they are necessary

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#74]
When the sense of a passage needs the nouns in English (which are indicated by gendered pronouns in French), the nouns can be inserted in the translation WITHOUT the supp tag.
I.e., search for a <sup> tag

**Comment by thuchacz** [comment]
NB: there are a bunch on (and around?) 46v, re: oil of sulfur. The AP refers to "le mesme huile" in subsequent entries, which is now represented as "le mesme huile <sup>de soufre</sup>"

Good question: given that some readers will navigate by entry, is it reasonable to ask that they think to skim prior entries to figure out which kind of oil is being referred to?

**Comment by TillmannTaape** [comment]
Re THU's comment on huile de soufre, I think that in purely grammatical terms, the referent is too far away (in a previous entry) to supply 'de soufre'; I think this would be better served with an editorial comment on the word 'huile' in both entries (it only occurs once per entry) where it clearly refers to the preceding oil of sulfur, pointing to the previous entry where oil of sulfur is discussed. That way, the reader gets more information (where the 'sulfur' comes from), and we are being less invasive with the text.

@ps2270?

**Comment by TillmannTaape** [comment]
Similar issue of <sup> vs editorial comment on fol. 9r:

the <m>grain</m><comment>p009r_1</comment> called
<pa><fr>pomole</fr></pa> in <pl>Gascony</pl> or
<pa><fr>baillard</fr></pa> in <pl><sup>northern</sup>
France</pl><comment>p009r_1</comment>

The supped 'northern' seems to me an interpretation that comes from outside the text. Valuable information, but I think it belongs in an editorial comment, citing evidence that this was indeed a Northern French word for this kind of barley. I've emailed MHS about this.
