### ISSUE TITLE
Check render of figures in tc, tcn, tl; identify problematic ones

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#751]
Plan to change size or location of figures in rendering?
Try to keep to a minimum for Dec
During translation read-through, find outliers and fix those
Create dedicated label in GitHub
DECISION: M&K team to create issues as they see outliers
→ optional parameter in the markup (attribute value)

**Comment by njr2128** [comment]
See https://github.com/cu-mkp/making-knowing-edition/issues/197 (izing of images/figures in tc/tcn/tl panes #197)

**Comment by njr2128** [comment]
https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/figure_data.csv

**Comment by njr2128** [comment]
In GD, recording assigned sized in **figure-index-size** spreadsheet (in DCE folder)

**Comment by njr2128** [comment]
New column added "size-suggestion" for suggested changes that have not been implemented (if implemented, value should be entered in appropriate column)

**Comment by thuchacz** [comment]
Figures have been checked and changed during the render check campaign.
Closing.
