### ISSUE TITLE
two letters cut off on 129r, 141r, 152r. How to markup?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#752]
129r
`aiguillons fort vene<ups>neu</ups>lx</add></ab>`
The last "lx" is cut off, so it's not technically `<ups>`. Marc says this choir has been cut very close. It cut off letters too. Should this be a `<corr></corr>`? We've only used that tag for scribal errors so far... 
Or do we use an editorial comment to handle this?
Marc says that usually it is an "lx" in a situation like this, though an "s" is also possible.

**Comment by thuchacz** [comment]
And same problem on 142r. the final "bs" is cut off
```
le dos de <m>vermeillon</m> mesle de <m>laque</m> &amp; les costes
&amp; de<ups>ssou</ups>bs
```

**Comment by thuchacz** [comment]
And 152r: the final "s" cut/written off the page
`promptem<exp>ent</exp> tu pourr<ups>a</ups>s<lb/>`

**Comment by TillmannTaape** [comment]
I think the `<sup>` tag would be more appropriate: we're supplying something that's not there but is inferrable from context. So your first example would be:

```
aiguillons fort vene<ups>neu</ups><sup>lx</sup></add></ab>
```
Or it could be
```
aiguillons fort vene<ups>neu<sup>lx</sup></ups></add></ab>
```
– not sure what the implications are. If UPS is rendered differently, it would make sense to have the supplied letters within the UPS tag, since the letters would be under the strip if they were in fact there...

If there's only three instances (or even a few more), I think `<sup>` tags and and editorial comment to say that the letters are cut off would be a good solution.

**Comment by ps2270** [comment]
Do we need sup tag (would it be in tc & tcn or just tcn?)? Can we not just have an editorial note on tc?  And the full word in tcn? A search would turn up the word in tcn, which would be sufficient, no?
If I'm not forgetting, we reduced used of sup tag to almost nothing, right? I think an ed note is enough, but let me know if I am not foreseeing a problem with this solution.

**Comment by TillmannTaape** [comment]
If we are phasing out sup tags, I agree with PHS's solution above.

**Comment by njr2128** [comment]
@thuchacz and @TillmannTaape - status?
I believe this can be closed

**Comment by thuchacz** [comment]
Yes—NJR and I will have to add an Editorial Comment, since <sup> is only
used for supplied headings and nothing else.

T.

**Comment by njr2128** [comment]
great. Added to list of open issues for us to review during ed comment sessions

**Comment by njr2128** [comment]
Done. 
Launage for ed comments:
> The final letter "-<i>s</i>" is missing in the original. It appears to have been cut off when the original choirs of the manuscript were cut apart during rebinding. See ann_326_ie_19 (Marc Smith).
or
>The last two letters "-<i>bs</i>" are missing in the original. They appear to have been cut off when the original choirs of the manuscript were cut apart during rebinding. See ann_326_ie_19 (Marc Smith).
