### ISSUE TITLE
Translation & markup problems for 157r

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#755]
TCN on 157r
```
pourcequil vient mieulx et plus net que le bas<lb/>
Fais le gect large &amp; que le <df>supraplus</df> (qui est la masse<ups>rote</ups><lb/>
aulx <pro>fondeurs</pro> de grand gect <del>Et</del>
```

1. MHS reads "masserote" with certainty (now reflected in TC and TCN) which needs a translation for TL. It's in `<fr>` tags for the moment in TL.
2. There is no actual closing parenthesis in the text. MHS thinks it ought to end after "gect." I've fixed this, leaving it out in TC and adding it after "gect" in TCN and TL with `<corr>` tags.
3. MHS also thinks the profession tag should end after gect as "founders of big things" or the like. Now, it is "founders of a large gate." This needs to be done. Also, did we not have a way of phrasing this from elsewhere in the manuscript? Should be in the `<pro>` tag list.

**Comment by ps2270** [comment]
Does masserote [masserotte] mean something besides, acc to Cotgrave, a wood-cleaver's beetle, or the head or butt-end of a club?
"Founders of large castings" is ok

**Comment by TillmannTaape** [comment]
Cannot find anything else for masserote (but Godefroy is down for maintenance so I'll check when it's back up).

**Comment by TillmannTaape** [comment]
@Pantagrueliste ?

**Comment by Pantagrueliste** [comment]
I cannot find much for masserotte, but I found quite a few things on Masselotte: 

> Réserve de métal liquide excédentaire devenant après refroidissement une masse excédentaire de métal

It comes from "machelote" : 
> petite boule, petite masse (little excrements in the XIII-c fabliaux ), 
but in 1704 (according to TLFi)
> métal superflu qui reste dans les moules après la fonte des canons

**Comment by ps2270** [comment]
@Pantagrueliste Great work!! 
Can you please change the word to masselotte with an editorial note in all three versions (leaving it in FR with fR tags in the translation), that includes 
    from "machelote:" Réserve de métal liquide excédentaire devenant après refroidissement une masse excédentaire de métal (excess reserve of liquid metal for filling the mold). Petite boule, petite masse (little excrements in the XIII-c fabliaux ); by 1704 (according to TLFi) métal superflu qui reste dans les moules après la fonte des canons.

Is that clear?

**Comment by ps2270** [comment]
Meant to also say,
Translation should be:
Make the gate wide & make sure that there is supraplus (which is the `<fr>masselotte<f>` for founders of large castings),

**Comment by ps2270** [comment]
@pantagrueliste:  I just checked this and it did not get changed to 
Make the gate wide & make sure that there is supraplus (which is the `<fr>masselotte<f>` **for `<pro>founders of large castings<pro>` )**
Please change it, check that it got changed, and close the issue when you are sure that the markup and all else is correct.
Thanks!

**Comment by Pantagrueliste** [comment]
done
