### ISSUE TITLE
punctuation of lists

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#757]
You'll note that in the TCN and TL for 1r, there are periods following each item in the lists.
I asked MHS about this convention by email months ago. He replied:
"We do tend to punctuate lists. The traditional way would be semi-colons, but I thought that would be a bit too much here. If you hate the periods, I won't put up a cultural fight."

I seem to recall we decided no punctuation for the TL (if so, it still needs to be removed).
If we want to keep the punctuation in the TCN (@Pantagrueliste, can you verify that this is a beloved convention?), then we need to extend it to other lists in the Ms., e.g., 170v.

**Comment by ps2270** [comment]
I say no punctuation.

**Comment by ps2270** [comment]
@thuchacz Can you please delete punctuation on the lists of books in TL and TCN?
Thanks

**Comment by thuchacz** [comment]
Done. Punctuation removed from TCN and TL on 1r, except in two list blocks that seemed more sentence-like.
