### ISSUE TITLE
add <df> tag to 96v "making them pass"?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#762]
96v_1 "Grey Guards" has the following passage:
>...And one needs to take good care that they do not pass too far beyond blue, for neither gold nor silver nor any color would take on it. To do this, which is called making them pass*, one takes a cauldron full of ashes....

the asterisk is an editorial comment by Jonathan Tavares:
>i.e. from one color to another by heating

the part "which is called making them pass" seems like an AP definition to me, and the AP even uses this language on the following folios which has been pointed out by Tavares (commenting that the AP has defined "passing" previously.

Thoughts?

**Comment by thuchacz** [comment]
I put `<df>` tags around "making them pass" / "les faire passer"
