### ISSUE TITLE
97r_2 - move comment anchor inside <head>

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#763]
comment c_097r_03 is outside of the head and the ab:
>`<head>`Gilding`</head><comment>`c_097r_03`</comment> <ab>`One prepares...

And so does not render. 
I believe the protocol is to move the comment inside the head. 
Can you confirm and implement?

**Comment by thuchacz** [comment]
Moved the comment in the `<head>`.
