### ISSUE TITLE
p099r_2 "Lean white sand" not a separate entry?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#764]
This appears to be inline italic script, as the "header" is part of the first sentence:
> `<head>`**Lean white sand**`</head>` Without bond renders well proper for casting...

The previous entry is "Founding", which discusses many types of sands and their properties.

This has implications for comment c_099r_01, "Text block starts immediately after title" 

Thoughts?

**Comment by ps2270** [comment]
We could treat this in the same way we treated those the ones in the other sand recipes, simply mark with `<emph>`
I think this is the right solution.

**Comment by thuchacz** [comment]
I agree. 

I have changed the markup accordingly, removing its separate `<div>` and ID, and swapping it's `<head>` tags for `<emph>` ones.

I've changed the comments tracking sheet for comment c_099r_01 to a red line with a delete recommendation and I've removed the comment anchor (prematurely, I know).

@njr2128 we've now demoted it from its current status as an entry. Can you adjust the entries tracking sheet? When done, you can close this issue out.

**Comment by njr2128** [comment]
Perfect. Thank you, all.
This has been updated in https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/DCE_entry-category-metadata.csv
and the GD version (https://docs.google.com/spreadsheets/d/1YHBMzEVFPNqRryCDERGCyiXzUnIpQ7dzwzvndo-9NWo/edit?usp=sharing)
