### ISSUE TITLE
Info for glossary entry "quarteron" and inconsistent translation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#766]
This was entered as an editorial comment in 104v_1, but missing in the glossary-table:
>a quarter of a pound. Cotgrave, via Dicfro gives "a quarter of a pound; also, a quarterne (or the fourth part) of a hundreth; also, a Pinte, or little Quart; also, the halfe of an Emine; also, a Quarter of the Moone. (En Languedoc le Quarteron, common & pour le bled, & pour la terre qui le produit, contient 4 Civadiers, dits aussi boisseuxm divisez par demiz.)" http://www.micmap.org/dicfro/search/cotgrave/quarteron

Do we want to add this additional info and citations?

**Comment by njr2128** [comment]
ALSO, inconsistent translation for this word. 
On 104v, the words has been left as "quarteron" - no french tags.
On 97r (097r_2), the word has been translated to "quarter pound"

This should be made consistent

**Comment by ps2270** [comment]
@TillmannTaape 
I think it is too uncertain whether it means "pound" to translate it that way. Therefore, please change the translation back to "quarteron" on 97r (w/ Fr tags). Add the following to glossary:
Cotgrave,  "a quarter of a pound; also, a quarterne (or the fourth part) of a hundreth; also, a Pinte, or little Quart; also, the halfe of an Emine; also, a Quarter of the Moone. (En Languedoc le Quarteron, common & pour le bled, & pour la terre qui le produit, contient 4 Civadiers, dits aussi boisseuxm divisez par demiz.)" 

We could also add this as an ed note in both instances.  Do you think that is warranted?  Also, could you please do an Oxygen search to make sure these are the only instances?

**Comment by TillmannTaape** [comment]
TL changed and glossary updated.
