### ISSUE TITLE
Inconsistent markup across tc, tcn, tl on 120r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#767]
Tc and tcn have one version of an added header for 120r_3 Nightingales while tl has a different one.

Tc/tcn:
> `<id>`p120r_3`</id>`
`<head><del>`Il`</del><al><add>`R`</add>`ossignol`</al></head>`

tl:
> `<id>`p120r_3`</id> <head><del>`Il`</del><add><al>`Nightingale`</al></add></head>`

This is most obvious in the edition rendering:
![image](https://user-images.githubusercontent.com/14779727/60216409-f60a3c80-9837-11e9-857e-c28fdf78c59f.png)

![image](https://user-images.githubusercontent.com/14779727/60216389-e985e400-9837-11e9-937d-1073e4257fd4.png)

The correct markup should be determined and then implemented across all three versions.

**Comment by TillmannTaape** [comment]
TC and TCN are correct; I changed TL to
`<head><del>Il</del><add><al>N</add>ightingale</al></head>`, reflecting the addition of only the initial letter.
