### ISSUE TITLE
Editorial comment for 107r,  p106v_2

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#768]
There  is a comment on 106v:
![image](https://user-images.githubusercontent.com/14779727/60218180-8fd3e880-983c-11e9-845f-e6ce128ad6c6.png)
that describes how this continues on 107r. 

However, there is no comment on 107r to indicate that the symbol is indicating the continuation from the previous page:
![image](https://user-images.githubusercontent.com/14779727/60218232-b98d0f80-983c-11e9-8008-5b30dd023154.png)

I think a comment should be added here. 
Thoughts?

**Comment by thuchacz** [comment]
I completely agree that there should be a corresponding comment.

I will add it and close this issue out.
