### ISSUE TITLE
108v - move margin block to left middle or bottom?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#770]
Margin block that begins halfway down the page is rendering at the very top in all three version.

@thuchacz , can you work your magic?

**Comment by thuchacz** [comment]
Sorry @njr2128 , but I can't move that block until Nick implements a feature request detailed in: 
[https://github.com/cu-mkp/making-knowing-edition/issues/174](https://github.com/cu-mkp/making-knowing-edition/issues/174)

**Comment by njr2128** [comment]
Ah, of course! Apologies. I am closing this issue as it is logged in the one linked above.
