### ISSUE TITLE
develop consistent format for ed comments with "sic" or "scribal error"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#771]
Search for "sic" and "scribal error" in the sheet and decide on how to format instances where we explain an error left in TC that we have corrected in TCN.

**Comment by ps2270** [comment]
I suggest:
Sic. Presumed scribal error. Corrected in the normalized version.

**Comment by thuchacz** [comment]
Slight tweak: Sic. Presumed scribal error. Corrected *from "___" to "___" *in
the normalized version.

**Comment by ps2270** [comment]
fine.

**Comment by ps2270** [comment]
Have made it 2/3 of the way through the editorial comment file, I'm coming to a conclusion that we should not include notes on words that were corrected in the normalized version. NJR has pretty consistently deleted those throughout the tracking sheet, and its dawning on my that they are notes from the earlier campaign of transcription, useful at that time for keeping track while transcribing, but, now, having made a decision, these seem like superfluous comments.  Does that make sense to you?  I'm sorry for your previous work on this, but having seen the range of team member responses to the various comments (of all kinds, not just this), I think this might be the most economical of asterisks, page clutter, and team time.  
@njr2128 @thuchacz  please let me know if you are ok with this, and I will go through and change, except in a few cases where the comments indicate something additional/larger. Thanks!

**Comment by TillmannTaape** [comment]
I agree that we do not need comment overkill for this.
We could keep it short and sweet for particularly odd cases (i.e. more than a weird spelling), and just put a comment in the TC reading "Sic. Correct: 'xyz.'" – this is what I think we already have in the majority of cases.

But I don't think it would be terrible to make these corrections silently in the TCN without flagging them in the TC. The only concern here would be that readers might assume that it's our typo when it's really the ap's scribo.

**Comment by njr2128** [comment]
DECISION:

- General principle: get rid sic comments or scribal errors etc. in all versions
- No reason for “sic” comments in tc (or other versions) unless very weird
- If “sic” in the comments has not been corrected in the tcn, it should be marked up with `<corr>`/`<del>`
- Carry over to tl (may need assessment on case-by-case basis) - related to comparison across versions

**Comment by ps2270** [comment]
@thuchacz @Pantagrueliste @njr2128 :  I have gone through the ed comm tracking sheet and highlighted in orange potential changes that need to be made in the tcn and tl for sic, scribal error, repetitions, etc. Some of these have been resuscitated from comments that were previously summarily marked for deletion .  You will probably want to go through the tracking sheet yourselves to make sure I've caught everything.  NB: by noting these as potential revisions, I am leaving the final decision up to you--you can decide that "sic" needs to be left as a comment.  Please just record in the tracking sheet what you've decided to do and reason for it (if needed).
Thanks!

**Comment by thuchacz** [comment]
CAG and THU went through PHS's orange-highlighted lines and also searched for "sic." Here is what we did:

If there was a slightly unusual spelling in the TC that was corrected in the TCN using `<corr>` tags and that corrected word was the basis for the translation in the TL, we flagged the comment for deletion. In very sparing cases, we retained a "sic" comment (twice, I think), because the instance was sufficiently strange or could have been ambiguously interpreted by a casual reader of the TC.
