### ISSUE TITLE
Name and wording of the DCE

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#774]
There has been discussion about the name and wording of the DCE. Need eventual decision.

- “A Digital Facsimile with Translation and Commentary”
- Digital Critical Edition and English Translation of BnF Ms. Fr. 640
- Digital Critical Edition and English Translation of “Recueil de recettes” 
- On the spine of the ms: “Choses diverses” = Various things
- BnF catalogue title: “Recueil de recettes et secrets concernant l’art du mouleur, de l’artificier et du peintre” = Collection of recipes and secrets concerning the art of the moulder, the artificer and the painter

- Header:
- Making and Knowing
- BnF Ms. Fr. 640. “Recueil de recettes et secrets concernant l’art du mouleur, de l’artificier et du peintre” 
- Digital Critical Edition and English Translation

**Comment by njr2128** [comment]
BnF Ms. Fr. 640: A Digital Critical Edition and English Translation

**Comment by njr2128** [comment]
Ms. Fr. 640, Recueil de recettes et secrets. A Digital Critical Edition and English Translation, 

Ms. Fr. 640, A French Collection of Recipes and Secrets. A Digital Critical Edition and English Translation, 

Ms. Fr. 640, A Digital Critical Edition and English Translation, 

Ms. Fr. 640, A Making and Knowing (Project) Digital Critical Edition and English Translation, 

Ms. Fr. 640, A Renaissance French Collection of Recipes and Secrets. A Digital Critical Edition and English Translation, 

Secrets of Craft and Nature in Renaissance France. A Digital Critical Edition and English Translation of Ms. Fr. 640

**Comment by njr2128** [comment]
**DECISION:** Secrets of Craft and Nature in Renaissance France. A Digital Critical Edition and English Translation of Ms. Fr. 640

**Comment by ps2270** [comment]
Prospectively (pending comment from Libraries)
The Making and Knowing Project, Pamela H. Smith, Naomi Rosenkranz, Tianna Helena Uchacz, Tillmann Taape, Clément Godbarge, Sophie Pitman, Jenny Boulboullé, Joel Klein, Donna Bilak, Marc Smith, and Terry Catapano, eds., Secrets of Craft and Nature in Renaissance France. A Digital Critical Edition and English Translation of BnF Ms. Fr. 640, http://edition640.makingandknowing.org (2020).

**Comment by njr2128** [comment]
FINAL DECISION
The Making and Knowing Project, Pamela H. Smith, Naomi Rosenkranz, Tianna Helena Uchacz, Tillmann Taape, Clément Godbarge, Sophie Pitman, Jenny Boulboullé, Joel Klein, Donna Bilak, Marc Smith, and Terry Catapano, eds, _Secrets of Craft and Nature in Renaissance France. A Digital Critical Edition and English Translation of BnF Ms. Fr. 640_, [URL] (2020).
