### ISSUE TITLE
Video resources of paging through ms

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#776]
In progress with MHS and @thuchacz 

Like https://digitalmontagny.inha.fr/en/page/how-use-site and http://earlymodernweb.org/resources/

See also https://github.com/cu-mkp/m-k-annotation-data/issues/5

**Comment by ps2270** [comment]
@ps2270 needs to write script for this

**Comment by njr2128** [comment]
completed and captioned https://vimeo.com/389763699
