### ISSUE TITLE
Editorial comment for p035r_1

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#787]
p035r_1
>**For telling someone that you will show teach him something he does not know, and neither do you**
Take a string or a small stick and take the measurement from the tip of his ear to the tip of his nose and show it to him. Thus you will teach him something you did not know, and neither did he.

Leonardo notebooks contain same joke as 35r
@ps2270 will get reference
Then comment should be added

**Comment by ps2270** [comment]
done.
