### ISSUE TITLE
find “imiter” and “contrefaire,” change to appropriate translation, insert editorial comment

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#79]
find “imiter” and “contrefaire” and change them to the fitting translation, i.e., imiter = imitate and contrefaire = counterfeit. 

This translation must be explained in an editorial comment, linking to Lores-Chavez annotation.

**Comment by Pantagrueliste** [comment]
_imiter_ as _mimesis_
_contrefaire_ as  a material double for the original (Jasper, coral, sapphires and diamonds)

1. find relevant word, decide if it fits this context
2. if yes add a comment anchor `<comment>id number</comment>`  e.g. c_007r_01

**Comment by Pantagrueliste** [comment]
I checked *imit* and *contref* in TCN and compared with the translation: no inconsistencies in sight.
