### ISSUE TITLE
Normalized spelling of historical authors in "lists" entry category

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#791]
Do we normalize names of historical figures and authors? E.g., should "Polydorus" on 2r become "Polydore"?

And, if so, do we do this in the body of the TL or in editorial comments?

**Comment by ps2270** [comment]
No, normalization of authors in tcn and tl.  This has been taken care by editorial comments.

**Comment by njr2128** [comment]
@Pantagrueliste will check that tl and tcn do not have normalized versions, and will add or update ed comments to include normalized name

**Comment by njr2128** [comment]
CHANGE: @njr2128 will do

**Comment by njr2128** [comment]
[issue791_pn-normalized-spelling](https://docs.google.com/spreadsheets/d/1IFZtVCOnXauka3VFyJxopihvV6-6SvGJL9bggDl5u-k/edit?usp=sharing) in DCE folder, Digital Admin and metadata

**Comment by njr2128** [comment]
UPDATE:

- NJR began work and saw that applying a general protocol of no normalization for <pn> raised many issues, particularly about when our work is to just translate the French
- There are discrepancies between tc and tcn, namely in the use of accents and other modern french characters, as well as capitalization
- For common names, like Ptolemy and Palissy, it required adding additional comments that were unnecessary before, and seemed needlessly complicated
- For names that just happen to be the same in AP’s French and modern English, they start to seem as if they are treated differently
- Best example: Archimedes and Ptolemy occur just a few words from one another on 5v. Archimedes would stay the same, without a comment and without <fr> tags. Conversely, Ptolemy would change to Ptolemee and get a comment.
- For saint names, it raised similar problems (having to add comments where they were not needed before); additional problems of expansions from “st” to “saint”
- It would require adding <fr> tags everywhere
- NJR is abandoning work started in branch issue791 (summarized in column O)
- Changes in xml files to edit names and add comments will not be merged with master
- Added comments (for people like Ptolemy and the saints) have been removed from comment-tracking
- FOLLOW-UP QUESTION: use of <pn> tag for words like:
- King
- Queen mother
- God
- Satan
- FOLLOW-UP TASK: correct tags that are incorrect, found while going through these names
- CAG is going through the table of personal names and assessing each tagged <pn> from TC/TCN to see if it can reasonably be translated in English (e.g., Ptolemé = Ptolemy; S<ainc>t Jehan = St. John). If it can, he is giving the standardized English name (per Wikipedia), and if not, he is recommending that the PN from the TCN be carried over

**Comment by ps2270** [comment]
CAG procedure is good; I endorse this decision.

**Comment by Pantagrueliste** [comment]
If we normalize Saint as St. in Enlgish, shall we do the same with places like Saint-Frajou?

**Comment by ps2270** [comment]
I don't think so. saint-germain is the same in English, for example

**Comment by ps2270** [comment]
I guess I'm not actually sure I understand what is going to happen to the list of names below. **All of these should be left as they are now (i.e., the list below is taken from the TL): they are perfectly understandable to English readers (who know about Latinization):**
Vuolfangus Lazius*

Petrus Appianus*
mathematicus Ingolstadiensis, Comment. urb. rom.*
Hieronimo Ruscelli*

Hermolaus Barbarus*

Angelius Bargaeus, De aucupio et venatione*

Nicolaus Damascenus*
Cares<ariensis>,*
De rebus Persarum*

Isidorus*
Osorius*
*

Eupolemus, historicus gentilis qui de rebus Davidis & Salomonis scripsit*
*
- Cathalogue des villes*

Calendrier des bergiers*

Grammaire italiene*

Arithmetique de Savonne*

Instruction pour le faict des finances*

Questions ænigmatiques*

Des præceptes d’agriculture*

+ Le secret des finances à Lyon*

Synesius*

Olaus Magnus*

+ Master Bernard Palissy*
, inventor of rustic figulines*
to the king and the queen mother
[List of books]
Aquatilium animalium historiae, Hypolito
Salviano Typhernate authore, Romae 1554*
[List of books and authors]
Les Annales de Normandie*
Monsieur*
Alexander Aphrodisaeus*

Polydorus Vergilius*

Appianus*

Athenaeus*

Pausanias
Statius Thebaidos*

Servius, In Aeneidem*

Macrobius*

Aulus Gellius
Alexander ab Alexandria
Festus*

Nonius*

Magius, Miscellanea*

Pollux, Onomasticon*

Hyginus*

Berosus*

Suetonius
Valerius Maximus
Cornelius Tacitus
Xenophon
Seneca
Dionisius Halicarnassensis*

Sabellicus*

cum permultis
aliis Julius Capitollinus*

Budaeus*

Spartianus*

Blondus*

Volaterranus*

Herodotus
Paulus Manutius*

Strabo
Julius Firmicus*

Quintus Curtius*

Dio*

Cornelius Nepos
Flavius Vopiscus*

**Comment by ps2270** [comment]
The following should also be left as it now stands
Books to recover
The chronicles of Sigebert*
. Ruffinus*
. Irenius*
In Exegesi*
. Paule Emile*
. Paule Jove*
. Polydorus*
. Bergomensis*
. Philippe de Commines*
.

**Comment by thuchacz** [comment]
PHS, CAG, and THU decided:
All personal names would be represented in TL identically to how they are in TCN and would each get an editorial comment. For those very common personal names (e.g., Plato), the comment would be extremely minimal (i.e., displaying conventional English name).

**Comment by njr2128** [comment]
DECISION:
Markup principle: create principle that personal names never get any language tags (in any language). 
Translation principle: We have respected the convention among early modern humanists to use latinized personal names. These have been slightly normalized in accordance with principles used across the tcn (accents, capitalization, punctuation, etc). These names have not been translated or further normalized in the English translation. See editorial comments for modern conventional names and additional information.
@ps2270, please let us know if you strongly object

**Comment by Pantagrueliste** [comment]
also remove <fr> tags from toponyms

**Comment by njr2128** [comment]
Next steps:
NJR will 

- change all TL to match TCN with no language tags and no expansions
- Remove latin from all personal names in all versions.
- add comment anchors in all versions for names that do not already have them

@Pantagrueliste and @thuchacz will create the content for the comments later this month

**Comment by njr2128** [comment]
I am marking new comments in DCE-comment-tracking in pink highlight

**Comment by njr2128** [comment]
Completed task. Need information about what to do about king, queen, god, satan, etc

**Comment by njr2128** [comment]
@thuchacz and @Pantagrueliste, comment content is ready to be written for the comment anchors I have created (and highlighted in light pink)

**Comment by njr2128** [comment]
completed and is being checked during editorial comment review
