### ISSUE TITLE
112v and 113r missing figure or mark

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#795]
There are corresponding marks on bottom of 112v and top of 113r to indicate continuation, but they are not included as either figure or mark in tc, tcn, tl

112v - bottom right corner
![image](https://user-images.githubusercontent.com/14779727/60534633-45d18380-9cd0-11e9-9d80-eb2b3472aec2.png)

113r - top left corner
![image](https://user-images.githubusercontent.com/14779727/60534698-64377f00-9cd0-11e9-9fd2-7716ff985e8d.png)

Should these be added as marks or figures?
Once decided, add to all versions

**Comment by njr2128** [comment]
ALSO, add editorial comment on 112v to indicate it continues on the next page in the margin

**Comment by thuchacz** [comment]
Editorial comment added.

The figures are included in the BnF Drawings Index and the XML files. However, they do not render since `<figure>` has not yet been designated as a possible child of `<ab>`.

**Comment by njr2128** [comment]
@thuchacz , since you have taken care of things on the data side and the only remaining issue is a rendering one, I think this issue can be closed.
