### ISSUE TITLE
<ups> for 117r

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#797]
`<id>`p117r_1`</id>`
<head>`Moyen de mouler les fleurs et herbes`</head>`

> .... `quille de <m>cire</m> <del>q</del> où l’herbe est hantée se joingne au
bout de la <mu>mandorle</mu><comment>c_117r_01</comment><lb/>`....

The comment here is that "mandorle" is under the paper strip. Delete comment and add ups

**Comment by thuchacz** [comment]
<ups> is present in TC (and TC _only_).
the comment is in TCN.
We need to make a decision about whether to pull <ups> across to TCN or to consider it a silent normalization.
