### ISSUE TITLE
<ups> tag function, use, etc.

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#798]
`<ups>` is present in TC (and TC only).
Should it also be carried over to TCN too?
We need to make a decision about whether to pull <ups> across to TCN or to consider it a silent normalization.

What about TL? Some sort of indicator around the word? (it is impossible to actually indicate the corresponding part of the word)

Editorial comments?

Covered in an annotation or essay only?

Rendering of this? need to then make issue in https://github.com/cu-mkp/making-knowing-edition

**Comment by ps2270** [comment]
I think in the interest of time it's ok if we don't carry over the markup to the tcn and tl (although CAG and I have already been doing so, at times), but we _should_ carry over the text, if it doesn't exist in the tcn and tl already.  I don't think we don't need editorial comments unless there is some pressing need. 
I see the tc as the place to indicate structural issues, like ups, and they are not necessary in the other versions.
Rendering could be any sort of brackets, if we have any choices left (we already use angle brackets in mark up, parentheses and square brackets in rendering, and we should not use curly brackets).   Not sure what choices we have left.  Italic and bold are already used. A faintly colored background? if that's possible??

**Comment by njr2128** [comment]
Resolved. Rendering is grey highlight. Not carried over in any version. Only in tc
