### ISSUE TITLE
'Meus' = 'motionless'

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#80]
'Meus' (e.g. p139v) should be translated 'motionless'

**Comment by thuchacz** [comment]
Checked for "meus" "meux" "moeu" and looked through 164 derivations of "meu." 
ONLY instance is the one on 139v.

@TillmannTaape Does "meus" mean "motionless"? or does "non meus" mean "motionless"?

**Comment by TillmannTaape** [comment]
@thuchacz Sorry, I think this got muddled somewhere between SJP's question in the vocab, MHS's answer, and my transferring it to the consistency list. 'Meus' is a weird spelling of the past participle of 'mouvoir', so 'non meus' = 'motionless'.

**Comment by thuchacz** [comment]
Fantastic! Then all is as it should be.
