### ISSUE TITLE
120v change phrase back to Latin and update comment with translation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#800]
In p120v_3, the marginal note now reads "Doubtful [question]" with a comment (c_120v_07) that reads it was originally in Latin.

As per protocol, this should be changed back to Latin, and the comment instead should contain the translation.

Once Latin has been changed, please change content of comment c_120v_07

**Comment by ps2270** [comment]
done.

**Comment by Pantagrueliste** [comment]
done
