### ISSUE TITLE
faire bonne prise

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#805]
faire bonne prise should be translated consistently as to give a good hold.

**Comment by Pantagrueliste** [comment]
done 
Changed 125r from "set wel"l to "give good hold." I also changed the tense.

**Comment by ps2270** [comment]
Hmmm...in this case, because it's a plaster, not a sand mold, it "sets" not "gives a good hold." But he seems to mean in this case, "when it will set well"  or "when it will give a good hold [i.e., set well]".  I think we need to change it back to
"when it will set well"....Sorry, @Pantagrueliste

**Comment by ps2270** [comment]
Hmmm...in this case, because it's a plaster, not a sand mold, it "sets" not "gives a good hold." But he seems to mean in this case, "when it will set well"  or "when it will give a good hold [i.e., set well]".  I think we need to change it back to
"when it will set well"....Sorry, @Pantagrueliste

**Comment by Pantagrueliste** [comment]
I reverted the commit.
