### ISSUE TITLE
translation of grille

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#806]
grille, when it means an ingot, should be translated grille ingot(s)

**Comment by ps2270** [comment]
yes. good.

**Comment by Pantagrueliste** [comment]
I will translate the following instances to "grille ingot":
28v, ``` la <env>mine</env>, pource que les <pro>m<exp>aistr</exp>e<exp>s</exp></pro> le refondent <del>a</del> en grille<lb/> ```
48v, ``` aigre</m>. L'aigre se gecte en grille par les ```
92r,  ``` le meilleur pour le gect est celuy qui, estant<lb/> gecté en grille, est <del>bruny &amp;</del> luisant &amp; poly co<exp>mm</exp>e un mirouer &amp; qui semble<lb/>```

**Comment by ps2270** [comment]
I am unsure that en grille means grille ingot. Please wait. I've just boarded a plane

**Comment by ps2270** [comment]
Need to look at other instances where grille means ingot. En grille may be a type of casting. Can you please check, @pantagrueliste.
Glossary first of all, I suppose

**Comment by Pantagrueliste** [comment]
these are the only three "en grille" I could find. The glossary also refers to these three instances. I am giving you more context. 
 
28v
> Pintiers. Ils estiment le meilleur estain celuy qui est en saulmon, qui n’ha poinct esté refondu despuys qu’il est venu de la mine, pource que les m{aistr}e{s} le refondent a en grille poisant deux ou trois lb, pour mieux le debiter et vendre en detail.

48v
>  Il y a estaim fin & doulx & estaim aigre. L'aigre se gecte en grille par les pintiers pour mieulx le vendre.

92r
> L’estain doulx qui est le meilleur pour le gect est celuy qui, estant gecté en grille, est bruny & luisant & poly co{mm}e un mirouer & qui semble avoyr esté bruny.

**Comment by ps2270** [comment]
Thanks
DECISIONS:
28v: change to grille ingots
48v:  change to grille ingots
92r: change to grille ingots

**Comment by Pantagrueliste** [comment]
done
