### ISSUE TITLE
FR "carnation" — sometimes as "flesh color," sometimes as "carnation" — consistify?

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#809]

**Comment by ps2270** [comment]
I don't think it's important to consistify this at this point; either is fine.

**Comment by ps2270** [comment]
Ok, @thuchacz?

**Comment by ps2270** [comment]
@thuchacz Perhaps you never commented here b/c you are uncomfortable with this decision?  I just searched and it looks like of the 22 instances of "carnation" (2 of which mean the flower), only 6 are left as "carnation" in the translation.  I propose we change these to "flesh color".  Can you please do that?  Check that they aren't the flower, of course. Thanks!

**Comment by thuchacz** [comment]
Update:
TCN has 33 instances of "carnation" (some that use `<exp>` to build from "carna")
TL has 11 instances of "carnation" (2 of which are the flower)
TL has 20 instances of "flesh color"

So... something's a bit off.

@ps2270 
I want to change all non-flower (i.e., paint-related) instances of _carnation_ to "flesh color"
Would that be okay?

**Comment by ps2270** [comment]
Yes

**Comment by thuchacz** [comment]
Done.
