### ISSUE TITLE
hr needed for squished notes with partial lines?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#817]
on 139r

![image](https://user-images.githubusercontent.com/14779727/60677480-9e7b5a80-9e4f-11e9-83bb-b849813f7797.png)

See the end of the addition on the left. Should we add a horizontal line?

**Comment by njr2128** [comment]
See similar case on 142v:
![image](https://user-images.githubusercontent.com/14779727/60678771-932a2e00-9e53-11e9-8a4d-f77174362ec9.png)

**Comment by njr2128** [comment]
About halfway down on 142v: 

![image](https://user-images.githubusercontent.com/14779727/60678902-f61bc500-9e53-11e9-84d8-0e5a30b1e99a.png)

**Comment by njr2128** [comment]
Another case on 165v: 
![image](https://user-images.githubusercontent.com/14779727/60844174-89cbf900-a1a6-11e9-9235-a43db203d770.png)

**Comment by thuchacz** [comment]
Done
