### ISSUE TITLE
integrate entry categories into ms markup

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#819]
working from entry category metadata, add assignments to each entry as new markup.

wait for end of editorial team readthrough campaign in first two weeks of July 2019

**Comment by tcatapano** [comment]
see: https://github.com/cu-mkp/m-k-manuscript-data/blob/master/metadata/DCE_entry-category-metadata.csv

**Comment by njr2128** [comment]
@matthewkumar to insert categories programmatically using https://github.com/cu-mkp/manuscript-object/blob/master/add_categories.py in new branch

**Comment by njr2128** [comment]
To check that all divs with ids have a category:
xpath query `//div[@id][not(@categories)]`

**Comment by njr2128** [comment]
To check that divs without ids do not have categories:
`//div[not(@id)][@categories]`

**Comment by njr2128** [comment]
done
