### ISSUE TITLE
figure on 111r

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#822]
the figure needs to be tagged correctly and inserted.

**Comment by ps2270** [comment]
It is actually tagged correctly and inserted, but it is not rendering b/c of the `<ab>` issue.  Tianna said she would fix.

**Comment by thuchacz** [comment]
The figure does not render since `<figure>` has not yet been designated as a possible child of `<ab>`.

**Comment by njr2128** [comment]
@thuchacz , since data is correct and the only issue is rendering, I think this issue can be closed.
