### ISSUE TITLE
&amp; and 

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#830]
```&amp; and``` search and destroy and

**Comment by thuchacz** [comment]
@Pantagrueliste 
Can you clarify the parameters of this "search and destroy" campaign? Often, when there has been an `&amp; and` combo, it is because the `&amp;` is intended to be read as an "&cetera" followed by an "and".

These need to be assessed individually and carefully.

**Comment by Pantagrueliste** [comment]
16 instances identified in TL. &cetera are written differently: &amp;c
```find . -name '*.xml' -print0 | xargs -0 sed -i "" "s/&amp; and/&amp;/g"```

**Comment by Pantagrueliste** [comment]
Done: 16 changes in total.
