### ISSUE TITLE
missing figure on 150v?

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#834]
This appears to be a figure we have not included, which has the notation "A" and is referenced on the next page, 151r

![image](https://user-images.githubusercontent.com/14779727/60742896-24c19a80-9f3d-11e9-9219-fc8d5878a807.png)

Add figure?

**Comment by njr2128** [comment]
location is bottom right corner

**Comment by thuchacz** [comment]
The figure was already included in the BnF Drawings Index and are now in the XML files.
I've given it a "right-bottom" position tag. There may be rendering tweaks to come, but this issue is now addressed
