### ISSUE TITLE
sur le mabre = on marble vs on the marble

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#837]
check and unify (or not, depending on context)

**Comment by ps2270** [comment]
We had a principle of translating it as "on marble", not "on the marble", in order to be consistent with "on porphyry", so it should be changed to that if you come across "on the marble" (CAG and I have changed a few), but if we miss some, it is not important at this point. Ok?

**Comment by TillmannTaape** [comment]
Searched for "marble" in the TL and deleted "the" in instances to do with grinding, crushing etc., where appropriate.
