### ISSUE TITLE
"vermeillon" = vermilion 

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#84]
vermeillon and variants should be translated as vermilion (see, for example, 141r-v)

**Comment by TillmannTaape** [comment]
Search terms:  vermeil, vermil

It was translated 'vermillion' in some cases which I changed to 'vermilion'. Both variants are correct according to the OED but it seems we decided on one L at some point.

The vocab has a note by MHS that vermillon in the ms is "presumably different" from vermeillon – @ @ps2270 do we think this is the case?
I am assuming that we think it's the same thing, since they were all translated as 'vermilion'.

**Comment by ps2270** [comment]
the only problem would be with the Boutons de vermeilles on 40r, which should not be vermilion, but I'm assuming you did not change that?

**Comment by TillmannTaape** [comment]
No I didn't change those; the vocab says to keep in Fr. because it's an enamel.
