### ISSUE TITLE
105v markup needs revising

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#840]
105v markup does not indicate that one of the headings on 105v, "Rossignol," is in the margin. Markup needs revising, so page will render correctly.

**Comment by thuchacz** [comment]
I have moved the two "Rossignol" entries to the left margin. Their headers are still rendering in the middle block, but there is an open issue for Nick to make `<head>` tags positionable. The rendering will right itself when he accommodates this feature request.
