### ISSUE TITLE
Doublet - definition in glossary?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#845]
@TillmannTaape and @thuchacz . did I understand that you came up with a new definition of "doublet" yesterday?  If so, please enter it in the glossary.  The present definition seems vague and possibly incorrect.

Also, "dessein" from 62r (only instance) is trans as "drawing" on f. 62r, but as "design" in the glossary.  @thuchacz , can you please decide about this (as an art historian)?

**Comment by TillmannTaape** [comment]
The definition of doublet in the glossary is "a jewel made of two pieces joined together", as per Cotgrave. I think it's clear and comprehensive enough for our purposes, but let me know if you disagree.
