### ISSUE TITLE
check "glaire d'oeuf" across Ms. for consistency

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#85]
Glaire (f.) = “glair” 
glaire d’oeuf = “glair of egg”

**Comment by Pantagrueliste** [comment]
so _Glair of Egg_ replaces _Egg Yolk_? @thuchacz

**Comment by thuchacz** [comment]
glair is the egg white, not the yolk.
The point is, we're not sure how consistently "glaire" / "glaire d'oeuf" has been translated. There may be some instances in which it was translated as "egg white" rather than what we now know that we want: "glair" or "glair of egg," depending on context.
