### ISSUE TITLE
should we remove the <sup>of sulfur</sup> in 46v_6 and 46_7

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#852]
On one hand, we want to get rid of <sup> tags as much as possible.
On the other, this makes markup problematic, as the material will be "aforesaid oil" — will this get associated with "oil of sulfur" in the markup vocabulary normalization?
NB: there is an editorial comment explaining that "aforesaid oil" is oil of sulfur.

**Comment by ps2270** [comment]
Hmmm...well, we have two competing goals: when searching to capture all instances of a material, and to remove sups.
In this case, I don't see the harm in leaving the suped "of sulfur", and deleting the ed note.

**Comment by ps2270** [comment]
@thuchacz didn't we talk about this during trans read-through, and decide differently?

**Comment by thuchacz** [comment]
We did talk about this, but I don't think we made a definitive decision. The issue hinged on 
1) whether vocab normalization would be able to connect "the aforementioned oil" to "sulfur" so that it might be caught in a) a search for "sulfur" or b) faceted browsing through a materials list to sulfur --> oil of sulfur
2) whether we could (nearly) eliminate the `<sup>` tags
3) how aggressively we wanted to prune the editorial comments

**Comment by ps2270** [comment]
- vocab normalization?
- can we have a silent sup tag that would allow capture in searching, but the word, or more importantly, the heading does not appear?

**Comment by njr2128** [comment]
Closing this issue as per #1140 and #724
