### ISSUE TITLE
corr tags instead of sup tags for et[c.]

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#858]
11 instances of supplied "c" after ampersand (to signifcy "etc.") using sup tags – should we change to corr tags?

**Comment by thuchacz** [comment]
Just checked again. 
TCN: 13 instances of `&amp;<sup>c`
TL: 1 instance

**PROBLEM 1**
Should these be `&amp;<sup>c</sup>` or `&amp;<corr>c</corr>`? These additions of the letter "c" are editorial decisions to transform (correct?) an ampersand into an etcetera. It seems our intervention is more than simply supplying a "c" to help clarify meaning, no??
**PROBLEM 2**
Should there be a period along with the "c" inside the sup/corr tags? Most instances do not include a period; those that do sometimes show the period inside, sometimes outside the tags.
**PROBLEM 3**
Should this sup/corr of ampersands not be brought over to the TL? Right now, 1/13 of those instances are indicated.

@ps2270, do you have any thoughts about this?

**Comment by ps2270** [comment]
Good questions:
1. it's true they are interpretations, but they all are pretty clearly "etc". Changing supp to corr will mean that it will be rendered as &[c], which is ok, I guess
DECISIONS: change to corr tags

2. No period.

3. Yes the decision should be carried over to the tl.

**Comment by thuchacz** [comment]
All ampersands (except for the 2 original to the TC which are marked up `&amp;c`) now indicated in TCN and TL with `&amp;<corr>c</corr>`
