### ISSUE TITLE
“plaste de terre” = "earthen slab" and “plaste de ardille” = "clay slab"

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#86]
“plaste de terre” should be earthen slab and “plaste de ardille” should be clay slab.

**Comment by thuchacz** [comment]
Search and hits (though not all relevant): "plaste" (18) "plasti" (0) "plate" (14) "platin" (7) "platte" (50) "platti" (0) "plass" (0) "plae" (0) "platie" (1)
