### ISSUE TITLE
emph tags for 166v

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#869]
@TillmannTaape , can you confirm that the script used at the end of the first `<ab>` (quoted below) is italic?
If so, can you add emph tags?

>"Manus meӕ fecerunt organum et digiti mei aptarunt psalterium"

**Comment by TillmannTaape** [comment]
Yes it's italic script. I've added emph tags. The markup was inconsistent re body part and la tags, so I tidied it up.
