### ISSUE TITLE
141v text under the paper strip 

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#870]
141v at the very bottom has at least one line (but legible) under the paper strip.  `ups` tags need to be added.

**Comment by thuchacz** [comment]
- updated TC with `<ups>` tags and line of text provided by MHS in recent email.
- updated TCN with line of text (no `<ups>` tags)
- updated TL with a translation of that line
- deleted the two editorial comment anchors in TCN (which were in no other versions), which pertained to this MHS double-check
- deleted the two rows for those comment anchors from the editorial comments sheet.
