### ISSUE TITLE
Translation of Joincture

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#876]
Go through and change, where appropriate, the translation of "joincture" from "joint" to "join".  This is especially appropriate for the JOIN of two halves of a mold.

**Comment by ps2270** [comment]
With much discussion, we have changed our minds that "joincture" should indeed be translated as "joint". 
DECISION: Translate "joincture" as "joint" unless there is a good reason not to do so.

**Comment by Pantagrueliste** [comment]
```
tcn_p055r_preTEI	, long co {mm} e la	joincture		du petit doigt & du qualibre, & le mects dans le
	tcn_p091r_preTEI	& si elle est offensée à droict la	joincture		, malaisem {ent} prend il, co {mm}
	tcn_p091v_preTEI	aultour en divers endroicts qui traversent sur la	joincture		des deulx os, affin de recognoistre bien l'endroit de leur
	tcn_p091v_preTEI	de recognoistre bien l'endroit de leur premiere	joincture		. Ou bien, avecq de petites pointes de bois, traverse
	tcn_p095v_preTEI	, pource que l'eau entre par la	joincture		du clou. Le mieulx est de l'apliquer avecq de la
	tcn_p141v_preTEI	estends les sur l’ardile jusques à la	joincture		, et l’aultre moictié des jambes demeure en hault recourbé pour
	tcn_p144v_preTEI	molles uniment & à chasque costé asseure leur	joincture		, qui ne se cognoist que bien peu, avecq deulx crampons
```

**Comment by Pantagrueliste** [comment]
done

**Comment by ps2270** [comment]
I see on fol. 144v that you left it as "join" (twice). I think we should translate it as "joint" to be consistent with the next 3 pages, which are talking about the same thing, and we have translated as joint, as that is in the end what we decided to do.

**Comment by Pantagrueliste** [comment]
I had left one "joins," I now changed it to "joints."
