### ISSUE TITLE
editorial comment for folios in scribe's hand

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#877]
Add an editorial comment at the top of all folios written not by the AP but by a scribe?
There are existing comments when the hand switches to or from the scribe. However, this leaves whole folios where there is no indication that it is in the scribe's hand - the only way someone would know is if they went back and forth a few pages.

**Comment by njr2128** [comment]
See folios 77r-79v

**Comment by njr2128** [comment]
also 73-76

**Comment by njr2128** [comment]
I have tracked the particular scribe who has problems with "sandarac" here: 

Folio | Entry-ID | Comment-ID | Checked and by whom | Comment | Comment-edit | comment-edit-notes | Category \| separated | reference-id
-- | -- | -- | -- | -- | -- | -- | -- | --
p077r | p077r_4 | c_077r_01 | NJR | hand shift back to the one scribe that is somewhat unreliable, that is, NOT our author/practitioner. handshift, noted by previous paleographer, noted by Marc Smith: "definitely (same as p73-76). | From this entry through to 79v, the writing is in a different hand to the author-practitioner, the same as the hand used 73r-76v (likely that of a scribe) | tc, tcn, tl | Handshift \| Structural | p077r-p079v \| p073r-p076v
p077r | p077r_1 | c_077r_02 | NJR | Writing returns to the hand of the author-practitioner (no longer in the scribe's hand) for the first three entries on this page |   | tc, tcn, tl | Handshift \| Structural | p077r_1 \| p077r_2 \| p077r_3
p077v | p077v_3 | c_077v_03 | NJR | the scribe had trouble with this. It could mean sandarac, but it's as though the scribe heard sang (blood) de Drac or da Rac (the devil's shout). Also the same problem on 78r, which clearly means sandarac. | The scribe seems to have difficulty understanding the word "sandarac," as if he heard sang (blood) de Drac or da Rac (the devil's shout). Also seen on 78r and 79v. In context, this is sandarac | tc, tcn, tl | Editorial | p078r_1 \| p079v_1
p078r | p078r_1 | c_078r_01 | NJR | the scribe had trouble with this. It's as though he heard sang (blood) de Drac or da Rac (the devil's shout). Here, it clearly means sandarac, whereas on 77v, it is uncertain. | The scribe seems to have difficulty understanding the word "sandarac," as if he heard sang (blood) de Drac or da Rac (the devil's shout). Also seen on 77v and 79v. In context, this is sandarac | tc, tcn, tl | Editorial | p077v_3 \| p079v_1
p079r | p079r_1 | c_079r_01 | NJR | The scribe left a gap because he couldn't read the text, then filled it in with moullée du grais and the dashes for the remaining blank. Moulée du grais is the powder of a particular type of potters' clay or earth for making stoneware vessels. | A gap left by the scribe has been filled in with three short horizontal strokes, perhaps because there is text the scribe could not understand and thus ommitted, or because a gap was left and later filled in with additional space left over | tc, tcn, tl | Editorial \| Structural |  
p079v | p079v_1 | c_079v_01 | NJR | see scribal problems on 77v & 78r. The scribe is still having problems understanding "sandarac" here. | The scribe seems to have difficulty understanding the word "sandarac" as is also seen on 77v and 78r. In context, this is sandarac | tc, tcn, tl | Editorial | p077v_3 \| p078r_1
p079v | p079v_2 | c_079v_02 | NJR | handshift, back to author-practioner's hand | Writing returns to the hand of the author-practitioner (no longer in the scribe's hand) | tc, tcn, tl | Handshift |

**Comment by TillmannTaape** [comment]
Marc says the info in the MS Structure and Composition doc is in fact complete at the folio level; I will just have to go through and note where the hand changes mid-folio.

**Comment by TillmannTaape** [comment]
Where should the comment anchor go? Before the first word on the page?

**Comment by TillmannTaape** [comment]
This has been done, although the comments themselves will be updated according to Marc's scheme of different hands. Closing.
