### ISSUE TITLE
charbon de pierre

### ISSUE THREAD

**Issue by TillmannTaape** [cu-mkp/m-k-manuscript-data#886]
Translate as mineral coal?

Or pit coal?   (see Description des Art et métiers, 1776, p. 579 which has charbon de pierre as a gloss for the English pit coal. Ibid., p. 359 notes that charbon de pierre and charbon de terre are interchangeable in French; and Cotgrave has "pit coal" for charbon de terre).

  @ps2270

**Comment by ps2270** [comment]
Ok, pit coal it is, with a glossary entry with explanation of what pit coal
is and refs for why we translated it as such

**Comment by TillmannTaape** [comment]
Added to glossary and changed in TL.
