### ISSUE TITLE
170v - '''ups''' tags needed at bottom of page for one more line of text

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#893]

**Comment by ps2270** [comment]
`ups` needed for one last title on 170v

**Comment by njr2128** [comment]
Waiting on MHS

**Comment by thuchacz** [comment]
- TC: added `<ups>` tags and author and book title per info in MHS email: 
`<ab><ups><emph><la><pn>Albertus magnus</pn> de mineralibus</la></emph></ups></ab>`
- TCN: added author and book title
- TL: added author and book title and editorial comment anchor
- added line to editorial comments tracking sheet for new comment
- emailed CAG to alert him to new item for his bibliography work
