### ISSUE TITLE
"après" = "next" NOT "after"

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#90]
après = “next,” not “after” (as it is in some translations from SP18)

**Comment by TillmannTaape** [comment]
Search term: aprés (NB the search is accent-specific), apres

Exceptions:
NB the translation 'after' for the expression 'aprés que' is correct and was not changed to 'next'.
fol. 4v: 'apres les sables' = 'after the sands' (referencing a location in the ms)
'apres avoir fait' = 'after having done'

**Comment by TillmannTaape** [comment]
On occasion I am allowing
'apres avoir fait' to be translated as 'after doing' rather than 'after having done' for better readibility.
E.g. fol 64r. 'aprés les avoyr broyées' = 'after grinding them' rather than 'after having ground them' which is very clunky.
