### ISSUE TITLE
FA15 Counterfeit Jasper file owned by author

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#904]
Transfer of ownership needed from Estrades to General Editor of file: AnnotationFall2015_Estrades_Counterfeit Jasper_10r.docx

**Comment by ps2270** [comment]
PHS wrote 7.12.19

**Comment by njr2128** [comment]
Note: original file is owned by institutional email and cannot be transferred. With @caro27, Estrades and @ps2270 created a copy of the original file which is now owned by General Editor.

For editors, the original has been left in the folder for reference and version history. The copy should become the main text.

Disclaimer note has been added to both files for the editors.
