### ISSUE TITLE
SP16 Sleight of Hand files/folders owned by author

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#906]
Transfer of ownership needed from Barwich to General Editor of files: 
CaptionsSpring2016_Barwich_SleightOfHandTricks_33r36r43v
AnnotationSpring2016_Barwich_SleightOfHandTricks_33r36r43v
and folder:
Illustrations_“Sleight of Hand Tricks,” fol. 33r, 36r, 43v (Barwich)
and 
all images are owned by Barwich - need to reupload from General Editor and relink throughout the text

**Comment by ps2270** [comment]
done
