### ISSUE TITLE
Editorial comments for 14r_1

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#937]
there are presently 3 editorial comments on fol 14r_1. The same comment for the tcn and tl are listed in separate lines in the tracking sheet.  
@njr2128 Should I delete one of them, or just leave them as they are?
@TillmannTaape: you were responsible for this section, so I've assigned you.  The problems are:
1. comment c_01 says that Pascal Brioist told us that the a-p is quoting a particular work. Was he positive about this?  Can you check with him, unless you know he was positive about it, please?
2. You have revised  comment c_05 to say that it is an "alchemical abbreviation" - I'm sure it was, but was it ONLY alchemical, do you happen to know?  Or was it used more generally?  If you are not positive it was ONLY alchemical, then could you pls change the comment to say "Used to mean... in alchemical writings, among others."  If you agree...?
thanks!

**Comment by njr2128** [comment]
I actually see two comments that are the same duplicated for tl and tcn. 
Luckily, the comment id is identical, so the lines are actually just unnecessary and instead the column of "x"s should be updated to indicate the comment anchor is present in tcn and tl.


p014r | p014r | p014r_1 | c_014r_01 |   |   | X |   | TT | PB : See Daniela Lamberini, <i>Il Sanmarino, Giovan Battista Belluzzi, architetto militare e trattatista del Cinque cento</i>, Florence: Olschki, 2007, quoting Belluzzi's manuscript on earth fortification of about 1550. See also Daniela Lamberini, <i>Il Trattato delle fortificazione di terra</i>, Florence: Olschki, 2007.
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
p014r | p014r | p014r_1 | c_014r_02 |   |   | X |   | TT | Word omitted (no blank space).
p014r | p014r | p014r_1 | c_014r_01 |   | X |   | delete | TT | PB : See Daniela Lamberini, Il Sanmarino, Giovan Battista Belluzzi, architetto militare e trattatista del Cinque cento, Olschki Florence, 2007. Quoting Belluzzi's manuscript on earth fortification of about 1550. <see also Daniela Lamberini, Il Trattato delle fortificazione di terra, >Olschki L.S., 2007..
p014r | p014r | p014r_1 | c_014r_02 |   | X | x |   | TT | Word omitted (no blank space).

**Comment by ps2270** [comment]
ok, thanks. I'm learning.

**Comment by njr2128** [comment]
> ok, thanks. I'm learning.

The lines were entered incorrectly, so you actually caught a mistake that should be fixed!

**Comment by TillmannTaape** [comment]
Sorry if I missed the duplication or forgot to update the xs. It now looks good to me. I've edited the SSS comment as you suggested.
