### ISSUE TITLE
ann_048 problems with footnotes/bibliography

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#938]
ann_048 contains two references to primary sources accessed through EEBO. These citations  (in footnotes 41 and 42) are incorrect, as they do not correspond to those in the bibliography file and as I could not find the quoted passages on either versions (footnote and bibliography). The footnotes, moreover,  need a permalink to the specific page in EEBO, and an access date.

**Comment by njr2128** [comment]
Update: author has been asked to review bibliography and is currently in progress.

**Comment by ps2270** [comment]
She is out of the country now and cannot finish revising until end August, just FYI

**Comment by ps2270** [comment]
superseded by completion of the annotation.
