### ISSUE TITLE
53v - incorrect punctuation

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#944]
@thuchacz please make the following changes on 53v:
in TL change from
See Hieronymus Vida Albensis, ep{iscop}us de b Cremonensis, scripsit carmine de bombicum natura..
to 
See Hieronymus Vida Albensis ep{iscop}us, de b Cremonensis, scripsit carmine de bombicum natura.  [deletions not rendering. i.e., move comma--he was from Cremona and was Bishop of Alba--and delete one of the periods]

in TCN change from
Voy Hieronymus Vida Albensis, ep{iscop}us de b Cremonensis, scripsit carmine de bombicum natura.
Coment on les remue.
to
Voy Hieronymus Vida Albensis ep{iscop}us, de b Cremonensis, scripsit carmine de bombicum natura.
Coment on les remue
[i.e., move comma and delete period after remue]
Thanks!

**Comment by thuchacz** [comment]
Done
