### ISSUE TITLE
Problem of crowd-sourced editorial comments

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#945]
On 55v, there is a note:
This recipe seems to be taken from Albertus Magnus: https://gallica.bnf.fr/ark:/12148/bpt6k97691521/f57.item.r=raifort

As it turns out, the link takes you to a book of "the Secrets of Albertus Magnus" printed by a publisher active betw 1784-1984 (or some similar span of years--Epinal/Pellerin). There are many pseudonymous "secrets of Albertus magnus" published from the late 14th century on, and they may well contain this recipe, but this note is not a scholarly reference, altho it is kind of useful info for the person who wants to explore further.

What to do?  Any thoughts?  I cannot think of brief definitive editorial-comment-like way of saying "this recipe may be associated with the pseudonymous Secrets of Albertus Magnus" without giving some sort of reference to back that up.  My different scholarly and information-loving instincts are at war here....
Maybe I should be thinking of the editorial comments not as definitive statements, but, like the rest of the Edition, an invitation to further research and exploration...

**Comment by njr2128** [comment]
We had discussed using language that was not definitive, like "this could" or "potentially" etc.
We could also end comments like the one here with "...More research is needed"

**Comment by TillmannTaape** [comment]
We could simply say "This recipe appears in a nineteenth-century collection atrributed to Albertus Magnus", perhaps with an additional qualification such as "although the attribution is by no means established"

**Comment by Pantagrueliste** [comment]
The issue with this particular book, is that it also allegedly includes recipes from Agrippa, "Thesmégiste" (sic: Trimegistus?) Arnau de Vilanova, Cardano, etc. which Pellerin never cites. So we don't even know if that particular recipe is specifically attributed to Albertus Magnus or another author. Unless we can prove that there is a tradition of pseudonymous secrets of Albertus Magnus that mention this recipe, I would not give importance to this source. Moreover, Pellerin was publisher of paper dolls, immortalised in France by the unflattering expression _image d'Épinal_...

**Comment by njr2128** [comment]
I believe we have dealt with this in the comment tracking and in person. Can this be closed?

**Comment by Pantagrueliste** [comment]
final decision: deleted
