### ISSUE TITLE
Over-writing of letters - how to indicate?

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#947]
When the a-p has overwritten letters, there are a variety of ways we have indicated this: 
1. editorial comment
2. markup (with `<del>` and `<add>`)
3. ed comm and markup
It seems to me that the markup leaves the page cleaner, but I realize we may well have decided on something else previously... See also #120 and #217 

Can @njr2128 @thuchacz @TillmannTaape @Pantagrueliste  please let me know whether you think the policy should be 1, 2, or 3.
thanks

**Comment by njr2128** [comment]
Tillmann and I went through this together a few times, and dealt with some case-by-case. When something was really evident and seemed warranted, we used markup (with/without comment using discretion). Other we left without markup or just flagged as problematic. I put this on the second sheet of the tracking sheet to be raised a larger problem that had not been done consistently in the issues for discussion.

Pamela, you and I discussed this as one of the outstanding questions logged in the second tab of the tracking sheet. This is what I have down as your decision then (with some examples of cases):
Indications that letters or words were written over another one? e.g ., c_082r_02, c_088v_01, c_089v_03, c_090r_01 |   |   | not consistently done - leave it out.
-- | -- | -- | --

Not sure what final decision is

**Comment by TillmannTaape** [comment]
I agree that the policy should be a markup solution if it is clear, with comment if really necessary, and comment only if it is not clear what the add/del situation is. Naomi, if you known of questionable cases in addition to the ones we looked at already, I'll happily have a look.

**Comment by ps2270** [comment]
decision: "correction in original: e written over d [or whatever]

**Comment by njr2128** [comment]
DECISIONS: 
- keep as editorial comments with the new form:
> Correction in original: [explanation]
>> -oubs written over -us		end
>> de- written over en-		beg of word
>> -e- written over -d-		middle 
- Carry through tc, tcn, tl
- Markup: original overwritten letter gets `<del>` and new letters have no markup (entered as regular text)
- @thuchacz and @Pantagrueliste to spend 1.5 hrs to find cases

**Comment by thuchacz** [comment]
CAG and THU implemented this decision by:
1) searching editorial comments tracking sheet for "sic"
2) revaluating the lines PHS flagged orange in the editorial tracking sheet
NB: any row turned red is approved for deletion; any row now white has been fit to this issue's protocol
3) searching the xml files for instances of `</del><add>` and assessing case by case
4) searching the xml files for instances of `</del> <add>` and assessing case by case
5) searching the xml files for lines that begin with `<add>` and assessing case by case

**NOTE**
this work both approved deletion of many editorial comments AND created about 40 new comments. All approved comments were anchored in all three versions of the xml files
