### ISSUE TITLE
155r - clean up of translation

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#957]
@Pantagrueliste  please change 
Wet the rose with eau-de-vie before putting it in the circle of clay. Do not forget to oil the gate with wax. And when you will have cast your tempered sand, blow thoroughly, until it begins to set. The rose came out well. But because the sand finds itself mixed among the petals, make your work soak in water for a long time in order that shaking it in the water, the earth is gone from it.
TO
Wet the rose with eau-de-vie before putting it in the circle of clay. Do not forget to oil the gate **of** wax. And when you will have cast your tempered sand, blow thoroughly, until it begins to set. The rose came out well. But because the sand finds itself mixed among the petals, make your work soak in water for a long time in order **that, shaking** it in the water, the earth is gone from it.

i.e., change **with** to **of**  and add a comma.

**Comment by ps2270** [comment]
New instructions!  Sorry!
**Do not forget to oil the wax gate.**  instead of "gate of wax" [this is used later and it makes absolutely clear what is being talked about here]

**Comment by Pantagrueliste** [comment]
done

**Comment by Pantagrueliste** [comment]
done
