### ISSUE TITLE
Fol.  161r_1 - alume jameni

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#958]
@TillmannTaape We seem to have corrected alume jameni to `alum<corr>in</corr>e jameni`. That is not correct, is it?  Isn't the name of the substance alumen jamenum, thus, if we just leave it as is (i.e., no corrections), it will be ok, right?

If you agree, please go ahead and delete `<corr>` tags in the tcn and tl.  Let me know if you don't agree.  It's in the glossary.
thanks!

**Comment by TillmannTaape** [comment]
I agree, and have taken out the "correction" in tcn and tl.
