### ISSUE TITLE
49r - markup

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#964]
@njr2128   @thuchacz Can we add `<lb>` to the tl to make the rendering of the marginal note left of 49r_1 read better, namely.
Lump of Iron
Calcined oyster shell

Thanks!

**Comment by thuchacz** [comment]
The markup is already there. Nick has yet to enable the rendering of `<lb>`s in either the TCN or the TL, but it is an open issue for him, so the rendering on 49r should auto update once he does this.

**Comment by ps2270** [comment]
Ah, thanks. I should have looked at markup
