### ISSUE TITLE
7v - markup needs changing

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#982]
In 7v_3, an extension (Goutte for G) appears for the capital G in the heading.  This extension should be deleted in all three versions, and the G **capitalized** (**with a period it looks to me--CHECK THIS**) in all 3 versions.
The editorial comment will discuss the interpretation of this abbreviation, but the G alone should appear in the heading.
@TillmannTaape can you please do this?  Thanks.

**Comment by ps2270** [comment]
@TillmannTaape I've already changed the comment--you just need to delete the ext and corr tags, as we want to leave this as "G." in all 3 versions.
thanks

**Comment by TillmannTaape** [comment]
Done.

**Comment by ps2270** [comment]
@TillmannTaape
