### ISSUE TITLE
Protocols for editorial commentary qc

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#984]
Instructions and larger issues that have been raised (see second sheet "Instr. & Ass." of DCE_comment-tracking):

## Version of text (tc, tcn, tl) 
For the most part, pull comments across all three versions.
However, this may not always make sense - use discretion and come to a decision after discussion if necessary. 
PHS will review each case carefully and determine final status.

## Categories
Assign each comment one of the following categories:

category | description
-- | --
editorial | explaining editorial decision or interpretation of the text and its semantics, e.g. uncorrected errors on AP's part
historical | historical background (like author page) - change category title to also include larger context informational, e.g. latin name of plants
structural | material page or structure of ms
conjectural | editorial conjecture
translation | we translated because...
handshift | mostly from MHS

## References
- when annotation, include ID in reference column. Leave out titles
-when referencing another folio, use folio id syntax (003r, 012v, 134r) and enter ID in reference column
- when referencing another entry, use folio id in the comment, but link entry id in reference column and use entry id syntax (p003r_1, p012v_2, p134r_3)
- external references, such as citations, books, etc - TBD - related to glossary references, see #985

## Language and formatting
- be as accurate and clear as possible
- if the comment is a full sentence: first word should be capitalized, end comment in period (if only a couple of words, no period is necessary)
- italics: indicate with `<i>` and `</i> around the words to be italicized
- use quotation marks (" - double, not single ticks) when needed
- "i.e.," - always with a comma as shown here
- use "author-practitioner" to refer to writer of Fr. 640
- all foreign languages that are translated in a comment should be of the format:	[Language]: [translation]
- Occitan terms should be treated as foreign language. Poitevin should not (words are marked up and dealt with in the glossary like other non-translated French terms)
- to indicate distance, use km (not miles)

**Comment by ps2270** [comment]
A couple of notes on my campaign:
- I looked pretty closely at whether and what to pull across all 3 versions, so if you want to change, I'd like to know why.
- I've revised comments extensively for clarity, accuracy, less concision(!), less certainty if we are not certain, changing author-practitioner to a more neutral form, suggesting why a handshift or inkchange might be interesting to us, etc., so I've already spent a lot of time revising comments, and I hope they don't need a lot more work.

I want to suggest a revision to the following:
**Language and formatting**
IF THE COMMENT IS A FULL SENTENCE OR MORE THAN A FEW WORDS, the first word should be capitalized and the comment should end in a period. [2 words in sentence form looks weird.

Also:
i.e. is always followed by a comma!

**Comment by njr2128** [comment]
I had taken these principles from our second sheet and was hoping you would have updates to them. So, I have now updated the above protocol to incorporate these changes

**Comment by ps2270** [comment]
If a comment is not a full sentence, it doesn't have to start with a capital letter nor end with a period.
I've excised author-practitioner from all comments except one, substituting the passive voice, and using a couple of times "writer," and "main hand" to refer to the main hand of the ms.   I hope that sound reasonable to you; I think it's less interpretative and the correct tone for these comments.

**Comment by njr2128** [comment]
Formatting questions - DECISIONS:
- Foreign language: italics
- Quoted English: quotation marks
- Latin - quotation marks when quoting a text
- Ink blots, smudges, etc that have not been deleted --> Leave for now, but if we notice outliers, review (add/delete)

**Comment by njr2128** [comment]
All dates in the entire Edition (comments, glossary, annotations) that necessitate this, should be written BCE (not BC) and CE (not AD).
We have a variety of abbrev. of folio. I suggest (and will institute it now) that the abbrev to be used in the comments (in the interest of brevity) will be "f."

**Comment by njr2128** [comment]
All decisions and formatting is being recorded in GD file, **DCE-comments-formatting**

**Comment by njr2128** [comment]
completed as of Feb 6 public release. See GD file, **DCE-comments-formatting**, for full protocol
