### ISSUE TITLE
Glossary title

### ISSUE THREAD

**Issue by Pantagrueliste** [cu-mkp/m-k-manuscript-data#988]
We now have a beautiful _Glossary of Terms_ on the staging edition, but I am wonderign whether we could just call it _Glossary_ as the current title is rather long and redundant.

**Comment by ps2270** [comment]
Yes, I didn't even realize it was G. of T.  Definitely, just Glossary is better.  Thanks.

**Comment by ps2270** [comment]
@tcatapano @njr2128 , just checking that you know that "Glossary of Terms" should be retitled to "Glossary"?
thanks

**Comment by njr2128** [comment]
This is now an open issue in Nick's repo (https://github.com/cu-mkp/making-knowing-edition/issues/233) so am closing here
