### ISSUE TITLE
"amortir" = "to die down" or "mortify" depending on context

### ISSUE THREAD

**Issue by thuchacz** [cu-mkp/m-k-manuscript-data#99]
amortir, amorty, etc.
1) = to die down (if of heat or redness)
2) mortify (if of a metal; 1 instance known now, 72v)

**Comment by Pantagrueliste** [comment]
Wouldn't a translation note on the polysemy of *amortir* make sense here? @thuchacz

**Comment by Pantagrueliste** [comment]
No inconsistencies detected.
