### ISSUE TITLE
review changes made to fix well-formedness

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#993]
3 well-formedness errors were found, and fixes were implemented by NJR+THC.
However, as we did not undertake the work that caused the errors, we want to make sure that the fixes we chose are correct.

Please review these files for accuracy at the points where interventions were made. Reference the pull request https://github.com/cu-mkp/m-k-manuscript-data/pull/992

**Comment by njr2128** [comment]
two errors for THU to review.
Last one is ok (CAG/NJR)

**Comment by thuchacz** [comment]
Yep! 
The first one is my error from last night. You fixed it perfectly.
The second one is TT's from a recent translation decision. Again, you got it!

**Comment by njr2128** [comment]
Fabulous!
Thank you, all done!
