### ISSUE TITLE
fix errors found through schema validation

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/m-k-manuscript-data#999]
Validate xml files with new schema
Fix errors identified

**Comment by njr2128** [comment]
errors logged in GD, https://docs.google.com/spreadsheets/d/13R19RkmicK-fxoeaFh9SVrLzwBzdUb2oR7gisl2iOEY/edit?usp=sharing

**Comment by njr2128** [comment]
@tcatapano - I need help with the following: div followed by figure:

**Comment by njr2128** [comment]
It appears all outstanding issues have to do with divs that have no ids as summarized in the linked spreadsheet.

**Comment by njr2128** [comment]
outstanding div issues are now a new task in #1000

**Comment by tcatapano** [comment]
`<id>` now optional in `<div>`  in schema, but added embedded schematron rule to warn if missing. See #1000
